#!/usr/bin/env bash
#
# install.sh — point GLOBAL git at devrc's tracked githooks/ dir.
#
# Sets `core.hooksPath <this dir>` in git's GLOBAL config so the
# version-controlled pre-push dispatcher runs for every repo that does NOT
# override core.hooksPath locally. It composes with repo-local
# .git/hooks/pre-push (chains to it first).
#
# The AUDIT flag defaults to SHADOW (installing changes nothing about the audit
# side of your push UX until you flip AUDIT_ON_PUSH=on). The TEST GATE, however,
# defaults to ON *in the devrc repo only* — devrc pushes will run the Python
# suite and block on a genuine failure (TESTS_ON_PUSH; DEVRC_SKIP_TESTS=1 to
# override a single push). It is a no-op in every other repo.
# Disable everything with: githooks/install.sh --uninstall
#
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# --------------------------------------------------------------------------- #
# 🔴 WHERE A "GLOBAL" SETTING CAN ACTUALLY BE WRITTEN
# --------------------------------------------------------------------------- #
# This script used to run `git config --global core.hooksPath "$DIR"`. On a
# home-manager host — which is every machine devrc targets — THAT CANNOT WORK.
#
# MEASURED on the workbench host 2026-08-26:
#   * `git config --global` resolves to `~/.config/git/config`
#   * that path is a symlink into the READ-ONLY nix store
#     (`/nix/store/…-hm_gitconfig`), generated by `nix/programs/git/default.nix`
#   * `~/.gitconfig` does not exist
#   * so the installer died on its FIRST config write:
#         error: could not lock config file …/.config/git/config:
#         Read-only file system
#     rc=255 — before chmod'ing nothing further, before seeding
#     `~/.claude/audit-on-push.env`, before printing anything useful.
#
# Consequence: `core.hooksPath` was never set on this host, so the pre-push test
# gate and the audit hook have never been installable here at all.
#
# 🔴 THE FIX IS NOT "DECLARE IT IN NIX". `nix/programs/git/default.nix` is where
# `core.sshCommand` went (#782/#887) and that was right for THAT setting: an
# ssh keepalive is a host-wide invariant with no opt-out. `core.hooksPath` is
# the opposite — it is an explicitly opt-in install with a documented
# `--uninstall`, and a nix-declared value CANNOT be unset by this script, so
# declaring it there would make `--uninstall` unsatisfiable. It would also be
# inert until someone ran `home-manager switch`.
#
# 🔴 THERE IS NO THIRD LOCATION. git consults exactly two files for global
# scope: `$XDG_CONFIG_HOME/git/config` (default `~/.config/git/config`) and
# `~/.gitconfig`. When home-manager owns the first, the second is the ONLY
# writable global location — so that is the fallback, and it is not a
# workaround, it is the other half of git's own documented pair.
#
# MEASURED, and this is what makes the fallback correct rather than merely
# writable: git reads BOTH files, and `~/.gitconfig` WINS for a key set in both.
# `git config --list --show-origin` with both present shows the home-manager
# file's `rebase.autostash=false`, `diff.algorithm=histogram` and `user.name`
# STILL IN EFFECT alongside `~/.gitconfig`'s `core.hooksPath`. Creating
# `~/.gitconfig` does NOT mask the home-manager config for real git operations.
#
# ⚠ ONE REAL SIDE EFFECT, STATED. Once `~/.gitconfig` exists it becomes the
# single file `--global` READS as well as writes: `git config --global --get
# user.name` then returns nothing on this host, because the home-manager values
# live in the XDG file and `--global` no longer looks there. Effective config is
# unchanged (`git config --get user.name` still answers); only the `--global`
# SCOPE view narrows. No script in devrc reads `git config --global` — checked
# across the tree — but a human debugging with `--global --list` will see less
# than they expect. `--uninstall` removes a `~/.gitconfig` it emptied, which
# restores the original resolution.

_xdg_config() { printf '%s/git/config\n' "${XDG_CONFIG_HOME:-$HOME/.config}"; }

# The file git ITSELF would write a `--global` setting to, by git's own rules:
# `~/.gitconfig` if it exists, else the XDG file if THAT exists, else
# `~/.gitconfig` (created). Reproduced here so the happy path on a non-nix host
# is byte-for-byte the behaviour this script always had.
_git_write_pick() {
  if [ -n "${GIT_CONFIG_GLOBAL:-}" ]; then printf '%s\n' "$GIT_CONFIG_GLOBAL"; return 0; fi
  if [ -e "$HOME/.gitconfig" ]; then printf '%s\n' "$HOME/.gitconfig"; return 0; fi
  local xdg; xdg="$(_xdg_config)"
  if [ -e "$xdg" ]; then printf '%s\n' "$xdg"; return 0; fi
  printf '%s\n' "$HOME/.gitconfig"
}

# Every file that could be holding a global `core.hooksPath` we wrote. Used by
# --uninstall, which must find our value wherever install.sh put it.
_global_candidates() {
  if [ -n "${GIT_CONFIG_GLOBAL:-}" ]; then printf '%s\n' "$GIT_CONFIG_GLOBAL"; return 0; fi
  printf '%s\n' "$HOME/.gitconfig"
  _xdg_config
}

_set_hookspath() {  # $1 = config file. stdout/stderr = git's own diagnostic.
  mkdir -p "$(dirname "$1")" 2>/dev/null || true
  git config --file "$1" core.hooksPath "$DIR"
}

# The EFFECTIVE value, as any later `git push` will see it — not the value we
# think we wrote. Repo pointers are cleared and cwd is moved out of any working
# tree so a repo-local core.hooksPath cannot answer for the global one.
_effective_hookspath() {
  local scratch; scratch="$(mktemp -d)"
  local out=""
  out="$(env -u GIT_DIR -u GIT_WORK_TREE git -C "$scratch" config --get core.hooksPath 2>/dev/null || true)"
  rmdir "$scratch" 2>/dev/null || true
  printf '%s\n' "$out"
}

# --------------------------------------------------------------------------- #
# UNINSTALL
# --------------------------------------------------------------------------- #
# 🔴 ONLY EVER UNSETS A VALUE EQUAL TO $DIR. A global core.hooksPath pointing
# somewhere else belongs to someone else and is left exactly as found — this
# script must never remove a setting it did not write.
if [ "${1:-}" = "--uninstall" ]; then
  cleared=0
  seen=""
  while IFS= read -r f; do
    [ -n "$f" ] || continue
    case " $seen " in *" $f "*) continue ;; esac
    seen="$seen $f"
    [ -f "$f" ] || continue
    current="$(git config --file "$f" --get core.hooksPath 2>/dev/null || true)"
    [ "$current" = "$DIR" ] || continue
    if git config --file "$f" --unset core.hooksPath 2>/dev/null; then
      echo "uninstalled: core.hooksPath cleared from $f (was $DIR)"
      cleared=$((cleared + 1))
      # git leaves a 0-BYTE file behind when the last key goes (measured). If
      # that file is the ~/.gitconfig this installer had to create, removing it
      # restores git's original --global resolution. Guarded on size 0, so it
      # can never delete content — there is none left to delete.
      if [ "$f" = "$HOME/.gitconfig" ] && [ ! -s "$f" ]; then
        rm -f "$f" && echo "  removed now-empty $f"
      fi
    else
      echo "WARNING: core.hooksPath in $f is ours but could NOT be unset" >&2
      echo "         (read-only?) — the hooks will still run. File: $f" >&2
      exit 1
    fi
  done <<EOF
$(_global_candidates)
EOF

  if [ "$cleared" -eq 0 ]; then
    effective="$(_effective_hookspath)"
    echo "nothing to do: no global core.hooksPath of ours found"
    echo "               (effective core.hooksPath is '${effective:-<unset>}', not '$DIR')"
  fi
  exit 0
fi

# --------------------------------------------------------------------------- #
# INSTALL
# --------------------------------------------------------------------------- #
chmod +x "$DIR/pre-push" "$DIR/audit-on-push.sh" "$DIR/tests-on-push.sh" 2>/dev/null || true

PICK="$(_git_write_pick)"
prev="$(git config --file "$PICK" --get core.hooksPath 2>/dev/null || true)"
if [ -z "$prev" ]; then prev="$(_effective_hookspath)"; fi
if [ -n "$prev" ] && [ "$prev" != "$DIR" ]; then
  echo "WARNING: global core.hooksPath was already set to: $prev"
  echo "         overwriting with: $DIR"
  echo "         (your previous global hooks dir will no longer run; move its hooks here if needed)"
fi

TARGET=""
if err="$(_set_hookspath "$PICK" 2>&1)"; then
  TARGET="$PICK"
elif [ -n "${GIT_CONFIG_GLOBAL:-}" ]; then
  # 🔴 NO FALLBACK WHEN GIT_CONFIG_GLOBAL IS SET. That variable is an explicit
  # override — the test suite's isolation guard uses it to keep a real installer
  # run away from the operator's config. Falling back to $HOME/.gitconfig here
  # would write OUTSIDE the file the caller nominated, which is precisely the
  # escape that guard exists to prevent.
  echo "ERROR: GIT_CONFIG_GLOBAL is set to '$GIT_CONFIG_GLOBAL' but is not writable." >&2
  echo "       Refusing to fall back — an explicit override is honoured or nothing is." >&2
  echo "       git said: $err" >&2
  exit 1
elif [ "$PICK" != "$HOME/.gitconfig" ] && err2="$(_set_hookspath "$HOME/.gitconfig" 2>&1)"; then
  TARGET="$HOME/.gitconfig"
  echo "NOTE: $PICK is not writable (home-manager owns it — it is a symlink into"
  echo "      the read-only nix store), so core.hooksPath went to $TARGET instead."
  echo "      git reads both; ~/.gitconfig takes precedence. Nothing else moved."
else
  echo "ERROR: could not write core.hooksPath to ANY global git config." >&2
  echo "       tried: $PICK" >&2
  echo "       git said: $err" >&2
  if [ "${err2+set}" = set ]; then
    echo "       tried: $HOME/.gitconfig" >&2
    echo "       git said: $err2" >&2
  fi
  exit 1
fi

# 🔴 WROTE IS NOT INSTALLED. A write to the XDG file loses to a `core.hooksPath`
# already present in ~/.gitconfig, and the write would still report success — so
# the claim is checked against what git actually resolves, from outside any repo.
effective="$(_effective_hookspath)"
if [ "$effective" != "$DIR" ]; then
  echo "ERROR: wrote core.hooksPath to $TARGET, but git resolves it to" >&2
  echo "       '${effective:-<unset>}' — the install did NOT take effect." >&2
  echo "       Something with higher precedence is overriding it." >&2
  exit 1
fi

# Seed the flag config file at shadow if it doesn't exist yet.
CONF="$HOME/.claude/audit-on-push.env"
if [ ! -f "$CONF" ]; then
  mkdir -p "$(dirname "$CONF")"
  cp "$DIR/audit-on-push.env.example" "$CONF" 2>/dev/null || true
  echo "seeded $CONF (AUDIT_ON_PUSH=shadow — sends nothing until you flip it to 'on')"
fi

echo "installed: core.hooksPath -> $DIR (in $TARGET)"
echo "active hooks: $(ls "$DIR" | grep -vE '\.(sh|md|example)$' | tr '\n' ' ')"
echo
echo "Audit flag is SHADOW by default (logs what it WOULD send, sends nothing)."
echo "  watch shadow decisions: tail -f ~/.claude/audit-on-push.log"
echo "  go live:  echo 'AUDIT_ON_PUSH=on' >> ~/.claude/audit-on-push.env"
echo "  back off: set AUDIT_ON_PUSH=off in ~/.claude/audit-on-push.env"
echo
echo "Test gate is ON by default IN DEVRC ONLY (devrc pushes run the Python"
echo "suite + block on a genuine failure; no-op elsewhere)."
echo "  warn-only: set TESTS_ON_PUSH=shadow in ~/.claude/audit-on-push.env"
echo "  disable:   set TESTS_ON_PUSH=off   in ~/.claude/audit-on-push.env"
echo "  skip one push: DEVRC_SKIP_TESTS=1 git push …"
echo
echo "  uninstall global hook: $DIR/install.sh --uninstall"
