"""Real dedupe: exact byte size first, a BOUNDED head+tail hash to confirm.

Every fixture here is synthetic: temp files full of generated bytes, the
sample library from conftest, an injected clock. No HDD, no browser, no
qBittorrent.

THE PINS ARE DELIBERATELY TWO-DIRECTIONAL. The size signal is a WIDENING —
it makes the router notice things it previously could not — so most of these
fail when the widening is deleted, not when it is over-applied. The name
signal it joins is pinned separately, because "do not regress the old signal"
is exactly the property a rewrite loses silently.
"""
from __future__ import annotations

import os
import sqlite3
import sys
import threading
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import config as config_mod  # noqa: E402
import dedupe as D  # noqa: E402
import server as S  # noqa: E402
from dirindex import FileIndex  # noqa: E402
from fetcher import Fetcher  # noqa: E402
from matcher import find_duplicate, norm_key  # noqa: E402
from safety import UnsafeName  # noqa: E402
import store as store_mod  # noqa: E402
from store import (  # noqa: E402
    MIGRATIONS, SCHEMA_VERSION, Store, source_url_key,
)


def write(path: Path, data: bytes) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    return path


def blob(size: int, *, head: bytes = b"H", middle: bytes = b"M",
         tail: bytes = b"T") -> bytes:
    """A `size`-byte blob whose regions line up EXACTLY with the sampled
    windows: the first HEAD_BYTES, the last TAIL_BYTES, and whatever the
    digest never looks at in between."""
    h = min(size, D.HEAD_BYTES)
    t = min(max(size - D.HEAD_BYTES, 0), D.TAIL_BYTES)
    m = size - h - t
    return (head * h) + (middle * m) + (tail * t)


class CountingOpener:
    """`open` that records how many bytes were actually read."""

    def __init__(self):
        self.read = 0

    def __call__(self, path, mode="rb"):
        outer = self

        class F:
            def __init__(self):
                self._fh = open(path, mode)

            def read(self, n=-1):
                data = self._fh.read(n)
                outer.read += len(data)
                return data

            def seek(self, *a):
                return self._fh.seek(*a)

            def __enter__(self):
                return self

            def __exit__(self, *a):
                self._fh.close()
                return False

        return F()


# --- the bounded digest ----------------------------------------------------- #
def test_the_digest_never_reads_the_whole_file(tmp_path):
    """THE BOUND, asserted in bytes. Widening this to a whole-file read makes
    this test fail by name."""
    size = D.HEAD_BYTES + D.TAIL_BYTES + (4 * 1024 * 1024)
    path = write(tmp_path / "big.mp4", blob(size))
    opener = CountingOpener()
    assert D.partial_digest(path, opener=opener)
    assert opener.read <= D.HEAD_BYTES + D.TAIL_BYTES
    assert opener.read < size / 4


def test_two_files_differing_only_in_the_middle_digest_the_same(tmp_path):
    """The behavioural half of the bound, and the honest cost of it.

    Not an oversight: it is the price of a constant-cost check on multi-GB
    media, and it is affordable only because a duplicate is a WARNING with a
    keep button, never an automatic destruction.
    """
    size = D.HEAD_BYTES + D.TAIL_BYTES + 8192
    a = write(tmp_path / "a.mp4", blob(size, middle=b"1"))
    b = write(tmp_path / "b.mp4", blob(size, middle=b"2"))
    assert a.read_bytes() != b.read_bytes()
    assert D.partial_digest(a) == D.partial_digest(b)


@pytest.mark.parametrize("region", ["head", "tail"])
def test_a_difference_in_either_sampled_window_is_seen(tmp_path, region):
    size = D.HEAD_BYTES + D.TAIL_BYTES + 8192
    base = blob(size)
    other = bytearray(base)
    other[0 if region == "head" else -1] ^= 0xFF
    a = write(tmp_path / "a.mp4", base)
    b = write(tmp_path / "b.mp4", bytes(other))
    assert D.partial_digest(a) != D.partial_digest(b)


# Sizes ACROSS the head/tail boundary. The first implementation guarded the
# tail read with `size > head + tail`, so a file bigger than the head window
# but no bigger than both combined had its tail silently never hashed --
# everything past 128 KiB was unread, and two files differing only in their
# LAST byte confirmed as duplicates. That is a false positive in the one check
# that gates the delete.
@pytest.mark.parametrize("size", [
    1,                              # smaller than anything
    D.HEAD_BYTES - 1,
    D.HEAD_BYTES,                   # exactly the head window
    D.HEAD_BYTES + 1,               # <-- the blind band starts here
    D.HEAD_BYTES + 4096,
    (D.HEAD_BYTES + D.TAIL_BYTES) // 2,
    D.HEAD_BYTES + D.TAIL_BYTES - 1,
    D.HEAD_BYTES + D.TAIL_BYTES,    # <-- and ends here
    D.HEAD_BYTES + D.TAIL_BYTES + 1,
    D.HEAD_BYTES + D.TAIL_BYTES + 65536,
])
def test_the_last_byte_is_always_hashed_at_every_size(tmp_path, size):
    base = bytes(bytearray(b"x" * size))
    other = bytearray(base)
    other[-1] ^= 0xFF
    a = write(tmp_path / "a.bin", base)
    b = write(tmp_path / "b.bin", bytes(other))
    assert D.partial_digest(a) != D.partial_digest(b), (
        f"the final byte of a {size}-byte file was never read")


@pytest.mark.parametrize("size", [
    D.HEAD_BYTES + 1, D.HEAD_BYTES + 4096, D.HEAD_BYTES + D.TAIL_BYTES,
    D.HEAD_BYTES + D.TAIL_BYTES + 65536,
])
def test_the_bound_still_holds_across_the_boundary(tmp_path, size):
    """Clamping the tail start must not turn into reading anything twice, or
    reading more than the two windows."""
    opener = CountingOpener()
    D.partial_digest(write(tmp_path / "a.bin", b"x" * size), opener=opener)
    assert opener.read <= D.HEAD_BYTES + D.TAIL_BYTES
    assert opener.read <= size, "a byte was fed to the digest twice"


def test_the_size_is_part_of_the_digest(tmp_path):
    a = write(tmp_path / "a.bin", b"x" * 100)
    b = write(tmp_path / "b.bin", b"x" * 200)
    assert D.partial_digest(a) != D.partial_digest(b)


def test_a_missing_or_empty_or_unreadable_file_has_no_digest(tmp_path):
    assert D.partial_digest(tmp_path / "nope.mp4") is None
    assert D.partial_digest(write(tmp_path / "empty.mp4", b"")) is None
    assert D.partial_digest(tmp_path) is None          # a directory
    if os.getuid() != 0:
        locked = write(tmp_path / "locked.mp4", b"secret")
        locked.chmod(0o000)
        try:
            assert D.partial_digest(locked) is None
        finally:
            locked.chmod(0o600)


# --- the cache -------------------------------------------------------------- #
def test_the_cache_reuses_a_digest_instead_of_re_reading(tmp_path):
    path = write(tmp_path / "a.mp4", blob(300000))
    cache = D.HashCache()
    opener = CountingOpener()
    first = cache.digest(path, opener=opener)
    after_first = opener.read
    second = cache.digest(path, opener=opener)
    assert first == second
    assert opener.read == after_first, "the second lookup re-read the file"
    assert cache.stats() == {"entries": 1, "hits": 1, "misses": 1}


def test_the_cache_re_hashes_a_file_rewritten_in_place(tmp_path):
    path = write(tmp_path / "a.mp4", blob(300000, head=b"A"))
    cache = D.HashCache()
    first = cache.digest(path)
    os.utime(path, (1000, 1000))
    cache.digest(path)
    write(path, blob(300000, head=b"B"))
    os.utime(path, (2000, 2000))
    assert cache.digest(path) != first


def test_the_cache_forgets_a_file_that_disappeared(tmp_path):
    path = write(tmp_path / "a.mp4", blob(1000))
    cache = D.HashCache()
    assert cache.digest(path)
    path.unlink()
    assert cache.digest(path) is None
    assert len(cache) == 0


def test_the_cache_is_bounded(tmp_path):
    cache = D.HashCache(max_entries=3)
    for i in range(10):
        cache.digest(write(tmp_path / f"f{i}.bin", blob(1000 + i)))
    assert len(cache) <= 3


class RecordingLock:
    """An RLock that counts acquisitions, so "is it locked?" is assertable."""

    def __init__(self):
        self._real = threading.RLock()
        self.entries = 0

    def __enter__(self):
        self.entries += 1
        return self._real.__enter__()

    def __exit__(self, *exc):
        return self._real.__exit__(*exc)


def test_every_cache_mutation_is_taken_under_the_lock(tmp_path):
    """THE STRUCTURAL PIN for the HashCache lock, and the reason it is
    structural rather than a stress test.

    One HashCache is shared by every ThreadingHTTPServer request thread, and
    /dedupe runs on the completion of every download. But under CPython's GIL,
    DELETING THIS LOCK AND RUNNING A STRESS TEST LEAVES IT GREEN -- measured,
    not assumed. A test that passes when the fix is removed is decoration, so
    the lock is asserted directly instead: every entry point that touches
    `_entries`, `hits` or `misses` must take it.

    COUNTED PER SECTION, not merely "was the lock touched at all". `digest()`
    has TWO critical sections -- the cached read, and the insert-plus-eviction
    after the hash -- and asserting only "> 0" let the write half be unlinked
    while the read half kept the test green. That was measured too.
    """
    cache = D.HashCache()
    lock = RecordingLock()
    cache._lock = lock
    path = write(tmp_path / "a.bin", blob(2000))

    def taken(fn):
        before = lock.entries
        fn()
        return lock.entries - before

    # A miss holds the lock TWICE: once to read, once to insert and evict.
    assert taken(lambda: cache.digest(path)) >= 2, (
        "the insert/eviction half of digest() ran unlocked")
    # A hit holds it once, for the read.
    assert taken(lambda: cache.digest(path)) >= 1, (
        "the hit path read the cache unlocked")
    assert taken(lambda: cache.forget(path)) >= 1, (
        "forget() mutated the cache unlocked")
    assert taken(cache.stats) >= 1, "stats() read the cache unlocked"
    assert taken(lambda: len(cache)) >= 1, "__len__ read the cache unlocked"
    # The stat-failed path evicts too.
    assert taken(lambda: cache.digest(tmp_path / "gone.bin")) >= 1, (
        "the missing-file path evicted unlocked")


def test_the_cache_stays_bounded_and_correct_under_concurrent_use(tmp_path):
    """A SMOKE TEST, NOT A PIN -- and labelled so nobody mistakes it for one.

    It exercises the real threaded shape (/dedupe on every completed download,
    one shared cache), but the GIL makes it pass with the lock removed, so it
    cannot be the thing that protects the invariant. See
    `test_every_cache_mutation_is_taken_under_the_lock`, which can.
    """
    paths = [write(tmp_path / f"f{i}.bin", blob(2000 + i)) for i in range(40)]
    truth = {str(p): D.partial_digest(p) for p in paths}
    cache = D.HashCache(max_entries=8)
    wrong: list = []
    barrier = threading.Barrier(6)

    def worker():
        barrier.wait()
        for _ in range(15):
            for p in paths:
                got = cache.digest(p)
                if got != truth[str(p)]:
                    wrong.append((str(p), got))

    threads = [threading.Thread(target=worker) for _ in range(6)]
    for t in threads:
        t.start()
    for t in threads:
        t.join(timeout=60)
    assert not any(t.is_alive() for t in threads), "a worker deadlocked"
    assert wrong == [], f"a concurrent read returned a wrong digest: {wrong[:3]}"
    assert len(cache) <= 8, f"the cap drifted to {len(cache)} under contention"


def test_forget_and_stats_are_safe_while_another_thread_hashes(tmp_path):
    paths = [write(tmp_path / f"g{i}.bin", blob(3000 + i)) for i in range(20)]
    cache = D.HashCache()
    stop = threading.Event()
    errors: list = []

    def churn():
        try:
            while not stop.is_set():
                cache.stats()
                for p in paths:
                    cache.forget(p)
        except Exception as exc:            # a dict mutated during iteration
            errors.append(exc)

    t = threading.Thread(target=churn)
    t.start()
    try:
        for _ in range(20):
            for p in paths:
                cache.digest(p)
    finally:
        stop.set()
        t.join(timeout=30)
    assert not t.is_alive()
    assert errors == [], f"{errors[:2]}"


# --- confirm_duplicate ------------------------------------------------------ #
def test_confirm_matches_identical_content_and_rejects_different(tmp_path):
    cache = D.HashCache()
    write(tmp_path / "Jane Doe" / "new.mp4", blob(200000))
    write(tmp_path / "john-smith" / "same.mp4", blob(200000))
    write(tmp_path / "john-smith" / "other.mp4", blob(200000, head=b"Z"))
    hit, why = D.confirm_duplicate(
        tmp_path, "Jane Doe/new.mp4",
        ["john-smith/other.mp4", "john-smith/same.mp4"], cache)
    assert hit == "john-smith/same.mp4"
    assert "digest" in why

    hit, why = D.confirm_duplicate(tmp_path, "Jane Doe/new.mp4",
                                   ["john-smith/other.mp4"], cache)
    assert hit is None
    assert "none with a matching" in why


def test_confirm_fails_closed_when_the_subject_cannot_be_read(tmp_path):
    write(tmp_path / "john-smith" / "same.mp4", blob(200000))
    hit, why = D.confirm_duplicate(tmp_path, "Jane Doe/gone.mp4",
                                   ["john-smith/same.mp4"], D.HashCache())
    assert hit is None
    assert "could not be read" in why


def test_confirm_never_matches_a_file_against_itself(tmp_path):
    write(tmp_path / "Jane Doe" / "a.mp4", blob(200000))
    hit, why = D.confirm_duplicate(tmp_path, "Jane Doe/a.mp4",
                                   ["Jane Doe/a.mp4"], D.HashCache())
    assert hit is None
    assert "no other file" in why


def test_confirm_skips_an_unreadable_candidate_and_says_so(tmp_path):
    write(tmp_path / "Jane Doe" / "a.mp4", blob(200000))
    hit, why = D.confirm_duplicate(tmp_path, "Jane Doe/a.mp4",
                                   ["john-smith/vanished.mp4"], D.HashCache())
    assert hit is None
    assert "unreadable" in why


def test_confirm_hashes_at_most_the_candidate_cap(tmp_path):
    write(tmp_path / "Jane Doe" / "a.mp4", blob(200000, head=b"Q"))
    cands = []
    for i in range(D.MAX_DUP_CANDIDATES + 6):
        rel = f"john-smith/c{i}.mp4"
        write(tmp_path / rel, blob(200000))
        cands.append(rel)
    cache = D.HashCache()
    D.confirm_duplicate(tmp_path, "Jane Doe/a.mp4", cands, cache)
    # subject + at most MAX_DUP_CANDIDATES others.
    assert cache.misses <= D.MAX_DUP_CANDIDATES + 1


# --- FileIndex.by_size ------------------------------------------------------ #
def test_the_file_index_buckets_by_exact_size(library, clock):
    write(library / "Jane Doe" / "aXNTnnsMMuBsAYEe.mp4", b"x" * 4096)
    write(library / "john-smith" / "75936.mov", b"y" * 4096)
    write(library / "john-smith" / "different.mov", b"y" * 4097)
    idx = FileIndex(library, clock=clock, ttl=60.0)
    rels = sorted(r for r, _ in idx.by_size(4096))
    assert rels == ["Jane Doe/aXNTnnsMMuBsAYEe.mp4", "john-smith/75936.mov"]
    assert [r for r, _ in idx.by_size(4097)] == ["john-smith/different.mov"]
    assert idx.by_size(999999) == []
    assert idx.stats()["sizes"] >= 2


def test_empty_files_never_share_a_size_bucket(library, clock):
    write(library / "Jane Doe" / "a.mp4", b"")
    write(library / "john-smith" / "b.mp4", b"")
    idx = FileIndex(library, clock=clock, ttl=60.0)
    assert idx.by_size(0) == []
    assert idx.by_size("nonsense") == []


# --- find_duplicate --------------------------------------------------------- #
class _SizeIndex:
    """A stub with BOTH accessors, mirroring the real FileIndex contract."""

    def __init__(self, entries):
        self.entries = [(rel, size) for rel, size in entries]

    def by_name_key(self, key):
        out = []
        for rel, size in self.entries:
            name = rel.rsplit("/", 1)[-1]
            stem = name.rsplit(".", 1)[0] if "." in name else name
            if norm_key(stem) == key:
                out.append((rel, size))
        return out

    def by_size(self, size):
        return [e for e in self.entries if e[1] == int(size)]


def test_a_size_match_is_found_when_the_names_are_unrelated():
    """THE WIDENING. Random per-download filenames are why the name signal
    fired zero times in seventeen real downloads; deleting the size branch
    makes this fail."""
    idx = _SizeIndex([("john-smith/75936.mov", 4096)])
    dup = find_duplicate(idx, "Jane Doe", "aXNTnnsMMuBsAYEe.mp4", size=4096)
    assert dup["kind"] == "size"
    assert dup["relpath"] == "john-smith/75936.mov"
    assert dup["where"] == "library"
    assert dup["candidates"] == ["john-smith/75936.mov"]


def test_a_size_miss_reports_nothing():
    idx = _SizeIndex([("john-smith/75936.mov", 4096)])
    assert find_duplicate(idx, "Jane Doe", "aXNTnnsMMuBsAYEe.mp4",
                          size=4097) is None


def test_a_size_of_zero_never_matches():
    """A size of 0 is what /match sees when the response has no
    Content-Length. It must not match every 0-length index entry."""
    idx = _SizeIndex([("john-smith/a.mov", 0), ("john-smith/b.mov", 4096)])
    assert find_duplicate(idx, "Jane Doe", "unrelated.mp4", size=0) is None


def test_the_name_signal_still_fires_on_its_own():
    """DO NOT REGRESS THE OLD SIGNAL. Same stem, different length: not the
    same bytes, still worth saying, and it carries no hash candidates because
    there is nothing a hash could confirm."""
    idx = _SizeIndex([("john-smith/clip01.mp4", 10)])
    dup = find_duplicate(idx, "Jane Doe", "clip01.mp4", size=99)
    assert dup["kind"] == "name"
    assert dup["candidates"] == []


def test_name_and_size_together_outrank_either_alone():
    idx = _SizeIndex([("john-smith/clip01.mp4", 4096),
                      ("Mary_Major/unrelated.mp4", 4096)])
    dup = find_duplicate(idx, "Jane Doe", "clip01.mp4", size=4096)
    assert dup["kind"] == "name+size"
    assert dup["relpath"] == "john-smith/clip01.mp4"
    # Both same-size files are offered to the hash step, best first.
    assert dup["candidates"] == ["john-smith/clip01.mp4",
                                 "Mary_Major/unrelated.mp4"]


def test_a_size_hit_outranks_a_name_hit_of_a_different_length():
    idx = _SizeIndex([("john-smith/clip01.mp4", 10),
                      ("Mary_Major/unrelated.mp4", 4096)])
    dup = find_duplicate(idx, "Jane Doe", "clip01.mp4", size=4096)
    assert dup["kind"] == "size"
    assert dup["relpath"] == "Mary_Major/unrelated.mp4"


def test_a_hit_inside_the_target_directory_wins_and_is_offered_first():
    idx = _SizeIndex([("john-smith/a.mp4", 4096), ("Jane Doe/b.mp4", 4096)])
    dup = find_duplicate(idx, "Jane Doe", "new.mp4", size=4096)
    assert dup["where"] == "target-dir"
    assert dup["relpath"] == "Jane Doe/b.mp4"
    assert dup["candidates"][0] == "Jane Doe/b.mp4"


def test_many_same_size_candidates_are_capped():
    idx = _SizeIndex([(f"john-smith/f{i}.mp4", 4096) for i in range(50)])
    dup = find_duplicate(idx, "Jane Doe", "new.mp4", size=4096)
    assert len(dup["candidates"]) == D.MAX_DUP_CANDIDATES


def test_a_file_is_never_a_duplicate_of_itself():
    idx = _SizeIndex([("Jane Doe/new.mp4", 4096)])
    assert find_duplicate(idx, "Jane Doe", "new.mp4", size=4096,
                          exclude_rel="Jane Doe/new.mp4") is None


def test_an_index_without_by_size_still_answers_on_the_name():
    class NameOnly:
        def by_name_key(self, key):
            return [("john-smith/clip01.mp4", 10)]

    dup = find_duplicate(NameOnly(), "Jane Doe", "clip01.mp4", size=4096)
    assert dup["kind"] == "name"


# --- the /dedupe endpoint --------------------------------------------------- #
@pytest.fixture
def app(cfg, store, dir_index, file_index, library, clock):
    return S.App(cfg, store=store, dir_index=dir_index, file_index=file_index,
                 fetcher=Fetcher(library, runner=lambda *a, **k: None,
                                 clock=clock),
                 clock=clock)


def test_dedupe_confirms_a_size_collision_by_hash(app, library):
    write(library / "john-smith" / "75936.mov", blob(300000))
    write(library / "Jane Doe" / "aXNTnnsMMuBsAYEe.mp4", blob(300000))
    app.files.refresh(force=True)
    out = app.dedupe_check({"relPath": "Jane Doe/aXNTnnsMMuBsAYEe.mp4"})
    assert out["duplicate"] is True
    assert out["dupRelPath"] == "john-smith/75936.mov"
    assert out["kind"] == "size+hash"


def test_dedupe_refuses_a_size_collision_whose_content_differs(app, library):
    write(library / "john-smith" / "75936.mov", blob(300000, head=b"A"))
    write(library / "Jane Doe" / "new.mp4", blob(300000, head=b"B"))
    app.files.refresh(force=True)
    out = app.dedupe_check({"relPath": "Jane Doe/new.mp4"})
    assert out["duplicate"] is False
    assert out["candidates"] == 1
    assert "none with a matching" in out["reason"]


def test_dedupe_reports_a_name_only_hit_as_a_signal_never_a_duplicate(app,
                                                                      library):
    write(library / "john-smith" / "clip01.mp4", blob(4096))
    write(library / "Jane Doe" / "clip01.mp4", blob(8192))
    app.files.refresh(force=True)
    out = app.dedupe_check({"relPath": "Jane Doe/clip01.mp4"})
    assert out["duplicate"] is False
    assert out["signal"]["kind"] == "name"
    assert "different size" in out["reason"]


def test_dedupe_says_nothing_when_the_size_is_unique(app, library):
    write(library / "Jane Doe" / "new.mp4", blob(4096))
    app.files.refresh(force=True)
    out = app.dedupe_check({"relPath": "Jane Doe/new.mp4"})
    assert out["duplicate"] is False
    assert "no other file" in out["reason"]


def test_dedupe_refuses_to_call_an_empty_file_a_duplicate(app, library):
    write(library / "john-smith" / "a.mp4", b"")
    write(library / "Jane Doe" / "b.mp4", b"")
    app.files.refresh(force=True)
    out = app.dedupe_check({"relPath": "Jane Doe/b.mp4"})
    assert out["duplicate"] is False
    assert "empty" in out["reason"]


def test_dedupe_reports_a_file_that_disappeared_as_not_found(app, library):
    with pytest.raises(FileNotFoundError):
        app.dedupe_check({"relPath": "Jane Doe/never-existed.mp4"})


def test_dedupe_refuses_a_path_outside_the_library(app):
    with pytest.raises(UnsafeName):
        app.dedupe_check({"relPath": "../../etc/passwd"})


def test_dedupe_skips_an_unreadable_candidate_without_failing(app, library):
    if os.getuid() == 0:
        pytest.skip("root reads everything")
    locked = write(library / "john-smith" / "locked.mov", blob(300000))
    write(library / "Jane Doe" / "new.mp4", blob(300000))
    app.files.refresh(force=True)
    locked.chmod(0o000)
    try:
        out = app.dedupe_check({"relPath": "Jane Doe/new.mp4"})
    finally:
        locked.chmod(0o600)
    assert out["duplicate"] is False
    assert "unreadable" in out["reason"]


def test_dedupe_reuses_the_hash_cache_across_calls(app, library):
    """A LIBRARY FILE IS HASHED ONCE, not once per colliding download."""
    write(library / "john-smith" / "a.mov", blob(300000))
    write(library / "Jane Doe" / "b.mp4", blob(300000))
    app.files.refresh(force=True)
    assert app.dedupe_check({"relPath": "Jane Doe/b.mp4"})["duplicate"] is True
    assert app.hashes.stats() == {"entries": 2, "hits": 0, "misses": 2}
    assert app.dedupe_check({"relPath": "Jane Doe/b.mp4"})["duplicate"] is True
    stats = app.hashes.stats()
    assert stats["misses"] == 2, "a cached digest was recomputed"
    assert stats["hits"] == 2


def test_a_size_collision_with_many_candidates_hashes_at_most_the_cap(app,
                                                                      library):
    for i in range(D.MAX_DUP_CANDIDATES + 5):
        write(library / "john-smith" / f"c{i}.mov", blob(300000, head=b"A"))
    write(library / "Jane Doe" / "new.mp4", blob(300000, head=b"B"))
    app.files.refresh(force=True)
    out = app.dedupe_check({"relPath": "Jane Doe/new.mp4"})
    assert out["duplicate"] is False
    assert out["candidates"] == D.MAX_DUP_CANDIDATES
    assert app.hashes.stats()["misses"] <= D.MAX_DUP_CANDIDATES + 1


# --- /discard: the provenance proof, BOTH directions ------------------------ #
def _pre_existing(app, library, clock, rel="john-smith/75936.mov", *,
                  size=300000, head=b"H"):
    """The library file a download duplicates: on disk BEFORE the routing
    decision. Back-dated deliberately -- a `keep` newer than the decision is
    now refused, because without that the two halves of a uniquify pair are
    interchangeable and /discard could remove the original."""
    path = write(library / rel, blob(size, head=head))
    os.utime(path, (clock.now - 3600, clock.now - 3600))
    return path


def _routed(app, library, clock, *, rel="Jane Doe/new.mp4",
            download_id="42", size=300000, head=b"H"):
    """A file this router demonstrably just wrote, plus its route row."""
    path = write(library / rel, blob(size, head=head))
    app.store.log_route(dir_name=rel.split("/")[0],
                        filename=path.name, download_id=download_id)
    os.utime(path, (clock.now + 1, clock.now + 1))
    return path


def test_discard_removes_the_new_copy_and_keeps_the_library_one(app, library,
                                                                clock):
    keep = _pre_existing(app, library, clock)
    new = _routed(app, library, clock)
    app.files.refresh(force=True)
    out = app.discard({"relPath": "Jane Doe/new.mp4",
                       "dupRelPath": "john-smith/75936.mov",
                       "downloadId": "42"})
    assert out["discarded"] is True
    assert not new.exists(), "the newly downloaded copy is gone"
    assert keep.exists(), "the pre-existing library file was kept"
    assert (library / S.TRASH_DIR / "new.mp4").is_file()
    assert out["trashRelPath"] == f"{S.TRASH_DIR}/new.mp4"


def test_the_trash_is_invisible_to_both_index_scans(app, library, clock):
    _pre_existing(app, library, clock)
    _routed(app, library, clock)
    app.files.refresh(force=True)
    app.discard({"relPath": "Jane Doe/new.mp4",
                 "dupRelPath": "john-smith/75936.mov", "downloadId": "42"})
    app.dirs.refresh(force=True)
    app.files.refresh(force=True)
    assert S.TRASH_DIR not in app.dirs.name_set()
    assert not any(rel.startswith(S.TRASH_DIR)
                   for rel, _ in app.files.by_size(300000))


def test_discard_can_unlink_when_the_operator_asks_for_it(cfg, store,
                                                          dir_index,
                                                          file_index, library,
                                                          clock):
    cfg.data.setdefault("dedupe", {})["delete_mode"] = "unlink"
    app = S.App(cfg, store=store, dir_index=dir_index, file_index=file_index,
                fetcher=Fetcher(library, runner=lambda *a, **k: None,
                                clock=clock), clock=clock)
    _pre_existing(app, library, clock)
    new = _routed(app, library, clock)
    app.files.refresh(force=True)
    out = app.discard({"relPath": "Jane Doe/new.mp4",
                       "dupRelPath": "john-smith/75936.mov",
                       "downloadId": "42"})
    assert out["mode"] == "unlink"
    assert not new.exists()
    assert not (library / S.TRASH_DIR).exists()


def test_discard_refuses_a_file_with_no_routing_decision(app, library, clock):
    write(library / "john-smith" / "75936.mov", blob(300000))
    write(library / "Jane Doe" / "new.mp4", blob(300000))
    app.files.refresh(force=True)
    with pytest.raises(UnsafeName) as exc:
        app.discard({"relPath": "Jane Doe/new.mp4",
                     "dupRelPath": "john-smith/75936.mov",
                     "downloadId": "999"})
    assert "cannot prove it created" in str(exc.value)
    assert (library / "Jane Doe" / "new.mp4").exists()


def test_discard_refuses_when_the_name_does_not_match_the_download(app,
                                                                   library,
                                                                   clock):
    """A FORGED REQUEST: a real downloadId pointed at a different file."""
    _pre_existing(app, library, clock)
    _routed(app, library, clock)
    victim = write(library / "Mary_Major" / "seeding-payload.mkv",
                   blob(300000))
    os.utime(victim, (clock.now + 1, clock.now + 1))
    app.files.refresh(force=True)
    with pytest.raises(UnsafeName) as exc:
        app.discard({"relPath": "Mary_Major/seeding-payload.mkv",
                     "dupRelPath": "john-smith/75936.mov",
                     "downloadId": "42"})
    assert "cannot prove it created" in str(exc.value)
    assert victim.exists()


def test_discard_refuses_a_file_that_predates_its_routing_decision(app,
                                                                   library,
                                                                   clock):
    """The qBittorrent payload shape: on disk before the decision existed."""
    _pre_existing(app, library, clock)
    old = _routed(app, library, clock)
    os.utime(old, (clock.now - 86400, clock.now - 86400))
    app.files.refresh(force=True)
    with pytest.raises(UnsafeName) as exc:
        app.discard({"relPath": "Jane Doe/new.mp4",
                     "dupRelPath": "john-smith/75936.mov",
                     "downloadId": "42"})
    assert "predates" in str(exc.value)
    assert old.exists()


def test_discard_refuses_a_stale_routing_decision(app, library, clock):
    """AGED. /relocate has no window because a rename is reversible; a delete
    is not, so only a file this router has JUST written may be discarded."""
    _pre_existing(app, library, clock)
    new = _routed(app, library, clock)
    clock.advance(S.DISCARD_MAX_ROUTE_AGE_S + 60)
    app.files.refresh(force=True)
    with pytest.raises(UnsafeName) as exc:
        app.discard({"relPath": "Jane Doe/new.mp4",
                     "dupRelPath": "john-smith/75936.mov",
                     "downloadId": "42"})
    assert "this old" in str(exc.value)
    assert new.exists()


def test_discard_refuses_the_pre_existing_file_it_duplicates(app, library,
                                                             clock):
    """THE CONFUSED DEPUTY: the two paths swapped, with DIFFERENT names.

    Kept for what it covers, but read the uniquify-pair test below before
    trusting it: with different names the identity proof does the work, and
    this test therefore says nothing about the case where the names are the
    same -- which is the case that actually occurred.
    """
    keep = _pre_existing(app, library, clock)
    _routed(app, library, clock)
    app.files.refresh(force=True)
    with pytest.raises(UnsafeName) as exc:
        app.discard({"relPath": "john-smith/75936.mov",
                     "dupRelPath": "Jane Doe/new.mp4",
                     "downloadId": "42"})
    assert "cannot prove it created" in str(exc.value)
    assert keep.exists()


def test_discard_refuses_the_ORIGINAL_half_of_a_uniquify_pair(app, library,
                                                              clock):
    """THE TEST THE PREVIOUS ONE ONLY LOOKED LIKE.

    `names_match` accepts BOTH `new.mp4` and `new (1).mp4` against a route
    recorded as `new.mp4` -- the uniquify tolerance is deliberate and
    irreducible. So with a real uniquify pair the identity proof cannot say
    which side is the new copy, and the only other discriminator was
    "mtime >= route_ts - slack", which any recently written file satisfies.
    /discard could therefore be pointed at the ORIGINAL and would remove it.

    The earlier test passed only because its two fixtures had DIFFERENT names:
    it asserted the specification, not the implementation. Same shape as the
    tail-window defect -- the fixture encoded the intent, so the bug was
    invisible.
    """
    # Both in one directory, same stem: exactly what `conflictAction:
    # "uniquify"` produces when a download collides with an existing file.
    original = write(library / "Jane Doe" / "new.mp4", blob(300000))
    os.utime(original, (clock.now - 3600, clock.now - 3600))
    downloaded = write(library / "Jane Doe" / "new (1).mp4", blob(300000))
    app.store.log_route(dir_name="Jane Doe", filename="new.mp4",
                        download_id="42")
    os.utime(downloaded, (clock.now + 1, clock.now + 1))
    app.files.refresh(force=True)

    # Pointing it at the ORIGINAL must be refused. Two gates can catch this
    # (the source predates its own routing decision; the kept file does not
    # predate it) and either is a correct answer -- what must never happen is
    # the original being removed.
    with pytest.raises(UnsafeName):
        app.discard({"relPath": "Jane Doe/new.mp4",          # the ORIGINAL
                     "dupRelPath": "Jane Doe/new (1).mp4",
                     "downloadId": "42"})
    assert original.exists(), "the pre-existing original was removed"

    # And the legitimate direction still works.
    out = app.discard({"relPath": "Jane Doe/new (1).mp4",
                       "dupRelPath": "Jane Doe/new.mp4", "downloadId": "42"})
    assert out["discarded"] is True
    assert original.exists()
    assert not downloaded.exists()


def test_a_uniquify_pair_written_IN_the_slack_window_refuses_both_ways(
        app, library, clock):
    """THE RESIDUAL GAP THE FIRST FIX LEFT, closed by making the two windows
    disjoint.

    `_prove_created` accepts a source at `mtime >= route_ts - slack`. If the
    kept file only had to be `<= route_ts + slack` there was a 10-second band
    in which BOTH files satisfied BOTH rules -- so the two halves of a uniquify
    pair stayed interchangeable and /discard could still take the original.
    This is the auditor's reproduction shape: everything written at once.
    """
    a = write(library / "Jane Doe" / "new.mp4", blob(300000))
    b = write(library / "Jane Doe" / "new (1).mp4", blob(300000))
    app.store.log_route(dir_name="Jane Doe", filename="new.mp4",
                        download_id="42")
    for path in (a, b):
        os.utime(path, (clock.now, clock.now))       # both AT the decision
    app.files.refresh(force=True)

    for src, keep in (("Jane Doe/new.mp4", "Jane Doe/new (1).mp4"),
                      ("Jane Doe/new (1).mp4", "Jane Doe/new.mp4")):
        with pytest.raises(UnsafeName) as exc:
            app.discard({"relPath": src, "dupRelPath": keep,
                         "downloadId": "42"})
        assert "predate" in str(exc.value)
    assert a.exists() and b.exists(), "fail-closed means BOTH survive"


def test_one_routing_decision_authorises_exactly_one_discard(app, library,
                                                             clock):
    """EVIDENCE THAT IS NEVER CONSUMED IS A CAPABILITY, NOT A PROOF.

    The route row was checked and left in place, so one downloadId removed
    `new.mp4`, `new (1).mp4` and `new (2).mp4` in turn -- each satisfies
    `names_match` against a route recorded as `new.mp4`, and each was inside
    the one-hour window.
    """
    keep = _pre_existing(app, library, clock)
    made = []
    for name in ("new.mp4", "new (1).mp4", "new (2).mp4"):
        path = write(library / "Jane Doe" / name, blob(300000))
        os.utime(path, (clock.now + 1, clock.now + 1))
        made.append(path)
    app.store.log_route(dir_name="Jane Doe", filename="new.mp4",
                        download_id="42")
    app.files.refresh(force=True)

    assert app.discard({"relPath": "Jane Doe/new.mp4",
                        "dupRelPath": "john-smith/75936.mov",
                        "downloadId": "42"})["discarded"] is True
    for name in ("new (1).mp4", "new (2).mp4"):
        with pytest.raises(UnsafeName) as exc:
            app.discard({"relPath": f"Jane Doe/{name}",
                         "dupRelPath": "john-smith/75936.mov",
                         "downloadId": "42"})
        assert "already been used to discard" in str(exc.value)
    assert made[1].exists() and made[2].exists()
    assert keep.exists()
    assert len(app.store.recent_discards()) == 1


def test_discard_refuses_a_file_as_a_duplicate_of_itself(app, library, clock):
    new = _routed(app, library, clock)
    app.files.refresh(force=True)
    with pytest.raises(UnsafeName) as exc:
        app.discard({"relPath": "Jane Doe/new.mp4",
                     "dupRelPath": "./Jane Doe/new.mp4", "downloadId": "42"})
    assert "duplicate of itself" in str(exc.value)
    assert new.exists()


def test_discard_refuses_when_the_kept_file_is_not_there(app, library, clock):
    new = _routed(app, library, clock)
    app.files.refresh(force=True)
    with pytest.raises(UnsafeName) as exc:
        app.discard({"relPath": "Jane Doe/new.mp4",
                     "dupRelPath": "john-smith/gone.mov", "downloadId": "42"})
    assert "is not there" in str(exc.value)
    assert new.exists()


def test_discard_re_proves_the_duplication_at_delete_time(app, library, clock):
    """The load-bearing proof: the bytes must demonstrably still exist
    elsewhere AT THE MOMENT OF THE DELETE, not merely when the toast was
    drawn."""
    keep = _pre_existing(app, library, clock, head=b"A")
    new = _routed(app, library, clock, head=b"A")
    app.files.refresh(force=True)
    # The library file is replaced between the toast and the click.
    write(keep, blob(300000, head=b"Z"))
    with pytest.raises(UnsafeName) as exc:
        app.discard({"relPath": "Jane Doe/new.mp4",
                     "dupRelPath": "john-smith/75936.mov",
                     "downloadId": "42"})
    assert "refusing to discard" in str(exc.value)
    assert new.exists()


def test_discard_refuses_when_the_sizes_no_longer_agree(app, library, clock):
    keep = _pre_existing(app, library, clock)
    new = _routed(app, library, clock)
    app.files.refresh(force=True)
    write(keep, blob(400000))
    os.utime(keep, (clock.now - 3600, clock.now - 3600))   # still pre-existing
    with pytest.raises(UnsafeName) as exc:
        app.discard({"relPath": "Jane Doe/new.mp4",
                     "dupRelPath": "john-smith/75936.mov",
                     "downloadId": "42"})
    assert "no longer the same size" in str(exc.value)
    assert new.exists()


def test_discard_refuses_a_path_outside_the_library(app, library, clock):
    _routed(app, library, clock)
    with pytest.raises(UnsafeName):
        app.discard({"relPath": "../../etc/passwd",
                     "dupRelPath": "Jane Doe/new.mp4", "downloadId": "42"})


def test_discard_drops_the_ownership_claim_for_the_emptied_path(app, library,
                                                                clock):
    _pre_existing(app, library, clock)
    _routed(app, library, clock)
    app.store.record_routed_file("Jane Doe/new.mp4", "42", "Jane Doe")
    app.files.refresh(force=True)
    app.discard({"relPath": "Jane Doe/new.mp4",
                 "dupRelPath": "john-smith/75936.mov", "downloadId": "42"})
    assert app.store.routed_file("Jane Doe/new.mp4") is None


# --- the source-URL ledger -------------------------------------------------- #
def test_the_url_key_is_deterministic_and_conservative():
    assert (source_url_key("HTTPS://Example-Site.test:443/a/b?x=1#frag")
            == "https://example-site.test/a/b?x=1")
    assert (source_url_key("http://example-site.test/a")
            == source_url_key("http://EXAMPLE-SITE.test:80/a"))
    # Different query, different asset: never merged.
    assert (source_url_key("https://example-site.test/get?id=1")
            != source_url_key("https://example-site.test/get?id=2"))
    for junk in ("", None, "not a url", "data:text/plain,hi",
                 "blob:https://example-site.test/abc", "https://"):
        assert source_url_key(junk) == ""


def test_the_ledger_records_and_looks_up_a_routed_url(store):
    store.record_source_url("https://example-site.test/a.mp4",
                            site="example-site.test", dir_name="Jane Doe",
                            download_id="42")
    row = store.source_url("https://example-site.test/a.mp4#anchor")
    assert row["dir"] == "Jane Doe"
    assert row["hits"] == 1
    assert store.source_url("https://example-site.test/b.mp4") is None


def test_the_ledger_counts_repeat_downloads_of_one_url(store):
    for _ in range(3):
        store.record_source_url("https://example-site.test/a.mp4",
                                dir_name="Jane Doe", download_id="42")
    assert store.source_url("https://example-site.test/a.mp4")["hits"] == 3
    assert store.source_url_count() == 1


def test_the_ledger_ignores_a_url_it_cannot_key(store):
    assert store.record_source_url("blob:https://example-site.test/x") == ""
    assert store.source_url_count() == 0


def test_a_correction_re_points_the_ledger(store):
    store.record_source_url("https://example-site.test/a.mp4",
                            dir_name="other", download_id="42")
    assert store.set_source_url_dir("42", "Jane Doe", "Jane Doe/a.mp4") == 1
    row = store.source_url("https://example-site.test/a.mp4")
    assert row["dir"] == "Jane Doe"
    assert row["rel_path"] == "Jane Doe/a.mp4"
    assert store.set_source_url_dir("", "Jane Doe") == 0


def test_match_writes_the_ledger_and_have_reads_it(app):
    app.match({"url": "https://example-site.test/clip.mp4",
               "pageUrl": "https://example-site.test/page",
               "filename": "clip.mp4", "downloadId": "42"})
    out = app.have_url("https://example-site.test/clip.mp4")
    assert out["have"] is True
    assert out["hits"] == 1
    assert app.have_url("https://example-site.test/other.mp4") == {
        "ok": True, "have": False}


def test_relocate_re_points_the_ledger(app, library, clock):
    write(library / "other" / "clip.mp4", b"x" * 32)
    app.match({"url": "https://example-site.test/clip.mp4",
               "filename": "clip.mp4", "downloadId": "42"})
    os.utime(library / "other" / "clip.mp4", (clock.now + 1, clock.now + 1))
    app.relocate({"fromRelPath": "other/clip.mp4", "toDir": "Jane Doe",
                  "downloadId": "42"})
    assert app.have_url("https://example-site.test/clip.mp4")["dir"] == "Jane Doe"


# --- the v5 migration ------------------------------------------------------- #
def test_the_ledger_migration_lands_at_the_current_version(tmp_path):
    store = Store(tmp_path / "db.sqlite3")
    assert store.version() == SCHEMA_VERSION == 6
    names = {r["name"] for r in store.conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table'")}
    assert "source_urls" in names
    idx = {r["name"] for r in store.conn.execute(
        "SELECT name FROM sqlite_master WHERE type='index'")}
    assert "source_urls_download" in idx
    assert "discards" in names, "the discard log (v6) is missing"
    store.close()


def test_migration_5_is_re_runnable_after_a_crash(tmp_path):
    """THE EXACT HAZARD v2's comment records, re-tested for v5: sqlite3
    autocommits DDL, so a crash between the last statement and the
    `PRAGMA user_version` bump re-runs the whole step list on the next open."""
    db = tmp_path / "db.sqlite3"
    Store(db).close()
    conn = sqlite3.connect(str(db))
    conn.execute("PRAGMA user_version=4")   # the table exists, the bump did not
    conn.commit()
    conn.close()

    store = Store(db)                        # must not raise
    assert store.version() == SCHEMA_VERSION
    store.record_source_url("https://example-site.test/a.mp4",
                            dir_name="Jane Doe")
    assert store.source_url("https://example-site.test/a.mp4")["dir"] == "Jane Doe"
    store.close()


def test_the_v5_migration_is_additive_and_preserves_existing_rows(tmp_path,
                                                                  monkeypatch):
    """A LIVE DATABASE IS BEING MIGRATED — the deployed one is at v4 with real
    routes and aliases in it. v4 data must survive untouched."""
    db = tmp_path / "db.sqlite3"
    monkeypatch.setattr(store_mod, "SCHEMA_VERSION", 4)
    old = Store(db)
    assert old.version() == 4
    old.upsert_alias("janedoe", "Jane Doe", "example-site.test",
                     source="title", evidence="e")
    old.log_route(dir_name="Jane Doe", filename="a.mp4", download_id="42")
    old.record_routed_file("Jane Doe/a.mp4", "42", "Jane Doe")
    old.close()
    monkeypatch.undo()

    store = Store(db)
    assert store.version() == SCHEMA_VERSION
    assert store.alias("janedoe", "example-site.test") == "Jane Doe"
    assert store.route_for_download("42")["dir"] == "Jane Doe"
    assert store.routed_file("Jane Doe/a.mp4")["download_id"] == "42"
    assert store.source_url_count() == 0
    store.close()


def test_running_the_v5_step_list_twice_is_a_no_op(tmp_path):
    store = Store(tmp_path / "db.sqlite3")
    store.record_source_url("https://example-site.test/a.mp4",
                            dir_name="Jane Doe")
    for step in MIGRATIONS[5]:
        store._run_migration_step(step)
    assert store.source_url_count() == 1, "a re-run dropped the ledger"
    assert store.migrate() == SCHEMA_VERSION
    store.close()


# --- findings from the adversarial audit ------------------------------------ #
def test_two_hardlinks_are_the_same_file_not_a_duplicate(app, library, clock):
    """HARDLINKS ARE ONE FILE. `resolve()` collapses symlinks and nothing
    else, so it called two links to one inode "two copies" -- the toast would
    claim a duplicate, the delete would free zero bytes, and under `unlink`
    it would remove the very path qBittorrent registered for that torrent.
    Hardlinking a payload into a subject directory is standard seeding
    practice, so this shape really occurs here."""
    payload = write(library / "john-smith" / "seed.mkv", blob(300000))
    link = library / "Jane Doe" / "new.mp4"
    link.parent.mkdir(parents=True, exist_ok=True)
    os.link(payload, link)
    assert payload.stat().st_ino == link.stat().st_ino
    app.store.log_route(dir_name="Jane Doe", filename="new.mp4",
                        download_id="42")
    os.utime(link, (clock.now + 1, clock.now + 1))
    app.files.refresh(force=True)

    with pytest.raises(UnsafeName) as exc:
        app.discard({"relPath": "Jane Doe/new.mp4",
                     "dupRelPath": "john-smith/seed.mkv", "downloadId": "42"})
    assert "same file on disk" in str(exc.value)
    assert link.exists() and payload.exists()
    assert payload.stat().st_nlink == 2, "a seeded link was removed"


def test_dedupe_and_discard_work_under_a_SYMLINKED_library_root(
        tmp_path, clock, dirs_file, monkeypatch):
    """`safe_rel_path` resolves; `cfg.library_root` does not. On the common
    NAS layout (`~/Media` -> `/mnt/pool/Media`) `relative_to` therefore raised
    for EVERY file, and `confirmDuplicate` swallows failures -- so the whole
    feature was silently dead with no diagnostic anywhere."""
    real = tmp_path / "real-library"
    for name in ("Jane Doe", "john-smith", "other"):
        (real / name).mkdir(parents=True)
    link = tmp_path / "library"
    link.symlink_to(real, target_is_directory=True)

    data = config_mod._deep_merge(config_mod.DEFAULTS, {
        "library_root": str(link), "host": "127.0.0.1", "port": 0})
    cfg = config_mod.Config(data, path=tmp_path / "config.toml",
                            state_dir=tmp_path / "state",
                            token_file=tmp_path / "token", dirs_file=dirs_file)
    store = Store(tmp_path / "db.sqlite3", clock=clock)
    app = S.App(cfg, store=store, clock=clock)
    try:
        keep = write(real / "john-smith" / "75936.mov", blob(300000))
        os.utime(keep, (clock.now - 3600, clock.now - 3600))
        new = write(real / "Jane Doe" / "new.mp4", blob(300000))
        app.files.refresh(force=True)

        out = app.dedupe_check({"relPath": "Jane Doe/new.mp4"})
        assert out["duplicate"] is True, out
        assert out["dupRelPath"] == "john-smith/75936.mov"

        app.store.log_route(dir_name="Jane Doe", filename="new.mp4",
                            download_id="42")
        os.utime(new, (clock.now + 1, clock.now + 1))
        done = app.discard({"relPath": "Jane Doe/new.mp4",
                            "dupRelPath": "john-smith/75936.mov",
                            "downloadId": "42"})
        assert done["discarded"] is True
        assert not new.exists()
    finally:
        store.close()


def test_discard_does_not_walk_the_library_before_answering(app, library,
                                                            clock, monkeypatch):
    """The forced index refresh used to run AFTER the rename and BEFORE the
    response -- a synchronous whole-tree walk inside the extension's 15 s
    timeout, for a delete that had already succeeded. On a timeout the user is
    told "Not deleted" about a file that is gone."""
    _pre_existing(app, library, clock)
    _routed(app, library, clock)
    app.files.refresh(force=True)
    walks = []
    monkeypatch.setattr(app.files, "refresh",
                        lambda force=False: walks.append(force))
    app.discard({"relPath": "Jane Doe/new.mp4",
                 "dupRelPath": "john-smith/75936.mov", "downloadId": "42"})
    assert True not in walks, (
        "a forced whole-tree walk is back on the destructive response path")


def test_discard_forgets_the_ownership_claim_under_EITHER_spelling(
        app, library, clock):
    """`routed_files` is keyed on the RAW payload string by _prove_owned and
    move_routed_file, but the discard normalises. A single normalised delete
    silently missed the row, leaving a standing ownership claim at an emptied
    path -- which _prove_owned's short-circuit honours for whatever lands
    there next."""
    _pre_existing(app, library, clock)
    _routed(app, library, clock)
    app.store.record_routed_file("Jane Doe/./new.mp4", "42", "Jane Doe")
    app.files.refresh(force=True)
    app.discard({"relPath": "Jane Doe/./new.mp4",
                 "dupRelPath": "john-smith/75936.mov", "downloadId": "42"})
    assert app.store.routed_file("Jane Doe/./new.mp4") is None
    assert app.store.routed_file("Jane Doe/new.mp4") is None


# --- the destructive path, audited a second time ---------------------------- #
#
# Every test below reproduces a shape a narrow audit of /discard found and the
# first round's tests did not cover. They are SHAPES rather than guards: the
# guards were pinned, the situations were not.

def sparse(path: Path, size: int, *, head: bytes = b"H",
           tail: bytes = b"T") -> Path:
    """A file with a real head and tail and a HOLE in the middle.

    This is what qBittorrent leaves on disk: it preallocates the full length at
    creation, so `st_size` is final from the start, and fills pieces in
    afterwards. With "download first and last pieces first" the two ends land
    early -- so the bounded head+tail digest of a 40%-complete payload is
    byte-identical to the finished file.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "wb") as fh:
        fh.write(head * D.HEAD_BYTES)
        fh.truncate(size)                       # the hole
        fh.seek(size - D.TAIL_BYTES)
        fh.write(tail * D.TAIL_BYTES)
    return path


def test_a_sparse_file_is_recognised_as_preallocated(tmp_path):
    size = D.HEAD_BYTES + D.TAIL_BYTES + (8 * 1024 * 1024)
    part = sparse(tmp_path / "part.mkv", size)
    whole = write(tmp_path / "whole.mkv", blob(size))
    assert part.stat().st_size == whole.stat().st_size
    # The premise of the whole finding: the digests AGREE.
    assert D.partial_digest(part) == D.partial_digest(whole)
    assert S.App._looks_preallocated(part.stat()) is True
    assert S.App._looks_preallocated(whole.stat()) is False


def test_discard_refuses_an_INCOMPLETE_file_as_proof(app, library, clock):
    """F1 -- the finding that inverted the guarantee.

    qBittorrent preallocates, so a partly-downloaded payload has full
    `st_size` from creation and, once its first and last pieces land, a
    head+tail digest identical to a finished copy. /dedupe said
    `duplicate: true` and /discard trashed the COMPLETE browser copy, keeping
    the 40%-shaped partial. No adversary, no forged request.
    """
    size = D.HEAD_BYTES + D.TAIL_BYTES + (4 * 1024 * 1024)
    partial = sparse(library / "john-smith" / "75936.mov", size)
    os.utime(partial, (clock.now - 3600, clock.now - 3600))
    complete = write(library / "Jane Doe" / "new.mp4", blob(size))
    app.store.log_route(dir_name="Jane Doe", filename="new.mp4",
                        download_id="42")
    os.utime(complete, (clock.now + 1, clock.now + 1))
    app.files.refresh(force=True)

    with pytest.raises(UnsafeName) as exc:
        app.discard({"relPath": "Jane Doe/new.mp4",
                     "dupRelPath": "john-smith/75936.mov",
                     "downloadId": "42"})
    assert "sparse" in str(exc.value)
    assert complete.exists(), "the COMPLETE copy was destroyed"
    assert complete.stat().st_size == size


def test_a_sparse_download_is_never_discarded_either(app, library, clock):
    """The same signal on the other side: a file still being written is not a
    thing to delete."""
    size = D.HEAD_BYTES + D.TAIL_BYTES + (4 * 1024 * 1024)
    _pre_existing(app, library, clock, size=size)
    part = sparse(library / "Jane Doe" / "new.mp4", size)
    app.store.log_route(dir_name="Jane Doe", filename="new.mp4",
                        download_id="42")
    os.utime(part, (clock.now + 1, clock.now + 1))
    app.files.refresh(force=True)
    with pytest.raises(UnsafeName) as exc:
        app.discard({"relPath": "Jane Doe/new.mp4",
                     "dupRelPath": "john-smith/75936.mov", "downloadId": "42"})
    assert "sparse" in str(exc.value)
    assert part.exists()


def test_discard_refuses_a_HARDLINKED_source(app, library, clock):
    """F-seed: the standard layout is a payload hardlinked into a subject
    directory. Removing THAT path breaks the seed even though the bytes
    survive -- and the trash does not help, because qBittorrent seeds by
    path."""
    _pre_existing(app, library, clock)
    payload = write(library / "other" / "payload.mkv", blob(300000))
    link = library / "Jane Doe" / "new.mp4"
    link.parent.mkdir(parents=True, exist_ok=True)
    os.link(payload, link)
    app.store.log_route(dir_name="Jane Doe", filename="new.mp4",
                        download_id="42")
    os.utime(link, (clock.now + 1, clock.now + 1))
    app.files.refresh(force=True)
    with pytest.raises(UnsafeName) as exc:
        app.discard({"relPath": "Jane Doe/new.mp4",
                     "dupRelPath": "john-smith/75936.mov", "downloadId": "42"})
    assert "hard link" in str(exc.value)
    assert link.exists() and payload.stat().st_nlink == 2


def test_discard_refuses_a_SYMLINKED_source(app, library, clock):
    """F8 -- `safe_rel_path` RESOLVES, so the discard would have removed the
    TARGET and left a dangling link."""
    _pre_existing(app, library, clock)
    target = write(library / "other" / "real.mkv", blob(300000))
    link = library / "Jane Doe" / "new.mp4"
    link.parent.mkdir(parents=True, exist_ok=True)
    link.symlink_to(target)
    app.store.log_route(dir_name="Jane Doe", filename="new.mp4",
                        download_id="42")
    os.utime(link, (clock.now + 1, clock.now + 1), follow_symlinks=False)
    os.utime(target, (clock.now + 1, clock.now + 1))
    app.files.refresh(force=True)
    with pytest.raises(UnsafeName) as exc:
        app.discard({"relPath": "Jane Doe/new.mp4",
                     "dupRelPath": "john-smith/75936.mov", "downloadId": "42"})
    assert "symlink" in str(exc.value)
    assert target.exists(), "the symlink's TARGET was removed"


def test_a_symlinked_trash_cannot_write_outside_the_library(app, library,
                                                            clock, tmp_path):
    """F3 -- the one path that skipped `safe_rel_path`.

    `os.makedirs(exist_ok=True)` FOLLOWS a symlink, so `os.rename` landed the
    file outside the library root, past the containment that is check #1.
    """
    outside = tmp_path / "somewhere-else"
    outside.mkdir()
    (library / S.TRASH_DIR).symlink_to(outside, target_is_directory=True)
    _pre_existing(app, library, clock)
    new = _routed(app, library, clock)
    app.files.refresh(force=True)
    with pytest.raises(UnsafeName) as exc:
        app.discard({"relPath": "Jane Doe/new.mp4",
                     "dupRelPath": "john-smith/75936.mov", "downloadId": "42"})
    assert "symlink" in str(exc.value)
    assert new.exists()
    assert list(outside.iterdir()) == [], "a file escaped the library root"


def test_a_file_ALREADY_IN_THE_TRASH_is_not_proof(app, library, clock):
    """F5 -- `safe_rel_path` checks containment, not VISIBILITY. Accepting a
    discarded copy as "the bytes exist elsewhere" let two discards empty the
    library of a file entirely: the second was proved against the first's
    corpse."""
    _pre_existing(app, library, clock)
    first = _routed(app, library, clock)
    app.files.refresh(force=True)
    out = app.discard({"relPath": "Jane Doe/new.mp4",
                       "dupRelPath": "john-smith/75936.mov",
                       "downloadId": "42"})
    trashed = out["trashRelPath"]

    second = write(library / "Mary_Major" / "second.mp4", blob(300000))
    app.store.log_route(dir_name="Mary_Major", filename="second.mp4",
                        download_id="43")
    os.utime(second, (clock.now + 1, clock.now + 1))
    with pytest.raises(UnsafeName) as exc:
        app.discard({"relPath": "Mary_Major/second.mp4",
                     "dupRelPath": trashed, "downloadId": "43"})
    assert "already in" in str(exc.value)
    assert second.exists()
    del first


def test_discard_takes_the_serialising_lock(app, library, clock):
    """THE STRUCTURAL PIN for the /discard lock.

    The race below is real but timing-dependent: measured, deleting the lock
    left it GREEN, because the window between one thread's proof and its
    rename is microseconds wide. That is the HashCache lesson again -- a test
    that passes when the fix is removed is decoration -- so the lock is also
    asserted directly.
    """
    lock = RecordingLock()
    app._discard_lock = lock
    _pre_existing(app, library, clock)
    _routed(app, library, clock)
    app.files.refresh(force=True)
    before = lock.entries
    app.discard({"relPath": "Jane Doe/new.mp4",
                 "dupRelPath": "john-smith/75936.mov", "downloadId": "42"})
    assert lock.entries > before, "/discard ran without taking its lock"


def test_two_concurrent_discards_of_one_pair_cannot_both_win(app, library,
                                                             clock,
                                                             monkeypatch):
    """F4 -- each proved the bytes survived in the other, and both won.

    It needs only two duplicate toasts open at once, and under
    `delete_mode = "unlink"` it is unrecoverable.

    A SMOKE TEST, NOT THE PIN -- and labelled so, because measuring beat
    guessing twice here. A bare barrier before the call reproduced nothing
    (the gap between the last proof and the rename is microseconds). Parking
    the first thread INSIDE the critical section until the other arrives gets
    much closer, but still does not fail reliably without the lock, because
    the post-proof re-stat added for F7 independently catches the loser: it
    re-stats the kept file after the digest and finds it renamed away.

    Two guards therefore overlap here, which is good for safety and bad for
    testability. `test_discard_takes_the_serialising_lock` is the pin that
    actually fails when the lock is deleted; this exercises the real threaded
    shape and asserts the INVARIANT (at least one copy survives) rather than
    the mechanism.
    """
    a = write(library / "Jane Doe" / "a.mp4", blob(300000))
    b = write(library / "john-smith" / "b.mp4", blob(300000))
    for name, ident, where in (("a.mp4", "42", "Jane Doe"),
                               ("b.mp4", "43", "john-smith")):
        app.store.log_route(dir_name=where, filename=name, download_id=ident)
    for path in (a, b):
        os.utime(path, (clock.now + 1, clock.now + 1))
    app.files.refresh(force=True)

    arrived = threading.Event()
    both_in = threading.Event()
    real = S.confirm_duplicate

    def rendezvous(root, rel, cands, cache, **kw):
        out = real(root, rel, cands, cache, **kw)
        if arrived.is_set():
            both_in.set()               # the second thread got in: no lock
        else:
            arrived.set()
            both_in.wait(timeout=2.0)   # serialised => times out, as it should
        return out

    monkeypatch.setattr(S, "confirm_duplicate", rendezvous)

    outcomes: list = []

    def go(src, keep, ident):
        try:
            app.discard({"relPath": src, "dupRelPath": keep,
                         "downloadId": ident})
            outcomes.append(("ok", src))
        except Exception as exc:                       # noqa: BLE001
            outcomes.append(("refused", src, str(exc)))

    threads = [
        threading.Thread(target=go, args=("Jane Doe/a.mp4",
                                          "john-smith/b.mp4", "42")),
        threading.Thread(target=go, args=("john-smith/b.mp4",
                                          "Jane Doe/a.mp4", "43")),
    ]
    for t in threads:
        t.start()
    for t in threads:
        t.join(timeout=60)
    assert not any(t.is_alive() for t in threads)
    # THE INVARIANT, which holds however the two threads interleaved: the
    # bytes cannot vanish from the library. Deliberately NOT asserting that
    # `both_in` stayed clear -- that is a statement about the mechanism, and
    # it is the flaky half.
    assert a.exists() or b.exists(), f"BOTH copies were removed: {outcomes}"
    assert sum(1 for o in outcomes if o[0] == "ok") <= 1, outcomes


def test_a_cross_device_trash_fails_closed(app, library, clock, monkeypatch):
    """EXDEV: a multi-mount library root. A copy-then-delete fallback would be
    a NON-ATOMIC destructive operation, which is the last thing this path
    should grow -- so it refuses and says which file to move by hand."""
    _pre_existing(app, library, clock)
    new = _routed(app, library, clock)
    app.files.refresh(force=True)

    def exdev(src, dst):
        raise OSError(18, "Invalid cross-device link")

    monkeypatch.setattr(os, "rename", exdev)
    with pytest.raises(UnsafeName) as exc:
        app.discard({"relPath": "Jane Doe/new.mp4",
                     "dupRelPath": "john-smith/75936.mov", "downloadId": "42"})
    assert "could not move the file into" in str(exc.value)
    assert new.exists()


def test_discard_drops_the_cached_digest_for_the_emptied_path(app, library,
                                                              clock):
    """The one line whose deletion the first round's suite did not notice.

    A stale digest under a path the file has left would answer for whatever
    arrives there next, until its mtime happened to differ.
    """
    _pre_existing(app, library, clock)
    _routed(app, library, clock)
    app.files.refresh(force=True)
    src = str(library / "Jane Doe" / "new.mp4")
    app.hashes.digest(src)
    assert len(app.hashes) >= 1
    app.discard({"relPath": "Jane Doe/new.mp4",
                 "dupRelPath": "john-smith/75936.mov", "downloadId": "42"})
    assert src not in app.hashes._entries, "a stale digest survived the discard"


def test_a_file_changing_under_the_proofs_is_refused(app, library, clock,
                                                     monkeypatch):
    """F7 -- a file still being WRITTEN passed every check and was then renamed
    out from under its own writer, which kept appending into the trash."""
    _pre_existing(app, library, clock)
    new = _routed(app, library, clock)
    app.files.refresh(force=True)

    real = S.confirm_duplicate

    def grow(root, rel, cands, cache, **kw):
        out = real(root, rel, cands, cache, **kw)
        with open(new, "ab") as fh:                   # the writer appends
            fh.write(b"more")
        return out

    monkeypatch.setattr(S, "confirm_duplicate", grow)
    with pytest.raises(UnsafeName) as exc:
        app.discard({"relPath": "Jane Doe/new.mp4",
                     "dupRelPath": "john-smith/75936.mov", "downloadId": "42"})
    assert "still being written" in str(exc.value)
    assert new.exists()


# --- qBittorrent corroboration (F6) ----------------------------------------- #
class _FakeQbt:
    """Enough of QbtClient for derive_live_state, with no network."""

    def __init__(self, torrents, files=None, fail=False):
        self._torrents = torrents
        self._files = files or {}
        self._fail = fail

    def torrents_info(self, hashes=None):
        if self._fail:
            raise RuntimeError("qBittorrent unreachable")
        return list(self._torrents)

    def torrents_files(self, torrent_hash):
        return list(self._files.get(torrent_hash, []))


def _with_qbt(app, client):
    app.cfg.data.setdefault("qbt", {}).update(
        {"username": "u", "password": "p", "url": "http://127.0.0.1:1"})
    app._qbt_client = lambda: client


def test_discard_refuses_a_file_live_qbittorrent_calls_a_payload(app, library,
                                                                 clock):
    """F6 -- `backfill apply` refuses to MOVE anything live qBittorrent cannot
    prove is not a payload, and that is the REVERSIBLE operation. /discard had
    no such check at all."""
    _pre_existing(app, library, clock)
    new = _routed(app, library, clock)
    app.files.refresh(force=True)
    torrent = {"hash": "abc", "save_path": str(library / "Jane Doe"),
               "name": "new.mp4", "content_path": str(new),
               "state": "downloading", "progress": 0.4}
    _with_qbt(app, _FakeQbt([torrent], {"abc": [{"name": "new.mp4"}]}))
    with pytest.raises(UnsafeName) as exc:
        app.discard({"relPath": "Jane Doe/new.mp4",
                     "dupRelPath": "john-smith/75936.mov", "downloadId": "42"})
    assert "torrent payload" in str(exc.value)
    assert new.exists()


def test_discard_refuses_when_qbittorrent_is_configured_but_unreachable(
        app, library, clock):
    """Fail CLOSED, on the same evidence backfill demands for a reversible
    move."""
    _pre_existing(app, library, clock)
    new = _routed(app, library, clock)
    app.files.refresh(force=True)
    _with_qbt(app, _FakeQbt([], fail=True))
    with pytest.raises(UnsafeName) as exc:
        app.discard({"relPath": "Jane Doe/new.mp4",
                     "dupRelPath": "john-smith/75936.mov", "downloadId": "42"})
    assert "could not corroborate" in str(exc.value)
    assert new.exists()


def test_no_qbittorrent_configured_leaves_the_local_guards_standing(
        app, library, clock):
    """Credentials are DELIBERATELY empty on this host, so a guard that only
    works when they are set is not a guard here. Pinning the fallback so the
    permissive branch cannot be widened silently."""
    assert app._qbt_client() is None
    _pre_existing(app, library, clock)
    _routed(app, library, clock)
    app.files.refresh(force=True)
    assert app.discard({"relPath": "Jane Doe/new.mp4",
                        "dupRelPath": "john-smith/75936.mov",
                        "downloadId": "42"})["discarded"] is True


def test_live_qbittorrent_state_is_derived_ONCE_per_discard(app, library,
                                                            clock):
    """`derive_live_state` lists every torrent AND every torrent's files.
    Deriving it per-path turned one delete into two full sweeps of a
    ~1000-torrent instance."""
    _pre_existing(app, library, clock)
    _routed(app, library, clock)
    app.files.refresh(force=True)
    calls = []

    class Counting(_FakeQbt):
        def torrents_info(self, hashes=None):
            calls.append(hashes)
            return super().torrents_info(hashes)

    _with_qbt(app, Counting([]))
    app.discard({"relPath": "Jane Doe/new.mp4",
                 "dupRelPath": "john-smith/75936.mov", "downloadId": "42"})
    assert len(calls) == 1, f"qBittorrent was swept {len(calls)} times"


def test_the_example_config_documents_delete_mode(tmp_path):
    """`delete_mode` decides whether the only destructive path is reversible.
    It was documented in the code, the README and the skill, and NOT in the
    file an operator actually copies."""
    example = Path(__file__).resolve().parent.parent / "config.example.toml"
    text = example.read_text(encoding="utf-8")
    assert "[dedupe]" in text
    assert "delete_mode" in text
    # And the example must parse as the real loader reads it.
    import tomllib
    parsed = tomllib.loads(text)
    assert parsed["dedupe"]["delete_mode"] in ("trash", "unlink")
