"""Real dedupe: exact byte size first, a BOUNDED head+tail hash to confirm.

Every fixture here is synthetic: temp files full of generated bytes, the
sample library from conftest, an injected clock. No HDD, no browser, no
qBittorrent.

THE PINS ARE DELIBERATELY TWO-DIRECTIONAL. The size signal is a WIDENING —
it makes the router notice things it previously could not — so most of these
fail when the widening is deleted, not when it is over-applied. The name
signal it joins is pinned separately, because "do not regress the old signal"
is exactly the property a rewrite loses silently.
"""
from __future__ import annotations

import os
import sqlite3
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import dedupe as D  # noqa: E402
import server as S  # noqa: E402
from dirindex import FileIndex  # noqa: E402
from fetcher import Fetcher  # noqa: E402
from matcher import find_duplicate, norm_key  # noqa: E402
from safety import UnsafeName  # noqa: E402
import store as store_mod  # noqa: E402
from store import (  # noqa: E402
    MIGRATIONS, SCHEMA_VERSION, Store, source_url_key,
)


def write(path: Path, data: bytes) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    return path


def blob(size: int, *, head: bytes = b"H", middle: bytes = b"M",
         tail: bytes = b"T") -> bytes:
    """A `size`-byte blob whose regions line up EXACTLY with the sampled
    windows: the first HEAD_BYTES, the last TAIL_BYTES, and whatever the
    digest never looks at in between."""
    h = min(size, D.HEAD_BYTES)
    t = min(max(size - D.HEAD_BYTES, 0), D.TAIL_BYTES)
    m = size - h - t
    return (head * h) + (middle * m) + (tail * t)


class CountingOpener:
    """`open` that records how many bytes were actually read."""

    def __init__(self):
        self.read = 0

    def __call__(self, path, mode="rb"):
        outer = self

        class F:
            def __init__(self):
                self._fh = open(path, mode)

            def read(self, n=-1):
                data = self._fh.read(n)
                outer.read += len(data)
                return data

            def seek(self, *a):
                return self._fh.seek(*a)

            def __enter__(self):
                return self

            def __exit__(self, *a):
                self._fh.close()
                return False

        return F()


# --- the bounded digest ----------------------------------------------------- #
def test_the_digest_never_reads_the_whole_file(tmp_path):
    """THE BOUND, asserted in bytes. Widening this to a whole-file read makes
    this test fail by name."""
    size = D.HEAD_BYTES + D.TAIL_BYTES + (4 * 1024 * 1024)
    path = write(tmp_path / "big.mp4", blob(size))
    opener = CountingOpener()
    assert D.partial_digest(path, opener=opener)
    assert opener.read <= D.HEAD_BYTES + D.TAIL_BYTES
    assert opener.read < size / 4


def test_two_files_differing_only_in_the_middle_digest_the_same(tmp_path):
    """The behavioural half of the bound, and the honest cost of it.

    Not an oversight: it is the price of a constant-cost check on multi-GB
    media, and it is affordable only because a duplicate is a WARNING with a
    keep button, never an automatic destruction.
    """
    size = D.HEAD_BYTES + D.TAIL_BYTES + 8192
    a = write(tmp_path / "a.mp4", blob(size, middle=b"1"))
    b = write(tmp_path / "b.mp4", blob(size, middle=b"2"))
    assert a.read_bytes() != b.read_bytes()
    assert D.partial_digest(a) == D.partial_digest(b)


@pytest.mark.parametrize("region", ["head", "tail"])
def test_a_difference_in_either_sampled_window_is_seen(tmp_path, region):
    size = D.HEAD_BYTES + D.TAIL_BYTES + 8192
    base = blob(size)
    other = bytearray(base)
    other[0 if region == "head" else -1] ^= 0xFF
    a = write(tmp_path / "a.mp4", base)
    b = write(tmp_path / "b.mp4", bytes(other))
    assert D.partial_digest(a) != D.partial_digest(b)


def test_the_size_is_part_of_the_digest(tmp_path):
    a = write(tmp_path / "a.bin", b"x" * 100)
    b = write(tmp_path / "b.bin", b"x" * 200)
    assert D.partial_digest(a) != D.partial_digest(b)


def test_a_missing_or_empty_or_unreadable_file_has_no_digest(tmp_path):
    assert D.partial_digest(tmp_path / "nope.mp4") is None
    assert D.partial_digest(write(tmp_path / "empty.mp4", b"")) is None
    assert D.partial_digest(tmp_path) is None          # a directory
    if os.getuid() != 0:
        locked = write(tmp_path / "locked.mp4", b"secret")
        locked.chmod(0o000)
        try:
            assert D.partial_digest(locked) is None
        finally:
            locked.chmod(0o600)


# --- the cache -------------------------------------------------------------- #
def test_the_cache_reuses_a_digest_instead_of_re_reading(tmp_path):
    path = write(tmp_path / "a.mp4", blob(300000))
    cache = D.HashCache()
    opener = CountingOpener()
    first = cache.digest(path, opener=opener)
    after_first = opener.read
    second = cache.digest(path, opener=opener)
    assert first == second
    assert opener.read == after_first, "the second lookup re-read the file"
    assert cache.stats() == {"entries": 1, "hits": 1, "misses": 1}


def test_the_cache_re_hashes_a_file_rewritten_in_place(tmp_path):
    path = write(tmp_path / "a.mp4", blob(300000, head=b"A"))
    cache = D.HashCache()
    first = cache.digest(path)
    os.utime(path, (1000, 1000))
    cache.digest(path)
    write(path, blob(300000, head=b"B"))
    os.utime(path, (2000, 2000))
    assert cache.digest(path) != first


def test_the_cache_forgets_a_file_that_disappeared(tmp_path):
    path = write(tmp_path / "a.mp4", blob(1000))
    cache = D.HashCache()
    assert cache.digest(path)
    path.unlink()
    assert cache.digest(path) is None
    assert len(cache) == 0


def test_the_cache_is_bounded(tmp_path):
    cache = D.HashCache(max_entries=3)
    for i in range(10):
        cache.digest(write(tmp_path / f"f{i}.bin", blob(1000 + i)))
    assert len(cache) <= 3


# --- confirm_duplicate ------------------------------------------------------ #
def test_confirm_matches_identical_content_and_rejects_different(tmp_path):
    cache = D.HashCache()
    write(tmp_path / "Jane Doe" / "new.mp4", blob(200000))
    write(tmp_path / "john-smith" / "same.mp4", blob(200000))
    write(tmp_path / "john-smith" / "other.mp4", blob(200000, head=b"Z"))
    hit, why = D.confirm_duplicate(
        tmp_path, "Jane Doe/new.mp4",
        ["john-smith/other.mp4", "john-smith/same.mp4"], cache)
    assert hit == "john-smith/same.mp4"
    assert "digest" in why

    hit, why = D.confirm_duplicate(tmp_path, "Jane Doe/new.mp4",
                                   ["john-smith/other.mp4"], cache)
    assert hit is None
    assert "none with a matching" in why


def test_confirm_fails_closed_when_the_subject_cannot_be_read(tmp_path):
    write(tmp_path / "john-smith" / "same.mp4", blob(200000))
    hit, why = D.confirm_duplicate(tmp_path, "Jane Doe/gone.mp4",
                                   ["john-smith/same.mp4"], D.HashCache())
    assert hit is None
    assert "could not be read" in why


def test_confirm_never_matches_a_file_against_itself(tmp_path):
    write(tmp_path / "Jane Doe" / "a.mp4", blob(200000))
    hit, why = D.confirm_duplicate(tmp_path, "Jane Doe/a.mp4",
                                   ["Jane Doe/a.mp4"], D.HashCache())
    assert hit is None
    assert "no other file" in why


def test_confirm_skips_an_unreadable_candidate_and_says_so(tmp_path):
    write(tmp_path / "Jane Doe" / "a.mp4", blob(200000))
    hit, why = D.confirm_duplicate(tmp_path, "Jane Doe/a.mp4",
                                   ["john-smith/vanished.mp4"], D.HashCache())
    assert hit is None
    assert "unreadable" in why


def test_confirm_hashes_at_most_the_candidate_cap(tmp_path):
    write(tmp_path / "Jane Doe" / "a.mp4", blob(200000, head=b"Q"))
    cands = []
    for i in range(D.MAX_DUP_CANDIDATES + 6):
        rel = f"john-smith/c{i}.mp4"
        write(tmp_path / rel, blob(200000))
        cands.append(rel)
    cache = D.HashCache()
    D.confirm_duplicate(tmp_path, "Jane Doe/a.mp4", cands, cache)
    # subject + at most MAX_DUP_CANDIDATES others.
    assert cache.misses <= D.MAX_DUP_CANDIDATES + 1


# --- FileIndex.by_size ------------------------------------------------------ #
def test_the_file_index_buckets_by_exact_size(library, clock):
    write(library / "Jane Doe" / "aXNTnnsMMuBsAYEe.mp4", b"x" * 4096)
    write(library / "john-smith" / "75936.mov", b"y" * 4096)
    write(library / "john-smith" / "different.mov", b"y" * 4097)
    idx = FileIndex(library, clock=clock, ttl=60.0)
    rels = sorted(r for r, _ in idx.by_size(4096))
    assert rels == ["Jane Doe/aXNTnnsMMuBsAYEe.mp4", "john-smith/75936.mov"]
    assert [r for r, _ in idx.by_size(4097)] == ["john-smith/different.mov"]
    assert idx.by_size(999999) == []
    assert idx.stats()["sizes"] >= 2


def test_empty_files_never_share_a_size_bucket(library, clock):
    write(library / "Jane Doe" / "a.mp4", b"")
    write(library / "john-smith" / "b.mp4", b"")
    idx = FileIndex(library, clock=clock, ttl=60.0)
    assert idx.by_size(0) == []
    assert idx.by_size("nonsense") == []


# --- find_duplicate --------------------------------------------------------- #
class _SizeIndex:
    """A stub with BOTH accessors, mirroring the real FileIndex contract."""

    def __init__(self, entries):
        self.entries = [(rel, size) for rel, size in entries]

    def by_name_key(self, key):
        out = []
        for rel, size in self.entries:
            name = rel.rsplit("/", 1)[-1]
            stem = name.rsplit(".", 1)[0] if "." in name else name
            if norm_key(stem) == key:
                out.append((rel, size))
        return out

    def by_size(self, size):
        return [e for e in self.entries if e[1] == int(size)]


def test_a_size_match_is_found_when_the_names_are_unrelated():
    """THE WIDENING. Random per-download filenames are why the name signal
    fired zero times in seventeen real downloads; deleting the size branch
    makes this fail."""
    idx = _SizeIndex([("john-smith/75936.mov", 4096)])
    dup = find_duplicate(idx, "Jane Doe", "aXNTnnsMMuBsAYEe.mp4", size=4096)
    assert dup["kind"] == "size"
    assert dup["relpath"] == "john-smith/75936.mov"
    assert dup["where"] == "library"
    assert dup["candidates"] == ["john-smith/75936.mov"]


def test_a_size_miss_reports_nothing():
    idx = _SizeIndex([("john-smith/75936.mov", 4096)])
    assert find_duplicate(idx, "Jane Doe", "aXNTnnsMMuBsAYEe.mp4",
                          size=4097) is None


def test_a_size_of_zero_never_matches():
    """A size of 0 is what /match sees when the response has no
    Content-Length. It must not match every 0-length index entry."""
    idx = _SizeIndex([("john-smith/a.mov", 0), ("john-smith/b.mov", 4096)])
    assert find_duplicate(idx, "Jane Doe", "unrelated.mp4", size=0) is None


def test_the_name_signal_still_fires_on_its_own():
    """DO NOT REGRESS THE OLD SIGNAL. Same stem, different length: not the
    same bytes, still worth saying, and it carries no hash candidates because
    there is nothing a hash could confirm."""
    idx = _SizeIndex([("john-smith/clip01.mp4", 10)])
    dup = find_duplicate(idx, "Jane Doe", "clip01.mp4", size=99)
    assert dup["kind"] == "name"
    assert dup["candidates"] == []


def test_name_and_size_together_outrank_either_alone():
    idx = _SizeIndex([("john-smith/clip01.mp4", 4096),
                      ("Mary_Major/unrelated.mp4", 4096)])
    dup = find_duplicate(idx, "Jane Doe", "clip01.mp4", size=4096)
    assert dup["kind"] == "name+size"
    assert dup["relpath"] == "john-smith/clip01.mp4"
    # Both same-size files are offered to the hash step, best first.
    assert dup["candidates"] == ["john-smith/clip01.mp4",
                                 "Mary_Major/unrelated.mp4"]


def test_a_size_hit_outranks_a_name_hit_of_a_different_length():
    idx = _SizeIndex([("john-smith/clip01.mp4", 10),
                      ("Mary_Major/unrelated.mp4", 4096)])
    dup = find_duplicate(idx, "Jane Doe", "clip01.mp4", size=4096)
    assert dup["kind"] == "size"
    assert dup["relpath"] == "Mary_Major/unrelated.mp4"


def test_a_hit_inside_the_target_directory_wins_and_is_offered_first():
    idx = _SizeIndex([("john-smith/a.mp4", 4096), ("Jane Doe/b.mp4", 4096)])
    dup = find_duplicate(idx, "Jane Doe", "new.mp4", size=4096)
    assert dup["where"] == "target-dir"
    assert dup["relpath"] == "Jane Doe/b.mp4"
    assert dup["candidates"][0] == "Jane Doe/b.mp4"


def test_many_same_size_candidates_are_capped():
    idx = _SizeIndex([(f"john-smith/f{i}.mp4", 4096) for i in range(50)])
    dup = find_duplicate(idx, "Jane Doe", "new.mp4", size=4096)
    assert len(dup["candidates"]) == D.MAX_DUP_CANDIDATES


def test_a_file_is_never_a_duplicate_of_itself():
    idx = _SizeIndex([("Jane Doe/new.mp4", 4096)])
    assert find_duplicate(idx, "Jane Doe", "new.mp4", size=4096,
                          exclude_rel="Jane Doe/new.mp4") is None


def test_an_index_without_by_size_still_answers_on_the_name():
    class NameOnly:
        def by_name_key(self, key):
            return [("john-smith/clip01.mp4", 10)]

    dup = find_duplicate(NameOnly(), "Jane Doe", "clip01.mp4", size=4096)
    assert dup["kind"] == "name"


# --- the /dedupe endpoint --------------------------------------------------- #
@pytest.fixture
def app(cfg, store, dir_index, file_index, library, clock):
    return S.App(cfg, store=store, dir_index=dir_index, file_index=file_index,
                 fetcher=Fetcher(library, runner=lambda *a, **k: None,
                                 clock=clock),
                 clock=clock)


def test_dedupe_confirms_a_size_collision_by_hash(app, library):
    write(library / "john-smith" / "75936.mov", blob(300000))
    write(library / "Jane Doe" / "aXNTnnsMMuBsAYEe.mp4", blob(300000))
    app.files.refresh(force=True)
    out = app.dedupe_check({"relPath": "Jane Doe/aXNTnnsMMuBsAYEe.mp4"})
    assert out["duplicate"] is True
    assert out["dupRelPath"] == "john-smith/75936.mov"
    assert out["kind"] == "size+hash"


def test_dedupe_refuses_a_size_collision_whose_content_differs(app, library):
    write(library / "john-smith" / "75936.mov", blob(300000, head=b"A"))
    write(library / "Jane Doe" / "new.mp4", blob(300000, head=b"B"))
    app.files.refresh(force=True)
    out = app.dedupe_check({"relPath": "Jane Doe/new.mp4"})
    assert out["duplicate"] is False
    assert out["candidates"] == 1
    assert "none with a matching" in out["reason"]


def test_dedupe_reports_a_name_only_hit_as_a_signal_never_a_duplicate(app,
                                                                      library):
    write(library / "john-smith" / "clip01.mp4", blob(4096))
    write(library / "Jane Doe" / "clip01.mp4", blob(8192))
    app.files.refresh(force=True)
    out = app.dedupe_check({"relPath": "Jane Doe/clip01.mp4"})
    assert out["duplicate"] is False
    assert out["signal"]["kind"] == "name"
    assert "different size" in out["reason"]


def test_dedupe_says_nothing_when_the_size_is_unique(app, library):
    write(library / "Jane Doe" / "new.mp4", blob(4096))
    app.files.refresh(force=True)
    out = app.dedupe_check({"relPath": "Jane Doe/new.mp4"})
    assert out["duplicate"] is False
    assert "no other file" in out["reason"]


def test_dedupe_refuses_to_call_an_empty_file_a_duplicate(app, library):
    write(library / "john-smith" / "a.mp4", b"")
    write(library / "Jane Doe" / "b.mp4", b"")
    app.files.refresh(force=True)
    out = app.dedupe_check({"relPath": "Jane Doe/b.mp4"})
    assert out["duplicate"] is False
    assert "empty" in out["reason"]


def test_dedupe_reports_a_file_that_disappeared_as_not_found(app, library):
    with pytest.raises(FileNotFoundError):
        app.dedupe_check({"relPath": "Jane Doe/never-existed.mp4"})


def test_dedupe_refuses_a_path_outside_the_library(app):
    with pytest.raises(UnsafeName):
        app.dedupe_check({"relPath": "../../etc/passwd"})


def test_dedupe_skips_an_unreadable_candidate_without_failing(app, library):
    if os.getuid() == 0:
        pytest.skip("root reads everything")
    locked = write(library / "john-smith" / "locked.mov", blob(300000))
    write(library / "Jane Doe" / "new.mp4", blob(300000))
    app.files.refresh(force=True)
    locked.chmod(0o000)
    try:
        out = app.dedupe_check({"relPath": "Jane Doe/new.mp4"})
    finally:
        locked.chmod(0o600)
    assert out["duplicate"] is False
    assert "unreadable" in out["reason"]


def test_dedupe_reuses_the_hash_cache_across_calls(app, library):
    """A LIBRARY FILE IS HASHED ONCE, not once per colliding download."""
    write(library / "john-smith" / "a.mov", blob(300000))
    write(library / "Jane Doe" / "b.mp4", blob(300000))
    app.files.refresh(force=True)
    assert app.dedupe_check({"relPath": "Jane Doe/b.mp4"})["duplicate"] is True
    assert app.hashes.stats() == {"entries": 2, "hits": 0, "misses": 2}
    assert app.dedupe_check({"relPath": "Jane Doe/b.mp4"})["duplicate"] is True
    stats = app.hashes.stats()
    assert stats["misses"] == 2, "a cached digest was recomputed"
    assert stats["hits"] == 2


def test_a_size_collision_with_many_candidates_hashes_at_most_the_cap(app,
                                                                      library):
    for i in range(D.MAX_DUP_CANDIDATES + 5):
        write(library / "john-smith" / f"c{i}.mov", blob(300000, head=b"A"))
    write(library / "Jane Doe" / "new.mp4", blob(300000, head=b"B"))
    app.files.refresh(force=True)
    out = app.dedupe_check({"relPath": "Jane Doe/new.mp4"})
    assert out["duplicate"] is False
    assert out["candidates"] == D.MAX_DUP_CANDIDATES
    assert app.hashes.stats()["misses"] <= D.MAX_DUP_CANDIDATES + 1


# --- /discard: the provenance proof, BOTH directions ------------------------ #
def _routed(app, library, clock, *, rel="Jane Doe/new.mp4",
            download_id="42", size=300000, head=b"H"):
    """A file this router demonstrably just wrote, plus its route row."""
    path = write(library / rel, blob(size, head=head))
    app.store.log_route(dir_name=rel.split("/")[0],
                        filename=path.name, download_id=download_id)
    os.utime(path, (clock.now + 1, clock.now + 1))
    return path


def test_discard_removes_the_new_copy_and_keeps_the_library_one(app, library,
                                                                clock):
    keep = write(library / "john-smith" / "75936.mov", blob(300000))
    new = _routed(app, library, clock)
    app.files.refresh(force=True)
    out = app.discard({"relPath": "Jane Doe/new.mp4",
                       "dupRelPath": "john-smith/75936.mov",
                       "downloadId": "42"})
    assert out["discarded"] is True
    assert not new.exists(), "the newly downloaded copy is gone"
    assert keep.exists(), "the pre-existing library file was kept"
    assert (library / S.TRASH_DIR / "new.mp4").is_file()
    assert out["trashRelPath"] == f"{S.TRASH_DIR}/new.mp4"


def test_the_trash_is_invisible_to_both_index_scans(app, library, clock):
    write(library / "john-smith" / "75936.mov", blob(300000))
    _routed(app, library, clock)
    app.files.refresh(force=True)
    app.discard({"relPath": "Jane Doe/new.mp4",
                 "dupRelPath": "john-smith/75936.mov", "downloadId": "42"})
    app.dirs.refresh(force=True)
    app.files.refresh(force=True)
    assert S.TRASH_DIR not in app.dirs.name_set()
    assert not any(rel.startswith(S.TRASH_DIR)
                   for rel, _ in app.files.by_size(300000))


def test_discard_can_unlink_when_the_operator_asks_for_it(cfg, store,
                                                          dir_index,
                                                          file_index, library,
                                                          clock):
    cfg.data.setdefault("dedupe", {})["delete_mode"] = "unlink"
    app = S.App(cfg, store=store, dir_index=dir_index, file_index=file_index,
                fetcher=Fetcher(library, runner=lambda *a, **k: None,
                                clock=clock), clock=clock)
    write(library / "john-smith" / "75936.mov", blob(300000))
    new = _routed(app, library, clock)
    app.files.refresh(force=True)
    out = app.discard({"relPath": "Jane Doe/new.mp4",
                       "dupRelPath": "john-smith/75936.mov",
                       "downloadId": "42"})
    assert out["mode"] == "unlink"
    assert not new.exists()
    assert not (library / S.TRASH_DIR).exists()


def test_discard_refuses_a_file_with_no_routing_decision(app, library, clock):
    write(library / "john-smith" / "75936.mov", blob(300000))
    write(library / "Jane Doe" / "new.mp4", blob(300000))
    app.files.refresh(force=True)
    with pytest.raises(UnsafeName) as exc:
        app.discard({"relPath": "Jane Doe/new.mp4",
                     "dupRelPath": "john-smith/75936.mov",
                     "downloadId": "999"})
    assert "cannot prove it created" in str(exc.value)
    assert (library / "Jane Doe" / "new.mp4").exists()


def test_discard_refuses_when_the_name_does_not_match_the_download(app,
                                                                   library,
                                                                   clock):
    """A FORGED REQUEST: a real downloadId pointed at a different file."""
    write(library / "john-smith" / "75936.mov", blob(300000))
    _routed(app, library, clock)
    victim = write(library / "Mary_Major" / "seeding-payload.mkv",
                   blob(300000))
    os.utime(victim, (clock.now + 1, clock.now + 1))
    app.files.refresh(force=True)
    with pytest.raises(UnsafeName) as exc:
        app.discard({"relPath": "Mary_Major/seeding-payload.mkv",
                     "dupRelPath": "john-smith/75936.mov",
                     "downloadId": "42"})
    assert "cannot prove it created" in str(exc.value)
    assert victim.exists()


def test_discard_refuses_a_file_that_predates_its_routing_decision(app,
                                                                   library,
                                                                   clock):
    """The qBittorrent payload shape: on disk before the decision existed."""
    write(library / "john-smith" / "75936.mov", blob(300000))
    old = _routed(app, library, clock)
    os.utime(old, (clock.now - 86400, clock.now - 86400))
    app.files.refresh(force=True)
    with pytest.raises(UnsafeName) as exc:
        app.discard({"relPath": "Jane Doe/new.mp4",
                     "dupRelPath": "john-smith/75936.mov",
                     "downloadId": "42"})
    assert "predates" in str(exc.value)
    assert old.exists()


def test_discard_refuses_a_stale_routing_decision(app, library, clock):
    """AGED. /relocate has no window because a rename is reversible; a delete
    is not, so only a file this router has JUST written may be discarded."""
    write(library / "john-smith" / "75936.mov", blob(300000))
    new = _routed(app, library, clock)
    clock.advance(S.DISCARD_MAX_ROUTE_AGE_S + 60)
    app.files.refresh(force=True)
    with pytest.raises(UnsafeName) as exc:
        app.discard({"relPath": "Jane Doe/new.mp4",
                     "dupRelPath": "john-smith/75936.mov",
                     "downloadId": "42"})
    assert "this old" in str(exc.value)
    assert new.exists()


def test_discard_refuses_the_pre_existing_file_it_duplicates(app, library,
                                                             clock):
    """THE CONFUSED DEPUTY: the two paths swapped. The library file must never
    be the one removed, even with a valid downloadId in hand."""
    keep = write(library / "john-smith" / "75936.mov", blob(300000))
    os.utime(keep, (clock.now + 1, clock.now + 1))
    _routed(app, library, clock)
    app.files.refresh(force=True)
    with pytest.raises(UnsafeName) as exc:
        app.discard({"relPath": "john-smith/75936.mov",
                     "dupRelPath": "Jane Doe/new.mp4",
                     "downloadId": "42"})
    assert "cannot prove it created" in str(exc.value)
    assert keep.exists()


def test_discard_refuses_a_file_as_a_duplicate_of_itself(app, library, clock):
    new = _routed(app, library, clock)
    app.files.refresh(force=True)
    with pytest.raises(UnsafeName) as exc:
        app.discard({"relPath": "Jane Doe/new.mp4",
                     "dupRelPath": "./Jane Doe/new.mp4", "downloadId": "42"})
    assert "duplicate of itself" in str(exc.value)
    assert new.exists()


def test_discard_refuses_when_the_kept_file_is_not_there(app, library, clock):
    new = _routed(app, library, clock)
    app.files.refresh(force=True)
    with pytest.raises(UnsafeName) as exc:
        app.discard({"relPath": "Jane Doe/new.mp4",
                     "dupRelPath": "john-smith/gone.mov", "downloadId": "42"})
    assert "is not there" in str(exc.value)
    assert new.exists()


def test_discard_re_proves_the_duplication_at_delete_time(app, library, clock):
    """The load-bearing proof: the bytes must demonstrably still exist
    elsewhere AT THE MOMENT OF THE DELETE, not merely when the toast was
    drawn."""
    keep = write(library / "john-smith" / "75936.mov", blob(300000, head=b"A"))
    new = _routed(app, library, clock, head=b"A")
    app.files.refresh(force=True)
    # The library file is replaced between the toast and the click.
    write(keep, blob(300000, head=b"Z"))
    with pytest.raises(UnsafeName) as exc:
        app.discard({"relPath": "Jane Doe/new.mp4",
                     "dupRelPath": "john-smith/75936.mov",
                     "downloadId": "42"})
    assert "refusing to discard" in str(exc.value)
    assert new.exists()


def test_discard_refuses_when_the_sizes_no_longer_agree(app, library, clock):
    keep = write(library / "john-smith" / "75936.mov", blob(300000))
    new = _routed(app, library, clock)
    app.files.refresh(force=True)
    write(keep, blob(400000))
    with pytest.raises(UnsafeName) as exc:
        app.discard({"relPath": "Jane Doe/new.mp4",
                     "dupRelPath": "john-smith/75936.mov",
                     "downloadId": "42"})
    assert "no longer the same size" in str(exc.value)
    assert new.exists()


def test_discard_refuses_a_path_outside_the_library(app, library, clock):
    _routed(app, library, clock)
    with pytest.raises(UnsafeName):
        app.discard({"relPath": "../../etc/passwd",
                     "dupRelPath": "Jane Doe/new.mp4", "downloadId": "42"})


def test_discard_drops_the_ownership_claim_for_the_emptied_path(app, library,
                                                                clock):
    write(library / "john-smith" / "75936.mov", blob(300000))
    _routed(app, library, clock)
    app.store.record_routed_file("Jane Doe/new.mp4", "42", "Jane Doe")
    app.files.refresh(force=True)
    app.discard({"relPath": "Jane Doe/new.mp4",
                 "dupRelPath": "john-smith/75936.mov", "downloadId": "42"})
    assert app.store.routed_file("Jane Doe/new.mp4") is None


# --- the source-URL ledger -------------------------------------------------- #
def test_the_url_key_is_deterministic_and_conservative():
    assert (source_url_key("HTTPS://Example-Site.test:443/a/b?x=1#frag")
            == "https://example-site.test/a/b?x=1")
    assert (source_url_key("http://example-site.test/a")
            == source_url_key("http://EXAMPLE-SITE.test:80/a"))
    # Different query, different asset: never merged.
    assert (source_url_key("https://example-site.test/get?id=1")
            != source_url_key("https://example-site.test/get?id=2"))
    for junk in ("", None, "not a url", "data:text/plain,hi",
                 "blob:https://example-site.test/abc", "https://"):
        assert source_url_key(junk) == ""


def test_the_ledger_records_and_looks_up_a_routed_url(store):
    store.record_source_url("https://example-site.test/a.mp4",
                            site="example-site.test", dir_name="Jane Doe",
                            download_id="42")
    row = store.source_url("https://example-site.test/a.mp4#anchor")
    assert row["dir"] == "Jane Doe"
    assert row["hits"] == 1
    assert store.source_url("https://example-site.test/b.mp4") is None


def test_the_ledger_counts_repeat_downloads_of_one_url(store):
    for _ in range(3):
        store.record_source_url("https://example-site.test/a.mp4",
                                dir_name="Jane Doe", download_id="42")
    assert store.source_url("https://example-site.test/a.mp4")["hits"] == 3
    assert store.source_url_count() == 1


def test_the_ledger_ignores_a_url_it_cannot_key(store):
    assert store.record_source_url("blob:https://example-site.test/x") == ""
    assert store.source_url_count() == 0


def test_a_correction_re_points_the_ledger(store):
    store.record_source_url("https://example-site.test/a.mp4",
                            dir_name="other", download_id="42")
    assert store.set_source_url_dir("42", "Jane Doe", "Jane Doe/a.mp4") == 1
    row = store.source_url("https://example-site.test/a.mp4")
    assert row["dir"] == "Jane Doe"
    assert row["rel_path"] == "Jane Doe/a.mp4"
    assert store.set_source_url_dir("", "Jane Doe") == 0


def test_match_writes_the_ledger_and_have_reads_it(app):
    app.match({"url": "https://example-site.test/clip.mp4",
               "pageUrl": "https://example-site.test/page",
               "filename": "clip.mp4", "downloadId": "42"})
    out = app.have_url("https://example-site.test/clip.mp4")
    assert out["have"] is True
    assert out["hits"] == 1
    assert app.have_url("https://example-site.test/other.mp4") == {
        "ok": True, "have": False}


def test_relocate_re_points_the_ledger(app, library, clock):
    write(library / "other" / "clip.mp4", b"x" * 32)
    app.match({"url": "https://example-site.test/clip.mp4",
               "filename": "clip.mp4", "downloadId": "42"})
    os.utime(library / "other" / "clip.mp4", (clock.now + 1, clock.now + 1))
    app.relocate({"fromRelPath": "other/clip.mp4", "toDir": "Jane Doe",
                  "downloadId": "42"})
    assert app.have_url("https://example-site.test/clip.mp4")["dir"] == "Jane Doe"


# --- the v5 migration ------------------------------------------------------- #
def test_the_ledger_migration_lands_at_version_5(tmp_path):
    store = Store(tmp_path / "db.sqlite3")
    assert store.version() == SCHEMA_VERSION == 5
    names = {r["name"] for r in store.conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table'")}
    assert "source_urls" in names
    idx = {r["name"] for r in store.conn.execute(
        "SELECT name FROM sqlite_master WHERE type='index'")}
    assert "source_urls_download" in idx
    store.close()


def test_migration_5_is_re_runnable_after_a_crash(tmp_path):
    """THE EXACT HAZARD v2's comment records, re-tested for v5: sqlite3
    autocommits DDL, so a crash between the last statement and the
    `PRAGMA user_version` bump re-runs the whole step list on the next open."""
    db = tmp_path / "db.sqlite3"
    Store(db).close()
    conn = sqlite3.connect(str(db))
    conn.execute("PRAGMA user_version=4")   # the table exists, the bump did not
    conn.commit()
    conn.close()

    store = Store(db)                        # must not raise
    assert store.version() == SCHEMA_VERSION
    store.record_source_url("https://example-site.test/a.mp4",
                            dir_name="Jane Doe")
    assert store.source_url("https://example-site.test/a.mp4")["dir"] == "Jane Doe"
    store.close()


def test_the_v5_migration_is_additive_and_preserves_existing_rows(tmp_path,
                                                                  monkeypatch):
    """A LIVE DATABASE IS BEING MIGRATED — the deployed one is at v4 with real
    routes and aliases in it. v4 data must survive untouched."""
    db = tmp_path / "db.sqlite3"
    monkeypatch.setattr(store_mod, "SCHEMA_VERSION", 4)
    old = Store(db)
    assert old.version() == 4
    old.upsert_alias("janedoe", "Jane Doe", "example-site.test",
                     source="title", evidence="e")
    old.log_route(dir_name="Jane Doe", filename="a.mp4", download_id="42")
    old.record_routed_file("Jane Doe/a.mp4", "42", "Jane Doe")
    old.close()
    monkeypatch.undo()

    store = Store(db)
    assert store.version() == 5
    assert store.alias("janedoe", "example-site.test") == "Jane Doe"
    assert store.route_for_download("42")["dir"] == "Jane Doe"
    assert store.routed_file("Jane Doe/a.mp4")["download_id"] == "42"
    assert store.source_url_count() == 0
    store.close()


def test_running_the_v5_step_list_twice_is_a_no_op(tmp_path):
    store = Store(tmp_path / "db.sqlite3")
    store.record_source_url("https://example-site.test/a.mp4",
                            dir_name="Jane Doe")
    for step in MIGRATIONS[5]:
        store._run_migration_step(step)
    assert store.source_url_count() == 1, "a re-run dropped the ledger"
    assert store.migrate() == SCHEMA_VERSION
    store.close()
