// session-env.js — export the CURRENT opencode session id into every bash tool
// invocation as `OPENCODE_SESSION_ID`.
//
// WHY: a nested `opencode` run had no identity of its own. Anything it shells
// out to saw the OUTER Claude Code session's `CLAUDE_CODE_SESSION_ID` — which
// opencode's CLI inherits and hands to its tool shells verbatim — so the
// browser bridge could only fail closed and attribute nothing (it declares
// `X-Session-Origin: opencode-inherited` and drops the session key). With this
// variable present, `browser`'s `derive_session_id` emits an `opencode:<id>`
// tier and the bridge writes a REAL session key: the same value
// `source='opencode'` rows in activity.events carry, because activity-plugin.js
// emits `session: input.sessionID` from the sibling `tool.execute.after` hook
// with the same id this hook receives. So the two populations JOIN.
//
// --------------------------------------------------------------------------- #
// 🔴 WHY THIS IS ITS OWN FILE, and not a third hook in activity-plugin.js or a
// line in the generated env.js:
//
//   * BLAST RADIUS. `shell.env` runs in the bash tool's PRE-SPAWN critical
//     path. activity-plugin.js is fire-and-forget telemetry that runs AFTER a
//     tool call completes. Those are different failure domains, and #298 is the
//     reason to keep them apart: one edit to activity-plugin.js (`export const
//     _internals = …`) made opencode reject the WHOLE module and killed all
//     opencode telemetry on both hosts for ~11 hours, silently. A file that can
//     only take itself down is the smaller hazard.
//   * activity-plugin.js's registered hook keys are a PINNED SCOPE DECISION
//     (scripts/collector/opencode/tests/test_plugin.py::
//     test_only_real_hooks_are_registered), made after three dead handlers sat
//     there firing zero times for five days. Widening that ledger to smuggle in
//     an unrelated hook would spend a guard that exists for a different reason.
//   * env.js is GENERATED by nix/home.nix from nix/agent-handles.nix — a pure
//     table of paths, stamped "do NOT edit". Hand-written behaviour inside a nix
//     string literal cannot be exercised as a real file by the python suite, and
//     mixes generated data with logic.
//   * PRECEDENT: guard.js and ledger.js are already single-purpose plugin files
//     in this directory. Two plugins may register the SAME hook key and both
//     run — guard.js and activity-plugin.js both register
//     `tool.execute.before` and both demonstrably work in production (the guard
//     blocks; the telemetry rows carry real durations). env.js + this file are
//     the same arrangement for `shell.env`.
//
// --------------------------------------------------------------------------- #
// 🔴 DO NOT ADD A NAMED EXPORT. opencode's loader iterates EVERY named export of
// a plugin module: a non-function export throws "Plugin export is not a
// function" and aborts the whole module, and a function export is CALLED as a
// plugin factory. Measured on 1.18.4 — see
// scripts/collector/opencode/tests/test_plugin.py's export-contract block.
//
// DEPLOYMENT CONSTRAINTS (same as guard.js / ledger.js / env.js): the plugin
// glob is `{plugin,plugins}/*.{ts,js}` — NON-RECURSIVE, `.ts`/`.js` only, a
// `.mjs` will NOT load. It must land directly at
// ~/.config/opencode/plugin/session-env.js, and NEVER also in `plugins/`
// (plural), which the glob also reads — a copy in each loads the plugin twice.

export const SessionEnvPlugin = async () => ({
  // The hook MUTATES `output.env`; it does not return a new object. The bash
  // tool builds its environment as `{...process.env, ...pluginEnv}`, so what we
  // write here WINS over anything inherited — which is the point: an opencode
  // run nested inside another opencode run overwrites its parent's id with its
  // own, and the innermost session is the one credited.
  "shell.env": async (input, output) => {
    // 🔴 The whole body is wrapped. A throwing `shell.env` sits in front of
    // every bash call opencode makes; losing an attribution is recoverable,
    // breaking the bash tool is not.
    try {
      // 🔴 NO EXPLICIT SHAPE GUARD ON `output`, DELIBERATELY, AND MEASURED. An
      // earlier draft opened with
      //     if (!output || typeof output.env !== "object" || output.env === null) return;
      // which reads as defence-in-depth and has NO observable effect: every
      // shape it rejects (`undefined`, `null`, no `env`, `env: null`) makes the
      // assignment below throw, and the catch turns that into exactly the same
      // outcome — nothing written, nothing propagated. Deleting the whole line
      // SURVIVED a 7-case battery of malformed inputs precisely because it could
      // not change any answer. A guard nothing can distinguish from its absence
      // is not a guard; worse, it invites someone to conclude the catch is
      // redundant. The catch IS the control here, and removing it kills all 7.
      //
      // `input &&` below is NOT in that category and must stay: with no input
      // object, reading `.sessionID` throws and the catch would leave an
      // ANCESTOR's id standing in the overlay. That one IS observable, and
      // test_an_unidentifiable_call_sets_the_variable_empty_not_stale's
      // undefined/null rows are what kill its removal.
      const id = input && input.sessionID;
      // 🔴 THE PTY PATH FIRES THIS HOOK WITH `{cwd}` ONLY — no sessionID. Set
      // the variable to the EMPTY STRING there rather than leaving it alone:
      // `output.env` is an overlay, so "leaving it alone" means whatever a
      // parent process exported survives, and a stale inherited id is exactly
      // the misattribution this file exists to prevent. Empty is falsy to the
      // consumer's `[ -n "${OPENCODE_SESSION_ID:-}" ]` test, so it degrades to
      // the same fail-closed path as no plugin at all.
      output.env.OPENCODE_SESSION_ID =
        typeof id === "string" && id.length > 0 ? id : "";
    } catch {
      // best-effort — never break the bash tool
    }
  },
});
