#!/usr/bin/env python3
"""Guards for `scripts/round0-attribution-rate.py` — the round-0 attribution RATE.

🔴 WHAT THESE ARE, HONESTLY. The script is NEW, so almost every test here is an
INVARIANT GUARD: it pins a property the implementation is supposed to have, and
none of them is a regression test, because there is no bug they were written
after. Calling them regression coverage would be a false claim about what has
been observed to fail (`claude/RULES.md` → "vacuous-guards"), so each such name
says `invariant`.

THE ONE EXCEPTION, and it is the important one: the two-way renderer pin
(`ANCHORS` against `scripts/lib/operator_asks.py`) is watched go RED against a
REWORDED and against a WIDENED copy of that module — a real red→green pair, run
as part of the suite rather than claimed in prose. It is the guard that matters
most, because a one-sided matcher would silently reclassify every report as
out-of-population and print a clean, wrong NOT MEASURABLE.

🔴 EVERY FIXTURE IS SYNTHETIC. devrc is PUBLIC and the corpus under measurement
is the operator's transcripts, so no record here is copied from one: the briefs
are generated by calling `operator_asks.render()` on invented inputs, and the
report text is written here. `scripts/tests/test_no_captured_text.py` gates the
tree for captured text; nothing in this file is derived from a real session.
"""
from __future__ import annotations

import importlib.util
import io
import json
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT = REPO_ROOT / "scripts" / "round0-attribution-rate.py"
OPERATOR_ASKS = REPO_ROOT / "scripts" / "lib" / "operator_asks.py"

PROJECT = "-home-zach-workspace-a-repo"
PRE_TS = "2026-09-20T10:00:00.000Z"          # before the cut used below
POST_TS = "2026-09-27T12:00:00.000Z"         # after it
CUT_ISO = "2026-09-27T00:49:10-05:00"        # `31033cdb`'s author date


def _load(path, name):
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    # Registered BEFORE exec: a module holding a `@dataclass` cannot be executed
    # unregistered (dataclasses resolve annotations via sys.modules).
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


@pytest.fixture(scope="module")
def r0():
    return _load(SCRIPT, "round0_attribution_rate")


@pytest.fixture(scope="module")
def oa(r0):
    return r0.load_operator_asks()


@pytest.fixture(autouse=True)
def _no_env_leak(monkeypatch, r0):
    """Neither env door may leak in from the caller's shell."""
    monkeypatch.delenv(r0.CORPUS_ENV, raising=False)
    monkeypatch.delenv(r0.OPERATOR_ASKS_ENV, raising=False)


# --------------------------------------------------------------------------- #
# fixture builders — synthetic transcripts
# --------------------------------------------------------------------------- #
def ledger(requirements=7, unattributed=2) -> str:
    """The round-0 ledger line, as the skill tells the auditor to write it."""
    return (f"## Round 0\nround 0 · requirements: {requirements} "
            f"(unattributed: {unattributed})\n")


def assistant(text, ts=PRE_TS) -> dict:
    return {"type": "assistant", "timestamp": ts,
            "message": {"role": "assistant",
                        "content": [{"type": "text", "text": text}]}}


def tool_result(text, ts=PRE_TS) -> dict:
    return {"type": "user", "timestamp": ts,
            "message": {"role": "user",
                        "content": [{"type": "tool_result", "tool_use_id": "t1",
                                     "content": text}]}}


def user_text(text, ts=PRE_TS) -> dict:
    return {"type": "user", "timestamp": ts,
            "message": {"role": "user",
                        "content": [{"type": "text", "text": text}]}}


def brief(r0, oa, shape, tmp_path) -> str:
    """A real `render()` output — the strings the instrument matches on.

    Built from the script's own probe matrix so the fixture cannot drift away
    from what production emits: `answered`, `unmeasured`, `dropped`, `no-source`.
    """
    probes = r0.renderer_probes(oa, tmp_path / "no-such-projects-root")
    return probes[shape]


def write(path: Path, records) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(json.dumps(r) for r in records) + "\n")
    return path


def corpus_with(tmp_path, sessions: dict) -> Path:
    """sessions: {relative transcript path -> [records]} under a fresh corpus."""
    root = tmp_path / "corpus"
    for rel, records in sessions.items():
        write(root / rel, records)
    root.mkdir(parents=True, exist_ok=True)
    return root


def run(r0, argv) -> tuple[int, str]:
    """-> (exit code, stdout text). `fail()` exits, so SystemExit is caught.

    The code is asserted to be an INT: this script exits only with its own
    documented codes, and a `str`/`None` exit would otherwise compare unequal to
    every expected code and read as an ordinary wrong-code failure.
    """
    buf = io.StringIO()
    try:
        code = r0.main(argv, out_stream=buf)
    except SystemExit as e:
        code = e.code
    assert isinstance(code, int), f"non-int exit {code!r}\n{buf.getvalue()}"
    return code, buf.getvalue()


def rates(r0, corpus, tmp_path, extra=()) -> tuple[int, str, dict]:
    """Run over `corpus` and return (code, stdout, the JSON bucket report).

    🔴 THE REPORT'S EXISTENCE IS ASSERTED HERE, never returned as `None`. A
    `None` payload would turn every caller's `payload["buckets"]…` arithmetic
    into a `TypeError` far from the cause — and a caller that checked only
    truthiness would sail past a run that produced no report at all, which is
    the vacuous-pass shape. A missing file is this helper's own failure, with the
    run's output attached.
    """
    out = tmp_path / "rates.json"
    code, text = run(r0, ["--corpus", str(corpus), "--cut-iso", CUT_ISO,
                          "--json", str(out), *extra])
    assert out.exists(), (
        f"the run wrote no --json report (exit {code}), so there are no buckets "
        f"to assert on. Its output was:\n{text}")
    payload = json.loads(out.read_text())
    assert isinstance(payload, dict) and "buckets" in payload, payload
    return code, text, payload


# --------------------------------------------------------------------------- #
# 1. THE TWO-WAY RENDERER PIN — the one guard with a real red->green pair
# --------------------------------------------------------------------------- #
def test_the_anchor_ledger_matches_what_operator_asks_emits_today(r0, oa, tmp_path):
    """GREEN half of the pair: every anchor is reachable and nothing is
    unmatched, against the live renderer."""
    probes = r0.renderer_probes(oa, tmp_path / "nope")
    r0.check_pins(oa, probes)               # must not raise

    seen, unmatched = set(), []
    for text in probes.values():
        lines = r0.session_source_lines(oa.SOURCE_SESSION,
                                        r0.sources_block_lines(text))
        _roles, ids, bad = r0.match_anchors(lines)
        seen |= ids
        unmatched += bad
    assert unmatched == [], (
        "operator_asks.render() emits a session-transcript source line the "
        f"ANCHORS ledger does not cover (GROWS): {unmatched}")
    assert seen == {a["id"] for a in r0.ANCHORS}, (
        "an anchor matches nothing a live render emits (SHRINKS): "
        f"{sorted({a['id'] for a in r0.ANCHORS} - seen)}")


def _reworded_copy(tmp_path, old, new, name="operator_asks.py"):
    """A copy of operator_asks.py with exactly ONE substitution applied.

    Asserts the substitution HAPPENED — a mutation that silently applies to
    nothing is a test that proves nothing.
    """
    src = OPERATOR_ASKS.read_text()
    assert src.count(old) == 1, (
        f"the mutation target {old!r} occurs {src.count(old)}x in "
        "operator_asks.py — the mutant would be ambiguous or inert")
    copy = tmp_path / name
    copy.write_text(src.replace(old, new))
    return copy


def test_the_pin_goes_RED_when_the_renderer_REWORDS_its_answered_line(
        r0, tmp_path, monkeypatch, capsys):
    """RED half, SHRINKS direction. This is the failure the whole instrument
    turns on: reword that line and every report classifies out-of-population,
    the denominator empties, and the run prints a clean NOT MEASURABLE that is
    indistinguishable from today's honest answer."""
    copy = _reworded_copy(tmp_path, "session(s) NAMED BY",
                          "session(s) IDENTIFIED VIA")
    monkeypatch.setenv(r0.OPERATOR_ASKS_ENV, str(copy))
    code, _out = run(r0, ["--corpus", str(tmp_path), "--cut-iso", CUT_ISO])
    err = capsys.readouterr().err
    assert code == r0.EXIT_PIN, f"expected exit {r0.EXIT_PIN}, got {code}"
    # A reword trips BOTH halves at once, and the refusal must say so — the old
    # spelling matches nothing AND the new line is covered by nothing.
    assert "SHRINKS" in err and "answered" in err, err
    assert "GROWS" in err and "signature of a REWORD" in err, err


def test_the_pin_goes_RED_when_the_renderer_GAINS_an_uncovered_source_line(
        r0, tmp_path, monkeypatch, capsys):
    """RED half, GROWS direction: a new session-transcript source line whose
    meaning for the in-population test nobody has decided."""
    copy = _reworded_copy(
        tmp_path,
        'lines += ["", "**Sources read:**"]',
        'lines += ["", "**Sources read:**",\n'
        '              f"  {SOURCE_SESSION}: a shape nobody has classified"]')
    monkeypatch.setenv(r0.OPERATOR_ASKS_ENV, str(copy))
    code, _out = run(r0, ["--corpus", str(tmp_path), "--cut-iso", CUT_ISO])
    err = capsys.readouterr().err
    assert code == r0.EXIT_PIN, f"expected exit {r0.EXIT_PIN}, got {code}"
    assert "GROWS" in err, err
    # A PURE addition must NOT be reported as a reword: every existing anchor
    # still matches, so only one half fails. This is what makes the two-way pin
    # diagnostic rather than just red.
    assert "SHRINKS" not in err, err


def test_the_pin_goes_RED_when_THIS_modules_own_ledger_is_mutated(
        r0, oa, tmp_path, monkeypatch, capsys):
    """RED half, mutating the LEDGER rather than the renderer — the same
    disagreement from the other side."""
    mutant = tuple(dict(a, text="session(s) LISTED BY") if a["id"] == "answered"
                   else a for a in r0.ANCHORS)
    monkeypatch.setattr(r0, "ANCHORS", mutant)
    with pytest.raises(SystemExit) as exc:
        r0.check_pins(oa, r0.renderer_probes(oa, tmp_path / "nope"))
    assert exc.value.code == r0.EXIT_PIN
    err = capsys.readouterr().err
    assert "SHRINKS" in err and "answered" in err, err
    assert "GROWS" in err, err


def test_a_renderer_that_indents_its_own_heading_fails_the_pin(
        r0, tmp_path, monkeypatch, capsys):
    """invariant: line-anchoring is a CLAIM about the renderer, so the renderer
    is checked against it. A block emitted indented would be invisible to the
    walk, and this is what makes that loud instead of silent."""
    copy = _reworded_copy(tmp_path, "    lines = [HEADING, \"\"]",
                          "    lines = ['    ' + HEADING, \"\"]")
    monkeypatch.setenv(r0.OPERATOR_ASKS_ENV, str(copy))
    code, _out = run(r0, ["--corpus", str(tmp_path), "--cut-iso", CUT_ISO])
    assert code == r0.EXIT_PIN
    assert "START of a line" in capsys.readouterr().err


def test_an_unreadable_renderer_is_a_pin_FAILURE_not_a_pass(
        r0, tmp_path, monkeypatch, capsys):
    """invariant: if the module the anchors describe cannot be read, nothing
    verified them — proceeding would report a confident zero."""
    monkeypatch.setenv(r0.OPERATOR_ASKS_ENV, str(tmp_path / "absent.py"))
    code, _out = run(r0, ["--corpus", str(tmp_path), "--cut-iso", CUT_ISO])
    assert code == r0.EXIT_PIN
    assert "does not exist" in capsys.readouterr().err


# --------------------------------------------------------------------------- #
# 2. THE THREE DISPOSITIONS
# --------------------------------------------------------------------------- #
def test_a_session_whose_asks_block_ANSWERED_is_in_population(
        r0, oa, tmp_path):
    """invariant: the in-population test is the asks block's own emitted text."""
    corpus = corpus_with(tmp_path, {
        f"{PROJECT}/s1.jsonl": [
            user_text(brief(r0, oa, "answered", tmp_path), ts=POST_TS),
            assistant(ledger(), ts=POST_TS)]})
    reports, facts = r0.walk(corpus, oa.SOURCE_SESSION)
    assert [r.disposition for r in reports] == ["in"]
    assert facts.dispositions["in"] == 1


def test_a_session_whose_asks_block_could_not_read_a_trailer_is_out(r0, oa, tmp_path):
    """invariant: the measured OUT case — the block says the session-transcript
    source did not answer."""
    corpus = corpus_with(tmp_path, {
        f"{PROJECT}/s1.jsonl": [
            user_text(brief(r0, oa, "unmeasured", tmp_path), ts=POST_TS),
            assistant(ledger(), ts=POST_TS)]})
    reports, _f = r0.walk(corpus, oa.SOURCE_SESSION)
    assert [r.disposition for r in reports] == ["out"]


def test_a_session_with_NO_asks_block_is_out_of_population(r0, oa, tmp_path):
    """invariant: a pre-fix report. Out, never UNKNOWN — nothing about it is
    unreadable."""
    corpus = corpus_with(tmp_path, {
        f"{PROJECT}/s1.jsonl": [assistant(ledger(), ts=PRE_TS)]})
    reports, _f = r0.walk(corpus, oa.SOURCE_SESSION)
    assert [r.disposition for r in reports] == ["out"]


def test_an_asks_block_with_an_unparseable_Sources_block_is_UNKNOWN(
        r0, oa, tmp_path):
    """invariant: present-but-unreadable is its OWN answer. The fixture is a
    heading at line start with no Sources block, which is what a truncated brief
    looks like on disk."""
    truncated = f"{oa.HEADING}\n\nsome asks were inlined here\n"
    corpus = corpus_with(tmp_path, {
        f"{PROJECT}/s1.jsonl": [user_text(truncated, ts=POST_TS),
                                assistant(ledger(), ts=POST_TS)]})
    reports, _f = r0.walk(corpus, oa.SOURCE_SESSION)
    assert [r.disposition for r in reports] == ["UNKNOWN"]


def test_a_source_READ_of_operator_asks_is_not_an_asks_block(r0, oa, tmp_path):
    """invariant, and the reason line-anchoring exists: MEASURED, 39 of 51
    blocks carrying the heading substring on this host are reads of the module's
    own source, and they were inventing UNKNOWNs. A tool_result holding the
    source must classify as `out`, not UNKNOWN."""
    source_read = OPERATOR_ASKS.read_text()
    assert r0.ANCHOR_BLOCK in source_read and r0.ANCHOR_SOURCES in source_read, (
        "this fixture only tests anything while operator_asks.py's own source "
        "carries both anchors — it does today, in HEADING and in render()")
    corpus = corpus_with(tmp_path, {
        f"{PROJECT}/s1.jsonl": [tool_result(source_read, ts=POST_TS),
                                assistant(ledger(), ts=POST_TS)]})
    reports, _f = r0.walk(corpus, oa.SOURCE_SESSION)
    assert [r.disposition for r in reports] == ["out"]


def test_UNKNOWN_is_excluded_from_the_rates_DENOMINATOR(r0, oa, tmp_path):
    """invariant, asserted as ARITHMETIC rather than as a label: the numbers of
    the UNKNOWN reports must appear in NO bucket total."""
    sessions = {}
    for i in range(10):                       # in-population, distinct numbers
        sessions[f"{PROJECT}/in{i}.jsonl"] = [
            user_text(brief(r0, oa, "answered", tmp_path), ts=POST_TS),
            assistant(ledger(5, 1), ts=POST_TS)]
    for i in range(3):                        # UNKNOWN, numbers that cannot mix
        sessions[f"{PROJECT}/unk{i}.jsonl"] = [
            user_text(f"{oa.HEADING}\n\nno sources block here\n", ts=POST_TS),
            assistant(ledger(9, 7), ts=POST_TS)]
    sessions[f"{PROJECT}/pre.jsonl"] = [assistant(ledger(4, 3), ts=PRE_TS)]
    corpus = corpus_with(tmp_path, sessions)

    code, text, payload = rates(r0, corpus, tmp_path)
    post_in = payload["buckets"]["post_in"]
    assert post_in["n"] == 10
    assert post_in["requirements"] == 50 and post_in["unattributed"] == 10, (
        "the three UNKNOWN reports (9/7 each) leaked into the denominator: "
        f"{post_in}")
    assert payload["post_unknown"] == 3
    # …and the POST-cut ALL row does not silently absorb them either.
    assert payload["buckets"]["post"]["n"] == 13
    assert code == r0.EXIT_OK, text


# --------------------------------------------------------------------------- #
# 3. THE MIN_REPORTS REFUSAL
# --------------------------------------------------------------------------- #
def test_MIN_REPORTS_is_ten_and_that_is_a_standing_instruction(r0):
    """invariant: a VALUE pin, so lowering the floor is a visible edit rather
    than a quiet retune. `handoff-audit-pr-operator-asks.md` NEXT #1: do not
    re-tune the feature off n<10."""
    assert r0.MIN_REPORTS == 10


@pytest.mark.parametrize("n_in", [0, 9])
def test_below_MIN_REPORTS_it_prints_NOT_MEASURABLE_and_exits_6(
        r0, oa, tmp_path, n_in):
    """invariant: the refusal. n=0 is today's real answer on this host."""
    sessions = {f"{PROJECT}/pre{i}.jsonl": [assistant(ledger(4, 3), ts=PRE_TS)]
                for i in range(12)}
    for i in range(n_in):
        sessions[f"{PROJECT}/in{i}.jsonl"] = [
            user_text(brief(r0, oa, "answered", tmp_path), ts=POST_TS),
            assistant(ledger(5, 1), ts=POST_TS)]
    code, text, payload = rates(r0, corpus_with(tmp_path, sessions), tmp_path)
    assert code == r0.EXIT_NOT_MEASURABLE, text
    assert f"NOT MEASURABLE (n={n_in} < 10)" in text
    assert "do NOT re-tune the feature" in text
    assert payload["buckets"]["post_in"]["n"] == n_in


def test_at_MIN_REPORTS_a_verdict_prints(r0, oa, tmp_path):
    """invariant: the floor is a floor and not a wall — at n=10 the comparison
    runs and the verdict names both statistics."""
    sessions = {f"{PROJECT}/pre{i}.jsonl": [assistant(ledger(4, 3), ts=PRE_TS)]
                for i in range(12)}
    for i in range(10):
        sessions[f"{PROJECT}/in{i}.jsonl"] = [
            user_text(brief(r0, oa, "answered", tmp_path), ts=POST_TS),
            assistant(ledger(5, 1), ts=POST_TS)]
    code, text, _p = rates(r0, corpus_with(tmp_path, sessions), tmp_path)
    assert code == r0.EXIT_OK, text
    assert "VERDICT: post-cut in-population is LOWER on both statistics" in text
    assert "not a causal claim" in text


def test_an_empty_PRE_bucket_is_also_NOT_MEASURABLE(r0, oa, tmp_path):
    """invariant: exit 6's SECOND reason — a comparison with no left-hand side.
    Documented as sharing the code because it demands the same action."""
    sessions = {}
    for i in range(10):
        sessions[f"{PROJECT}/in{i}.jsonl"] = [
            user_text(brief(r0, oa, "answered", tmp_path), ts=POST_TS),
            assistant(ledger(5, 1), ts=POST_TS)]
    code, text, _p = rates(r0, corpus_with(tmp_path, sessions), tmp_path)
    assert code == r0.EXIT_NOT_MEASURABLE, text
    assert "pre-cut bucket is empty" in text


# --------------------------------------------------------------------------- #
# 4. PROVENANCE SEPARATION
# --------------------------------------------------------------------------- #
def test_the_same_ledger_line_in_an_assistant_block_and_a_tool_result_counts_ONCE(
        r0, oa, tmp_path):
    """invariant: the naive walk's over-count. The skill body and the brief are
    injected as tool_result/user text, so the sentence a report is recognised by
    also appears in what ASKED for the report."""
    line = ledger(7, 2)
    corpus = corpus_with(tmp_path, {
        f"{PROJECT}/s1.jsonl": [tool_result(line, ts=POST_TS),
                                user_text(line, ts=POST_TS),
                                assistant(line, ts=POST_TS)]})
    reports, facts = r0.walk(corpus, oa.SOURCE_SESSION)
    assert len(reports) == 1, [r.__dict__ for r in reports]
    assert facts.injected_ledger_lines == 2, (
        "the injected copies must be COUNTED and excluded, not ignored — the "
        "over-count is what the report discloses")


def test_a_thinking_block_is_not_a_report(r0, oa, tmp_path):
    """invariant: reasoning about the ledger is not reporting it."""
    corpus = corpus_with(tmp_path, {
        f"{PROJECT}/s1.jsonl": [
            {"type": "assistant", "timestamp": POST_TS,
             "message": {"role": "assistant",
                         "content": [{"type": "thinking",
                                      "thinking": ledger(7, 2)}]}}]})
    reports, facts = r0.walk(corpus, oa.SOURCE_SESSION)
    assert reports == []
    assert facts.injected_ledger_lines == 1


# --------------------------------------------------------------------------- #
# 5. CORPUS WALKING — the nested transcript and its project
# --------------------------------------------------------------------------- #
NESTED = f"{PROJECT}/b5e21e7f-0000-0000-0000-000000000000/subagents/agent-a0.jsonl"


def test_a_nested_subagents_transcript_is_walked_and_counted(r0, oa, tmp_path):
    """invariant: a real post-merge report of this arc lives three levels down,
    in `<project>/<session>/subagents/<agent>.jsonl`. The fixture sits at that
    exact depth on purpose — a shallower one SURVIVES a mutant that globs one
    level (measured in this arc: a `*/` pattern read as covering `subagents/`)."""
    assert NESTED.count("/") == 3
    corpus = corpus_with(tmp_path, {NESTED: [
        user_text(brief(r0, oa, "answered", tmp_path), ts=POST_TS),
        assistant(ledger(), ts=POST_TS)]})
    reports, _f = r0.walk(corpus, oa.SOURCE_SESSION)
    assert len(reports) == 1 and reports[0].disposition == "in"


def test_the_project_is_the_FIRST_segment_not_the_parent_directory(
        r0, oa, tmp_path):
    """invariant: `path.parent.name` is literally `subagents` for the fixture
    above — the trap this derivation exists to avoid."""
    corpus = corpus_with(tmp_path, {NESTED: [assistant(ledger(), ts=POST_TS)]})
    reports, _f = r0.walk(corpus, oa.SOURCE_SESSION)
    assert reports[0].project == PROJECT
    assert reports[0].project != "subagents"
    assert r0._project_of(corpus / NESTED, corpus) == PROJECT


def test_a_record_with_no_timestamp_is_undated_and_folded_into_nothing(
        r0, oa, tmp_path):
    """invariant: an undated report is reported and belongs to NEITHER bucket."""
    undated = {"type": "assistant",
               "message": {"role": "assistant",
                           "content": [{"type": "text", "text": ledger(6, 6)}]}}
    corpus = corpus_with(tmp_path, {
        f"{PROJECT}/s1.jsonl": [undated],
        f"{PROJECT}/s2.jsonl": [assistant(ledger(4, 3), ts=PRE_TS)]})
    code, text, payload = rates(r0, corpus, tmp_path)
    assert payload["undated"] == 1
    assert payload["buckets"]["pre"]["n"] == 1
    assert payload["buckets"]["post"]["n"] == 0
    assert payload["buckets"]["pre"]["unattributed"] == 3, (
        "the undated report's 6 leaked into the PRE bucket")
    assert "undated (no `timestamp`): 1" in text
    assert code == r0.EXIT_NOT_MEASURABLE


def test_the_cut_is_a_PARAMETER_and_moves_the_buckets(r0, oa, tmp_path):
    """invariant: bucketing is by the record's own timestamp against the cut, so
    moving the cut moves reports. A hardcoded cut could not be measured at two
    points, and one measurement is not a general claim."""
    corpus = corpus_with(tmp_path, {
        f"{PROJECT}/s1.jsonl": [assistant(ledger(4, 3), ts=POST_TS)]})
    out = tmp_path / "a.json"
    run(r0, ["--corpus", str(corpus), "--cut-iso", CUT_ISO, "--json", str(out)])
    assert json.loads(out.read_text())["buckets"]["post"]["n"] == 1
    run(r0, ["--corpus", str(corpus), "--cut-iso", "2026-09-28T00:00:00Z",
             "--json", str(out)])
    assert json.loads(out.read_text())["buckets"]["post"]["n"] == 0


# --------------------------------------------------------------------------- #
# 6. THE SELF-CONTROLS
# --------------------------------------------------------------------------- #
def test_an_empty_corpus_fails_the_POSITIVE_control_with_exit_4(r0, tmp_path):
    """invariant: a walk that found no assistant-authored ledger line anywhere
    is indistinguishable from a walk wired to nothing, so it must refuse rather
    than print a reassuring 0."""
    empty = tmp_path / "corpus"
    empty.mkdir()
    code, text = run(r0, ["--corpus", str(empty), "--cut-iso", CUT_ISO])
    assert code == r0.EXIT_NOTHING_WALKED, text
    assert "POSITIVE" in text and "FAILED" in text
    assert "VERDICT" not in text, "no verdict may print off a failed control"


def test_the_negative_control_refuses_when_the_sentinel_is_planted(
        r0, oa, tmp_path):
    """invariant: the matcher must not be matching anything. The sentinel is
    COMPUTED, so this plants `NEG_CONTROL`'s value rather than a literal —
    writing the literal into a tracked file is what poisoned the sibling
    sweep's control for weeks."""
    corpus = corpus_with(tmp_path, {
        f"{PROJECT}/s1.jsonl": [assistant(ledger(4, 3), ts=PRE_TS),
                                assistant(f"x {r0.NEG_CONTROL} y", ts=PRE_TS)]})
    code, text = run(r0, ["--corpus", str(corpus), "--cut-iso", CUT_ISO])
    assert code == r0.EXIT_CONTROL, text
    assert "NEGATIVE" in text and "FAILED" in text
    assert "VERDICT" not in text


def test_the_sentinel_is_computed_and_not_written_down(r0):
    """invariant: the corpus IS the transcripts, so a literal sentinel in this
    tree poisons its own control the moment any session reads the file."""
    assert r0.NEG_CONTROL not in SCRIPT.read_text()
    assert r0.NEG_CONTROL not in Path(__file__).read_text()
    assert len(r0.NEG_CONTROL) > 16


# --------------------------------------------------------------------------- #
# 7. WHAT THE OUTPUT MAY AND MAY NOT CARRY
# --------------------------------------------------------------------------- #
def test_default_output_carries_no_transcript_prose(r0, oa, tmp_path):
    """invariant: devrc is PUBLIC and the corpus is transcripts. Counts, rates
    and shapes only."""
    secret = "an-invented-operator-sentence-that-must-not-be-echoed"
    ask = oa.Ask(source=oa.SOURCE_SESSION, text=secret, session_id="a" * 8)
    block = oa.render([ask], session_ids=("a" * 8,), comments_examined=0,
                      projects_root=tmp_path / "nope")
    assert secret in block
    corpus = corpus_with(tmp_path, {
        f"{PROJECT}/s1.jsonl": [user_text(block, ts=POST_TS),
                                assistant(f"{secret}\n{ledger()}", ts=POST_TS)]})
    _code, text = run(r0, ["--corpus", str(corpus), "--cut-iso", CUT_ISO])
    assert secret not in text


def test_samples_is_opt_in_and_prints_shapes_only(r0, oa, tmp_path):
    """invariant: `--samples` may print numbers and a project, never prose or a
    transcript path."""
    corpus = corpus_with(tmp_path, {
        f"{PROJECT}/s1.jsonl": [assistant(ledger(4, 3), ts=PRE_TS)]})
    _c, plain = run(r0, ["--corpus", str(corpus), "--cut-iso", CUT_ISO])
    assert "SAMPLES" not in plain
    _c, sampled = run(r0, ["--corpus", str(corpus), "--cut-iso", CUT_ISO,
                           "--samples", "3"])
    assert "SAMPLES" in sampled
    assert "requirements=4 unattributed=3" in sampled
    assert str(corpus) not in sampled.split("SAMPLES", 1)[1], (
        "a transcript path is per-session metadata; the samples block must not "
        "carry one")


def test_every_exit_code_constant_is_documented_in_the_docstring(r0):
    """invariant: a code nobody documented is a code a reader will guess at.
    Two-way-ish: each constant's NUMBER must appear in the `Exit codes:` prose,
    and the prose is the only place their meanings live."""
    doc = r0.__doc__ or ""
    codes = doc.split("Exit codes:", 1)
    assert len(codes) == 2, "the docstring has no `Exit codes:` section"
    legend = codes[1]
    for name in ("EXIT_OK", "EXIT_USAGE", "EXIT_CONTROL", "EXIT_NOTHING_WALKED",
                 "EXIT_PIN", "EXIT_NOT_MEASURABLE"):
        value = getattr(r0, name)
        assert f"{value} " in legend or f"{value}·" in legend, (
            f"{name}={value} is not documented in the Exit codes legend")


def test_the_report_states_its_own_method(r0, oa, tmp_path):
    """invariant: defect 1 was a number quoted without its method. The run must
    say what one report IS, and that a count is not the statistic."""
    corpus = corpus_with(tmp_path, {
        f"{PROJECT}/s1.jsonl": [assistant(ledger(4, 3), ts=PRE_TS)]})
    _code, text = run(r0, ["--corpus", str(corpus), "--cut-iso", CUT_ISO])
    assert "assistant-authored text block" in text
    assert "a RATE, never a count" in text
    assert "mean/report" in text and "share" in text
