#!/usr/bin/env python3
"""Guards for `scripts/round0-attribution-rate.py` — the round-0 attribution RATE.

🔴 WHAT THESE ARE, HONESTLY. The script is NEW, so almost every test here is an
INVARIANT GUARD: it pins a property the implementation is supposed to have, and
none of them is a regression test, because there is no bug they were written
after. Calling them regression coverage would be a false claim about what has
been observed to fail (`claude/RULES.md` → "vacuous-guards"), so each such name
says `invariant`.

THE EXCEPTIONS, and they are the guards that matter:

  * the two-way renderer pin (`ANCHORS` against `scripts/lib/operator_asks.py`)
    is watched go RED against a REWORDED and against a WIDENED copy of that
    module — a real red→green pair run as part of the suite, not claimed in
    prose. A one-sided matcher would silently reclassify every report as
    out-of-population and print a clean, wrong NOT MEASURABLE.
  * 🔴 the PRECEDENCE guards are REGRESSION tests for a defect `#1901 round 0`
    found and the coordinator reproduced: `session(s) NAMED BY` was scored as
    `answered`, so a block whose own text says **NO OPERATOR ASK COULD BE READ
    FOR THIS PR** classified as in-population and entered the closing
    condition's left-hand side. The tests named `…named_but_unreadable…` and
    `…only_the_answered_role…` are that bug's guards, and they are BEHAVIOURAL
    against live `render()` output at both poles, because every anchor string
    was already correct when the defect shipped.

🔴 EVERY FIXTURE IS SYNTHETIC. devrc is PUBLIC and the corpus under measurement
is the operator's transcripts, so no record here is copied from one: the briefs
are generated by calling `operator_asks.render()` on invented inputs, and the
report text is written here. `scripts/tests/test_no_captured_text.py` gates the
tree for captured text; nothing in this file is derived from a real session.
"""
from __future__ import annotations

import importlib.util
import inspect
import io
import json
import re
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT = REPO_ROOT / "scripts" / "round0-attribution-rate.py"
OPERATOR_ASKS = REPO_ROOT / "scripts" / "lib" / "operator_asks.py"

sys.path.insert(0, str(REPO_ROOT / "scripts"))
from testlib import hermetic_git  # noqa: E402  the ONE hermetic git env

PROJECT = "-home-zach-workspace-a-repo"
PRE_TS = "2026-09-20T10:00:00.000Z"          # before the cut used below
POST_TS = "2026-09-27T12:00:00.000Z"         # after it
#: `31033cdb`'s LANDING instant. Its author and committer dates are identical to
#: the second, so this constant reads the same under either clock — which is
#: exactly why the wrong-clock defect was invisible here. See
#: `test_the_cut_is_read_off_the_COMMITTER_date_not_the_author_date`.
CUT_ISO = "2026-09-27T00:49:10-05:00"


def _load(path, name):
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    # Registered BEFORE exec: a module holding a `@dataclass` cannot be executed
    # unregistered (dataclasses resolve annotations via sys.modules).
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


@pytest.fixture(scope="module")
def r0():
    return _load(SCRIPT, "round0_attribution_rate")


@pytest.fixture(scope="module")
def oa(r0):
    return r0.load_operator_asks()


@pytest.fixture(autouse=True)
def _no_env_leak(monkeypatch, r0):
    """Neither env door may leak in from the caller's shell."""
    monkeypatch.delenv(r0.CORPUS_ENV, raising=False)
    monkeypatch.delenv(r0.OPERATOR_ASKS_ENV, raising=False)


# --------------------------------------------------------------------------- #
# fixture builders — synthetic transcripts
# --------------------------------------------------------------------------- #
def ledger(requirements=7, unattributed=2) -> str:
    """The round-0 ledger line, as the skill tells the auditor to write it."""
    return (f"## Round 0\nround 0 · requirements: {requirements} "
            f"(unattributed: {unattributed})\n")


def assistant(text, ts=PRE_TS) -> dict:
    return {"type": "assistant", "timestamp": ts,
            "message": {"role": "assistant",
                        "content": [{"type": "text", "text": text}]}}


def tool_result(text, ts=PRE_TS) -> dict:
    return {"type": "user", "timestamp": ts,
            "message": {"role": "user",
                        "content": [{"type": "tool_result", "tool_use_id": "t1",
                                     "content": text}]}}


def user_text(text, ts=PRE_TS) -> dict:
    return {"type": "user", "timestamp": ts,
            "message": {"role": "user",
                        "content": [{"type": "text", "text": text}]}}


def brief(r0, oa, shape, tmp_path) -> str:
    """A real `render()` output — the strings the instrument matches on.

    Built from the script's own probe matrix so the fixture cannot drift away
    from what production emits: `answered`, `unmeasured`, `dropped`, `no-source`.
    """
    probes = r0.renderer_probes(oa, tmp_path / "no-such-projects-root")
    return probes[shape]


def write(path: Path, records) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(json.dumps(r) for r in records) + "\n")
    return path


def corpus_with(tmp_path, sessions: dict) -> Path:
    """sessions: {relative transcript path -> [records]} under a fresh corpus."""
    root = tmp_path / "corpus"
    for rel, records in sessions.items():
        write(root / rel, records)
    root.mkdir(parents=True, exist_ok=True)
    return root


def run(r0, argv) -> tuple[int, str]:
    """-> (exit code, stdout text). `fail()` exits, so SystemExit is caught.

    The code is asserted to be an INT: this script exits only with its own
    documented codes, and a `str`/`None` exit would otherwise compare unequal to
    every expected code and read as an ordinary wrong-code failure.
    """
    buf = io.StringIO()
    try:
        code = r0.main(argv, out_stream=buf)
    except SystemExit as e:
        code = e.code
    assert isinstance(code, int), f"non-int exit {code!r}\n{buf.getvalue()}"
    return code, buf.getvalue()


def rates(r0, oa, corpus, extra=()) -> tuple[int, str, dict]:
    """Run over `corpus`, and ALSO return the buckets as DATA.

    ⚠ The buckets come from `bucket_reports` — the same pure function `main()`
    uses — and not from a `--json` file: that flag had zero consumers and `#1901
    round 0`'s deletion pass removed it. A function's return value is a better
    seam than a file: it cannot go stale and needs no IO. `stats()` then lets a
    test assert ARITHMETIC rather than a label.
    """
    code, text = run(r0, ["--corpus", str(corpus), "--cut-iso", CUT_ISO, *extra])
    reports, _facts = r0.walk(Path(corpus), oa.SOURCE_SESSION)
    return code, text, r0.bucket_reports(reports, r0.parse_ts(CUT_ISO))


# --------------------------------------------------------------------------- #
# 1. THE TWO-WAY RENDERER PIN — the one guard with a real red->green pair
# --------------------------------------------------------------------------- #
def test_the_anchor_ledger_matches_what_operator_asks_emits_today(r0, oa, tmp_path):
    """GREEN half of the pair: every anchor is reachable and nothing is
    unmatched, against the live renderer."""
    probes = r0.renderer_probes(oa, tmp_path / "nope")
    r0.check_pins(oa, probes)               # must not raise

    seen, unmatched = set(), []
    for text in probes.values():
        asks, sources, _found = r0.block_regions(text)
        # mirrors `check_pins`: EVERY source line, not just session ones —
        # the narrower version made three anchors unreachable here and would
        # have masked the GROWS widening F4 asked for.
        for lines, where in ((asks, "asks"), (sources, "sources")):
            _roles, ids, bad = r0.match_anchors(lines, where)
            seen |= ids
            unmatched += bad
    assert unmatched == [], (
        "operator_asks.render() emits a line the ANCHORS ledger does not cover "
        f"(GROWS): {unmatched}")
    assert seen == {a["id"] for a in r0.ANCHORS}, (
        "an anchor matches nothing a live render emits (SHRINKS): "
        f"{sorted({a['id'] for a in r0.ANCHORS} - seen)}")


def _reworded_copy(tmp_path, old, new, name="operator_asks.py"):
    """A copy of operator_asks.py with exactly ONE substitution applied.

    Asserts the substitution HAPPENED — a mutation that silently applies to
    nothing is a test that proves nothing.
    """
    src = OPERATOR_ASKS.read_text()
    assert src.count(old) == 1, (
        f"the mutation target {old!r} occurs {src.count(old)}x in "
        "operator_asks.py — the mutant would be ambiguous or inert")
    copy = tmp_path / name
    copy.write_text(src.replace(old, new))
    return copy


def test_the_pin_goes_RED_when_the_renderer_REWORDS_its_selection_line(
        r0, tmp_path, monkeypatch, capsys):
    """RED half, SHRINKS direction, on the `selected` anchor."""
    copy = _reworded_copy(tmp_path, "session(s) NAMED BY",
                          "session(s) IDENTIFIED VIA")
    monkeypatch.setenv(r0.OPERATOR_ASKS_ENV, str(copy))
    code, _out = run(r0, ["--corpus", str(tmp_path), "--cut-iso", CUT_ISO])
    err = capsys.readouterr().err
    assert code == r0.EXIT_PIN, f"expected exit {r0.EXIT_PIN}, got {code}"
    # A reword trips BOTH halves at once, and the refusal must say so — the old
    # spelling matches nothing AND the new line is covered by nothing.
    assert "SHRINKS" in err and "selected" in err, err
    assert "GROWS" in err and "signature of a REWORD" in err, err


def test_the_pin_goes_RED_when_the_renderer_REWORDS_its_ASK_HEADING(
        r0, tmp_path, monkeypatch, capsys):
    """RED half on the anchor that now carries `answered` — the ONLY line that
    proves the operator's words arrived. If this one silently stops matching the
    denominator empties and the run prints a clean, wrong NOT MEASURABLE."""
    copy = _reworded_copy(tmp_path, 'f"### from the {source}"',
                          'f"### sourced from {source}"')
    monkeypatch.setenv(r0.OPERATOR_ASKS_ENV, str(copy))
    code, _out = run(r0, ["--corpus", str(tmp_path), "--cut-iso", CUT_ISO])
    err = capsys.readouterr().err
    assert code == r0.EXIT_PIN, f"expected exit {r0.EXIT_PIN}, got {code}"
    assert "SHRINKS" in err and "asks-read-session" in err, err


def test_the_pin_goes_RED_when_the_renderer_GAINS_an_uncovered_source_line(
        r0, tmp_path, monkeypatch, capsys):
    """RED half, GROWS direction: a new session-transcript source line whose
    meaning for the in-population test nobody has decided."""
    copy = _reworded_copy(
        tmp_path,
        'lines += ["", "**Sources read:**"]',
        'lines += ["", "**Sources read:**",\n'
        '              f"  {SOURCE_SESSION}: a shape nobody has classified"]')
    monkeypatch.setenv(r0.OPERATOR_ASKS_ENV, str(copy))
    code, _out = run(r0, ["--corpus", str(tmp_path), "--cut-iso", CUT_ISO])
    err = capsys.readouterr().err
    assert code == r0.EXIT_PIN, f"expected exit {r0.EXIT_PIN}, got {code}"
    assert "GROWS" in err, err
    # A PURE addition must NOT be reported as a reword: every existing anchor
    # still matches, so only one half fails. This is what makes the two-way pin
    # diagnostic rather than just red.
    assert "SHRINKS" not in err, err


def test_the_pin_goes_RED_when_THIS_modules_own_ledger_is_mutated(
        r0, oa, tmp_path, monkeypatch, capsys):
    """RED half, mutating the LEDGER rather than the renderer — the same
    disagreement from the other side."""
    mutant = tuple(dict(a, text="session(s) LISTED BY") if a["id"] == "selected"
                   else a for a in r0.ANCHORS)
    monkeypatch.setattr(r0, "ANCHORS", mutant)
    with pytest.raises(SystemExit) as exc:
        r0.check_pins(oa, r0.renderer_probes(oa, tmp_path / "nope"))
    assert exc.value.code == r0.EXIT_PIN
    err = capsys.readouterr().err
    assert "SHRINKS" in err and "selected" in err, err
    assert "GROWS" in err, err


def test_a_renderer_that_indents_its_own_heading_fails_the_pin(
        r0, tmp_path, monkeypatch, capsys):
    """invariant: line-anchoring is a CLAIM about the renderer, so the renderer
    is checked against it. A block emitted indented would be invisible to the
    walk, and this is what makes that loud instead of silent."""
    copy = _reworded_copy(tmp_path, "    lines = [HEADING, \"\"]",
                          "    lines = ['    ' + HEADING, \"\"]")
    monkeypatch.setenv(r0.OPERATOR_ASKS_ENV, str(copy))
    code, _out = run(r0, ["--corpus", str(tmp_path), "--cut-iso", CUT_ISO])
    assert code == r0.EXIT_PIN
    assert "START of a line" in capsys.readouterr().err


def test_an_unreadable_renderer_is_a_pin_FAILURE_not_a_pass(
        r0, tmp_path, monkeypatch, capsys):
    """invariant: if the module the anchors describe cannot be read, nothing
    verified them — proceeding would report a confident zero."""
    monkeypatch.setenv(r0.OPERATOR_ASKS_ENV, str(tmp_path / "absent.py"))
    code, _out = run(r0, ["--corpus", str(tmp_path), "--cut-iso", CUT_ISO])
    assert code == r0.EXIT_PIN
    assert "does not exist" in capsys.readouterr().err


# --------------------------------------------------------------------------- #
# 1a. THE DELIVERY FORM — REGRESSION guards for `#1901 round 1`'s 🔴
# --------------------------------------------------------------------------- #
def cat_n(text: str, start: int = 1) -> str:
    """`text` as a Read tool_result renders it: `<spaces><n>\\t<line>`.

    Not hypothetical: `audit-dispatch.py`'s output is redirected to a scratchpad
    `.md` and the dispatch prompt tells the auditor to READ it, so a brief reaches
    the auditor in this form — both of the coordinator's dispatches this session
    delivered it that way.
    """
    return "".join(f"{i + start:6d}\t{line}\n"
                   for i, line in enumerate(text.splitlines()))


def test_a_brief_delivered_as_a_LINE_NUMBERED_read_is_still_found(
        r0, oa, tmp_path):
    """🔴 REGRESSION for round 1's 🔴, POSITIVE pole. The bare `^` anchor round 0
    added cannot match a `cat -n` tool_result, so 13 of 20 post-cut reports were
    scored `out` with the reason "no asks block in this session (a pre-fix
    report)" — affirmatively FALSE — the control row was contaminated with
    sessions that DID receive a block, and `post_in` was deflated with the floor
    unreachable by the DOMINANT delivery path."""
    numbered = cat_n(brief(r0, oa, "answered", tmp_path), start=111)
    assert "\t## THE OPERATOR'S OWN ASKS" in numbered   # really numbered
    assert not numbered.startswith("## ")
    assert r0.ANCHOR_BLOCK_RE.search(numbered), "the block must still be found"
    asks, sources, found = r0.block_regions(numbered)
    assert found, "the Sources block must be located under a line number"
    assert asks, "the ask headings must survive the line numbers"
    assert sources, (
        "the source lines must survive: unstripped, the indent test fails on the "
        "FIRST line and the block reads as having no sources at all")
    disp, why = r0.disposition_of([numbered], oa.SOURCE_SESSION)
    assert disp == "in", f"got {disp!r} ({why})"


def test_the_numbered_sources_region_STOPS_where_the_unnumbered_one_does(
        r0, oa, tmp_path):
    """🔴 EARNED BY A SURVIVING MUTANT: `strip_lineno(raw)` → `raw` survived the
    whole suite. `cat -n` right-pads its numbers with SPACES, so an unstripped
    numbered line passes the two-space indent test by accident — the region never
    ends, and everything after the Sources block (the `**Ledger:**` line, the
    UNKNOWN directive, the publish warning, the agent-side paths) is collected as
    a "source line". Nothing classified differently, so no test noticed; the pin
    would have gone rc 5 on a numbered probe.

    This asserts the REGION, not the classification: the numbered block must
    yield exactly the source lines the unnumbered one does."""
    plain = brief(r0, oa, "every-source", tmp_path)
    numbered = cat_n(plain, start=40)
    _a1, src_plain, _f1 = r0.block_regions(plain)
    _a2, src_numbered, _f2 = r0.block_regions(numbered)
    assert src_plain, "the fixture must have source lines at all"
    assert len(src_numbered) == len(src_plain), (
        f"the numbered region collected {len(src_numbered)} lines against "
        f"{len(src_plain)}: {src_numbered[len(src_plain):]}")
    assert src_numbered == src_plain, "and the same lines, line numbers removed"
    for line in src_numbered:
        assert "**Ledger:**" not in line, (
            "the region must END at the Ledger line, as it does unnumbered")
        assert not r0._LINENO_RE.match(line), (
            "each line must have its number REMOVED — the message here used to\n             say the opposite of what the assertion requires (`#1901 round 2`)")


def test_a_LINE_NUMBERED_source_read_is_still_NOT_a_block(r0, oa, tmp_path):
    """🔴 REGRESSION, NEGATIVE pole of the same widening: tolerating a line number
    must not re-admit the false-positive class line-anchoring was added for.
    `operator_asks.py`'s own source carries both anchors, and under `cat -n` the
    number lands in front of `HEADING = "## THE OPERATOR…`."""
    numbered = cat_n(OPERATOR_ASKS.read_text())
    assert r0.ANCHOR_BLOCK in numbered, "the fixture must carry the substring"
    assert not r0.ANCHOR_BLOCK_RE.search(numbered), (
        "a numbered SOURCE READ must not match the block anchor")
    assert not r0._BLOCKLIKE_BLOCK_RE.search(numbered), (
        "…nor the wider safety-net pattern, or every source read becomes UNKNOWN")
    corpus = corpus_with(tmp_path, {
        f"{PROJECT}/s1.jsonl": [tool_result(numbered, ts=POST_TS),
                                assistant(ledger(), ts=POST_TS)]})
    reports, _f = r0.walk(corpus, oa.SOURCE_SESSION)
    assert [r.disposition for r in reports] == ["out"]


def test_EVERY_line_anchored_matcher_survives_the_numbered_form(r0, oa, tmp_path):
    """🔴 WIDEST READING of round 1's finding: fixing one matcher while a sibling
    stays blind MOVES the defect. Every `^`-anchored pattern the module defines is
    swept here against one numbered render."""
    numbered = cat_n(brief(r0, oa, "every-source", tmp_path), start=7)
    anchored = {name: obj for name, obj in vars(r0).items()
                if isinstance(obj, re.Pattern) and obj.pattern.startswith("^")}
    assert {"ANCHOR_BLOCK_RE", "ANCHOR_SOURCES_RE", "ASK_HEADING_RE",
            "_BLOCKLIKE_BLOCK_RE"} <= set(anchored), sorted(anchored)
    unmatched = sorted(name for name, rx in anchored.items()
                       if name != "_LINENO_RE" and not rx.search(numbered))
    assert unmatched == [], (
        f"these line-anchored patterns cannot see the numbered form: {unmatched}")
    # `_LINENO_RE` is the one pattern that must match the NUMBERING itself
    assert r0._LINENO_RE.search(numbered.splitlines()[0])
    assert r0.disposition_of([numbered], oa.SOURCE_SESSION)[0] == "in"


def test_a_block_in_a_form_I_cannot_parse_is_UNKNOWN_not_a_pre_fix_report(
        r0, oa, tmp_path):
    """🔴 REGRESSION-shaped: the reason "no asks block in this session (a pre-fix
    report)" asserts TWO things — no block, and pre-fix — and it was false for 13
    reports. Any block-like text the matcher cannot locate must route to UNKNOWN
    (my blindness). The fixture is a blockquoted delivery: a form the matcher
    does not parse and never claimed to."""
    quoted = "\n".join("> " + l for l in
                       brief(r0, oa, "answered", tmp_path).splitlines())
    assert not r0.ANCHOR_BLOCK_RE.search(quoted)
    assert r0._BLOCKLIKE_BLOCK_RE.search(quoted)
    corpus = corpus_with(tmp_path, {
        f"{PROJECT}/s1.jsonl": [user_text(quoted, ts=POST_TS),
                                assistant(ledger(), ts=POST_TS)]})
    reports, _f = r0.walk(corpus, oa.SOURCE_SESSION)
    assert [r.disposition for r in reports] == ["UNKNOWN"]
    assert "not in a form this instrument can locate" in reports[0].why
    assert "pre-fix" in reports[0].why, (
        "the reason must say explicitly that this is NOT a pre-fix report")


# --------------------------------------------------------------------------- #
# 1b. PRECEDENCE — the REGRESSION guards for `#1901 round 0`'s 🔴
# --------------------------------------------------------------------------- #
def test_a_block_that_NAMED_a_session_but_could_read_NOTHING_is_NOT_in_population(
        r0, oa, tmp_path):
    """🔴 REGRESSION, not an invariant guard. `#1901 round 0` found this and the
    coordinator reproduced it: when trailers name a session AND nothing can be
    read, `render()` emits `session transcript: N session(s) NAMED BY …`
    (guarded by `if session_ids:` alone) BESIDE `! session transcript: UNKNOWN`,
    and the block's own text says **NO OPERATOR ASK COULD BE READ FOR THIS PR**.
    Scoring the first line as `answered` put that report in `post_in` — the
    closing condition's entire left-hand side, and what the floor counts.

    The fixture is LIVE `render()` output for exactly that input, not a
    hand-written approximation of it."""
    block = brief(r0, oa, "named-but-unreadable", tmp_path)
    # the fixture must really carry BOTH lines, or it cannot see this defect
    assert "session(s) NAMED BY" in block and ": UNKNOWN — " in block, block[:400]
    assert "NO OPERATOR ASK COULD BE READ" in block
    roles, _found, _bad = r0.roles_of_block(block, oa.SOURCE_SESSION)
    assert roles >= {"selected", "unmeasured"}
    assert "answered" not in roles, (
        "NAMED BY is SELECTION — trailers picking a session — and must never "
        f"carry the role that means the words arrived: {sorted(roles)}")
    disp, why = r0.disposition_of([block], oa.SOURCE_SESSION)
    assert disp == "out", f"got {disp!r} ({why})"
    assert "could not be read" in why


def test_only_the_answered_role_can_make_a_report_in_population(r0):
    """🔴 REGRESSION: the one-line ledger that replaced the precedence bug.
    Re-admitting `selected` here is what the defect WAS, so it must be a visible
    edit that fails a test rather than a quiet change of meaning."""
    assert r0.IN_POPULATION_ROLES == ("answered",)
    assert "selected" not in r0.IN_POPULATION_ROLES
    # …and the role really is carried by the ask-heading anchor, not by a source
    # line: an `answered` role attached to a `sources` anchor would reintroduce
    # the bug with the ledger still reading correctly.
    carriers = [a for a in r0.ANCHORS if a["role"] == "answered"]
    assert [a["id"] for a in carriers] == ["asks-read-session"]
    assert carriers[0]["where"] == "asks"


def test_the_run_REFUSES_when_a_live_pole_classifies_wrongly(
        r0, oa, tmp_path, monkeypatch, capsys):
    """🔴 REGRESSION: the behavioural half of the pin, watched RED. Every anchor
    string was CORRECT when the defect shipped — the precedence between them was
    wrong — so a structural ledger cannot catch this class and the run classifies
    both poles of live `render()` output on every invocation."""
    monkeypatch.setattr(r0, "IN_POPULATION_ROLES", ("answered", "selected"))
    with pytest.raises(SystemExit) as exc:
        r0.check_behavioural_poles(
            oa, r0.renderer_probes(oa, tmp_path / "nope"))
    assert exc.value.code == r0.EXIT_PIN
    err = capsys.readouterr().err
    assert "'named-but-unreadable' pole" in err, err
    assert "classifies as 'in'" in err and "expected 'out'" in err, err


def test_every_live_pole_classifies_correctly_today(r0, oa, tmp_path):
    """GREEN half of that pair, over the SAME code path the corpus walk uses."""
    probes = r0.renderer_probes(oa, tmp_path / "nope")
    r0.check_behavioural_poles(oa, probes)          # must not raise
    for name, expected in r0.BEHAVIOURAL_POLES:
        got, why = r0.disposition_of([probes[name]], oa.SOURCE_SESSION)
        assert got == expected, f"{name}: {got!r} ({why})"
    assert dict(r0.BEHAVIOURAL_POLES) == {"named-but-unreadable": "out",
                                          "answered": "in",
                                          "no-source": "out",
                                          "pr-comment-only": "out"}, (
        "the pole set is a LEDGER: a disposition branch with no pole gets no "
        "RUNTIME check, which is how two mutants survived a green suite")
    assert {n for n, _ in r0.BEHAVIOURAL_POLES} <= set(probes), (
        "a pole naming no probe would make the whole check vacuous")
    # 🔴 and every branch of `disposition_of` that can return `out`/`in` must have
    # a pole — derived, so a new branch fails here until it gets one
    body = inspect.getsource(r0.disposition_of)
    branch_roles = set(re.findall(r'"(\w[\w-]*)" in roles', body))
    covered = set()
    for name, _exp in r0.BEHAVIOURAL_POLES:
        covered |= r0.roles_of_block(probes[name], oa.SOURCE_SESSION)[0]
    assert branch_roles <= covered | set(r0.IN_POPULATION_ROLES), (
        "these disposition branches have no behavioural pole exercising them: "
        f"{sorted(branch_roles - covered - set(r0.IN_POPULATION_ROLES))}")


def test_a_block_that_says_NO_SOURCE_WAS_CONSULTED_is_out_not_UNKNOWN(
        r0, oa, tmp_path):
    """🔴 REGRESSION for TWO mutants that survived a fully green 52-test suite
    (`#1901 round 2`): disabling the `none-consulted` branch, and deleting
    `scope="block"` from its anchor. Either one turns a block that plainly says
    nothing was consulted into UNKNOWN — excluded from every denominator, so it
    VANISHES from the contemporaneous control row instead of counting as a
    reading of non-arrival.

    Neither was caught because `check_pins` passes `scopes=None` (so the anchor id
    still counts as "seen"), `no-source` is not a behavioural pole, and the module
    named none of the three strings."""
    block = brief(r0, oa, "no-source", tmp_path)
    assert "no source was consulted at all" in block
    # the anchor must be BLOCK-scoped: this line names no source, so a
    # session-filtered read cannot see it
    anchor = [a for a in r0.ANCHORS if a["id"] == "no-source-consulted"]
    assert len(anchor) == 1, anchor
    # `.get`, not `[...]`: a mutant that DELETES the key must fail with this
    # assertion's own message rather than a `KeyError` from the test itself —
    # a guard dying for the wrong reason tells the next reader nothing.
    assert anchor[0].get("scope") == "block", (
        "this line names no source, so only a BLOCK-scoped anchor can see it; "
        f"deleting the scope makes the block UNKNOWN: {anchor[0]}")
    assert anchor[0]["role"] == "none-consulted"
    assert r0.session_source_lines(oa.SOURCE_SESSION,
                                   r0.block_regions(block)[1]) == [], (
        "the fixture only tests the block scope while this line is NOT a "
        "session-transcript line — which is the whole reason the scope exists")
    roles, _found, _bad = r0.roles_of_block(block, oa.SOURCE_SESSION)
    assert roles == {"none-consulted"}, sorted(roles)
    disp, why = r0.disposition_of([block], oa.SOURCE_SESSION)
    assert disp == "out", f"got {disp!r} ({why})"
    assert "no source was consulted at all" in why
    # …and end to end, so it lands in the CONTROL row rather than vanishing
    corpus = corpus_with(tmp_path, {
        f"{PROJECT}/s1.jsonl": [user_text(block, ts=POST_TS),
                                assistant(ledger(6, 4), ts=POST_TS)]})
    _code, _text, b = rates(r0, oa, corpus)
    assert r0.stats(b["post_out"])["n"] == 1
    assert r0.stats(b["post_unknown"] if "post_unknown" in b else [])["n"] == 0


def test_a_SESSION_scoped_anchor_is_not_read_off_another_sources_line(
        r0, oa, tmp_path):
    """🔴 The other half of the `scope` mechanism, and a real hazard rather than
    symmetry: `: UNKNOWN — ` is `scope="session"` precisely so that
    `! PR comment: UNKNOWN — …` — which `render()` emits whenever comments were
    consulted — cannot be read as "the session transcript was unreadable". If that
    anchor were block-scoped, every PR with an unreadable COMMENT source would
    report non-arrival of the operator's typed words."""
    unmeasured_comment = oa.Unmeasured(source=oa.SOURCE_PR_COMMENT,
                                       reason="the comment API did not answer")
    sid = "a" * 8
    ask = oa.Ask(source=oa.SOURCE_SESSION, text="an ask", session_id=sid)
    block = oa.render([ask], session_ids=(sid,), unmeasured=(unmeasured_comment,),
                      comments_examined=0, projects_root=tmp_path / "nope")
    sources = r0.block_regions(block)[1]
    assert any(": UNKNOWN — " in l and oa.SOURCE_PR_COMMENT in l
               for l in sources), "the fixture must carry a PR-comment UNKNOWN"
    assert not any(": UNKNOWN — " in l and oa.SOURCE_SESSION + ":" in l
                   for l in sources), "…and NO session-transcript UNKNOWN"
    roles, _f, _b = r0.roles_of_block(block, oa.SOURCE_SESSION)
    assert "unmeasured" not in roles, (
        "a PR-comment UNKNOWN must not mark the SESSION source unreadable: "
        f"{sorted(roles)}")
    assert r0.disposition_of([block], oa.SOURCE_SESSION)[0] == "in"
    # the scope really is what makes that true
    anchor = [a for a in r0.ANCHORS if a["id"] == "unmeasured"][0]
    assert anchor.get("scope", r0._DEFAULT_SCOPE) == "session"


def test_every_anchor_is_MATCHED_by_a_live_probe_line_and_carries_its_role(
        r0, oa, tmp_path):
    """🔴 The per-anchor half of the coverage ledger, and it EXERCISES rather than
    names: every anchor must match at least one line some live `render()` emits,
    in its own region, and a role that must not reach classification must not.

    This is what was missing when two of round 2's mutants survived a green suite
    — the ledger below only checks that a NAME appears, while this drives each
    anchor through real renderer output."""
    probes = r0.renderer_probes(oa, tmp_path / "nope")
    hits = {a["id"]: [] for a in r0.ANCHORS}
    for text in probes.values():
        asks, sources, _f = r0.block_regions(text)
        for region, lines in (("asks", asks), ("sources", sources)):
            for line in lines:
                for a in r0.ANCHORS:
                    if a["where"] == region and a["text"] in line:
                        hits[a["id"]].append(line)
    unmatched = sorted(i for i, got in hits.items() if not got)
    assert unmatched == [], (
        "these anchors match nothing any probe emits, so nothing exercises them: "
        f"{unmatched}")

    # the informational anchors are EXACTLY the ones that cannot classify
    informational = {a["id"] for a in r0.ANCHORS
                     if a["role"] in ("informational", "informational-other")}
    assert informational == {"dropped", "comments-examined",
                             "review-comment-caveat", "comment-skipped"}, \
        sorted(informational)
    body = inspect.getsource(r0.disposition_of)
    for a in r0.ANCHORS:
        if a["id"] in informational:
            assert f'"{a["role"]}" in roles' not in body, (
                f"{a['id']} is informational but its role branches: {a['role']}")
    # `asks-read-pr-comment` IS a branch (`other-source`) and is deliberately NOT
    # in-population — the route the fix shipped is the session transcript
    pr = [a for a in r0.ANCHORS if a["id"] == "asks-read-pr-comment"][0]
    assert pr["role"] == "other-source"
    assert pr["role"] not in r0.IN_POPULATION_ROLES


def test_every_ANCHOR_and_ROLE_is_NAMED_by_this_module(r0):
    """🔴 THE DERIVABLE COVERAGE LEDGER, and it is the fix for the CAUSE rather
    than for the two instances. Both survivors of round 2's sweep were additions
    made in the SAME round as the sweep, so a hand-maintained mutant list could
    not see them. This test derives the guard surface from the module itself and
    requires each element to be NAMED in this file, so a new anchor, scope or
    disposition role fails the suite until something asserts on it.

    ⚠ Naming is weaker than exercising, and that is stated rather than implied:
    this catches "nobody wrote a guard at all", not "the guard is weak". It is
    cheap, mechanical, and it is exactly the hole that let two mutants live."""
    src = Path(__file__).read_text()
    missing_ids = [a["id"] for a in r0.ANCHORS if a["id"] not in src]
    assert missing_ids == [], (
        f"these anchors are named nowhere in this test module: {missing_ids}")
    roles = {a["role"] for a in r0.ANCHORS}
    missing_roles = sorted(r for r in roles if f'"{r}"' not in src)
    assert missing_roles == [], (
        f"these anchor ROLES are asserted on nowhere: {missing_roles}")
    scoped = sorted({a.get("scope", r0._DEFAULT_SCOPE) for a in r0.ANCHORS})
    for scope in scoped:
        assert f'scope="{scope}"' in src or f'"{scope}"' in src, (
            f"the {scope!r} anchor scope is named nowhere, so a mutant deleting "
            "it would survive — which is how two did")
    # every `disposition_of` branch must be named too: derive the role each one
    # tests from the function's own source
    body = inspect.getsource(r0.disposition_of)
    branch_roles = sorted(set(re.findall(r'"(\w[\w-]*)" in roles', body)))
    assert len(branch_roles) >= 3, branch_roles
    unnamed = [r for r in branch_roles if r not in src]
    assert unnamed == [], (
        f"these disposition branches are named in no test: {unnamed}")


def test_asks_that_arrived_only_from_a_PR_COMMENT_are_out_of_population(
        r0, oa, tmp_path):
    """invariant: the population is the SESSION-TRANSCRIPT route the fix shipped.
    A PR comment is a different, weaker route — that arc's own open
    investigation records agent-posted comments being attributed to the operator
    — so it is `out` with a named reason, never `in` and never UNKNOWN."""
    block = brief(r0, oa, "pr-comment-only", tmp_path)
    assert "### from the PR comment" in block
    assert "### from the session transcript" not in block
    disp, why = r0.disposition_of([block], oa.SOURCE_SESSION)
    assert disp == "out", f"got {disp!r} ({why})"
    assert "another source" in why


# --------------------------------------------------------------------------- #
# 2. THE THREE DISPOSITIONS
# --------------------------------------------------------------------------- #
def test_a_session_whose_asks_block_ANSWERED_is_in_population(
        r0, oa, tmp_path):
    """invariant: in-population is an ask RENDERED from a session transcript —
    the `### from the session transcript` heading `_render_asks` emits."""
    corpus = corpus_with(tmp_path, {
        f"{PROJECT}/s1.jsonl": [
            user_text(brief(r0, oa, "answered", tmp_path), ts=POST_TS),
            assistant(ledger(), ts=POST_TS)]})
    reports, facts = r0.walk(corpus, oa.SOURCE_SESSION)
    assert [r.disposition for r in reports] == ["in"]
    assert facts.dispositions["in"] == 1


def test_a_session_whose_asks_block_could_not_read_a_trailer_is_out(r0, oa, tmp_path):
    """invariant: the measured OUT case — the block says the session-transcript
    source did not answer."""
    corpus = corpus_with(tmp_path, {
        f"{PROJECT}/s1.jsonl": [
            user_text(brief(r0, oa, "unmeasured", tmp_path), ts=POST_TS),
            assistant(ledger(), ts=POST_TS)]})
    reports, _f = r0.walk(corpus, oa.SOURCE_SESSION)
    assert [r.disposition for r in reports] == ["out"]


def test_a_session_with_NO_asks_block_is_out_of_population(r0, oa, tmp_path):
    """invariant: a pre-fix report. Out, never UNKNOWN — nothing about it is
    unreadable."""
    corpus = corpus_with(tmp_path, {
        f"{PROJECT}/s1.jsonl": [assistant(ledger(), ts=PRE_TS)]})
    reports, _f = r0.walk(corpus, oa.SOURCE_SESSION)
    assert [r.disposition for r in reports] == ["out"]


def test_an_asks_block_with_an_unparseable_Sources_block_is_UNKNOWN(
        r0, oa, tmp_path):
    """invariant: present-but-unreadable is its OWN answer. The fixture is a
    heading at line start with no Sources block, which is what a truncated brief
    looks like on disk."""
    truncated = f"{oa.HEADING}\n\nsome asks were inlined here\n"
    corpus = corpus_with(tmp_path, {
        f"{PROJECT}/s1.jsonl": [user_text(truncated, ts=POST_TS),
                                assistant(ledger(), ts=POST_TS)]})
    reports, _f = r0.walk(corpus, oa.SOURCE_SESSION)
    assert [r.disposition for r in reports] == ["UNKNOWN"]


def test_a_source_READ_of_operator_asks_is_not_an_asks_block(r0, oa, tmp_path):
    """invariant, and the reason line-anchoring exists: MEASURED, 39 of 51
    blocks carrying the heading substring on this host are reads of the module's
    own source, and they were inventing UNKNOWNs. A tool_result holding the
    source must classify as `out`, not UNKNOWN."""
    source_read = OPERATOR_ASKS.read_text()
    assert r0.ANCHOR_BLOCK in source_read and r0.ANCHOR_SOURCES in source_read, (
        "this fixture only tests anything while operator_asks.py's own source "
        "carries both anchors — it does today, in HEADING and in render()")
    corpus = corpus_with(tmp_path, {
        f"{PROJECT}/s1.jsonl": [tool_result(source_read, ts=POST_TS),
                                assistant(ledger(), ts=POST_TS)]})
    reports, _f = r0.walk(corpus, oa.SOURCE_SESSION)
    assert [r.disposition for r in reports] == ["out"]


def test_UNKNOWN_is_excluded_from_the_rates_DENOMINATOR(r0, oa, tmp_path):
    """invariant, asserted as ARITHMETIC rather than as a label: the numbers of
    the UNKNOWN reports must appear in NO bucket total."""
    sessions = {}
    for i in range(10):                       # in-population, distinct numbers
        sessions[f"{PROJECT}/in{i}.jsonl"] = [
            user_text(brief(r0, oa, "answered", tmp_path), ts=POST_TS),
            assistant(ledger(5, 1), ts=POST_TS)]
    for i in range(3):                        # UNKNOWN, numbers that cannot mix
        sessions[f"{PROJECT}/unk{i}.jsonl"] = [
            user_text(f"{oa.HEADING}\n\nno sources block here\n", ts=POST_TS),
            assistant(ledger(9, 7), ts=POST_TS)]
    sessions[f"{PROJECT}/pre.jsonl"] = [assistant(ledger(4, 3), ts=PRE_TS)]
    corpus = corpus_with(tmp_path, sessions)

    code, text, b = rates(r0, oa, corpus)
    post_in = r0.stats(b["post_in"])
    assert post_in["n"] == 10
    assert post_in["requirements"] == 50 and post_in["unattributed"] == 10, (
        "the three UNKNOWN reports (9/7 each) leaked into the denominator: "
        f"{post_in}")
    assert len(b["post_unknown"]) == 3
    # …and the POST-cut ALL row does not silently absorb them either.
    assert r0.stats(b["post"])["n"] == 13
    assert code == r0.EXIT_OK, text


# --------------------------------------------------------------------------- #
# 3. THE FLOOR — MIN_SESSIONS, in DISTINCT SESSIONS
# --------------------------------------------------------------------------- #
def test_MIN_SESSIONS_is_ten_and_that_is_a_standing_instruction(r0):
    """invariant: a VALUE pin, so lowering the floor is a visible edit rather
    than a quiet retune. `handoff-audit-pr-operator-asks.md` NEXT #1: do not
    re-tune the feature off n<10."""
    assert r0.MIN_SESSIONS == 10


def _in_population_sessions(r0, oa, tmp_path, n, per_session=1) -> dict:
    """`n` sessions, each with `per_session` in-population reports."""
    sessions = {}
    for i in range(n):
        sessions[f"{PROJECT}/in{i}.jsonl"] = (
            [user_text(brief(r0, oa, "answered", tmp_path), ts=POST_TS)]
            + [assistant(ledger(5, 1), ts=POST_TS) for _ in range(per_session)])
    return sessions


@pytest.mark.parametrize("n_in", [0, 9])
def test_below_MIN_SESSIONS_it_prints_NOT_MEASURABLE_and_exits_6(
        r0, oa, tmp_path, n_in):
    """invariant: the refusal. n=0 is today's real answer on this host."""
    sessions = {f"{PROJECT}/pre{i}.jsonl": [assistant(ledger(4, 3), ts=PRE_TS)]
                for i in range(12)}
    sessions.update(_in_population_sessions(r0, oa, tmp_path, n_in))
    code, text, b = rates(r0, oa, corpus_with(tmp_path, sessions))
    assert code == r0.EXIT_NOT_MEASURABLE, text
    assert f"NOT MEASURABLE (n={n_in} distinct session(s)" in text
    assert "do NOT re-tune the feature" in text
    assert r0.stats(b["post_in"])["n"] == n_in


def test_the_floor_counts_DISTINCT_SESSIONS_not_ledger_lines(r0, oa, tmp_path):
    """🔴 REGRESSION-shaped, from the auditor's own run: it reported
    `POST-cut in-population n=2` and BOTH reports came from ONE session, so one
    verbose round 0 supplied 20% of a ten-REPORT floor. Nine sessions each
    emitting two ledger lines is 18 reports and NINE observations — it must still
    refuse, and the line must name both numbers so nobody reads n=10 as ten
    independent observations."""
    sessions = {f"{PROJECT}/pre{i}.jsonl": [assistant(ledger(4, 3), ts=PRE_TS)]
                for i in range(12)}
    sessions.update(_in_population_sessions(r0, oa, tmp_path, 9, per_session=2))
    code, text, b = rates(r0, oa, corpus_with(tmp_path, sessions))
    assert r0.stats(b["post_in"])["n"] == 18, "the fixture must emit 18 reports"
    assert len({r.session_id for r in b["post_in"]}) == 9
    assert code == r0.EXIT_NOT_MEASURABLE, text
    assert "NOT MEASURABLE (n=9 distinct session(s) / 9 transcript file(s) / 18 report(s)" in text
    assert "the floor counts SESSIONS" in text


def test_the_floor_counts_REAL_SESSIONS_not_transcript_FILES(r0, oa, tmp_path):
    """🔴 REGRESSION for `#1901 round 1`'s F2. A round-0 report is written by an
    auditor SUBAGENT, whose transcript is `<project>/<sid>/subagents/agent-*.jsonl`
    — a different FILE from the parent's, and several auditors of one session are
    several files again (corpus-wide ~6.9x, re-derived 2026-09-28 with
    `_session_id_of` itself; the figure first published here was produced by a
    naive derivation and is pinned as a MECHANISM by
    `test_the_naive_session_derivation_double_counts_and_ours_does_not`). Counting
    files was the same label-wider-than-the-unit defect the `MIN_SESSIONS` rename
    closed, one level up.

    The fixture is ONE session with three in-population files — the parent plus
    two auditor subagents, at the real depth — and it must still refuse."""
    sid = "b5e21e7f-0000-0000-0000-000000000000"
    block = brief(r0, oa, "answered", tmp_path)
    sessions = {f"{PROJECT}/pre{i}.jsonl": [assistant(ledger(4, 3), ts=PRE_TS)]
                for i in range(12)}
    sessions[f"{PROJECT}/{sid}.jsonl"] = [
        user_text(block, ts=POST_TS), assistant(ledger(5, 1), ts=POST_TS)]
    for n in ("a1", "a2"):
        sessions[f"{PROJECT}/{sid}/subagents/agent-{n}.jsonl"] = [
            user_text(block, ts=POST_TS), assistant(ledger(5, 1), ts=POST_TS)]
    code, text, b = rates(r0, oa, corpus_with(tmp_path, sessions))
    assert r0.stats(b["post_in"])["files"] == 3, "the fixture must span 3 files"
    assert r0.stats(b["post_in"])["sessions"] == 1, (
        "three files of ONE session are one observation: "
        f"{sorted({r.session_id for r in b['post_in']})}")
    assert code == r0.EXIT_NOT_MEASURABLE, text
    assert "n=1 distinct session(s) / 3 transcript file(s) / 3 report(s)" in text
    # …and the derivation itself, at both corpus depths
    root = corpus_with(tmp_path, sessions)
    assert r0._session_id_of(root / f"{PROJECT}/{sid}.jsonl", root) == sid
    assert r0._session_id_of(
        root / f"{PROJECT}/{sid}/subagents/agent-a1.jsonl", root) == sid


def test_the_naive_session_derivation_double_counts_and_ours_does_not(
        r0, tmp_path):
    """🔴 REGRESSION for a wrong FIGURE, pinning the MECHANISM rather than a
    census. A corpus-session count published in this arc came from taking the
    first path segment WITHOUT stripping `.jsonl`, which counts a session holding
    both a top-level transcript and a `subagents/` directory TWICE.

    Re-derived on this host 2026-09-28 with `_session_id_of` itself: 6,718 files /
    974 sessions (~6.9x), where the naive derivation gives 1,571 = 974 top-level +
    597 nested with all 597 overlapping. Corpus numbers DRIFT, so what is pinned
    here is the mechanism against a fixture — a future wrong number then FAILS
    instead of reading fine."""
    root = tmp_path / "corpus"
    files = [
        root / PROJECT / "s-top-only.jsonl",
        root / PROJECT / "s-both.jsonl",
        root / PROJECT / "s-both/subagents/agent-a.jsonl",
        root / PROJECT / "s-both/subagents/agent-b.jsonl",
        root / PROJECT / "s-nested-only/subagents/agent-c.jsonl",
    ]
    for f in files:
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text("{}\n")

    ours = {r0._session_id_of(f, root) for f in files}
    assert ours == {"s-top-only", "s-both", "s-nested-only"}, sorted(ours)
    assert len(ours) == 3 and len(files) == 5

    # the DEFECT, spelled out: the same walk WITHOUT the `.jsonl` strip
    naive = {f.relative_to(root).parts[1] for f in files}
    assert naive == {"s-top-only.jsonl", "s-both.jsonl", "s-both",
                     "s-nested-only"}, sorted(naive)
    assert len(naive) == 4 > len(ours), (
        "the naive derivation must OVER-count — that over-count is what produced "
        "the wrong published figure, and this asserts it exists to be avoided")
    assert "s-both.jsonl" in naive and "s-both" in naive, (
        "…and the double-counted session is exactly the one with BOTH shapes")


def test_at_MIN_SESSIONS_a_verdict_prints(r0, oa, tmp_path):
    """invariant: the floor is a floor and not a wall — at ten sessions the
    comparison runs and the verdict names both statistics and the unit."""
    sessions = {f"{PROJECT}/pre{i}.jsonl": [assistant(ledger(4, 3), ts=PRE_TS)]
                for i in range(12)}
    sessions.update(_in_population_sessions(r0, oa, tmp_path, 10))
    code, text, _b = rates(r0, oa, corpus_with(tmp_path, sessions))
    assert code == r0.EXIT_OK, text
    assert "VERDICT: post-cut in-population is LOWER on both statistics" in text
    assert "n=10 distinct session(s) / 10 transcript file(s) / 10 report(s)" in text
    assert "not a causal claim" in text


def test_an_UNDEFINED_share_refuses_instead_of_being_read_as_zero(
        r0, oa, tmp_path):
    """🔴 REGRESSION for `#1901 round 1`'s F3. `stats()` returns None for the
    share whenever a bucket's summed `requirements` is 0 — reachable whenever a
    round 0 legitimately reports zero requirements — and `(x or 0)` turned that
    into a FABRICATED delta inside the one line the closing condition is read
    from: `LOWER on both statistics (… share — vs 0.750, Δ-0.750)`. The mean was
    guarded twice; the share was not guarded at all."""
    sessions = {f"{PROJECT}/pre{i}.jsonl": [assistant(ledger(4, 3), ts=PRE_TS)]
                for i in range(12)}
    # ten in-population sessions, every one reporting ZERO requirements
    for i in range(10):
        sessions[f"{PROJECT}/in{i}.jsonl"] = [
            user_text(brief(r0, oa, "answered", tmp_path), ts=POST_TS),
            assistant(ledger(0, 0), ts=POST_TS)]
    code, text, b = rates(r0, oa, corpus_with(tmp_path, sessions))
    assert r0.stats(b["post_in"])["requirements"] == 0
    assert r0.stats(b["post_in"])["unattributed_share"] is None
    assert code == r0.EXIT_NOT_MEASURABLE, text
    assert "SHARE is UNDEFINED" in text and "no denominator" in text
    assert "on both statistics" not in text, (
        "the verdict must not claim two statistics moved when one does not exist")
    assert "Δ-0." not in text and "Δ+0." not in text, "no fabricated delta"


def test_an_empty_PRE_bucket_is_also_NOT_MEASURABLE(r0, oa, tmp_path):
    """invariant: exit 6's SECOND reason — a comparison with no left-hand side.
    Documented as sharing the code because it demands the same action."""
    sessions = _in_population_sessions(r0, oa, tmp_path, 10)
    code, text, _b = rates(r0, oa, corpus_with(tmp_path, sessions))
    assert code == r0.EXIT_NOT_MEASURABLE, text
    assert "pre-cut bucket is empty" in text


# --------------------------------------------------------------------------- #
# 3b. WHAT THE REPORT MUST SAY ABOUT ITS OWN ROWS
# --------------------------------------------------------------------------- #
def test_the_CONTEMPORANEOUS_control_row_is_printed_beside_the_comparator(
        r0, oa, tmp_path):
    """invariant: the comparator is a SELECTED post population against an
    UNSELECTED pre one. POST-cut out-of-population holds skill revision, model
    and repo mix roughly constant and differs only in whether the asks arrived,
    so it is computed by the same walk and must be printed, not discarded."""
    sessions = {f"{PROJECT}/pre{i}.jsonl": [assistant(ledger(4, 3), ts=PRE_TS)]
                for i in range(12)}
    sessions.update(_in_population_sessions(r0, oa, tmp_path, 10))
    for i in range(4):                      # contemporaneous, asks NOT arrived
        sessions[f"{PROJECT}/out{i}.jsonl"] = [
            user_text(brief(r0, oa, "named-but-unreadable", tmp_path),
                      ts=POST_TS),
            assistant(ledger(8, 6), ts=POST_TS)]
    code, text, b = rates(r0, oa, corpus_with(tmp_path, sessions))
    assert r0.stats(b["post_out"])["n"] == 4
    assert "POST-cut out-of-population [control]" in text
    assert "CONTROL (contemporaneous)" in text
    assert "is not the asks block" in text
    assert code == r0.EXIT_OK, text


def test_the_PRE_in_population_note_describes_WHICHEVER_case_HOLDS(
        r0, oa, tmp_path):
    """🔴 REGRESSION for a claim of MY OWN that the next measurement refuted. That
    row was labelled `[struct. 0]` with "cannot be non-zero: no asks block existed
    pre-cut", and the very next real run printed **2** there: the feature's own
    development session rendered real asks blocks from its BRANCH before the
    squash landed. A static label the same run contradicts is the "a comment is a
    claim too" defect, so the note is computed — and BOTH cases are asserted here,
    because a one-pole test is how the false label survived."""
    empty = corpus_with(tmp_path / "a", {
        f"{PROJECT}/s1.jsonl": [assistant(ledger(4, 3), ts=PRE_TS)]})
    _c, text = run(r0, ["--corpus", str(empty), "--cut-iso", CUT_ISO])
    assert "0 as expected" in text
    assert "cannot be non-zero" not in text, "that claim is refuted; do not print it"

    with_pre_in = corpus_with(tmp_path / "b", {
        f"{PROJECT}/s1.jsonl": [
            user_text(brief(r0, oa, "answered", tmp_path), ts=PRE_TS),
            assistant(ledger(4, 3), ts=PRE_TS)]})
    _c, text2 = run(r0, ["--corpus", str(with_pre_in), "--cut-iso", CUT_ISO])
    assert "NON-ZERO (1 report(s) in 1 session(s))" in text2
    assert "pre-merge development use" in text2
    assert "not the comparator" in text2


def test_every_post_cut_report_prints_the_REASON_it_was_classified(
        r0, oa, tmp_path):
    """invariant: the classification is auditable from the output — the same
    `why` strings `disposition_of` returns, with counts."""
    sessions = {
        f"{PROJECT}/a.jsonl": [
            user_text(brief(r0, oa, "answered", tmp_path), ts=POST_TS),
            assistant(ledger(5, 1), ts=POST_TS)],
        f"{PROJECT}/b.jsonl": [
            user_text(brief(r0, oa, "named-but-unreadable", tmp_path),
                      ts=POST_TS),
            assistant(ledger(5, 1), ts=POST_TS)],
    }
    _code, text = run(r0, ["--corpus", str(corpus_with(tmp_path, sessions)),
                           "--cut-iso", CUT_ISO])
    assert "post-cut ·" in text
    assert "the operator's words reached the auditor" in text
    assert "could not be read, so no ask arrived" in text


# --------------------------------------------------------------------------- #
# 4. PROVENANCE SEPARATION
# --------------------------------------------------------------------------- #
def test_the_same_ledger_line_in_an_assistant_block_and_a_tool_result_counts_ONCE(
        r0, oa, tmp_path):
    """invariant: the naive walk's over-count. The skill body and the brief are
    injected as tool_result/user text, so the sentence a report is recognised by
    also appears in what ASKED for the report."""
    line = ledger(7, 2)
    corpus = corpus_with(tmp_path, {
        f"{PROJECT}/s1.jsonl": [tool_result(line, ts=POST_TS),
                                user_text(line, ts=POST_TS),
                                assistant(line, ts=POST_TS)]})
    reports, facts = r0.walk(corpus, oa.SOURCE_SESSION)
    assert len(reports) == 1, [r.__dict__ for r in reports]
    assert facts.injected_ledger_lines == 2, (
        "the injected copies must be COUNTED and excluded, not ignored — the "
        "over-count is what the report discloses")


def test_a_thinking_block_is_not_a_report(r0, oa, tmp_path):
    """invariant: reasoning about the ledger is not reporting it."""
    corpus = corpus_with(tmp_path, {
        f"{PROJECT}/s1.jsonl": [
            {"type": "assistant", "timestamp": POST_TS,
             "message": {"role": "assistant",
                         "content": [{"type": "thinking",
                                      "thinking": ledger(7, 2)}]}}]})
    reports, facts = r0.walk(corpus, oa.SOURCE_SESSION)
    assert reports == []
    assert facts.injected_ledger_lines == 1


# --------------------------------------------------------------------------- #
# 5. CORPUS WALKING — the nested transcript and its project
# --------------------------------------------------------------------------- #
NESTED = f"{PROJECT}/b5e21e7f-0000-0000-0000-000000000000/subagents/agent-a0.jsonl"


def test_a_nested_subagents_transcript_is_walked_and_counted(r0, oa, tmp_path):
    """invariant: a real post-merge report of this arc lives three levels down,
    in `<project>/<session>/subagents/<agent>.jsonl`. The fixture sits at that
    exact depth on purpose — a shallower one SURVIVES a mutant that globs one
    level (measured in this arc: a `*/` pattern read as covering `subagents/`)."""
    assert NESTED.count("/") == 3
    corpus = corpus_with(tmp_path, {NESTED: [
        user_text(brief(r0, oa, "answered", tmp_path), ts=POST_TS),
        assistant(ledger(), ts=POST_TS)]})
    reports, _f = r0.walk(corpus, oa.SOURCE_SESSION)
    assert len(reports) == 1 and reports[0].disposition == "in"


def test_the_project_is_the_FIRST_segment_not_the_parent_directory(
        r0, oa, tmp_path):
    """invariant: `path.parent.name` is literally `subagents` for the fixture
    above — the trap this derivation exists to avoid."""
    corpus = corpus_with(tmp_path, {NESTED: [assistant(ledger(), ts=POST_TS)]})
    reports, _f = r0.walk(corpus, oa.SOURCE_SESSION)
    assert reports[0].project == PROJECT
    assert reports[0].project != "subagents"
    assert r0._project_of(corpus / NESTED, corpus) == PROJECT


def test_a_record_with_no_timestamp_is_undated_and_folded_into_nothing(
        r0, oa, tmp_path):
    """invariant: an undated report is reported and belongs to NEITHER bucket."""
    undated = {"type": "assistant",
               "message": {"role": "assistant",
                           "content": [{"type": "text", "text": ledger(6, 6)}]}}
    corpus = corpus_with(tmp_path, {
        f"{PROJECT}/s1.jsonl": [undated],
        f"{PROJECT}/s2.jsonl": [assistant(ledger(4, 3), ts=PRE_TS)]})
    code, text, b = rates(r0, oa, corpus)
    assert len(b["undated"]) == 1
    assert r0.stats(b["pre"])["n"] == 1
    assert r0.stats(b["post"])["n"] == 0
    assert r0.stats(b["pre"])["unattributed"] == 3, (
        "the undated report's 6 leaked into the PRE bucket")
    assert "undated (no `timestamp`): 1" in text
    assert code == r0.EXIT_NOT_MEASURABLE


#: The widest real author/committer divergence over the 1,200 newest
#: `origin/main` commits (`daa6fd65`: +2,556 s = 42.6 min; 10 of 1,200 diverge at
#: all). Used as the fixture's two dates so a test can tell the clocks apart.
FIXTURE_AUTHOR_DATE = "2026-08-22T13:20:35-05:00"
FIXTURE_COMMITTER_DATE = "2026-08-22T14:03:11-05:00"


def _repo_with_diverging_clocks(r0, tmp_path):
    """A one-commit git repo whose author and committer dates DIFFER.

    🔴 A FIXTURE REPO, NEVER THIS CHECKOUT. The `nix build` sandbox tier copies
    the tree with NO `.git` (`CLAUDE.md`), so any test resolving a sha in
    `REPO_ROOT` is red there while passing on the dev host — the two-tier blind
    spot. Built through `testlib.hermetic_git` so git's auto-maintenance cannot
    race the fixture.
    """
    repo = tmp_path / "repo"
    repo.mkdir()
    env = hermetic_git.hermetic_git_env(
        GIT_AUTHOR_DATE=FIXTURE_AUTHOR_DATE,
        GIT_COMMITTER_DATE=FIXTURE_COMMITTER_DATE,
        GIT_AUTHOR_NAME="a", GIT_AUTHOR_EMAIL="a@example.invalid",
        GIT_COMMITTER_NAME="a", GIT_COMMITTER_EMAIL="a@example.invalid")

    def git(*args):
        out = subprocess.run(["git", "-C", str(repo), *args], env=env,
                             capture_output=True, text=True)
        assert out.returncode == 0, out.stderr
        return out.stdout.strip()

    git("init", "-q", "-b", "main")
    (repo / "f").write_text("x\n")
    git("add", "f")
    git("commit", "-q", "-m", "a squash whose two clocks disagree")
    sha = git("rev-parse", "HEAD")
    # CONTROL: the fixture must really carry two different instants, or a test
    # using it cannot tell the clocks apart and would pass under the defect.
    got_a, got_c = git("log", "-1", "--format=%aI\t%cI").split("\t")
    assert r0.parse_ts(got_a) != r0.parse_ts(got_c), (
        "the fixture's two clocks coincide, so it cannot distinguish %aI from "
        f"%cI: {got_a} vs {got_c}")
    return repo, sha, FIXTURE_AUTHOR_DATE, FIXTURE_COMMITTER_DATE


def test_the_cut_is_read_off_the_COMMITTER_date_not_the_author_date(
        r0, tmp_path):
    """invariant, and the guard for a REAL defect this replaced: the condition
    is "reports recorded AFTER `31033cdb`" — i.e. after the change LANDED. For a
    GitHub squash the author date is the PR author's own and can precede the
    merge, so reading `%aI` classifies reports written in that window as
    POST-cut while the fix was not yet on `main` — contaminating the post-cut
    bucket with PRE-fix reports, the exact misattribution this tool measures.

    The fixture's two dates are ~42 min apart on purpose: that is the WIDEST
    real divergence over the 1,200 newest `origin/main` commits (`daa6fd65`,
    +2,556 s; 10 of 1,200 diverge at all). A fixture whose dates coincided would
    pass under either clock — which is how the defect survived, since
    `31033cdb`'s own two dates are identical to the second.
    """
    repo, sha, author, committer = _repo_with_diverging_clocks(r0, tmp_path)
    cut = r0.resolve_cut(sha, repo)
    assert r0.parse_ts(cut) == r0.parse_ts(committer), (
        "the cut must be the COMMITTER date (when the change LANDED), not the "
        f"author date: got {cut}, committer {committer}, author {author}")
    assert r0.parse_ts(cut) != r0.parse_ts(author)
    assert r0.CUT_CLOCK == "%cI"
    assert "committer" in r0.CUT_CLOCK_LABEL


def test_the_run_NAMES_the_clock_its_cut_came_from(r0, oa, tmp_path):
    """invariant: a cut printed without saying which of a commit's two dates it
    read leaves the reader unable to tell "authored" from "landed"."""
    repo, sha, author, committer = _repo_with_diverging_clocks(r0, tmp_path)
    corpus = corpus_with(tmp_path, {
        f"{PROJECT}/s1.jsonl": [assistant(ledger(4, 3), ts=PRE_TS)]})
    _code, text = run(r0, ["--corpus", str(corpus), "--since-sha", sha,
                           "--repo", str(repo)])
    assert "%cI" in text and "committer date" in text
    # …and the cut it printed is the LANDING instant, not the authored one.
    assert committer[:19] in text and author[:19] not in text
    # and the hermetic door says plainly that no git was consulted at all
    _code, hermetic = run(r0, ["--corpus", str(corpus), "--cut-iso", CUT_ISO])
    assert "no git consulted" in hermetic


def test_the_cut_is_a_PARAMETER_and_moves_the_buckets(r0, oa, tmp_path):
    """invariant: bucketing is by the record's own timestamp against the cut, so
    moving the cut moves reports. A hardcoded cut could not be measured at two
    points, and one measurement is not a general claim."""
    corpus = corpus_with(tmp_path, {
        f"{PROJECT}/s1.jsonl": [assistant(ledger(4, 3), ts=POST_TS)]})
    reports, _f = r0.walk(corpus, oa.SOURCE_SESSION)
    before = r0.bucket_reports(reports, r0.parse_ts(CUT_ISO))
    after = r0.bucket_reports(reports, r0.parse_ts("2026-09-28T00:00:00Z"))
    assert r0.stats(before["post"])["n"] == 1
    assert r0.stats(after["post"])["n"] == 0
    assert r0.stats(after["pre"])["n"] == 1, "it moved buckets, not vanished"


# --------------------------------------------------------------------------- #
# 6. THE SELF-CONTROLS
# --------------------------------------------------------------------------- #
def test_an_empty_corpus_fails_the_POSITIVE_control_with_exit_4(r0, tmp_path):
    """invariant: a walk that found no assistant-authored ledger line anywhere
    is indistinguishable from a walk wired to nothing, so it must refuse rather
    than print a reassuring 0."""
    empty = tmp_path / "corpus"
    empty.mkdir()
    code, text = run(r0, ["--corpus", str(empty), "--cut-iso", CUT_ISO])
    assert code == r0.EXIT_NOTHING_WALKED, text
    assert "POSITIVE" in text and "FAILED" in text
    assert "VERDICT" not in text, "no verdict may print off a failed control"


def test_the_negative_control_refuses_when_the_sentinel_is_planted(
        r0, oa, tmp_path):
    """invariant: the matcher must not be matching anything. The sentinel is
    COMPUTED, so this plants `NEG_CONTROL`'s value rather than a literal —
    writing the literal into a tracked file is what poisoned the sibling
    sweep's control for weeks."""
    corpus = corpus_with(tmp_path, {
        f"{PROJECT}/s1.jsonl": [assistant(ledger(4, 3), ts=PRE_TS),
                                assistant(f"x {r0.NEG_CONTROL} y", ts=PRE_TS)]})
    code, text = run(r0, ["--corpus", str(corpus), "--cut-iso", CUT_ISO])
    assert code == r0.EXIT_CONTROL, text
    assert "NEGATIVE" in text and "FAILED" in text
    assert "VERDICT" not in text


def test_the_sentinel_is_computed_and_not_written_down(r0):
    """invariant: the corpus IS the transcripts, so a literal sentinel in this
    tree poisons its own control the moment any session reads the file."""
    assert r0.NEG_CONTROL not in SCRIPT.read_text()
    assert r0.NEG_CONTROL not in Path(__file__).read_text()
    assert len(r0.NEG_CONTROL) > 16


# --------------------------------------------------------------------------- #
# 7. WHAT THE OUTPUT MAY AND MAY NOT CARRY
# --------------------------------------------------------------------------- #
def test_default_output_carries_no_transcript_prose(r0, oa, tmp_path):
    """invariant: devrc is PUBLIC and the corpus is transcripts. Counts, rates
    and shapes only."""
    secret = "an-invented-operator-sentence-that-must-not-be-echoed"
    ask = oa.Ask(source=oa.SOURCE_SESSION, text=secret, session_id="a" * 8)
    block = oa.render([ask], session_ids=("a" * 8,), comments_examined=0,
                      projects_root=tmp_path / "nope")
    assert secret in block
    corpus = corpus_with(tmp_path, {
        f"{PROJECT}/s1.jsonl": [user_text(block, ts=POST_TS),
                                assistant(f"{secret}\n{ledger()}", ts=POST_TS)]})
    _code, text = run(r0, ["--corpus", str(corpus), "--cut-iso", CUT_ISO])
    assert secret not in text


def test_no_transcript_PATH_is_ever_printed(r0, oa, tmp_path):
    """invariant: a transcript path names a session and a project directory; it
    is per-session metadata about the operator's work and this repo is PUBLIC.
    ⚠ `--samples` — the flag that used to print shapes under a prohibition on
    committing them — was DELETED by `#1901 round 0`'s deletion pass (no
    consumers), so there is no surface left that could carry one.
    """
    corpus = corpus_with(tmp_path, {
        f"{PROJECT}/s1.jsonl": [assistant(ledger(4, 3), ts=PRE_TS)]})
    _c, text = run(r0, ["--corpus", str(corpus), "--cut-iso", CUT_ISO])
    assert "s1.jsonl" not in text
    assert "SAMPLES" not in text
    # the corpus ROOT is printed on purpose (it says what was walked); a
    # per-session path under it is not.
    assert f"{PROJECT}/s1" not in text


def test_the_deleted_flags_are_really_gone(r0, tmp_path):
    """invariant: `--samples` and `--json` were removed, not hidden. argparse
    must REJECT them, so a caller (or a stale recipe) fails loudly instead of
    silently getting a different report."""
    corpus = corpus_with(tmp_path, {
        f"{PROJECT}/s1.jsonl": [assistant(ledger(4, 3), ts=PRE_TS)]})
    for flag, value in (("--samples", "3"), ("--json", str(tmp_path / "x.json"))):
        code, _text = run(
            r0, ["--corpus", str(corpus), "--cut-iso", CUT_ISO, flag, value])
        assert code == r0.EXIT_USAGE, (
            f"{flag} must be an argparse error (exit {r0.EXIT_USAGE}), got "
            f"{code} — a silently-accepted dead flag is worse than none")


def test_an_unreadable_corpus_exits_4_AS_THE_LEGEND_SAYS(r0, tmp_path):
    """🔴 REGRESSION for `#1901 round 1`'s F5, and a check the number-only test
    below structurally CANNOT do: the legend said an unreadable corpus path was
    rc 2 while `walk` refuses with rc 4. This asserts the documented CLAIM by
    running it, so the description is pinned and not just the digit."""
    code, _text = run(r0, ["--corpus", str(tmp_path / "absent"),
                           "--cut-iso", CUT_ISO])
    assert code == r0.EXIT_NOTHING_WALKED, f"got {code}"
    legend = (r0.__doc__ or "").split("Exit codes:", 1)[1]
    line = f"{r0.EXIT_NOTHING_WALKED} nothing walked"
    assert line in legend, (
        f"the legend must describe rc {r0.EXIT_NOTHING_WALKED} as what it does; "
        f"it reads: {legend[:220]!r}")
    assert "corpus path" in legend.split(line, 1)[1][:160]


def test_every_render_KWARG_is_exercised_by_a_probe(r0, oa, tmp_path):
    """🔴 REGRESSION for `#1901 round 2`'s 🟡-4, and it makes the SOURCES axis
    derivable instead of hand-enumerated. `render()` emits
    `{PR comment}: N skipped — {why}` from its `comment_skips` keyword, no probe
    drove that keyword, so the widened GROWS never saw the shape — F4's claim that
    GROWS matches EVERY source line was true only of shapes the probe matrix
    happened to emit.

    The asks side is derived from `SOURCE_ORDER`; this is the sources side: every
    parameter of `render()` that can add a line must be driven by some probe, so a
    NEW keyword fails the suite until a probe drives it."""
    params = [p for p in inspect.signature(oa.render).parameters
              if p not in ("asks", "projects_root")]
    assert set(params) == {"unmeasured", "session_ids", "comment_skips",
                           "comments_examined", "dropped"}, params
    probes = r0.renderer_probes(oa, tmp_path / "nope")
    # each keyword's own line shape must appear in at least one probe's output
    marker = {"unmeasured": ": UNKNOWN — ",
              "session_ids": "session(s) NAMED BY",
              "comment_skips": " skipped — ",
              "comments_examined": "comment(s) examined",
              "dropped": ": dropped "}
    assert set(marker) == set(params), (
        "a keyword gained or lost a marker — decide what line it emits and "
        f"whether an anchor covers it: {sorted(set(params) ^ set(marker))}")
    for kw, needle in marker.items():
        assert any(needle in text for text in probes.values()), (
            f"no probe drives `{kw}`, so the pin is blind to the line it emits")
    # …and every one of those lines is covered by an anchor (the GROWS claim)
    for text in probes.values():
        _asks, sources, _f = r0.block_regions(text)
        _roles, _ids, bad = r0.match_anchors(sources, "sources")
        assert bad == [], f"uncovered source line(s): {bad}"


def test_the_pin_reach_the_ANCHORS_header_CLAIMS_is_the_reach_it_HAS(
        r0, oa, tmp_path):
    """🔴 REGRESSION for `#1901 round 1`'s F4: that header claimed two things the
    implementation did not do, both measured INERT (rc 4, not rc 5). Both are
    asserted here as behaviour rather than prose.

    (a) a NEW ask source must reach a probe — the probes are derived from
        `oa.SOURCE_ORDER`, not from two hand-named constants;
    (b) GROWS must cover EVERY source line, not just session-transcript ones.
    """
    probes = r0.renderer_probes(oa, tmp_path / "nope")
    # (a) every declared source appears as a heading in the `every-source` probe
    asks, sources, _f = r0.block_regions(probes["every-source"])
    assert len(asks) == len(oa.SOURCE_ORDER) >= 2, (asks, oa.SOURCE_ORDER)
    for src in oa.SOURCE_ORDER:
        assert any(f"### from the {src}" in a for a in asks), src
    # (b) a PR-comment source line is covered, so an UNCOVERED one would GROW
    pr_lines = [l for l in sources if oa.SOURCE_PR_COMMENT + ":" in l]
    assert pr_lines, "the probe must emit PR-comment source lines"
    _roles, ids, bad = r0.match_anchors(pr_lines, "sources")
    assert bad == [] and ids, (bad, ids)
    # …and an invented source line really does trip GROWS
    _r, _i, invented = r0.match_anchors(
        ["  a new source: 3 thing(s) considered"], "sources")
    assert invented, "an uncovered source line must be reported as unmatched"


def test_every_exit_code_constant_is_documented_in_the_docstring(r0):
    """invariant: a code nobody documented is a code a reader will guess at.
    Two-way-ish: each constant's NUMBER must appear in the `Exit codes:` prose,
    and the prose is the only place their meanings live."""
    doc = r0.__doc__ or ""
    codes = doc.split("Exit codes:", 1)
    assert len(codes) == 2, "the docstring has no `Exit codes:` section"
    legend = codes[1]
    for name in ("EXIT_OK", "EXIT_USAGE", "EXIT_CONTROL", "EXIT_NOTHING_WALKED",
                 "EXIT_PIN", "EXIT_NOT_MEASURABLE"):
        value = getattr(r0, name)
        assert f"{value} " in legend or f"{value}·" in legend, (
            f"{name}={value} is not documented in the Exit codes legend")


def test_the_report_states_its_own_method(r0, oa, tmp_path):
    """invariant: defect 1 was a number quoted without its method. The run must
    say what one report IS, and that a count is not the statistic."""
    corpus = corpus_with(tmp_path, {
        f"{PROJECT}/s1.jsonl": [assistant(ledger(4, 3), ts=PRE_TS)]})
    _code, text = run(r0, ["--corpus", str(corpus), "--cut-iso", CUT_ISO])
    assert "assistant-authored text block" in text
    assert "a RATE, never a count" in text
    assert "mean/report" in text and "share" in text
