"""🔴 `githooks/install.sh` must be able to install on a home-manager host.

WHY THIS FILE EXISTS
--------------------
MEASURED on the workbench host 2026-08-26 (#905). `install.sh` ran
`git config --global core.hooksPath "$DIR"`. On this machine:

  * `git config --global` resolves to `~/.config/git/config`
  * that path is a symlink into the READ-ONLY nix store
    (`/nix/store/…-hm_gitconfig`) generated by `nix/programs/git/default.nix`
  * `~/.gitconfig` does not exist

so the installer died on its FIRST config write:

    error: could not lock config file …/.config/git/config: Read-only file system
    rc=255

before seeding `~/.claude/audit-on-push.env` and before printing anything
useful. `core.hooksPath` was therefore unset on this host and the pre-push test
gate and the audit hook had NEVER been installable here at all.

THE MECHANISM THE FIX RESTS ON, MEASURED RATHER THAN ASSUMED. git consults
exactly two files for global scope — `$XDG_CONFIG_HOME/git/config` and
`~/.gitconfig` — and it reads BOTH, with `~/.gitconfig` winning for a key set in
both. So when home-manager owns the XDG file, `~/.gitconfig` is not a workaround,
it is the other half of git's own documented pair, and writing there leaves every
home-manager setting in force. `test_the_home_manager_settings_survive_the_fallback`
is that claim as an executable assertion rather than a comment.

🔴 TWO BASELINES, BECAUSE THERE ARE TWO DEFECTS. Quoting only the first would
mislabel four tests. Measured, both restored byte-identical afterwards:

  * vs `origin/main` (the #905 defect):        12 FAILED / 4 PASSED
  * vs 426c4d52 (this branch's first commit,
    the code the audit findings were against):  4 FAILED / 12 PASSED

The 4 red at 426c4d52 are exactly the four audit findings — provenance-vs-size,
the un-rolled-back failed install, the TMPDIR-inside-a-repo read, and the unset
HOME diagnostic. Two of them (`…keeps_an_operator_created_gitconfig`,
`…rolls_back_the_file_it_created`) are GREEN at `origin/main` and that is not
coverage: at base the installer never gets far enough to create a file, so they
pass for a reason unrelated to what they assert. Judge those two against
426c4d52 only.

WHAT IS REGRESSION COVERAGE HERE AND WHAT IS NOT (RULES.md asks for the label):

  * `test_the_installer_succeeds_when_the_global_config_is_read_only` is THE
    regression test for #905. It is the measured failure, reproduced.
  * `test_the_hooks_path_is_actually_in_effect_not_merely_written` is regression
    coverage too, and it is the one that matters: `core.hooksPath` sitting in a
    file git does not consult installs nothing. "Wrote" and "in effect" are
    separate claims and this asserts the second.
  * `test_the_audit_env_file_is_seeded_on_a_read_only_host` is regression
    coverage for the SECOND consequence of the same defect — the script exited
    before the seeding block, so the flag file was never created either.
  * `test_the_home_manager_settings_survive_the_fallback` is regression coverage
    for the hazard the FIX introduces: a fallback that silently disabled
    `rebase.autoStash = false` would be a worse defect than the one it closes
    (that setting is the repo's fail-closed guard against the shared stash —
    see `nix/programs/git/default.nix`). Nothing else in the tree would notice.
  * `test_uninstall_reverts_the_fallback_file` is regression coverage: the
    fallback moved WHERE the value lives, so an `--uninstall` that only looked
    at `git config --global` would silently leave the hooks armed.
  * `test_the_effectiveness_check_refuses_a_shadowed_write` is regression
    coverage for the same "wrote != installed" hazard, exercised through a real
    input (`GIT_CONFIG_COUNT`, which outranks every config file) rather than
    through a mutant.
  * `test_uninstall_keeps_an_operator_created_gitconfig` is regression coverage
    for an audit finding, AGAINST 426c4d52 (red there, green at origin/main —
    see the two-baseline note): removal used to be gated on the file being
    0 bytes, which is SIZE, not PROVENANCE.
  * `test_uninstall_removes_only_a_gitconfig_it_created_itself` is its pair, and
    the pair is deliberate — the test above alone is satisfied by an
    `--uninstall` that never removes anything. It is red at `origin/main` and
    GREEN at 426c4d52, which is correct: the size-based version also removed the
    file. It pins the capability the provenance fix must not lose.
  * `test_a_failed_install_rolls_back_the_file_it_created` is regression
    coverage for the other half of that finding: a FAILED install used to leave
    its new `~/.gitconfig` behind, narrowing `git config --global` permanently
    and for nothing.
  * `test_the_effective_read_is_not_poisoned_by_a_repo_around_TMPDIR` is
    regression coverage for an audit finding: `mktemp -d` honours $TMPDIR and is
    NOT necessarily outside a repository, so the effectiveness read could return
    a repo-local value and fail a good install.

  * `test_uninstall_leaves_a_hooks_path_it_did_not_write` is an INVARIANT GUARD.
    The pre-fix script already refused to unset a foreign value; no bug ever
    violated it. It is here because the fix widened `--uninstall` from one file
    to several, and widening a search is exactly how such a rule gets lost. It
    is NOT counted as regression coverage for #905.
  * `test_an_unset_HOME_gives_a_diagnostic_not_an_unbound_variable` is RED at
    BOTH baselines, so it is regression coverage by measurement — but for a
    LEGIBILITY defect nobody ever hit in practice, not a behavioural one. Both
    halves stated rather than picking the flattering one.
  * `test_an_explicit_GIT_CONFIG_GLOBAL_is_never_escaped` is an INVARIANT GUARD,
    and it guards the suite's own isolation: `scripts/tests/test_nogit_isolation.py`
    runs this very installer with `GIT_CONFIG_GLOBAL` pointed at a session file
    to keep it off the operator's config. A fallback that fired when THAT file
    was unwritable would write outside the nominated file and defeat the guard.
    The pre-fix script had no fallback, so it passes at base; labelled a guard
    for that reason.
  * `test_the_xdg_location_is_honoured_whether_or_not_XDG_CONFIG_HOME_is_set`
    is REGRESSION coverage — both parametrisations are red at base, because at
    base the installer cannot install at all. It is listed apart only because it
    ADDITIONALLY measures at two points on a dimension the fixture would
    otherwise pin: a suite that always exports XDG_CONFIG_HOME is structurally
    blind to a defect in the `${XDG_CONFIG_HOME:-$HOME/.config}` default, and
    one that never exports it is blind to the variable being honoured.
    (It was drafted as an invariant guard; the measured base run said otherwise
    and the label follows the measurement.)

🔴 NOTHING HERE MAY TOUCH THE OPERATOR'S GIT CONFIG. Every child gets a HOME
under `tmp_path` and an environment with every `GIT_CONFIG_*` /
`XDG_CONFIG_HOME` lever REMOVED — removed rather than set, because the outer
gate run exports `GIT_CONFIG_GLOBAL` for its own isolation and leaving it in
place would send every run down the explicit-override branch, so the fallback
under test would never execute and the whole file would pass vacuously.
`test_the_fixture_actually_exercises_the_fallback` is the positive control that
this did not happen.
"""
from __future__ import annotations

import os
import subprocess
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]

# 🔴 A TEST-ONLY SEAM, and the reason it exists is the mutation battery.
# `scripts/tests/mutants-install-sh.sh` must be able to run this file against a
# MUTATED installer without ever writing a mutant into the working tree — the
# convention every other `mutants-*.sh` in this directory follows, because an
# EXIT-trap restore over a tracked file is one SIGKILL or one concurrent
# `git add` away from someone else staging a mutant.
#
# 🔴 GITHOOKS IS DERIVED FROM THE INSTALLER, NOT NAMED SEPARATELY. install.sh
# computes `$DIR` from its own location, so a copy at `<tmp>/githooks/install.sh`
# installs `<tmp>/githooks`. Two independently-spelled constants would agree
# until the day the seam was used, and then this file would assert against the
# wrong directory and score a mutant SURVIVED.
INSTALLER = Path(os.environ.get("DEVRC_TEST_INSTALLER")
                 or REPO_ROOT / "githooks" / "install.sh").resolve()
GITHOOKS = INSTALLER.parent

# The string the installer prints when it had to use the fallback. Assembled
# rather than spelled so this file's own text cannot satisfy a grep for it.
FALLBACK_NOTE = "is not writable (home-manager owns it"


# --------------------------------------------------------------------------- #
# Fixture: a faithful home-manager host
# --------------------------------------------------------------------------- #
@pytest.fixture
def hm_home(tmp_path):
    """A HOME whose global git config is a symlink into a read-only store.

    This reproduces the measured shape exactly: the XDG config EXISTS (so git
    picks it as the global file), it is a symlink (so `readlink -f` leaves the
    home directory), and its target plus target directory are read-only (so the
    lock file git needs cannot be created — which is the actual failure, not the
    file mode itself).

    The read-only mode is restored on teardown; pytest cannot clean a 0555
    directory and the next run would error for an unrelated reason.
    """
    home = tmp_path / "hm-home"
    store = tmp_path / "nix-store"
    (home / ".config" / "git").mkdir(parents=True)
    store.mkdir()

    hm_cfg = store / "hm_gitconfig"
    hm_cfg.write_text(
        # 🔴 THE TWO autoStash KEYS AND core.sshCommand ARE HERE ON PURPOSE.
        # README and the module docstring claim EVERY home-manager setting stays
        # in force; a fixture carrying three keys could not observe that, and the
        # two most safety-relevant ones were the ones missing. `merge.autoStash`
        # is the sibling of `rebase.autoStash` (both must stay false — the
        # fail-closed guard against the repo-global stash), and `core.sshCommand`
        # is #782/#887's push keepalive, which a masked fallback would silently
        # drop and turn long pre-push gates back into SIGPIPE failures.
        "[user]\n\tname = FromHomeManager\n"
        "[rebase]\n\tautoStash = false\n"
        "[merge]\n\tautoStash = false\n"
        "[diff]\n\talgorithm = histogram\n"
        "[core]\n\tsshCommand = ssh -o ServerAliveInterval=30 "
        "-o ServerAliveCountMax=6\n",
        encoding="utf-8",
    )
    (home / ".config" / "git" / "config").symlink_to(hm_cfg)
    hm_cfg.chmod(0o444)
    store.chmod(0o555)
    try:
        yield home
    finally:
        store.chmod(0o755)
        hm_cfg.chmod(0o644)


def _env(home: Path, **extra) -> dict:
    """Child env with every global-config lever stripped, then HOME redirected.

    Stripping is the point — see this module's docstring. `None` in `extra`
    removes a key.
    """
    env = {k: v for k, v in os.environ.items()
           if not k.startswith("GIT_CONFIG")
           and k not in ("XDG_CONFIG_HOME", "GIT_DIR", "GIT_WORK_TREE")}
    env["HOME"] = str(home)
    env["XDG_CONFIG_HOME"] = str(home / ".config")
    for k, v in extra.items():
        if v is None:
            env.pop(k, None)
        else:
            env[k] = str(v)
    return env


def _install(home: Path, *args: str, env: dict | None = None):
    return subprocess.run(
        ["bash", str(INSTALLER), *args],
        capture_output=True, text=True, timeout=120,
        cwd=str(REPO_ROOT), env=env if env is not None else _env(home),
    )


def _git(home: Path, *args: str, env: dict | None = None) -> str:
    """Read EFFECTIVE config the way a later `git push` would, outside any repo."""
    proc = subprocess.run(
        ["git", "-C", str(home), *args],
        capture_output=True, text=True, timeout=60,
        env=env if env is not None else _env(home),
    )
    return proc.stdout.strip()


# --------------------------------------------------------------------------- #
# Positive control for the fixture itself
# --------------------------------------------------------------------------- #
def test_the_fixture_actually_exercises_the_fallback(hm_home):
    """🔴 POSITIVE CONTROL — without it every test below could pass vacuously.

    Two independent ways this file could test nothing: the fixture's XDG config
    could be writable after all (so the installer never needs the fallback), or
    an inherited `GIT_CONFIG_GLOBAL` could send the run down the explicit-override
    branch. Both would leave the assertions below green while the code path under
    test never executed.

    So: assert the config really is unwritable, and assert the installer really
    said it fell back.
    """
    cfg = hm_home / ".config" / "git" / "config"
    assert cfg.is_symlink(), "fixture is not the measured shape (not a symlink)"
    assert not os.access(cfg.resolve(), os.W_OK), (
        f"{cfg} resolves to a WRITABLE file — the fixture does not reproduce a "
        "home-manager host and every test in this file would pass vacuously")

    proc = _install(hm_home)
    assert "GIT_CONFIG_GLOBAL" not in _env(hm_home), (
        "the child env still carries GIT_CONFIG_GLOBAL — the installer would "
        "take the explicit-override branch and the fallback would never run")
    assert FALLBACK_NOTE in proc.stdout, (
        "the installer did NOT report using the fallback, so the branch this "
        f"file exists to test did not execute:\n{proc.stdout}{proc.stderr}")


# --------------------------------------------------------------------------- #
# Regression coverage for #905
# --------------------------------------------------------------------------- #
def test_the_installer_succeeds_when_the_global_config_is_read_only(hm_home):
    """THE regression test: the measured rc=255, reproduced.

    At base this fails with `could not lock config file … Read-only file system`.
    """
    proc = _install(hm_home)
    assert proc.returncode == 0, (
        "installer failed on a home-manager host (#905):\n"
        f"rc={proc.returncode}\n{proc.stdout}\n{proc.stderr}")
    assert "Read-only file system" not in proc.stderr


def test_the_hooks_path_is_actually_in_effect_not_merely_written(hm_home):
    """🔴 WROTE IS NOT INSTALLED. Assert what git RESOLVES, not what we wrote.

    `core.hooksPath` sitting in a file git does not consult installs nothing, and
    a write to such a file still reports success. This reads the value back the
    way a later `git push` will.
    """
    proc = _install(hm_home)
    assert proc.returncode == 0, proc.stdout + proc.stderr
    assert _git(hm_home, "config", "--get", "core.hooksPath") == str(GITHOOKS), (
        "core.hooksPath is not what git resolves after a successful install")


# --------------------------------------------------------------------------- #
# CDPATH — the dimension every other test in this file PINS
# --------------------------------------------------------------------------- #
# 🔴 `_install()` runs the installer by ABSOLUTE path, which is the one
# invocation shape that CANNOT exhibit this defect, so the whole suite was
# structurally blind to it. `_env()` passes CDPATH through untouched but it is
# inert against an absolute path. These two tests widen the harness onto the
# invocation-path dimension; that widening IS the fix, not extra work.
def _install_relative(home: Path, *args: str, cdpath: str = "."):
    """Invoke the installer the way its own header used to document: relatively.

    Derived from INSTALLER rather than spelled, so that pointing
    DEVRC_TEST_INSTALLER at a mutated copy still exercises the real seam.
    """
    env = _env(home)
    env["CDPATH"] = cdpath
    rel = f"{INSTALLER.parent.name}/{INSTALLER.name}"
    return subprocess.run(
        ["bash", rel, *args],
        capture_output=True, text=True, timeout=120,
        cwd=str(INSTALLER.parent.parent), env=env,
    )


def test_an_exported_CDPATH_cannot_corrupt_the_global_config(hm_home):
    """🔴 THE regression test for the CDPATH hazard. Watched RED at 1b0c57c6.

    With CDPATH exported, bash `cd` echoes the directory it resolved via CDPATH,
    so a RELATIVE invocation made the installer's `$DIR` a two-line string. $DIR
    is interpolated into the provenance stamp, so line 2 landed in ~/.gitconfig
    as CONFIG rather than as a comment.

    The symptom this pins is the real one and it is host-wide: EVERY later git
    command in EVERY repo dies `fatal: bad config line 4`. So the assertion is
    not "the installer exited 0" — a corrupt install can exit 0 (measured, in
    the pre-existing-gitconfig arm). It is that git still WORKS afterwards.
    """
    proc = _install_relative(hm_home)

    # The real symptom, asserted first and independently of the installer's rc:
    # a plain read that any later `git push` performs.
    readback = subprocess.run(
        ["git", "config", "--get", "core.hooksPath"],
        capture_output=True, text=True, timeout=60,
        cwd=str(hm_home), env=_env(hm_home),
    )
    assert "bad config line" not in readback.stderr, (
        "an exported CDPATH corrupted the global git config — git is now broken "
        f"in every repo on the host:\n{readback.stderr}\n"
        f"installer rc={proc.returncode}\n{proc.stdout}\n{proc.stderr}")

    # And the install is either cleanly refused or cleanly correct — never a
    # success report over a two-line value (the arm that exits 0 while the hook
    # never runs).
    if proc.returncode == 0:
        assert readback.stdout.strip() == str(GITHOOKS), (
            "installer reported success but core.hooksPath is not the hooks dir; "
            f"got {readback.stdout.strip()!r}")
    else:
        # Refusing is a correct outcome, but only if it says WHY — an operator
        # who cannot tell this apart from an unrelated failure will reach for
        # the relative invocation again. Pinned on the whole normalised claim,
        # not a lone keyword: `CDPATH` alone also appears in the file's comments
        # and would keep matching if the message were reworded into nonsense.
        normalised = " ".join(proc.stderr.split())
        assert ("refusing to continue" in normalised
                and "single-line path to a real directory" in normalised
                and "CDPATH hazard" in normalised), (
            "installer refused but did not name the CDPATH hazard:\n" + proc.stderr)


def test_an_exported_CDPATH_leaves_a_parseable_gitconfig(hm_home):
    """The stamp must not smuggle a newline into the file it authorises removal of.

    Separate from the test above because that one can be satisfied by refusing
    to run at all, while this one pins the FILE's shape whenever one was created
    — the property `--uninstall` and the failed-install rollback both depend on.
    """
    _install_relative(hm_home)
    gitconfig = hm_home / ".gitconfig"
    if not gitconfig.exists():
        pytest.skip("no fallback file was created; nothing to parse")

    # git's own parser is the arbiter — not a regex of ours.
    proc = subprocess.run(
        ["git", "config", "--file", str(gitconfig), "--list"],
        capture_output=True, text=True, timeout=60, env=_env(hm_home),
    )
    assert proc.returncode == 0, (
        f"the file the installer created is not parseable by git:\n{proc.stderr}\n"
        f"--- {gitconfig} ---\n{gitconfig.read_text()}")
    for key, value in (line.split("=", 1) for line in
                       proc.stdout.splitlines() if "=" in line):
        assert "\n" not in value, f"multi-line value for {key}"


def test_the_audit_env_file_is_seeded_on_a_read_only_host(hm_home):
    """The SECOND consequence of #905: the script exited before this block.

    Confirmed at base — no `.claude` directory was created at all, because the
    config write dies several lines earlier.
    """
    proc = _install(hm_home)
    assert proc.returncode == 0, proc.stdout + proc.stderr
    assert (hm_home / ".claude" / "audit-on-push.env").is_file(), (
        "the flag file was not seeded — the installer exited before reaching it")


def test_the_home_manager_settings_survive_the_fallback(hm_home):
    """🔴 The fallback must not cost the settings home-manager declares.

    `rebase.autoStash = false` is the repo's fail-closed guard against the
    repo-global stash. A fallback that shadowed it would be a worse defect than
    #905. Each key is asserted separately: an aggregate check could pass on one
    surviving key while another was masked.
    """
    proc = _install(hm_home)
    assert proc.returncode == 0, proc.stdout + proc.stderr

    for key, expected in (("rebase.autoStash", "false"),
                          ("merge.autoStash", "false"),
                          ("core.sshCommand",
                           "ssh -o ServerAliveInterval=30 -o ServerAliveCountMax=6"),
                          ("diff.algorithm", "histogram"),
                          ("user.name", "FromHomeManager")):
        assert _git(hm_home, "config", "--get", key) == expected, (
            f"{key} was masked by the fallback — home-manager's value is no "
            "longer in effect")


def test_uninstall_reverts_the_fallback_file(hm_home):
    """`--uninstall` must find the value wherever the installer put it.

    The fix moved WHERE `core.hooksPath` lives, so an uninstall that only
    consulted `git config --global` would report success and leave the hooks
    armed. Asserted on the EFFECTIVE value, for the same reason as the install.
    """
    assert _install(hm_home).returncode == 0
    assert _git(hm_home, "config", "--get", "core.hooksPath") == str(GITHOOKS)

    proc = _install(hm_home, "--uninstall")
    assert proc.returncode == 0, proc.stdout + proc.stderr
    assert _git(hm_home, "config", "--get", "core.hooksPath") == "", (
        "core.hooksPath is STILL in effect after --uninstall")
    # And the home-manager side is untouched by the removal.
    assert _git(hm_home, "config", "--get", "rebase.autoStash") == "false"


def test_the_effectiveness_check_refuses_a_shadowed_write(hm_home):
    """A write that does not take effect must FAIL, not report success.

    Driven by a real input, not a mutant: `GIT_CONFIG_COUNT`/`GIT_CONFIG_KEY_0`
    outrank every config file, so the installer's write genuinely lands and is
    genuinely shadowed — exactly the "wrote but not installed" state.

    🔴 The assertion names THIS guard's own message. A bare non-zero rc would be
    satisfied by any earlier failure, and would still pass with the guard deleted.
    """
    env = _env(hm_home, GIT_CONFIG_COUNT="1",
               GIT_CONFIG_KEY_0="core.hooksPath",
               GIT_CONFIG_VALUE_0="/somewhere/else")
    proc = _install(hm_home, env=env)
    assert proc.returncode != 0, (
        "the installer reported success while core.hooksPath resolved "
        f"elsewhere:\n{proc.stdout}{proc.stderr}")
    assert "did NOT take effect" in proc.stderr, (
        "install failed, but not with the effectiveness check's own message — "
        f"this test would pass for the wrong reason:\n{proc.stdout}{proc.stderr}")


# --------------------------------------------------------------------------- #
# Invariant guards (NOT regression coverage for #905 — see module docstring)
# --------------------------------------------------------------------------- #
def test_uninstall_keeps_an_operator_created_gitconfig(hm_home):
    """🔴 `--uninstall` must not delete a `~/.gitconfig` it did not create.

    REGRESSION coverage for an audit finding. An earlier revision removed the
    file when it was 0 bytes after the unset, and called that "the file this
    installer had to create". SIZE IS NOT PROVENANCE. Measured: an operator's
    own empty `~/.gitconfig` — the exact manual workaround someone would apply
    for #905 — was silently deleted, after which their next `git config --global`
    write fails against the read-only store again.

    The file here is empty and operator-owned, so it is indistinguishable from
    the deleted case BY SIZE and distinguishable only by the absence of a stamp.
    """
    operator_file = hm_home / ".gitconfig"
    operator_file.write_text("", encoding="utf-8")

    assert _install(hm_home).returncode == 0
    proc = _install(hm_home, "--uninstall")

    assert operator_file.exists(), (
        "--uninstall DELETED a ~/.gitconfig the operator created — size was "
        "mistaken for provenance")
    assert proc.returncode == 0, proc.stdout + proc.stderr


def test_uninstall_removes_only_a_gitconfig_it_created_itself(hm_home):
    """The other half of the pair: a file we DID create is cleaned up.

    Without this, the test above is satisfied by an `--uninstall` that never
    removes anything, and the `--global` narrowing would be permanent.
    """
    assert not (hm_home / ".gitconfig").exists(), "fixture precondition"
    assert _install(hm_home).returncode == 0
    assert (hm_home / ".gitconfig").exists(), "the installer created no fallback file"

    proc = _install(hm_home, "--uninstall")
    assert proc.returncode == 0, proc.stdout + proc.stderr
    assert not (hm_home / ".gitconfig").exists(), (
        "the installer created ~/.gitconfig but --uninstall left it behind, "
        "permanently narrowing `git config --global` on this host")


def test_a_failed_install_rolls_back_the_file_it_created(hm_home):
    """A FAILED install must not leave a new `~/.gitconfig` behind.

    REGRESSION coverage for an audit finding: when the effectiveness check
    fails the script exits 1 — but it had already created the file, narrowing
    `git config --global` on that host for nothing, with no hint and no cleanup.

    Driven through the same real input as the effectiveness test itself, so the
    failure is genuine rather than simulated.
    """
    assert not (hm_home / ".gitconfig").exists(), "fixture precondition"
    env = _env(hm_home, GIT_CONFIG_COUNT="1",
               GIT_CONFIG_KEY_0="core.hooksPath",
               GIT_CONFIG_VALUE_0="/somewhere/else")
    proc = _install(hm_home, env=env)

    assert proc.returncode != 0, "expected the effectiveness check to fail"
    assert not (hm_home / ".gitconfig").exists(), (
        "the install FAILED but left behind the ~/.gitconfig it created — "
        "`git config --global` is now permanently narrowed for nothing")


def test_the_effective_read_is_not_poisoned_by_a_repo_around_TMPDIR(
        hm_home, tmp_path):
    """🔴 `mktemp -d` is not necessarily outside a git repository.

    REGRESSION coverage for an audit finding. The installer verifies its write by
    reading `core.hooksPath` back from a scratch dir — but `mktemp -d` honours
    $TMPDIR, and if TMPDIR sits inside a checkout, git walks UP, finds that repo
    and answers with its REPO-LOCAL value. Measured: `/REPO/LOCAL/POISON` came
    back, which fails the effectiveness check on a perfectly good install.

    This is a realistic configuration, not a contrivance — a per-session TMPDIR
    under a working tree is exactly how agent scratch dirs are laid out here.
    """
    repo = tmp_path / "enclosing-repo"
    repo.mkdir()
    subprocess.run(["git", "init", "-q", str(repo)], check=True, timeout=60,
                   capture_output=True)
    subprocess.run(["git", "-C", str(repo), "config",
                    "core.hooksPath", "/REPO/LOCAL/POISON"],
                   check=True, timeout=60, capture_output=True)
    tmpdir = repo / "scratch"
    tmpdir.mkdir()

    proc = _install(hm_home, env=_env(hm_home, TMPDIR=tmpdir))
    assert proc.returncode == 0, (
        "the install failed because the effectiveness read found a REPO-LOCAL "
        f"core.hooksPath instead of the global one:\n{proc.stdout}{proc.stderr}")
    assert "/REPO/LOCAL/POISON" not in proc.stderr


def test_an_unset_HOME_gives_a_diagnostic_not_an_unbound_variable(hm_home):
    """INVARIANT GUARD: fail with an explanation, not `HOME: unbound variable`.

    Every path in the script is anchored on $HOME, and under `set -u` an unset
    HOME aborts from whichever line touches it first. Not a bug anyone hit — a
    legibility floor, labelled as a guard and not counted as regression coverage.
    """
    env = _env(hm_home, HOME=None)
    proc = subprocess.run(["bash", str(INSTALLER)], capture_output=True,
                          text=True, timeout=120, cwd=str(REPO_ROOT), env=env)
    assert proc.returncode != 0
    combined = proc.stdout + proc.stderr
    assert "HOME is not set" in combined, (
        f"expected a diagnostic about HOME; got:\n{combined}")
    assert "unbound variable" not in combined


def test_uninstall_leaves_a_hooks_path_it_did_not_write(hm_home):
    """INVARIANT GUARD: never remove a setting this installer did not write."""
    foreign = "/somebody/elses/hooks"
    (hm_home / ".gitconfig").write_text(
        f"[core]\n\thooksPath = {foreign}\n", encoding="utf-8")

    proc = _install(hm_home, "--uninstall")
    # 🔴 THE OWNERSHIP ASSERTION COMES FIRST, AND THE ORDER IS LOAD-BEARING.
    # Measured: with the ownership check removed, `--uninstall` strips the
    # foreign value AND then fails trying to unset from the read-only XDG file,
    # so it exits non-zero. A leading `returncode == 0` assertion therefore ate
    # the mutant and this test died with the WRONG message — scored a kill while
    # its own assertion was never reached.
    assert _git(hm_home, "config", "--get", "core.hooksPath") == foreign, (
        "--uninstall removed a core.hooksPath belonging to someone else")
    assert proc.returncode == 0, proc.stdout + proc.stderr


def test_an_explicit_GIT_CONFIG_GLOBAL_is_never_escaped(hm_home, tmp_path):
    """INVARIANT GUARD protecting the suite's OWN isolation.

    `test_nogit_isolation.py` runs this installer with `GIT_CONFIG_GLOBAL`
    pointed at a session file precisely so a real run cannot reach the operator's
    config. If that file were unwritable and the installer fell back to
    `$HOME/.gitconfig`, it would write outside the nominated file — the exact
    escape that guard exists to prevent. Refusing is the only correct answer.

    🔴 THE WITNESS IS THE FILE'S CONTENT, NOT ITS EXISTENCE, AND THE DIFFERENCE
    WAS MEASURED. This test used to assert `~/.gitconfig` does not exist. Once the
    failed-install ROLLBACK landed, an escaping installer wrote the file, failed
    its effectiveness check, and then DELETED the file on the way out — so the
    escape happened and the assertion still passed. The mutant that removes the
    refusal went from killed to SURVIVED without the guard changing at all.

    So `~/.gitconfig` is pre-created, empty and operator-owned. That makes the
    rollback structurally unable to erase the evidence (it only removes files the
    run itself created), and turns "did it escape" into a question about CONTENT.
    """
    ro_dir = tmp_path / "ro"
    ro_dir.mkdir()
    nominated = ro_dir / "nominated.config"
    nominated.write_text("", encoding="utf-8")
    nominated.chmod(0o444)
    ro_dir.chmod(0o555)
    operator_file = hm_home / ".gitconfig"
    operator_file.write_text("", encoding="utf-8")
    try:
        proc = _install(hm_home, env=_env(hm_home, GIT_CONFIG_GLOBAL=nominated))
        assert proc.returncode != 0, (
            "installer reported success against an unwritable nominated file")
        assert "hooksPath" not in operator_file.read_text(encoding="utf-8"), (
            "the installer ESCAPED the nominated GIT_CONFIG_GLOBAL and wrote to "
            "$HOME/.gitconfig — this defeats the suite's isolation guard")
        assert FALLBACK_NOTE not in proc.stdout, (
            "the installer ESCAPED the nominated GIT_CONFIG_GLOBAL by taking the "
            "fallback branch, which must never run when an override is set")
    finally:
        ro_dir.chmod(0o755)
        nominated.chmod(0o644)


# --------------------------------------------------------------------------- #
# Back to REGRESSION coverage — this one is red at base (see its docstring); it
# lives down here only because it also measures a fixture dimension at 2 points.
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("xdg_set", [True, False])
def test_the_xdg_location_is_honoured_whether_or_not_XDG_CONFIG_HOME_is_set(
        hm_home, xdg_set):
    """REGRESSION coverage, measured at BOTH points on a dimension the fixture pins.

    🔴 NOT an invariant guard, though it was drafted as one and an earlier
    revision of this file still said so in three places. The measured base run
    settles it: BOTH parametrisations are red at `origin/main`, because at base
    the installer cannot install at all. The label follows the measurement.

    The installer resolves the XDG config as `${XDG_CONFIG_HOME:-$HOME/.config}`.
    A suite that always exports the variable is structurally blind to a defect in
    the default, and one that never exports it is blind to the variable being
    honoured. Both branches must reach the same file, so both must install.
    """
    env = _env(hm_home) if xdg_set else _env(hm_home, XDG_CONFIG_HOME=None)
    assert ("XDG_CONFIG_HOME" in env) is xdg_set, "the parametrisation is inert"

    proc = _install(hm_home, env=env)
    assert proc.returncode == 0, (
        f"install failed with XDG_CONFIG_HOME {'set' if xdg_set else 'unset'}:\n"
        f"{proc.stdout}{proc.stderr}")
    assert FALLBACK_NOTE in proc.stdout, (
        "the read-only XDG config was not detected on this branch, so the "
        "installer did not go through the fallback it should have")
    assert _git(hm_home, "config", "--get", "core.hooksPath", env=env) == str(GITHOOKS)
