r"""Tests for the home-manager-managed opencode configuration.

WHAT IS UNDER TEST (see scripts/opencode/README.md for the measurements):

  1. The GENERATED ~/.config/opencode/AGENTS.md. `nix/home.nix` builds it by
     CONCATENATING claude/PRINCIPLES.md + claude/RULES.md +
     claude/opencode-addendum.md at switch time. It has to be a concatenation
     because opencode does NOT expand `@`-imports in AGENTS.md/CLAUDE.md
     (measured on v1.18.4 with an all-tools-denied agent, so no file read was
     possible: an imported passphrase returned NONE, the same content inline
     returned verbatim). ~/.claude/CLAUDE.md is ~1.5 KB of `@PRINCIPLES.md` +
     `@RULES.md` import lines, so if opencode read THAT it would receive none of
     the 32 KB of actual rules. These tests are the regression guard for that
     whole point: they assert the rules TEXT is present, not merely that a file
     exists.

  2. 🔴 The EFFECTIVE RESOLVED PERMISSION for a set of dangerous commands, on
     EVERY agent. This is the section that matters, and it is deliberately NOT
     a restatement of the file's keys.

     A previous version of this file asserted only key ORDER, and was vacuous
     against the two mutations that actually break the config:
       * appending a trailing `"git *": "allow"` (resurrects every git deny)
         — 82 passed;
       * sorting the bash keys alphabetically — 82 passed, because `"*"` (0x2A)
         sorts to the front, so the "wildcard is first" assertion still held
         while a broad `ask` overtook the narrow `deny` it was meant to lose to.
     Both are pinned by `effective_bash_action` below, which REIMPLEMENTS
     opencode's resolver and asserts the outcome.

  3. The resolver model itself. opencode 1.18.4 resolves a permission by
     `findLast` over a FLAT ORDERED array (built-in defaults, then agent rules,
     then user config — later wins), matching with a hand-rolled glob→regex:

         pattern.replace(/[.+^${}()|[\]\\]/g,"\\$&").replace(/\*/g,".*")
                .replace(/\?/g,".")   ->   new RegExp("^"+p+"$","s")

     so `*` is an unrestricted `.*` (dotAll) that CROSSES spaces, `/` and `-`.
     `wildcard_match` below is a faithful port, including the special case where
     a pattern ending in `" *"` also matches without the trailing part.

     VALIDATED against the real engine, not just read off the source: the same
     expectations were replayed through `opencode debug agent <a> --tool bash`
     (which performs a genuine permission check) and all 18 deny cases and 3
     allow cases agreed. NOTE `ask` is auto-approved in that non-interactive
     mode and is indistinguishable from `allow` there, which is why the `ask`
     rows are pinned by this model rather than by execution.

  4. The `shell.env` handles. Generated by nix from nix/agent-handles.nix, the
     single source of truth shared with programs/zsh.

  5. The subagent definitions parse as YAML frontmatter + body, and — 🔴 — that
     no agent re-opens the bash wildcard.

Mostly hermetic: pure file reads under the repo. Two tests shell out to
`nix-instantiate --eval` to pin the generated handle VALUES; they FAIL (not
skip) if nix is absent, because a silent skip there is how a wrong path ships.

    run:  python -m pytest scripts/tests/test_opencode_config.py -q
"""

import json
import re
import shutil
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
CLAUDE_DIR = ROOT / "claude"
OC_DIR = ROOT / "scripts" / "opencode"
HOME_NIX = ROOT / "nix" / "home.nix"
HANDLES_NIX = ROOT / "nix" / "agent-handles.nix"
ZSH_NIX = ROOT / "nix" / "programs" / "zsh" / "default.nix"

PRINCIPLES = CLAUDE_DIR / "PRINCIPLES.md"
RULES = CLAUDE_DIR / "RULES.md"
ADDENDUM = CLAUDE_DIR / "opencode-addendum.md"

AGENT_DIR = OC_DIR / "agent"
EXPECTED_AGENTS = {"nav", "k8s", "review"}

# Ceiling for the generated instruction file. The real thing is ~37 KB; a
# 331 KB AGENTS.md puts opencode into a PERMANENT COMPACTION LOOP. 100 KB is a
# deliberately loose bound — it only has to catch growth into that failure mode.
AGENTS_MD_MAX_BYTES = 100 * 1024

# 🔴 yaml is REQUIRED, not optional. It used to be pulled in with
# `pytest.importorskip`, which meant a run without PyYAML reported
# "77 passed, 5 skipped" and exit 0 — a green that had silently stopped checking
# every agent permission block, i.e. exactly the assertions that matter most.
yaml = pytest.importorskip(
    "yaml",
    reason=(
        "PyYAML is REQUIRED for this suite — without it the agent-permission "
        "tests silently vanish and the run still reports success. Install it "
        "(nix-shell -p python312Packages.pyyaml) rather than skipping."
    ),
)


# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #
def generated_agents_md() -> str:
    """Reproduce EXACTLY what nix/home.nix concatenates at switch time.

    Kept in lockstep with home.nix by test_home_nix_generates_agents_md_by
    _concatenation below, which asserts home.nix really does read these three
    files in this order. Without that companion test this helper would be
    asserting against a fiction of its own making.
    """
    return (
        PRINCIPLES.read_text()
        + "\n\n"
        + RULES.read_text()
        + "\n\n"
        + ADDENDUM.read_text()
    )


def strip_jsonc(text: str) -> str:
    """Strip `//` and `/* */` comments, leaving string literals untouched.

    Hand-rolled rather than regex because opencode.jsonc contains `https://`
    inside a string — a naive `//`-to-end-of-line regex would eat the rest of
    the `$schema` line and the file would not parse. Validated by
    test_strip_jsonc_preserves_urls_in_strings below.
    """
    out = []
    i, n = 0, len(text)
    in_str = False
    while i < n:
        c = text[i]
        if in_str:
            out.append(c)
            if c == "\\" and i + 1 < n:
                out.append(text[i + 1])
                i += 2
                continue
            if c == '"':
                in_str = False
            i += 1
            continue
        if c == '"':
            in_str = True
            out.append(c)
            i += 1
            continue
        if c == "/" and i + 1 < n and text[i + 1] == "/":
            while i < n and text[i] != "\n":
                i += 1
            continue
        if c == "/" and i + 1 < n and text[i + 1] == "*":
            i += 2
            while i + 1 < n and not (text[i] == "*" and text[i + 1] == "/"):
                i += 1
            i += 2
            continue
        out.append(c)
        i += 1
    return "".join(out)


def load_config() -> dict:
    """Parse scripts/opencode/opencode.jsonc, PRESERVING key order.

    json.loads yields a dict, and dicts preserve insertion order — which is what
    makes the resolver model below possible at all.
    """
    return json.loads(strip_jsonc((OC_DIR / "opencode.jsonc").read_text()))


def parse_frontmatter(text: str):
    """Return (frontmatter_text, body) for a `---`-delimited markdown file.

    🔴 Anchored on the FIRST TWO `---` lines only. A naive `text.split('---')`
    re-matches horizontal rules and `---` inside the body and reports a false
    parse failure — two extractors were bitten by exactly that.
    """
    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        raise AssertionError("file does not start with a '---' frontmatter fence")
    for idx in range(1, len(lines)):
        if lines[idx].strip() == "---":
            return "\n".join(lines[1:idx]), "\n".join(lines[idx + 1:])
    raise AssertionError("frontmatter fence is never closed")


def frontmatter_top_level_keys(fm: str) -> set:
    """Top-level (column-0) `key:` names in a YAML frontmatter block."""
    return {
        m.group(1)
        for m in (re.match(r"^([A-Za-z_][A-Za-z0-9_-]*):", ln) for ln in fm.split("\n"))
        if m
    }


def agent_permission(name: str) -> dict:
    fm, _ = parse_frontmatter((AGENT_DIR / f"{name}.md").read_text())
    return yaml.safe_load(fm).get("permission") or {}


# --------------------------------------------------------------------------- #
# 🔴 the resolver model
#
# Faithful port of opencode 1.18.4's `Wildcard.match` + the `findLast` resolver.
# See the module docstring for the verbatim source it was ported from and for
# how it was validated against the real engine.
# --------------------------------------------------------------------------- #
_GLOB_ESCAPE = re.compile(r"[.+^${}()|\[\]\\]")


def wildcard_match(text: str, pattern: str) -> bool:
    t = text.replace("\\", "/")
    p = _GLOB_ESCAPE.sub(lambda m: "\\" + m.group(0), pattern.replace("\\", "/"))
    p = p.replace("*", ".*").replace("?", ".")
    # opencode special case: a pattern ending in " *" also matches without it,
    # so `rg *` matches a bare `rg`.
    if p.endswith(" .*"):
        p = p[:-3] + "( .*)?"
    return re.match("^" + p + "$", t, re.S) is not None


def bash_ruleset(agent: str | None = None) -> list:
    """The ORDERED (pattern, action) list opencode resolves a bash command against.

    Order mirrors the real merge: the built-in `permission:"*" pattern:"*"
    allow`, then the global config block, then the agent's own block appended
    LAST — which is precisely why an agent-level `"*": "allow"` would nullify
    every global rule.
    """
    rules = [("*", "allow")]  # built-in catch-all
    rules += list(load_config()["permission"]["bash"].items())
    if agent:
        perm = agent_permission(agent).get("bash")
        if isinstance(perm, str):
            rules.append(("*", perm))
        elif isinstance(perm, dict):
            rules += list(perm.items())
    return rules


def effective_bash_action(command: str, agent: str | None = None) -> str:
    """LAST match wins — the inverse of Claude Code.

    🔴 SCOPE: `command` must be a SINGLE command node. opencode parses the shell
    with tree-sitter and matches each `command` descendant's text separately,
    denying the whole call if ANY node resolves deny (measured: `cd /tmp && git
    status` is checked as just `git status`, since `cd` is in opencode's skip
    set). This model deliberately does NOT reimplement that AST split — doing so
    badly would be worse than not doing it — so do not pass `&&`/`|`/`;` chains
    or command substitutions to it. Chains are SAFER than this model would
    suggest, never less safe: an extra node can only add a deny.
    """
    action = "ask"  # opencode's fallback when nothing matches
    for pattern, act in bash_ruleset(agent):
        if wildcard_match(command, pattern):
            action = act
    return action


def nix_eval(expr: str):
    if not shutil.which("nix-instantiate"):
        pytest.fail(
            "nix-instantiate not on PATH. This test pins the GENERATED handle "
            "values and must not be skipped — a skip here is how a wrong "
            "kubeconfig path ships. Run under `nix develop` / nix-shell."
        )
    p = subprocess.run(
        ["nix-instantiate", "--eval", "--strict", "--json", "-E", expr],
        capture_output=True, text=True, cwd=ROOT, timeout=180,
    )
    assert p.returncode == 0, f"nix eval failed:\n{p.stderr}"
    return json.loads(p.stdout)


def handles() -> dict:
    return nix_eval(f'import {HANDLES_NIX} {{ home = "/home/testuser"; }}')


# --------------------------------------------------------------------------- #
# harness self-validation  (negative controls)
#
# 🔴 A harness that reports green while testing nothing is worse than no test.
# These feed each helper a case it MUST reject, so the greens below mean
# something. They are INVARIANT GUARDS on the harness, not regression coverage
# for any shipped bug.
# --------------------------------------------------------------------------- #
def test_strip_jsonc_preserves_urls_in_strings():
    """`https://` must survive; a real comment must not."""
    src = '{"a": "https://x.example/y", // gone\n "b": 1}'
    assert json.loads(strip_jsonc(src)) == {"a": "https://x.example/y", "b": 1}


def test_strip_jsonc_removes_block_comments():
    assert json.loads(strip_jsonc('{/* c */"a": 1}')) == {"a": 1}


@pytest.mark.parametrize(
    "text,pattern,expected",
    [
        # `*` must cross spaces, `/` and `-` — the whole basis of the F3 fix.
        ("git -C /tmp stash", "*git*stash*", True),
        ("FOO=1 git stash", "*git*stash*", True),
        ("sudo -n git stash", "*git*stash*", True),
        ("git stash", "*git*stash*", True),
        # …and the bare form must NOT, which is the bug being fixed.
        ("git -C /tmp stash", "git stash*", False),
        ("FOO=1 git stash", "git stash*", False),
        ("git status", "*git*stash*", False),
        # the " *" suffix special case
        ("rg", "rg *", True),
        ("rg foo", "rg *", True),
        # anchoring
        ("mkfs.ext4 /dev/sda", "*mkfs*", True),
        ("ls -la", "*mkfs*", False),
    ],
)
def test_wildcard_match_models_the_real_engine(text, pattern, expected):
    """MUTATION CONTROL for the resolver model.

    Every row was replayed through the real engine (`opencode debug agent
    --tool bash`, or the extracted `Wildcard.match` run under node). If this
    port drifts from opencode's semantics, every effective-action assertion
    below becomes a fiction, so it is pinned independently.
    """
    assert wildcard_match(text, pattern) is expected


def test_effective_action_model_is_last_match_wins():
    """Negative control for the resolver: a later broad rule MUST beat an
    earlier narrow one. If this ever reports first-match-wins, every
    effective-action test below is meaningless."""
    rules = [("*", "allow"), ("git stash*", "deny"), ("git *", "allow")]
    action = "ask"
    for pat, act in rules:
        if wildcard_match("git stash", pat):
            action = act
    assert action == "allow", "model is not last-match-wins"


def test_parse_frontmatter_rejects_a_file_without_frontmatter():
    with pytest.raises(AssertionError):
        parse_frontmatter("no frontmatter here\n---\nbody")


def test_parse_frontmatter_is_not_confused_by_body_dashes():
    fm, body = parse_frontmatter("---\nk: v\n---\nintro\n\n---\n\nmore\n")
    assert fm.strip() == "k: v"
    assert "more" in body


# --------------------------------------------------------------------------- #
# 1. the generated AGENTS.md
# --------------------------------------------------------------------------- #
def test_source_files_exist():
    for p in (PRINCIPLES, RULES, ADDENDUM):
        assert p.is_file(), f"missing AGENTS.md source: {p}"


def test_home_nix_generates_agents_md_by_concatenation():
    """home.nix must build the file from all THREE sources, by readFile."""
    nix = HOME_NIX.read_text()
    assert 'home.file.".config/opencode/AGENTS.md".text' in nix, (
        "AGENTS.md must be GENERATED (.text), not symlinked (.source) — a "
        "symlink to CLAUDE.md would deliver only unexpanded @-import lines"
    )
    for src in (
        "builtins.readFile ../claude/PRINCIPLES.md",
        "builtins.readFile ../claude/RULES.md",
        "builtins.readFile ../claude/opencode-addendum.md",
    ):
        assert src in nix, f"home.nix does not concatenate {src}"


@pytest.mark.parametrize(
    "needle",
    [
        "Software Engineering Principles",
        "Evidence > assumptions",
        "KISS / YAGNI / DRY",
        "Verification Honesty",
        "git stash",
        "Never `git add -A`",
        "Never `git reset --hard`",
        "Git Workflow",
        "Deployed ≠ verified",
        "$KC_HOMELAB",
        "$KC_WORKBENCH",
        "$KC_PROD",
        "$HOMELAB",
    ],
)
def test_generated_agents_md_carries_the_rules_text(needle):
    assert needle in generated_agents_md(), (
        f"the generated AGENTS.md does not contain {needle!r} — opencode would "
        f"run without that rule"
    )


def test_generated_agents_md_has_no_unexpanded_imports():
    offenders = [
        (i + 1, ln)
        for i, ln in enumerate(generated_agents_md().split("\n"))
        if re.match(r"^\s*@[\w./-]+\.md\s*$", ln)
    ]
    assert not offenders, (
        "unexpanded @-import lines in the generated AGENTS.md (opencode will "
        f"NOT expand these, so their content is missing): {offenders}"
    )


def test_generated_agents_md_size_is_sane():
    size = len(generated_agents_md().encode("utf-8"))
    assert size > 8 * 1024, (
        f"generated AGENTS.md is only {size} B — far too small to contain "
        f"RULES.md; the concatenation is probably broken"
    )
    assert size < AGENTS_MD_MAX_BYTES, (
        f"generated AGENTS.md is {size} B (> {AGENTS_MD_MAX_BYTES} B). A very "
        f"large AGENTS.md drives opencode into a permanent compaction loop."
    )


# --------------------------------------------------------------------------- #
# 2. 🔴 EFFECTIVE resolved permissions — the load-bearing section
# --------------------------------------------------------------------------- #

# Commands that must NEVER resolve to plain `allow`, in every spelling an agent
# actually uses. The `VAR=…`, `sudo ` and `git -C <path> ` forms are here
# because the house style MANDATES them (k8s.md tells the agent to write
# `KUBECONFIG=$KC_HOMELAB kubectl …`; RULES.md tells it to write
# `git -C <path> …`) — i.e. the habitual spelling was the bypassing one.
MUST_DENY = [
    "git stash",
    "FOO=1 git stash",
    "sudo -n git stash",
    "git -C /tmp stash",
    "git stash push -m x",
    "bash -c \"git stash\"",
    "git reset --hard",
    "FOO=1 git reset --hard",
    "sudo -n git reset --hard",
    "git -C /tmp reset --hard",
    "git add -A",
    "FOO=1 git add -A",
    "git -C /tmp add -A",
    "git add --all",
    "git add .",
    "git clean -fd",
    "rm -rf ~/x",
    "rm -rf /var/x",
    "sudo rm -rf /",
    "rm -rf .",
    "rm -rf $HOME/x",
    "talosctl reset",
    "KUBECONFIG=$KC_HOMELAB talosctl reset",
    "mkfs.ext4 /dev/sda",
]

MUST_ASK = [
    "kubectl delete pod x",
    "KUBECONFIG=$KC_HOMELAB kubectl delete pod x",
    "kubectl apply -f x",
    "KUBECONFIG=$KC_HOMELAB kubectl apply -f x",
    "kubectl get secret x -o yaml",
    "KUBECONFIG=$KC_HOMELAB kubectl get secret x -o yaml",
    "kubectl exec -it x -- sh",
    "kubectl cp a b",
    "kubectl edit deploy x",
    "kubectl rollout undo deploy/x",
    "flux delete source git x",
    "helm uninstall x",
    "sops -d s.enc.yaml",
    "FOO=1 sops -d s.enc.yaml",
    "sops exec-env s.enc.yaml env",
    "age -d -i k f",
    "home-manager switch",
    "nixos-rebuild switch",
    "nix profile remove x",
    "systemctl restart foo",
    "sudo -n systemctl restart foo",
    "chmod -R 777 /x",
    "chown -R me /x",
    "git push --force",
    "git checkout -- foo",
    "git branch -D foo",
    "talosctl upgrade --image x",
    "dd if=/dev/zero of=/dev/sda",
    "sudo something-unlisted",
]

# Read-only, high-frequency. If these start prompting, the operator is trained
# to click through — which is how the prompts that matter stop working.
MUST_ALLOW = [
    "ls -la",
    "kubectl get pods -A",
    "KUBECONFIG=$KC_HOMELAB kubectl get pods -A",
    "KUBECONFIG=$KC_WORKBENCH kubectl -n remix logs deploy/remix --tail=100",
    "git status",
    "git -C /tmp status",
    "git -C /tmp log --oneline -5",
    "git -C /tmp diff",
    "systemctl status foo",
    "rg foo",
    "flux get kustomizations -A",
    "kubectl rollout restart deploy/x",
]

# Every agent that ships, plus the implicit primary. `None` == no agent block.
ALL_AGENTS = [None] + sorted(EXPECTED_AGENTS)


@pytest.mark.parametrize("command", MUST_DENY)
@pytest.mark.parametrize("agent", ALL_AGENTS)
def test_dangerous_commands_resolve_deny_on_every_agent(agent, command):
    """🔴 THE load-bearing assertion.

    Pins the RESOLVED OUTCOME, not the file's keys — so it stays honest under a
    key re-sort or an appended broad allow, both of which beat a key-order test.

    On `nav` and `review` bash is denied wholesale, so these resolve deny for a
    different (also correct) reason; the parametrisation over every agent is
    what catches an agent-level block that re-opens the wildcard.
    """
    got = effective_bash_action(command, agent)
    assert got == "deny", (
        f"agent={agent or '<primary>'}: {command!r} resolves {got!r}, expected "
        f"'deny'. opencode is LAST-MATCH-WINS over a flat array — check that no "
        f"later rule (including an agent-level '*') re-opens it."
    )


@pytest.mark.parametrize("command", MUST_ASK)
def test_high_blast_radius_commands_prompt_on_the_primary_agent(command):
    got = effective_bash_action(command, None)
    assert got == "ask", f"{command!r} resolves {got!r}, expected 'ask'"


@pytest.mark.parametrize("command", MUST_ASK)
@pytest.mark.parametrize("agent", ALL_AGENTS)
def test_high_blast_radius_never_plain_allow_on_any_agent(agent, command):
    got = effective_bash_action(command, agent)
    assert got in ("ask", "deny"), (
        f"agent={agent or '<primary>'}: {command!r} resolves {got!r} — it must "
        f"prompt or be denied, never run silently"
    )


@pytest.mark.parametrize("command", MUST_ALLOW)
def test_read_only_commands_stay_allowed_on_the_primary_agent(command):
    """Prompt fatigue is a security failure, not a UX one."""
    got = effective_bash_action(command, None)
    assert got == "allow", (
        f"{command!r} resolves {got!r} — this is a read-only, high-frequency "
        f"command and must not prompt"
    )


@pytest.mark.parametrize("command", ["kubectl get pods -A", "ls -la", "git -C /tmp log --oneline -3"])
def test_k8s_agent_keeps_read_only_commands_allowed(command):
    """The F1 fix removes k8s's `"*": allow`; this pins that doing so did not
    over-restrict the agent into uselessness."""
    assert effective_bash_action(command, "k8s") == "allow"


def test_no_agent_reopens_the_bash_wildcard_with_allow():
    """🔴 The k8s regression, structurally.

    An agent-level `bash: {"*": allow}` is appended AFTER the entire global
    block, so last-match-wins makes it nullify every global deny at a stroke.
    Measured on 1.18.4: it landed at index 74 after all 30 global rules and left
    only the 4 agent-local rules standing — `git stash`, `git reset --hard`,
    `rm -rf ~…`, `sops -d`, `nixos-rebuild` and `home-manager switch` were all
    plain ALLOW on the k8s agent.

    An agent block may only ever TIGHTEN. The global `"*": allow` already keeps
    bash present in the tool map, so re-stating it buys nothing and costs
    everything.
    """
    offenders = []
    for name in sorted(EXPECTED_AGENTS):
        bash = agent_permission(name).get("bash")
        if isinstance(bash, dict) and bash.get("*") == "allow":
            offenders.append(name)
    assert not offenders, (
        f"agent(s) {offenders} declare `bash: {{'*': allow}}`. That is appended "
        f"AFTER the global block and NULLIFIES every global deny/ask. Drop it — "
        f"the global wildcard already enables bash."
    )


def test_bash_permission_wildcard_is_first():
    """`"*": "allow"` must be the FIRST key of the bash block.

    NOTE this is an INVARIANT GUARD, not regression coverage: it is exactly the
    assertion that passed under both mutations that mattered. It is kept because
    it localises the failure, but the real protection is the effective-action
    tests above.
    """
    bash = load_config()["permission"]["bash"]
    keys = list(bash)
    assert keys[0] == "*", (
        f"first key of the bash permission block is {keys[0]!r}, not '*'."
    )
    assert bash["*"] == "allow"


def test_no_allow_rule_follows_the_wildcard():
    """🔴 The missing assertion that makes a trailing `"git *": "allow"` fail.

    A single broad `allow` appended anywhere after index 0 resurrects every deny
    above it. Nothing but the leading wildcard may be an `allow`.
    """
    bash = load_config()["permission"]["bash"]
    offenders = [k for k, v in list(bash.items())[1:] if v == "allow"]
    assert not offenders, (
        f"`allow` rules after the leading wildcard: {offenders}. opencode is "
        f"LAST-MATCH-WINS, so each of these re-opens every deny/ask above it."
    )


def test_all_asks_precede_all_denies():
    """Deny-last is what makes a narrow deny beat a broad ask.

    `*talosctl reset*: deny` only wins over `*talosctl*: ask` because it comes
    later. Interleaving them, or sorting the block, silently downgrades denies.
    """
    items = list(load_config()["permission"]["bash"].items())[1:]
    last_ask = max((i for i, (_, v) in enumerate(items) if v == "ask"), default=-1)
    first_deny = min((i for i, (_, v) in enumerate(items) if v == "deny"), default=len(items))
    assert first_deny > last_ask, (
        f"a `deny` appears at index {first_deny} before an `ask` at {last_ask}. "
        f"All asks must precede all denies, or a broad ask can override a "
        f"narrow deny."
    )


def test_every_dangerous_pattern_is_prefix_tolerant():
    """🔴 Every deny/ask must be leading-`*`.

    opencode matches a command node's FULL text, so a bare `"git stash*"` misses
    `FOO=1 git stash`, `sudo -n git stash` and `git -C /tmp stash` — measured,
    all three ALLOWED. A handful of anchored patterns are legitimate (a bare
    command name that cannot be meaningfully prefixed); they are listed
    explicitly so adding a new anchored pattern is a deliberate act.
    """
    allowed_anchored = {"*", "sudo*", "dd *"}
    offenders = [
        k for k, v in load_config()["permission"]["bash"].items()
        if v != "allow" and not k.startswith("*") and k not in allowed_anchored
    ]
    assert not offenders, (
        f"bash patterns that are not prefix-tolerant: {offenders}. Prefix each "
        f"with `*` or add it to `allowed_anchored` with a reason."
    )


@pytest.mark.parametrize(
    "command",
    [
        # Every command family the audit called out as unlisted. Asserted by
        # RESOLVED OUTCOME, not by substring-matching the config keys — a key
        # search would pass on a pattern that is present but shadowed.
        "git stash", "git reset --hard", "git add -A", "rm -rf /x",
        "talosctl reset", "kubectl delete pod x", "kubectl apply -f x",
        "kubectl exec -it x -- sh", "kubectl cp a b", "kubectl edit deploy x",
        "kubectl replace -f x", "kubectl rollout undo deploy/x",
        "kubectl get secret x -o yaml", "flux delete source git x",
        "flux suspend kustomization x", "helm uninstall x",
        "sops -d s.enc.yaml", "sops exec-env s.enc.yaml env", "age -d -i k f",
        "sudo whoami", "chmod -R 777 /x", "chown -R me /x",
        "git checkout -- foo", "git restore foo", "git branch -D foo",
        "git push --force", "talosctl upgrade --image x",
        "talosctl apply-config -f x", "talosctl shutdown",
        "dd if=/dev/zero of=/dev/sda", "mkfs.ext4 /dev/sda",
        "nix profile remove x", "systemctl stop foo", "nixos-rebuild switch",
        "home-manager switch", "nix-collect-garbage -d",
    ],
)
def test_dangerous_command_family_is_gated(command):
    """Every family the audit called out resolves to something other than a
    silent `allow`, on the primary agent."""
    got = effective_bash_action(command, None)
    assert got != "allow", f"{command!r} resolves 'allow' — it would run unprompted"


# --------------------------------------------------------------------------- #
# 3. tool-level permissions
# --------------------------------------------------------------------------- #
def test_no_blanket_read_allow():
    """🔴 opencode ships a built-in `.env` guard:
        read: {"*": allow, "*.env": ask, "*.env.*": ask, "*.env.example": allow}
    A blanket `"read": "allow"` here is appended AFTER those (measured: it landed
    at index 30, the guards at 25-27) and silently defeats them on every agent.
    The default already allows everything except `.env`, so there is nothing to
    add — the correct config is to say nothing.
    """
    perm = load_config()["permission"]
    assert "read" not in perm, (
        "`read: allow` defeats opencode's built-in .env guard on every agent. "
        "Remove the key; the default already allows all non-.env reads."
    )


@pytest.mark.parametrize("dead", ["list", "websearch"])
def test_no_nonexistent_tools_in_permission_block(dead):
    """There is no `list` and no `websearch` tool on 1.18.4. The resolved tool
    map is exactly {bash, edit, glob, grep, invalid, question, read, skill,
    task, todowrite, webfetch, write}. Naming a nonexistent tool is a silent
    no-op that reads like configuration."""
    assert dead not in load_config()["permission"], (
        f"{dead!r} is not a tool on opencode 1.18.4 — the key does nothing"
    )


@pytest.mark.parametrize("name", ["title", "summary", "compaction"])
def test_hidden_agents_are_pinned_and_tool_less(name):
    """🔴 Cost AND blast radius.

    Their STOCK tool set is EMPTY (measured against a bare config dir:
    `enabled=[]`). But every entry in the global `permission` block is appended
    to their resolved list too, which re-enabled bash, write, edit, task and
    skill on all three. `compaction` runs automatically on every context
    overflow, so that handed a shell and a writer to the cheap model on a path
    nobody watches, and made every title generation carry the ~3,730-token skill
    catalogue.

    Verified after the fix: all three resolve `enabled=[]` again.
    """
    agents = load_config()["agent"]
    assert name in agents, f"hidden agent {name!r} is not pinned"
    assert "flash" in agents[name]["model"], (
        f"{name!r} is pinned to {agents[name]['model']!r}, not the cheap model"
    )
    assert agents[name].get("permission", {}).get("*") == "deny", (
        f"{name!r} must carry `permission: {{'*': 'deny'}}` — otherwise the "
        f"global permission block re-enables bash/write/skill on it"
    )


def test_plan_agent_is_genuinely_read_only():
    """`task: {general: deny}` is a RESTORATION, not an addition.

    Stock `plan` resolves `task 'general' deny` at index 30 — it may not spawn
    the `general` subagent, which HAS a shell. The global `"task": "allow"`
    landed at index 41, after it, and flipped it to allow: `plan` could reach a
    shell by delegating. Restating it at agent level puts it last again.
    """
    plan = load_config()["agent"]["plan"]["permission"]
    assert plan["edit"] == "deny"
    assert plan["bash"] == "deny"
    assert plan["write"] == "deny"
    assert plan["task"] == {"general": "deny"}, (
        "plan must re-deny the `general` subagent — the global `task: allow` "
        "overrides opencode's built-in deny, giving plan a shell by proxy"
    )


def test_no_deprecated_keys():
    cfg = load_config()
    for dead in ("mode", "layout", "autoshare", "reference", "maxSteps", "theme", "keybinds", "tui"):
        assert dead not in cfg, f"{dead!r} is deprecated on 1.18.4 and must not be set"


def test_core_settings():
    cfg = load_config()
    assert cfg["autoupdate"] is False
    assert cfg["share"] == "disabled"
    assert cfg["snapshot"] is True
    assert cfg["subagent_depth"] == 2
    assert cfg["compaction"] == {"auto": True, "prune": True, "reserved": 16000}
    assert cfg["tool_output"] == {"max_lines": 800, "max_bytes": 24576}
    assert set(cfg["watcher"]["ignore"]) == {
        "node_modules/**", ".git/**", "result/**", ".direnv/**", "**/*.enc.yaml",
    }


# --------------------------------------------------------------------------- #
# 4. the shell.env plugin + the shared handle definitions
# --------------------------------------------------------------------------- #
def test_env_plugin_is_generated_not_a_hardcoded_file():
    """🔴 `scripts/opencode/env.js` used to be a checked-in file with a
    hardcoded `/home/zach/workspace/homelab-talos`, duplicating (and drifted
    from) nix/programs/zsh. It is now GENERATED from nix/agent-handles.nix."""
    assert not (OC_DIR / "env.js").exists(), (
        "scripts/opencode/env.js is back. It hardcoded an absolute home path "
        "and duplicated the zsh handle block; generate it from "
        "nix/agent-handles.nix instead."
    )
    nix = HOME_NIX.read_text()
    assert 'home.file.".config/opencode/plugin/env.js".text' in nix, (
        "env.js must be GENERATED (.text) from agent-handles.nix, not symlinked"
    )
    assert "./agent-handles.nix" in nix
    # The glob is NON-RECURSIVE — a `plugin/` dir symlink would break the moment
    # anything nests, and a `.mjs` would never load at all.
    assert 'home.file.".config/opencode/plugin" =' not in nix
    assert not (OC_DIR / "env.mjs").exists()


def test_env_plugin_generation_registers_a_shell_env_hook():
    nix = HOME_NIX.read_text()
    assert '"shell.env"' in nix, (
        "the generated plugin must register a `shell.env` hook — there is NO "
        "`env` config key in opencode, so this hook is the only way to reach "
        "the bash tool"
    )
    assert "output.env." in nix, "the hook must MUTATE output.env"


def test_env_plugin_existence_guards_every_handle():
    """An unguarded handle pointing at a missing kubeconfig is worse than an
    absent one: the command runs against NO cluster while looking like it
    worked. zsh has always guarded; the old env.js did not."""
    nix = HOME_NIX.read_text()
    for needle in ("statSync", "isDirectory()", "const isDir =", "const isFile =",
                   'entry "isDir"', 'entry "isFile"'):
        assert needle in nix, f"generated env.js lacks {needle!r} — no existence guard"


@pytest.mark.parametrize(
    "group,var,expected",
    [
        ("repos", "HOMELAB", "/home/testuser/workspace/homelab-talos"),
        ("repos", "DEVRC", "/home/testuser/workspace/devrc"),
        ("repos", "DATAPACKET", "/home/testuser/workspace/civit/datapacket-talos"),
        ("repos", "CIVITAI", "/home/testuser/workspace/civit/civitai"),
        ("repos", "CIVITAI_CLI", "/home/testuser/workspace/civit/civitai-cli"),
        ("kubeconfigs", "KC_HOMELAB", "/home/testuser/workspace/homelab-talos/homelab-kubeconfig"),
        ("kubeconfigs", "KC_WORKBENCH", "/home/testuser/workspace/homelab-talos/workbench-kubeconfig"),
        ("kubeconfigs", "KC_PROD", "/home/testuser/workspace/homelab-talos/production-kubeconfig"),
        ("kubeconfigs", "KC_DPPROD", "/home/testuser/workspace/civit/datapacket-talos/prod-kubeconfig"),
        ("kubeconfigs", "KC_NEBULA", "/home/testuser/.kube/homelab-nebula.yaml"),
    ],
)
def test_handles_resolve_to_the_exact_expected_paths(group, var, expected):
    """🔴 FULL literal paths, derived from a NON-real home.

    The previous version asserted only the filename tail, so it passed with
    `HOMELAB` mutated to `/tmp/totally-wrong` and with the KC_HOMELAB /
    KC_WORKBENCH targets SWAPPED. Pinning the whole path against a synthetic
    home (`/home/testuser`) also catches a re-hardcoded `/home/zach`.
    """
    got = handles()[group].get(var)
    assert got == expected, f"{var} resolves to {got!r}, expected {expected!r}"


def test_zsh_and_opencode_share_one_handle_definition():
    """Both consumers must import agent-handles.nix. Two hand-written copies is
    exactly how KC_PROD came to exist for opencode and not for zsh."""
    assert "agent-handles.nix" in ZSH_NIX.read_text(), (
        "programs/zsh must generate its exports from nix/agent-handles.nix"
    )
    assert "agent-handles.nix" in HOME_NIX.read_text(), (
        "home.nix must generate plugin/env.js from nix/agent-handles.nix"
    )
    # And the hand-written export lines must be gone, or they would shadow it.
    zsh = ZSH_NIX.read_text()
    assert "export KC_HOMELAB=$HOME/workspace" not in zsh, (
        "hand-written handle exports survive in zsh alongside the generated "
        "ones — delete them, they are the copy that drifts"
    )


# --------------------------------------------------------------------------- #
# 5. the subagents
# --------------------------------------------------------------------------- #
def test_exactly_the_expected_agents_exist():
    found = {p.stem for p in AGENT_DIR.glob("*.md")}
    assert found == EXPECTED_AGENTS, f"expected {EXPECTED_AGENTS}, found {found}"


@pytest.mark.parametrize("name", sorted(EXPECTED_AGENTS))
def test_agent_frontmatter_is_valid(name):
    text = (AGENT_DIR / f"{name}.md").read_text()
    fm, body = parse_frontmatter(text)
    keys = frontmatter_top_level_keys(fm)

    assert "description" in keys, f"{name}.md frontmatter has no `description`"
    assert "mode" in keys, f"{name}.md frontmatter has no `mode`"

    desc = re.search(r"^description:\s*(.+)$", fm, re.M).group(1).strip()
    assert len(desc) > 20, f"{name}.md description is too short to route on: {desc!r}"

    mode = re.search(r"^mode:\s*(\S+)", fm, re.M).group(1)
    assert mode == "subagent", f"{name}.md mode is {mode!r}, expected 'subagent'"

    assert body.strip(), f"{name}.md has an empty body (no system prompt)"


@pytest.mark.parametrize("name", sorted(EXPECTED_AGENTS))
def test_agent_frontmatter_parses_as_yaml(name):
    fm, _ = parse_frontmatter((AGENT_DIR / f"{name}.md").read_text())
    data = yaml.safe_load(fm)
    assert isinstance(data, dict), f"{name}.md frontmatter is not a YAML mapping"
    assert data.get("mode") == "subagent"
    assert isinstance(data.get("description"), str) and data["description"]


def test_nav_has_no_shell():
    """🔴 `bash: deny` on nav is the DETERMINISTIC fix for ~356 file-navigation
    shell-outs. A prose instruction to "prefer the native tools" is exactly the
    heuristic patch this replaces — if this flips to allow, the fix is gone."""
    perm = agent_permission("nav")
    assert perm["bash"] == "deny", "nav MUST have bash denied"
    assert perm["edit"] == "deny"
    assert perm["write"] == "deny"


def test_nav_is_kept_lean():
    """nav must not carry the skill catalogue or be able to recurse.

    VERIFIED against `opencode debug agent nav` on 1.18.4: with these denies the
    resolved tool set is exactly {glob, grep, read} (+ the internal `invalid`).
    Without `skill: deny` it also carries {skill, task, todowrite, webfetch} —
    and `skill` alone injects the whole catalogue, measured at ~3,730 tokens on
    EVERY request. This is a cost guard, and it is the high-frequency agent.
    """
    perm = agent_permission("nav")
    for tool in ("skill", "task"):
        assert perm.get(tool) == "deny", (
            f"nav must deny {tool!r} — it is the cheap high-frequency navigator "
            f"and `skill` alone costs ~3,730 tokens per request"
        )


def test_no_agent_promises_a_list_tool():
    """There is NO `list` tool on opencode 1.18.4."""
    targets = [AGENT_DIR / f"{n}.md" for n in EXPECTED_AGENTS] + [ADDENDUM]
    bad = []
    for p in targets:
        for i, ln in enumerate(p.read_text().split("\n"), 1):
            if re.search(r"`list`", ln) and "no `list` tool" not in ln:
                bad.append(f"{p.name}:{i}: {ln.strip()}")
    assert not bad, f"reference(s) to a nonexistent `list` tool: {bad}"


def test_review_denies_bash_first_then_allows_read_only_git():
    """review's block is the INVERSE shape of the global one: a `"*": "deny"`
    FIRST, then the read-only git/rg allows after it."""
    bash = agent_permission("review")["bash"]
    keys = list(bash)
    assert keys[0] == "*" and bash["*"] == "deny", (
        f"review's bash block must start with '*': deny, got {keys[0]!r}"
    )
    assert all(bash[k] == "allow" for k in keys[1:]), "only allows may follow the deny-all"


@pytest.mark.parametrize(
    "command",
    [
        "git -C /home/zach/workspace/devrc-opencode diff",
        "git -C /tmp/wt log --oneline -20",
        "git -C /tmp/wt show HEAD",
        "git -C /tmp/wt status",
        "git diff",
        "git status",
        "rg needle",
    ],
)
def test_review_can_actually_read_a_worktree_diff(command):
    """🔴 The silent-failure bug.

    With only the bare `git diff*` spelling, `git -C <path> diff` resolved DENY
    — and in the worktree-first workflow RULES.md mandates, that is the ONLY
    spelling a reviewer uses. The agent then fell back to read/grep and reported
    a review of a diff it had never seen.
    """
    assert effective_bash_action(command, "review") == "allow", (
        f"review cannot run {command!r} — it will silently fall back to "
        f"read/grep and report a review it did not perform"
    )


@pytest.mark.parametrize("command", ["FOO=1 git diff", "sudo git diff", "env git diff"])
def test_review_does_not_accidentally_allow_wrapped_git(command):
    """The allow-list is anchored ON PURPOSE. A leading-`*` allow here would
    punch a hole straight through the global deny block (which is all
    leading-`*`), so the wrapper forms must stay denied.

    NOTE these are all SINGLE command nodes — see the model's scope note.
    """
    assert effective_bash_action(command, "review") == "deny"


def test_k8s_names_the_handles_verbatim():
    text = (AGENT_DIR / "k8s.md").read_text()
    for handle in ("$KC_HOMELAB", "$KC_WORKBENCH", "$KC_PROD", "$HOMELAB"):
        assert handle in text, f"k8s.md does not mention {handle}"
    for phrase in ("trunk", "rollout restart", "Never construct"):
        assert phrase in text, f"k8s.md is missing guidance on {phrase!r}"


def test_k8s_only_tightens():
    """k8s may add rules, never re-open. Its one agent-specific tightening is
    broadening talosctl to `ask`, with the narrow `reset` deny restated AFTER
    it (last-match-wins would otherwise let the broad ask re-open `reset`)."""
    bash = agent_permission("k8s")["bash"]
    assert "*" not in bash, "k8s must not declare a bash wildcard at all"
    assert bash.get("*talosctl*") == "ask"
    assert bash.get("*talosctl reset*") == "deny"
    assert list(bash).index("*talosctl reset*") > list(bash).index("*talosctl*"), (
        "the narrow deny must come AFTER the broad ask, or last-match-wins "
        "re-opens `talosctl reset`"
    )


# --------------------------------------------------------------------------- #
# 6. the pre-existing unmanaged opencode.jsonc
# --------------------------------------------------------------------------- #
def test_switch_cannot_be_blocked_by_the_unmanaged_config():
    nix = HOME_NIX.read_text()
    assert "home.activation.opencodeDropStaleConfig" in nix
    block = nix.split("home.activation.opencodeDropStaleConfig", 1)[1][:800]
    assert 'entryBefore ["checkLinkTargets"]' in block
    assert "! -L" in block
    assert "mv" in block and "rm -f" not in block


# --------------------------------------------------------------------------- #
# 7. browser-agent config-dir isolation AND warming
# --------------------------------------------------------------------------- #
BROWSER_AGENT = ROOT / "scripts" / "browser-bridge" / "browser-agent"


def test_browser_agent_isolates_its_opencode_config_dir():
    src = BROWSER_AGENT.read_text()
    assert "export OPENCODE_CONFIG_DIR=" in src


def test_browser_agent_config_dir_is_stable_not_per_run():
    """🔴 A FRESH config dir per run is NOT acceptable: it makes opencode
    materialise 62 MB of node_modules, and offline it HUNG (killed at 120 s, 0
    bytes, tripping the harness's own tool-set gate)."""
    src = BROWSER_AGENT.read_text()
    line = next(ln for ln in src.split("\n") if ln.startswith("OC_CONFIG_DIR="))
    assert "mktemp" not in line
    assert ".cache" in line


def test_browser_agent_warms_the_config_dir():
    """🔴 Stable is only half of it — an EMPTY-but-existing dir IS the cold-start
    case, and that is what shipped (the dir existed with 0 entries).

    The warm step must also be verified by OUTCOME: `debug paths`, `debug
    config`, `debug skill` and `debug agent` from a plain directory all exit 0
    while installing NOTHING. Only resolving a project's `.opencode/tools/`
    (browser.js imports `@opencode-ai/plugin`) triggers the install.
    """
    src = BROWSER_AGENT.read_text()
    assert "oc_bootstrap" in src and "oc_is_warm" in src
    assert ".opencode/tools" in src, (
        "the warm step must run from a seed project carrying the tools — a bare "
        "`opencode debug` command exits 0 and leaves the dir just as cold"
    )
    assert '[ -d "$OC_CONFIG_DIR/node_modules" ]' in src, (
        "warmth must be verified by node_modules existing, never by exit code"
    )


def test_browser_agent_warm_handles_races_staleness_and_failure():
    src = BROWSER_AGENT.read_text()
    assert "OC_LOCK" in src and "mkdir \"$OC_LOCK\"" in src, (
        "concurrent runs must be serialised by an atomic lock"
    )
    assert "OC_STAMP" in src and "--version" in src, (
        "a version stamp must force a clean re-warm across an opencode upgrade"
    )
    assert "OC_ISOLATED" in src and "WARNING" in src, (
        "failure to warm must degrade to the global config LOUDLY, not silently "
        "hang or die"
    )


def test_browser_agent_isolated_config_keeps_the_global_safety_settings():
    """Isolation silently drops autoupdate/share/tool_output. Each is worth
    re-stating in the isolated dir; the permission block and AGENTS.md are
    deliberately NOT copied (they are the cost this exists to shed)."""
    src = BROWSER_AGENT.read_text()
    for needle in ('"autoupdate": false', '"share": "disabled"', '"tool_output"'):
        assert needle in src, f"isolated opencode.jsonc does not set {needle}"


def test_browser_agent_fails_loud_if_an_instruction_file_appears():
    src = BROWSER_AGENT.read_text()
    assert '"$OC_CONFIG_DIR/AGENTS.md"' in src


def test_readme_documents_the_one_time_command():
    readme = (OC_DIR / "README.md").read_text()
    assert "opencode.jsonc" in readme
    assert "mv ~/.config/opencode/opencode.jsonc" in readme
