r"""Tests for the home-manager-managed opencode configuration.

WHAT IS UNDER TEST (see scripts/opencode/README.md for the measurements):

  1. The GENERATED ~/.config/opencode/AGENTS.md. `nix/home.nix` builds it by
     CONCATENATING claude/PRINCIPLES.md + claude/RULES.md +
     claude/opencode-addendum.md at switch time. It has to be a concatenation
     because opencode does NOT expand `@`-imports in AGENTS.md/CLAUDE.md
     (measured on v1.18.4 with an all-tools-denied agent, so no file read was
     possible: an imported passphrase returned NONE, the same content inline
     returned verbatim). ~/.claude/CLAUDE.md is ~1.5 KB of `@PRINCIPLES.md` +
     `@RULES.md` import lines, so if opencode read THAT it would receive none of
     the 32 KB of actual rules. These tests are the regression guard for that
     whole point: they assert the rules TEXT is present, not merely that a file
     exists.

  2. 🔴 The EFFECTIVE RESOLVED PERMISSION for a set of dangerous commands, on
     EVERY agent. This is the section that matters, and it is deliberately NOT
     a restatement of the file's keys.

     A previous version of this file asserted only key ORDER, and was vacuous
     against the two mutations that actually break the config:
       * appending a trailing `"git *": "allow"` (resurrects every git deny)
         — 82 passed;
       * sorting the bash keys alphabetically — 82 passed, because `"*"` (0x2A)
         sorts to the front, so the "wildcard is first" assertion still held
         while a broad `ask` overtook the narrow `deny` it was meant to lose to.
     Both are pinned by `effective_bash_action` below, which REIMPLEMENTS
     opencode's resolver and asserts the outcome.

  2b. 🔴 PER-RULE COVERAGE — a claim about the RULES, not about commands.
     Everything in (2) asserts that a COMMAND resolves correctly. None of it
     asserts that a RULE is doing any work, and the two come apart: MEASURED at
     f76b3d7 by deleting each of opencode.jsonc's 77 single-line verdict rows
     one at a time and re-running this file, **39 of 77 deletions left the suite
     fully green** — 17 of them real holes where a realistic command dropped to
     plain `allow` at BOTH layers (`*git*commit*`, `*kubectl*drain*`,
     `*helm*upgrade*`, all four mutating `systemctl` verbs, the anchored
     `sudo*`, `*rm*-r*`, …). The aggregate `len(asks) >= 40` floor could not see
     it: deleting exactly ten ask rules left exactly 40 and reported
     480 passed, 0 failed while ten dangerous families ran unprompted.
     `test_every_ask_rule_is_individually_pinned` and its deny twin turn that
     manual sweep into a standing assertion — after them, 10 of 77 survive, and
     all ten are non-bash tool rows.

  3. The resolver model itself. opencode 1.18.4 resolves a permission by
     `findLast` over a FLAT ORDERED array (built-in defaults, then agent rules,
     then user config — later wins), matching with a hand-rolled glob→regex:

         pattern.replace(/[.+^${}()|[\]\\]/g,"\\$&").replace(/\*/g,".*")
                .replace(/\?/g,".")   ->   new RegExp("^"+p+"$","s")

     so `*` is an unrestricted `.*` (dotAll) that CROSSES spaces, `/` and `-`.
     `wildcard_match` below is a faithful port, including the special case where
     a pattern ending in `" *"` also matches without the trailing part.

     VALIDATED against the real engine, not just read off the source: the same
     expectations were replayed through `opencode debug agent <a> --tool bash`
     (which performs a genuine permission check) and all 18 deny cases and 3
     allow cases agreed. NOTE `ask` is auto-approved in that non-interactive
     mode and is indistinguishable from `allow` there, which is why the `ask`
     rows are pinned by this model rather than by execution.

  4. The `shell.env` handles. Generated by nix from nix/agent-handles.nix, the
     single source of truth shared with programs/zsh.

  5. The subagent definitions parse as YAML frontmatter + body, and — 🔴 — that
     no agent re-opens the bash wildcard.

Mostly hermetic: pure file reads under the repo. Two tests shell out to
`nix-instantiate --eval` to pin the generated handle VALUES; they FAIL (not
skip) if nix is absent, because a silent skip there is how a wrong path ships.

    run:  python -m pytest scripts/tests/test_opencode_config.py -q
"""

import functools
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
CLAUDE_DIR = ROOT / "claude"
OC_DIR = ROOT / "scripts" / "opencode"
HOME_NIX = ROOT / "nix" / "home.nix"
HANDLES_NIX = ROOT / "nix" / "agent-handles.nix"
ZSH_NIX = ROOT / "nix" / "programs" / "zsh" / "default.nix"

PRINCIPLES = CLAUDE_DIR / "PRINCIPLES.md"
RULES = CLAUDE_DIR / "RULES.md"
ADDENDUM = CLAUDE_DIR / "opencode-addendum.md"

AGENT_DIR = OC_DIR / "agent"
EXPECTED_AGENTS = {"nav", "k8s", "review"}

# Ceiling for the generated instruction file. The real thing is ~37 KB; a
# 331 KB AGENTS.md puts opencode into a PERMANENT COMPACTION LOOP. 100 KB is a
# deliberately loose bound — it only has to catch growth into that failure mode.
AGENTS_MD_MAX_BYTES = 100 * 1024

# 🔴 yaml is REQUIRED, not optional — a HARD import, on purpose.
#
# It was previously pulled in with `pytest.importorskip`, under a comment
# claiming that had already been replaced. It had not. MEASURED: without PyYAML
# the run reported "486 passed, 1 skipped", exit 0 — while 384 assertions across
# every agent-permission test had silently vanished. That is the worst kind of
# green: a comment certifying a hazard that is open is worse than no comment,
# because it is what stops the next reader from checking.
#
# A hard import makes a missing PyYAML a COLLECTION ERROR (loud, exit non-zero)
# instead of a skip. Install it: nix-shell -p python312Packages.pyyaml.
import yaml  # noqa: E402


# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #
def generated_agents_md() -> str:
    """Reproduce EXACTLY what nix/home.nix concatenates at switch time.

    Kept in lockstep with home.nix by test_home_nix_generates_agents_md_by
    _concatenation below, which asserts home.nix really does read these three
    files in this order. Without that companion test this helper would be
    asserting against a fiction of its own making.
    """
    return (
        PRINCIPLES.read_text()
        + "\n\n"
        + RULES.read_text()
        + "\n\n"
        + ADDENDUM.read_text()
    )


def strip_jsonc(text: str) -> str:
    """Strip `//` and `/* */` comments, leaving string literals untouched.

    Hand-rolled rather than regex because opencode.jsonc contains `https://`
    inside a string — a naive `//`-to-end-of-line regex would eat the rest of
    the `$schema` line and the file would not parse. Validated by
    test_strip_jsonc_preserves_urls_in_strings below.
    """
    out = []
    i, n = 0, len(text)
    in_str = False
    while i < n:
        c = text[i]
        if in_str:
            out.append(c)
            if c == "\\" and i + 1 < n:
                out.append(text[i + 1])
                i += 2
                continue
            if c == '"':
                in_str = False
            i += 1
            continue
        if c == '"':
            in_str = True
            out.append(c)
            i += 1
            continue
        if c == "/" and i + 1 < n and text[i + 1] == "/":
            while i < n and text[i] != "\n":
                i += 1
            continue
        if c == "/" and i + 1 < n and text[i + 1] == "*":
            i += 2
            while i + 1 < n and not (text[i] == "*" and text[i + 1] == "/"):
                i += 1
            i += 2
            continue
        out.append(c)
        i += 1
    return "".join(out)


def load_config() -> dict:
    """Parse scripts/opencode/opencode.jsonc, PRESERVING key order.

    json.loads yields a dict, and dicts preserve insertion order — which is what
    makes the resolver model below possible at all.
    """
    return json.loads(strip_jsonc((OC_DIR / "opencode.jsonc").read_text()))


def parse_frontmatter(text: str):
    """Return (frontmatter_text, body) for a `---`-delimited markdown file.

    🔴 Anchored on the FIRST TWO `---` lines only. A naive `text.split('---')`
    re-matches horizontal rules and `---` inside the body and reports a false
    parse failure — two extractors were bitten by exactly that.
    """
    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        raise AssertionError("file does not start with a '---' frontmatter fence")
    for idx in range(1, len(lines)):
        if lines[idx].strip() == "---":
            return "\n".join(lines[1:idx]), "\n".join(lines[idx + 1:])
    raise AssertionError("frontmatter fence is never closed")


def frontmatter_top_level_keys(fm: str) -> set:
    """Top-level (column-0) `key:` names in a YAML frontmatter block."""
    return {
        m.group(1)
        for m in (re.match(r"^([A-Za-z_][A-Za-z0-9_-]*):", ln) for ln in fm.split("\n"))
        if m
    }


def agent_permission(name: str) -> dict:
    fm, _ = parse_frontmatter((AGENT_DIR / f"{name}.md").read_text())
    return yaml.safe_load(fm).get("permission") or {}


# --------------------------------------------------------------------------- #
# 🔴 the resolver model
#
# Faithful port of opencode 1.18.4's `Wildcard.match` + the `findLast` resolver.
# See the module docstring for the verbatim source it was ported from and for
# how it was validated against the real engine.
# --------------------------------------------------------------------------- #
_GLOB_ESCAPE = re.compile(r"[.+^${}()|\[\]\\]")


def wildcard_match(text: str, pattern: str) -> bool:
    t = text.replace("\\", "/")
    p = _GLOB_ESCAPE.sub(lambda m: "\\" + m.group(0), pattern.replace("\\", "/"))
    p = p.replace("*", ".*").replace("?", ".")
    # opencode special case: a pattern ending in " *" also matches without it,
    # so `rg *` matches a bare `rg`.
    if p.endswith(" .*"):
        p = p[:-3] + "( .*)?"
    return re.match("^" + p + "$", t, re.S) is not None


@functools.lru_cache(maxsize=None)
def bash_ruleset(agent: str | None = None) -> tuple:
    """The ORDERED (pattern, action) list opencode resolves a bash command against.

    Order mirrors the real merge: the built-in `permission:"*" pattern:"*"
    allow`, then the global config block, then the agent's own block appended
    LAST — which is precisely why an agent-level `"*": "allow"` would nullify
    every global rule.

    Cached, and a TUPLE rather than a list, for one reason each:
      * cached because the per-rule ledger resolves ~63 rules x ~90 commands,
        and re-reading + hand-parsing the 13 KB JSONC each time took this file
        from 1.7 s to 18.5 s — a real cost on a gate that runs in CI;
      * a tuple because a cached MUTABLE result is poisonable, and this repo has
        a caller that mutates a parsed config in place (test_opencode_engine.py's
        `add_trailing_git_allow`). `load_config()` is deliberately left UNCACHED
        for exactly that caller.
    """
    rules = [("*", "allow")]  # built-in catch-all
    rules += list(load_config()["permission"]["bash"].items())
    if agent:
        perm = agent_permission(agent).get("bash")
        if isinstance(perm, str):
            rules.append(("*", perm))
        elif isinstance(perm, dict):
            rules += list(perm.items())
    return tuple(rules)


def effective_bash_action(command: str, agent: str | None = None) -> str:
    """LAST match wins — the inverse of Claude Code.

    🔴 SCOPE: `command` must be a SINGLE command node. opencode parses the shell
    with tree-sitter and matches each `command` descendant's text separately,
    denying the whole call if ANY node resolves deny (measured: `cd /tmp && git
    status` is checked as just `git status`, since `cd` is in opencode's skip
    set). This model deliberately does NOT reimplement that AST split — doing so
    badly would be worse than not doing it — so do not pass `&&`/`|`/`;` chains
    or command substitutions to it. Chains are SAFER than this model would
    suggest, never less safe: an extra node can only add a deny.
    """
    action = "ask"  # opencode's fallback when nothing matches
    for pattern, act in bash_ruleset(agent):
        if wildcard_match(command, pattern):
            action = act
    return action


def effective_bash_action_without(drop: str, command: str, agent: str | None = None) -> str:
    """`effective_bash_action`, with rule `drop` DELETED from the config block.

    🔴 This is the deletion mutant, run in-process. The suite's whole
    coverage-of-the-permission-block story is "if this rule vanished, some
    pinned command would change verdict" — a claim that can only be checked by
    actually removing the rule, never by looking at the file. The rules below
    that use it turn a manual mutation sweep into a standing assertion.

    The leading built-in `("*", "allow")` is never dropped: it is not a config
    rule, and removing it would change every verdict at once.
    """
    action = "ask"
    for i, (pattern, act) in enumerate(bash_ruleset(agent)):
        if i and pattern == drop:
            continue
        if wildcard_match(command, pattern):
            action = act
    return action


def nix_eval(expr: str):
    if not shutil.which("nix-instantiate"):
        pytest.fail(
            "nix-instantiate not on PATH. This test pins the GENERATED handle "
            "values and must not be skipped — a skip here is how a wrong "
            "kubeconfig path ships. Run under `nix develop` / nix-shell."
        )
    p = subprocess.run(
        ["nix-instantiate", "--eval", "--strict", "--json", "-E", expr],
        capture_output=True, text=True, cwd=ROOT, timeout=180,
    )
    assert p.returncode == 0, f"nix eval failed:\n{p.stderr}"
    return json.loads(p.stdout)


def handles() -> dict:
    return nix_eval(f'import {HANDLES_NIX} {{ home = "/home/testuser"; }}')


# --------------------------------------------------------------------------- #
# harness self-validation  (negative controls)
#
# 🔴 A harness that reports green while testing nothing is worse than no test.
# These feed each helper a case it MUST reject, so the greens below mean
# something. They are INVARIANT GUARDS on the harness, not regression coverage
# for any shipped bug.
# --------------------------------------------------------------------------- #
def test_strip_jsonc_preserves_urls_in_strings():
    """`https://` must survive; a real comment must not."""
    src = '{"a": "https://x.example/y", // gone\n "b": 1}'
    assert json.loads(strip_jsonc(src)) == {"a": "https://x.example/y", "b": 1}


def test_strip_jsonc_removes_block_comments():
    assert json.loads(strip_jsonc('{/* c */"a": 1}')) == {"a": 1}


@pytest.mark.parametrize(
    "text,pattern,expected",
    [
        # `*` must cross spaces, `/` and `-` — the whole basis of the F3 fix.
        ("git -C /tmp stash", "*git*stash*", True),
        ("FOO=1 git stash", "*git*stash*", True),
        ("sudo -n git stash", "*git*stash*", True),
        ("git stash", "*git*stash*", True),
        # …and the bare form must NOT, which is the bug being fixed.
        ("git -C /tmp stash", "git stash*", False),
        ("FOO=1 git stash", "git stash*", False),
        ("git status", "*git*stash*", False),
        # the " *" suffix special case
        ("rg", "rg *", True),
        ("rg foo", "rg *", True),
        # anchoring
        ("mkfs.ext4 /dev/sda", "*mkfs*", True),
        ("ls -la", "*mkfs*", False),
    ],
)
def test_wildcard_match_models_the_real_engine(text, pattern, expected):
    """MUTATION CONTROL for the resolver model.

    Every row was replayed through the real engine (`opencode debug agent
    --tool bash`, or the extracted `Wildcard.match` run under node). If this
    port drifts from opencode's semantics, every effective-action assertion
    below becomes a fiction, so it is pinned independently.
    """
    assert wildcard_match(text, pattern) is expected


def test_effective_action_model_is_last_match_wins():
    """Negative control for the resolver: a later broad rule MUST beat an
    earlier narrow one. If this ever reports first-match-wins, every
    effective-action test below is meaningless."""
    rules = [("*", "allow"), ("git stash*", "deny"), ("git *", "allow")]
    action = "ask"
    for pat, act in rules:
        if wildcard_match("git stash", pat):
            action = act
    assert action == "allow", "model is not last-match-wins"


def test_parse_frontmatter_rejects_a_file_without_frontmatter():
    with pytest.raises(AssertionError):
        parse_frontmatter("no frontmatter here\n---\nbody")


def test_parse_frontmatter_is_not_confused_by_body_dashes():
    fm, body = parse_frontmatter("---\nk: v\n---\nintro\n\n---\n\nmore\n")
    assert fm.strip() == "k: v"
    assert "more" in body


# --------------------------------------------------------------------------- #
# 1. the generated AGENTS.md
# --------------------------------------------------------------------------- #
def test_source_files_exist():
    for p in (PRINCIPLES, RULES, ADDENDUM):
        assert p.is_file(), f"missing AGENTS.md source: {p}"


def test_home_nix_generates_agents_md_by_concatenation():
    """home.nix must build the file from all THREE sources, by readFile."""
    nix = HOME_NIX.read_text()
    assert 'home.file.".config/opencode/AGENTS.md".text' in nix, (
        "AGENTS.md must be GENERATED (.text), not symlinked (.source) — a "
        "symlink to CLAUDE.md would deliver only unexpanded @-import lines"
    )
    for src in (
        "builtins.readFile ../claude/PRINCIPLES.md",
        "builtins.readFile ../claude/RULES.md",
        "builtins.readFile ../claude/opencode-addendum.md",
    ):
        assert src in nix, f"home.nix does not concatenate {src}"


@pytest.mark.parametrize(
    "needle",
    [
        "Software Engineering Principles",
        "Evidence > assumptions",
        "KISS / YAGNI / DRY",
        "Verification Honesty",
        "git stash",
        "Never `git add -A`",
        "Never `git reset --hard`",
        "Git Workflow",
        "Deployed ≠ verified",
        "$KC_HOMELAB",
        "$KC_WORKBENCH",
        "$KC_PROD",
        "$HOMELAB",
    ],
)
def test_generated_agents_md_carries_the_rules_text(needle):
    assert needle in generated_agents_md(), (
        f"the generated AGENTS.md does not contain {needle!r} — opencode would "
        f"run without that rule"
    )


def test_generated_agents_md_has_no_unexpanded_imports():
    offenders = [
        (i + 1, ln)
        for i, ln in enumerate(generated_agents_md().split("\n"))
        if re.match(r"^\s*@[\w./-]+\.md\s*$", ln)
    ]
    assert not offenders, (
        "unexpanded @-import lines in the generated AGENTS.md (opencode will "
        f"NOT expand these, so their content is missing): {offenders}"
    )


def test_generated_agents_md_size_is_sane():
    size = len(generated_agents_md().encode("utf-8"))
    assert size > 8 * 1024, (
        f"generated AGENTS.md is only {size} B — far too small to contain "
        f"RULES.md; the concatenation is probably broken"
    )
    assert size < AGENTS_MD_MAX_BYTES, (
        f"generated AGENTS.md is {size} B (> {AGENTS_MD_MAX_BYTES} B). A very "
        f"large AGENTS.md drives opencode into a permanent compaction loop."
    )


# --------------------------------------------------------------------------- #
# 2. 🔴 EFFECTIVE resolved permissions — the load-bearing section
#
# 🔴 TWO LAYERS. `effective_bash_action` models LAYER 1 ONLY (the globs). Since
# c1e4c02 there is a LAYER 2 — ~/.config/opencode/plugin/guard.js, which runs
# guard_core.py's "opencode" policy on every bash call and THROWS on a deny. The
# glob layer is friction; the guard is the control.
#
# So the assertions below come in two shapes, and mixing them up is how a test
# starts asserting a fiction:
#   * `layered_verdict()` — what actually happens to the agent. Use this for
#     "must not run".
#   * `effective_bash_action()` — the globs alone. Use this ONLY for claims
#     about the config file's own structure (ordering, prefix tolerance,
#     no-allow-after-wildcard), and for `ask`, which the guard cannot express.
# --------------------------------------------------------------------------- #
sys.path.insert(0, str(ROOT / "scripts" / "claude-hooks"))
import guard_core  # noqa: E402


def guard_verdict(command: str) -> str:
    """LAYER 2: what guard_core's opencode policy does with this command."""
    return "deny" if guard_core.evaluate(command, "opencode") else "allow"


def layered_verdict(command: str, agent: str | None = None) -> str:
    """What actually reaches the shell. The guard runs from
    `tool.execute.before`, so its deny is final regardless of the glob outcome.
    """
    if guard_verdict(command) == "deny":
        return "deny"
    return effective_bash_action(command, agent)

# Commands that must NEVER resolve to plain `allow`, in every spelling an agent
# actually uses. The `VAR=…`, `sudo ` and `git -C <path> ` forms are here
# because the house style MANDATES them (k8s.md tells the agent to write
# `KUBECONFIG=$KC_HOMELAB kubectl …`; RULES.md tells it to write
# `git -C <path> …`) — i.e. the habitual spelling was the bypassing one.
MUST_DENY = [
    "git stash",
    "FOO=1 git stash",
    "sudo -n git stash",
    "git -C /tmp stash",
    "git stash push -m x",
    "bash -c \"git stash\"",
    "git reset --hard",
    "FOO=1 git reset --hard",
    "sudo -n git reset --hard",
    "git -C /tmp reset --hard",
    "git add -A",
    "FOO=1 git add -A",
    "git -C /tmp add -A",
    "git add --all",
    "git add .",
    "git clean -fd",
    "rm -rf ~/x",
    "rm -rf /var/x",
    "sudo rm -rf /",
    "rm -rf .",
    "rm -rf $HOME/x",
    "talosctl reset",
    "KUBECONFIG=$KC_HOMELAB talosctl reset",
    "mkfs.ext4 /dev/sda",
]

MUST_ASK = [
    "kubectl delete pod x",
    "KUBECONFIG=$KC_HOMELAB kubectl delete pod x",
    "kubectl apply -f x",
    "KUBECONFIG=$KC_HOMELAB kubectl apply -f x",
    "kubectl get secret x -o yaml",
    "KUBECONFIG=$KC_HOMELAB kubectl get secret x -o yaml",
    "kubectl exec -it x -- sh",
    "kubectl cp a b",
    "kubectl edit deploy x",
    "kubectl rollout undo deploy/x",
    "flux delete source git x",
    "helm uninstall x",
    "sops -d s.enc.yaml",
    "FOO=1 sops -d s.enc.yaml",
    "sops exec-env s.enc.yaml env",
    "age -d -i k f",
    "home-manager switch",
    "nixos-rebuild switch",
    "nix profile remove x",
    "systemctl restart foo",
    "sudo -n systemctl restart foo",
    "chmod -R 777 /x",
    "chown -R me /x",
    "git push --force",
    "git checkout -- foo",
    "git branch -D foo",
    "talosctl upgrade --image x",
    "dd if=/dev/zero of=/dev/sda",
    "sudo something-unlisted",
    # 🔴 FOUND BY MUTATION TESTING, not by review. Deleting `"*sudo *": "ask"`
    # left the suite 465-GREEN, because the only sudo row above starts with
    # `sudo` and is caught redundantly by the ANCHORED `"sudo*"`. The infix rule
    # is load-bearing for exactly one shape — sudo in NON-LEADING position — and
    # nothing exercised it. `doas` was worse: it has no anchored counterpart, so
    # `"*doas *"` was its only gate and had no test case at all.
    # MEASURED on the restored config: each row below matches `*sudo *`/`*doas *`
    # and NOTHING else (bar the two catch-alls), so each one kills a distinct
    # deletion mutant. The `VAR=…` prefix is the house style, which is precisely
    # why this shape is the one that must not be allow.
    "FOO=1 sudo something-unlisted",
    "doas something-unlisted",
    "FOO=1 doas something-unlisted",

    # 🔴 THE SAME FINDING AS A CLASS, not as two more instances.
    #
    # The `*sudo *`/`*doas *` rows above closed TWO deletion mutants. An
    # exhaustive re-sweep of all 77 single-line verdict rows (delete one, run
    # this file, attribute by failing test id) then measured **39 survivors**,
    # of which **17** are real holes: a realistic command in that family drops
    # to plain `allow` at BOTH layers with the rule gone. Every row below is one
    # of those 17, chosen so that the rule named in its comment is its SOLE
    # DECIDER — `test_every_ask_rule_is_individually_pinned` re-measures that
    # claim rather than trusting this comment, so a row that stops being
    # load-bearing fails loudly instead of rotting into decoration.
    #
    # House spellings are deliberate: RULES.md mandates `git -C <path> …` and
    # k8s.md mandates `KUBECONFIG=$KC_… kubectl -n ns …`, i.e. the habitual
    # spelling is the prefixed one.
    "git -C /repo commit -m x",                                  # *git*commit*
    "git -C /repo rebase origin/main",                           # *git*rebase*
    "git -C /repo worktree remove ../wt",                        # *git*worktree remove*
    "gh pr merge 12 --squash",                                   # *gh*pr merge*
    "KUBECONFIG=$KC_HOMELAB kubectl -n ns patch deploy x --type=merge",  # *kubectl*patch*
    "KUBECONFIG=$KC_HOMELAB kubectl -n ns scale deploy x --replicas=0",  # *kubectl*scale*
    "KUBECONFIG=$KC_HOMELAB kubectl drain node1 --ignore-daemonsets",    # *kubectl*drain*
    "helm upgrade --install app ./chart -n ns",                  # *helm*upgrade*
    "helm rollback app 1 -n ns",                                 # *helm*rollback*
    "flux resume kustomization apps",                            # *flux*resume*
    # The four MUTATING systemctl verbs. `*systemctl*restart*` is redundant —
    # `*systemctl*start*` already matches "re-START" — which is exactly why the
    # one row that existed ("systemctl restart foo") pinned neither of them.
    "systemctl --user start browser-bridge",                     # *systemctl*start*
    "systemctl --user enable bar-status-poll.timer",             # *systemctl*enable*
    "systemctl --user disable bar-status-poll.timer",            # *systemctl*disable*
    "systemctl --user daemon-reload",                            # *systemctl*daemon-reload*
    # 🔴 THE MIRROR of the `*sudo *` finding above, and MISSED by the audit that
    # found that one: the ANCHORED `sudo*` is the only rule covering a `sudo`
    # that is not followed by a space. `*sudo *` needs the literal "sudo ", so
    # `sudoedit` walks straight past it.
    "sudoedit /etc/nixos/configuration.nix",                     # sudo*
    # `rm -r` / `rm --recursive` on an ORDINARY path. guard_core's
    # check_rm_rf_critical deliberately does NOT fire here (its fatal-target set
    # is `/`, `~`/`$HOME`, `.`/`..` and the top-level system dirs only — see
    # test_guard_core_catches_recursive_rm_without_the_force_flag below), so
    # this glob is the ONLY thing between an agent and a silent recursive
    # delete of a project directory.
    "rm -r /repo/build",                                         # *rm*-r*
    "rm --recursive /repo/node_modules",                         # *rm*-r*
    # A leading `dd` with neither an `if=` nor an `of=` operand — the one shape
    # the operand-scoped `*dd if=*`/`*dd of=*` rules structurally cannot see.
    # Stated honestly: this spelling is the least dangerous of the dd family
    # (no `of=` means no output file), and the destructive spellings are held by
    # `*dd if=*`/`*dd of=*` AND by guard_core. It is pinned because `dd *` is
    # load-bearing for SOMETHING, and an unpinned rule is how this class returns.
    "dd conv=notrunc",                                           # dd *
]

# 🔴 ASK rules that are DELIBERATELY redundant: deleting one changes no verdict,
# because another rule already covers the family. Being on this list is a claim
# — "some other rule has this" — and `test_every_ask_rule_is_individually_pinned`
# VERIFIES it both ways: an entry here that turns out to be load-bearing fails,
# and so does a rule that is load-bearing but absent from MUST_ASK and from here.
# So a future edit that removes the COVERING rule cannot leave this list quietly
# wrong.
REDUNDANTLY_COVERED_ASKS = {
    "*sops*--decrypt*": "`*sops*-d*` already matches `--d`ecrypt",
    "*age*--decrypt*": "`*age*-d*` already matches `--d`ecrypt",
    "*systemctl*restart*": "`*systemctl*start*` already matches re-`start`",
    # Kept for documentation value: an operator reading the block should see the
    # family named, not have to notice it is caught by accident.
    "*nix-collect-garbage*": (
        "caught ACCIDENTALLY by `*age*-d*`: 'nix-collect-gar(bage) … -d'. That "
        "is a coincidence of spelling, not a design — do not delete `*age*-d*` "
        "on the reasoning that garbage collection is covered."
    ),
    "*dd if=*": "guard_core denies a dd whose operands name a device; `dd *` holds the leading form",
    "*dd of=*": "guard_core denies a dd whose operands name a device; `dd *` holds the leading form",
}

# 🔴 DENY rules the GUARD layer backstops by design. The config header says the
# deny block is "a short, deliberately NON-EXHAUSTIVE mirror of the guard's
# families in their naive spellings" — so a deny glob whose deletion changes no
# LAYERED verdict is working as intended, not untested. Being on this list is
# again a verified claim: `test_every_deny_rule_is_individually_pinned` asserts
# the command still resolves deny with the glob removed, i.e. that the guard
# really is holding it.
# 🔴 The deny rules the GLOB layer itself enforces (i.e. not merely mirrors of a
# guard check), each with a command it decides. Declared rather than derived,
# because a derived list is read OFF the current verdicts — and a rule silently
# downgraded `deny`->`ask` simply drops out of the set being checked, which is
# exactly how that mutant survived every other assertion here.
GLOB_ENFORCED_DENIES = {
    "*git*add -A*": "git add -A",
    "*git*stash*": "git stash",
    "*git*reset --hard*": "git reset --hard",
    "*rm -rf /*": "rm -rf /var/x",
    "*rm -rf ~*": "rm -rf ~/x",
    "*rm -rf $HOME*": "rm -rf $HOME/x",
    "*mkfs*": "mkfs.ext4 /dev/sda",
}

GUARD_BACKSTOPPED_DENIES = {
    "*git*add --all*": "git -C /repo add --all",
    "*git*add .": "git add .",
    "*git*clean -f*": "git -C /repo clean -fd",
    "*talosctl*reset*": "talosctl -n 10.0.0.1 reset",
    "*mke2fs*": "mke2fs /dev/sdc",
    "*mkswap*": "mkswap /dev/sdd",
}

# Read-only, high-frequency. If these start prompting, the operator is trained
# to click through — which is how the prompts that matter stop working.
MUST_ALLOW = [
    "ls -la",
    "kubectl get pods -A",
    "KUBECONFIG=$KC_HOMELAB kubectl get pods -A",
    "KUBECONFIG=$KC_WORKBENCH kubectl -n remix logs deploy/remix --tail=100",
    "git status",
    "git -C /tmp status",
    "git -C /tmp log --oneline -5",
    "git -C /tmp diff",
    "systemctl status foo",
    "rg foo",
    "flux get kustomizations -A",
    "kubectl rollout restart deploy/x",
]

# Every agent that ships, plus the implicit primary. `None` == no agent block.
ALL_AGENTS = [None] + sorted(EXPECTED_AGENTS)


@pytest.mark.parametrize("command", MUST_DENY)
@pytest.mark.parametrize("agent", ALL_AGENTS)
def test_dangerous_commands_resolve_deny_on_every_agent(agent, command):
    """🔴 THE load-bearing assertion.

    Pins the RESOLVED OUTCOME, not the file's keys — so it stays honest under a
    key re-sort or an appended broad allow, both of which beat a key-order test.

    On `nav` and `review` bash is denied wholesale, so these resolve deny for a
    different (also correct) reason; the parametrisation over every agent is
    what catches an agent-level block that re-opens the wildcard.
    """
    got = layered_verdict(command, agent)
    assert got == "deny", (
        f"agent={agent or '<primary>'}: {command!r} resolves {got!r}, expected "
        f"'deny'. Two layers can produce this: opencode is LAST-MATCH-WINS over a "
        f"flat array (check no later rule, including an agent-level '*', re-opens "
        f"it), and guard_core.py's 'opencode' policy runs from "
        f"`tool.execute.before`. glob-only={effective_bash_action(command, agent)!r}, "
        f"guard={guard_verdict(command)!r}."
    )


# --------------------------------------------------------------------------- #
# 🔴 THE SPELLINGS THE GLOBS COULD NOT EXPRESS
#
# Every row below RESOLVED ALLOW on the primary agent at c1e4c02 — measured by
# replaying that ref's config through this same resolver model. They are the
# reason the guard exists, and they are asserted twice: once for the outcome
# (must not run) and once for WHICH LAYER catches it (the guard), so a future
# "fix" that only widens a glob does not quietly claim the credit.
# --------------------------------------------------------------------------- #
GLOB_BLIND_SPOTS = [
    # tool and verb NOT adjacent — `*talosctl reset*` never matched these.
    "talosctl -n 192.168.50.94 reset",
    "talosctl --nodes 192.168.50.94 reset",
    "talosctl --nodes=192.168.50.94 reset",
    "talosctl -e 1.2.3.4 -n 5.6.7.8 reset",
    "talosctl --talosconfig /tmp/tc -n 1.2.3.4 reset",
    "sudo -n talosctl -n 192.168.50.94 reset",
    # flag ORDER the `rm -rf` patterns did not know.
    "rm -f -r /",
    "rm --recursive --force /",
    "rm -r -f $HOME",
    # binaries the `*mkfs*` pattern did not know.
    "mke2fs /dev/sdc",
    "mkswap /dev/sdd",
    # the global-option hop past a raw-text `git reset` anchor.
    "git -C /tmp/x reset --hard",
]


@pytest.mark.parametrize("command", GLOB_BLIND_SPOTS)
@pytest.mark.parametrize("agent", [None] + sorted(EXPECTED_AGENTS))
def test_glob_blind_spots_are_denied_on_every_agent(agent, command):
    assert layered_verdict(command, agent) == "deny"


@pytest.mark.parametrize("command", GLOB_BLIND_SPOTS)
def test_glob_blind_spots_are_caught_by_the_GUARD_not_the_globs(command):
    """🔴 The attribution assertion.

    If someone later widens a glob to cover one of these, this test still passes
    — but if someone DELETES the guard check believing the glob has it, it fails.
    That is the direction that matters: the glob layer is friction and cannot be
    made airtight (unbounded spellings), so the guard must be what holds.
    """
    assert guard_verdict(command) == "deny", (
        f"{command!r} is not caught by guard_core's opencode policy. It was "
        f"measured ALLOW under the c1e4c02 globs; a glob is not an acceptable "
        f"sole control for an irreversible action."
    )


@pytest.mark.parametrize("command", MUST_ASK)
def test_high_blast_radius_commands_prompt_on_the_primary_agent(command):
    got = effective_bash_action(command, None)
    assert got == "ask", f"{command!r} resolves {got!r}, expected 'ask'"


@pytest.mark.parametrize("command", MUST_ASK)
@pytest.mark.parametrize("agent", ALL_AGENTS)
def test_high_blast_radius_never_plain_allow_on_any_agent(agent, command):
    got = effective_bash_action(command, agent)
    assert got in ("ask", "deny"), (
        f"agent={agent or '<primary>'}: {command!r} resolves {got!r} — it must "
        f"prompt or be denied, never run silently"
    )


@pytest.mark.parametrize("command", MUST_ALLOW)
def test_read_only_commands_stay_allowed_on_the_primary_agent(command):
    """Prompt fatigue is a security failure, not a UX one."""
    got = effective_bash_action(command, None)
    assert got == "allow", (
        f"{command!r} resolves {got!r} — this is a read-only, high-frequency "
        f"command and must not prompt"
    )


@pytest.mark.parametrize("command", ["kubectl get pods -A", "ls -la", "git -C /tmp log --oneline -3"])
def test_k8s_agent_keeps_read_only_commands_allowed(command):
    """The F1 fix removes k8s's `"*": allow`; this pins that doing so did not
    over-restrict the agent into uselessness."""
    assert effective_bash_action(command, "k8s") == "allow"


def test_no_agent_reopens_the_bash_wildcard_with_allow():
    """🔴 The k8s regression, structurally.

    An agent-level `bash: {"*": allow}` is appended AFTER the entire global
    block, so last-match-wins makes it nullify every global deny at a stroke.
    Measured on 1.18.4: it landed at index 74 after all 30 global rules and left
    only the 4 agent-local rules standing — `git stash`, `git reset --hard`,
    `rm -rf ~…`, `sops -d`, `nixos-rebuild` and `home-manager switch` were all
    plain ALLOW on the k8s agent.

    An agent block may only ever TIGHTEN. The global `"*": allow` already keeps
    bash present in the tool map, so re-stating it buys nothing and costs
    everything.
    """
    offenders = []
    for name in sorted(EXPECTED_AGENTS):
        bash = agent_permission(name).get("bash")
        if isinstance(bash, dict) and bash.get("*") == "allow":
            offenders.append(name)
    assert not offenders, (
        f"agent(s) {offenders} declare `bash: {{'*': allow}}`. That is appended "
        f"AFTER the global block and NULLIFIES every global deny/ask. Drop it — "
        f"the global wildcard already enables bash."
    )


def test_bash_permission_wildcard_is_first():
    """`"*": "allow"` must be the FIRST key of the bash block.

    NOTE this is an INVARIANT GUARD, not regression coverage: it is exactly the
    assertion that passed under both mutations that mattered. It is kept because
    it localises the failure, but the real protection is the effective-action
    tests above.
    """
    bash = load_config()["permission"]["bash"]
    keys = list(bash)
    assert keys[0] == "*", (
        f"first key of the bash permission block is {keys[0]!r}, not '*'."
    )
    assert bash["*"] == "allow"


def test_no_allow_rule_follows_the_wildcard():
    """🔴 The missing assertion that makes a trailing `"git *": "allow"` fail.

    A single broad `allow` appended anywhere after index 0 resurrects every deny
    above it. Nothing but the leading wildcard may be an `allow`.
    """
    bash = load_config()["permission"]["bash"]
    offenders = [k for k, v in list(bash.items())[1:] if v == "allow"]
    assert not offenders, (
        f"`allow` rules after the leading wildcard: {offenders}. opencode is "
        f"LAST-MATCH-WINS, so each of these re-opens every deny/ask above it."
    )


def test_all_asks_precede_all_denies():
    """Deny-last is what makes a narrow deny beat a broad ask.

    `*talosctl reset*: deny` only wins over `*talosctl*: ask` because it comes
    later. Interleaving them, or sorting the block, silently downgrades denies.

    🔴 THE NON-VACUITY GUARD BELOW IS LOAD-BEARING — it is not defensive padding.
    MEASURED: at 1fb8c2b a blind `ask`->`allow` sed emptied the ask block (50 ->
    0 asks) and THIS TEST STILL PASSED, because `last_ask` falls back to -1 and
    every `first_deny` beats -1. It sat green through the entire 117-failure
    outage, asserting an ordering over an empty set. `test_every_dangerous_
    pattern_is_prefix_tolerant` went vacuous the same way and for the same
    reason: it filters on `v != "allow"`, so a wiped ask block leaves it
    inspecting only the deny block. One wipe silently defanged two tests, so the
    floor is asserted HERE, once, rather than restated at each vacuous site.

    The floor is a LITERAL, not derived from the config: 50 ask rules were
    measured after the restoration.

    🔴 THE FLOOR WAS 40, AND THE TEN-RULE SLACK WAS ITSELF EXPLOITABLE. An
    adversarial sweep deleted exactly ten ask rules — the four mutating
    `systemctl` verbs, `kubectl` patch/scale/drain, `helm` upgrade/rollback and
    `flux resume` — leaving exactly 40. The suite reported 480 passed, 0 failed
    while all ten of those commands resolved `glob=allow layered=allow`. "Room
    to prune ten deliberately" and "room to un-gate ten dangerous families" are
    the same slack; the docstring only named the first.

    So the floor is now the MEASURED count, 50, with no cushion. That is a
    deliberate trade: a genuine prune must lower this literal in the same
    commit, which is what makes a prune a visible act instead of free slack.
    Adding rules is unaffected (`>=`).

    WHAT THIS FLOOR NOW UNIQUELY COVERS — honestly, very little, and it is kept
    as a cheap tripwire rather than a control:
      * a mass ask->allow FLIP is already caught by
        `test_no_allow_rule_follows_the_wildcard` (that is what produced the
        original 117 failures), and ask->deny by the ordering assertion below;
      * mass DELETION, which used to be its one unique catch, is now caught rule
        by rule and BY NAME by `test_every_ask_rule_is_individually_pinned`.
    Its remaining value is that it fails on the COUNT, so a mass edit is
    localised to one obvious assertion before the per-rule ledger enumerates it.
    """
    items = list(load_config()["permission"]["bash"].items())[1:]
    asks = [k for k, v in items if v == "ask"]
    assert len(asks) >= 50, (
        f"only {len(asks)} `ask` rules in the bash block (50 measured after the "
        f"1fb8c2b restoration; the floor IS that measurement, with no cushion — "
        f"see this test's docstring for why the old 40 was exploitable). "
        f"A collapse is the signature of a blanket ask->allow rewrite, which "
        f"ALSO makes this test's ordering assertion and the prefix-tolerance "
        f"test vacuous. If you pruned a rule deliberately, lower this literal "
        f"in the SAME commit and check "
        f"`test_every_ask_rule_is_individually_pinned` still passes."
    )
    last_ask = max((i for i, (_, v) in enumerate(items) if v == "ask"), default=-1)
    first_deny = min((i for i, (_, v) in enumerate(items) if v == "deny"), default=len(items))
    assert first_deny > last_ask, (
        f"a `deny` appears at index {first_deny} before an `ask` at {last_ask}. "
        f"All asks must precede all denies, or a broad ask can override a "
        f"narrow deny."
    )


def test_every_dangerous_pattern_is_prefix_tolerant():
    """🔴 Every deny/ask must be leading-`*`.

    opencode matches a command node's FULL text, so a bare `"git stash*"` misses
    `FOO=1 git stash`, `sudo -n git stash` and `git -C /tmp stash` — measured,
    all three ALLOWED. A handful of anchored patterns are legitimate (a bare
    command name that cannot be meaningfully prefixed); they are listed
    explicitly so adding a new anchored pattern is a deliberate act.
    """
    allowed_anchored = {"*", "sudo*", "dd *"}
    offenders = [
        k for k, v in load_config()["permission"]["bash"].items()
        if v != "allow" and not k.startswith("*") and k not in allowed_anchored
    ]
    assert not offenders, (
        f"bash patterns that are not prefix-tolerant: {offenders}. Prefix each "
        f"with `*` or add it to `allowed_anchored` with a reason."
    )


# Every command family the audit called out as unlisted. Asserted by RESOLVED
# OUTCOME, not by substring-matching the config keys — a key search would pass
# on a pattern that is present but shadowed.
#
# 🔴 A MODULE-LEVEL CONSTANT, not an inline parametrize list, because the
# per-rule ledger below must consider EVERY command this file pins. Left inline,
# these rows were invisible to it and four rules they cover
# (`*git*restore*`, `*kubectl*replace*`, `*flux*suspend*`, `*systemctl*stop*`)
# were reported as unpinned. The ledger's question is "would deleting this rule
# turn any pinned command green-to-silent", so its pool must be all of them.
DANGEROUS_FAMILIES = [
        "git stash", "git reset --hard", "git add -A", "rm -rf /x",
        "talosctl reset", "kubectl delete pod x", "kubectl apply -f x",
        "kubectl exec -it x -- sh", "kubectl cp a b", "kubectl edit deploy x",
        "kubectl replace -f x", "kubectl rollout undo deploy/x",
        "kubectl get secret x -o yaml", "flux delete source git x",
        "flux suspend kustomization x", "helm uninstall x",
        "sops -d s.enc.yaml", "sops exec-env s.enc.yaml env", "age -d -i k f",
        "sudo whoami", "chmod -R 777 /x", "chown -R me /x",
        "git checkout -- foo", "git restore foo", "git branch -D foo",
        "git push --force", "talosctl upgrade --image x",
        "talosctl apply-config -f x", "talosctl shutdown",
        "dd if=/dev/zero of=/dev/sda", "mkfs.ext4 /dev/sda",
        "nix profile remove x", "systemctl stop foo", "nixos-rebuild switch",
        "home-manager switch", "nix-collect-garbage -d",
]


@pytest.mark.parametrize("command", DANGEROUS_FAMILIES)
def test_dangerous_command_family_is_gated(command):
    """Every family the audit called out resolves to something other than a
    silent `allow`, on the primary agent."""
    got = effective_bash_action(command, None)
    assert got != "allow", f"{command!r} resolves 'allow' — it would run unprompted"


# --------------------------------------------------------------------------- #
# 🔴 THE PER-RULE LEDGER — the mutation sweep, as a standing assertion.
#
# THE DEFECT CLASS THESE CLOSE. Every assertion above is a claim about a
# COMMAND. None is a claim about a RULE, and the two are not the same: a rule
# can be deleted outright while every pinned command keeps its verdict, because
# some OTHER rule happens to catch each one. MEASURED on this file at f76b3d7 by
# deleting each of the 77 single-line verdict rows in opencode.jsonc one at a
# time and re-running: **39 of 77 deletions left the suite fully green**, and
# **17** of those were real holes — a realistic command in that family dropped to
# plain `allow` at BOTH the glob layer and the layered (glob + guard_core) layer.
# Among them: `*git*commit*`, `*kubectl*drain*`, `*helm*upgrade*` and all four
# mutating `systemctl` verbs.
#
# 🔴 AND THE AGGREGATE FLOOR COULD NOT SEE IT. `test_all_asks_precede_all_denies`
# pins `len(asks) >= 40` against 50 measured, so ten ask rules could be deleted
# with the gate GREEN — which is exactly ten dangerous families going ungated.
# That is why the protection has to be PER RULE. The floor is now a tripwire
# behind these, not the primary guard.
#
# The two tests below assert a RELATIONSHIP, not a component: every ask/deny rule
# is either the SOLE DECIDER for some pinned command, or explicitly declared
# redundant/guard-backstopped with that claim re-measured. They fail when the
# rule set GROWS (a new rule nobody pinned) and when it SHRINKS (a rule the
# declarations depended on went away).
# --------------------------------------------------------------------------- #
def _sole_decider_commands(pattern: str, commands: list) -> list:
    """Commands whose PRIMARY-agent verdict changes when `pattern` is deleted."""
    return [c for c in commands
            if effective_bash_action(c, None)
            != effective_bash_action_without(pattern, c, None)]


def test_every_ask_rule_is_individually_pinned():
    """🔴 Deleting ANY single `ask` rule must change a pinned command's verdict.

    An `ask` rule with no such command is dead weight in the test suite's eyes:
    it can be deleted and nothing goes red, so the family it names silently
    drops to `allow`. Every rule must therefore be either
      * the SOLE DECIDER for at least one command this file pins — MUST_ASK
        (asserted `== ask`) or DANGEROUS_FAMILIES (asserted `!= allow`) — or
      * listed in REDUNDANTLY_COVERED_ASKS — and that listing is VERIFIED here,
        not taken on trust, so it cannot outlive the rule that covers it.
    """
    bash = load_config()["permission"]["bash"]
    asks = [k for k, v in list(bash.items())[1:] if v == "ask"]

    pinned = MUST_ASK + DANGEROUS_FAMILIES
    unpinned, wrongly_redundant = [], []
    for pat in asks:
        killers = _sole_decider_commands(pat, pinned)
        if pat in REDUNDANTLY_COVERED_ASKS:
            if killers:
                wrongly_redundant.append((pat, killers[:3]))
        elif not killers:
            unpinned.append(pat)

    stale = [p for p in REDUNDANTLY_COVERED_ASKS if p not in asks]

    assert not unpinned, (
        f"{len(unpinned)} `ask` rule(s) are pinned by NOTHING — each can be "
        f"deleted with this suite fully green, dropping its family to plain "
        f"`allow`: {unpinned}\n"
        f"Fix by adding one MUST_ASK command that ONLY this rule matches (mind "
        f"the house spellings: `git -C <path> …`, `KUBECONFIG=$KC_… kubectl -n "
        f"ns …`), or — if another rule genuinely covers it — by adding it to "
        f"REDUNDANTLY_COVERED_ASKS with the covering pattern named."
    )
    assert not wrongly_redundant, (
        f"rule(s) declared REDUNDANTLY_COVERED_ASKS are in fact LOAD-BEARING: "
        f"{wrongly_redundant}. The rule that used to cover them is gone or "
        f"changed. Remove them from that dict — they now need real coverage."
    )
    assert not stale, (
        f"REDUNDANTLY_COVERED_ASKS names pattern(s) that no longer exist in the "
        f"config: {stale}. Drop the stale entries."
    )


def test_every_deny_rule_is_individually_pinned():
    """🔴 The deny-block half, asserted at the layer that actually holds it.

    The config header is explicit that the deny globs are "a short, deliberately
    NON-EXHAUSTIVE mirror of the guard's families in their naive spellings" —
    defence in depth, not the control. So a deny rule may legitimately be
    unnecessary at the GLOB layer. What may NOT happen is that nobody checks.

    Each deny rule is therefore either the sole decider for a MUST_DENY command
    at the glob layer, or listed in GUARD_BACKSTOPPED_DENIES with a command that
    is re-measured here to still resolve `deny` once the glob is removed. That
    second assertion is the one that matters: it fails if someone deletes the
    GUARD check believing the glob has it, or the glob believing the guard does.

    🔴 THE VERDICT IS ALSO ASSERTED AT THE GLOB LAYER, not only end-to-end.
    MEASURED: downgrading `"*git*add -A*"` from `deny` to `ask` survived every
    other assertion in this file, because guard_core denies `git add -A` anyway
    so nothing observable changed. That mutant is not equivalent, though — the
    deny block's whole reason for existing is the case where guard.js FAILS TO
    LOAD, and under a silent downgrade the interactive TUI would offer a human
    the chance to approve it. So each deny rule must resolve `deny` at the glob
    layer too.
    """
    bash = load_config()["permission"]["bash"]
    denies = [k for k, v in list(bash.items())[1:] if v == "deny"]

    # 🔴 FIRST: the SET, against the declarations. Reading `denies` off the
    # config and only checking what is in it cannot see a rule that left the set
    # — a `deny`->`ask` downgrade removes the rule from every subsequent loop.
    expected = set(GLOB_ENFORCED_DENIES) | set(GUARD_BACKSTOPPED_DENIES)
    assert set(denies) == expected, (
        f"the deny block's pattern SET differs from the declarations.\n"
        f"  no longer `deny` (deleted, or downgraded to ask/allow): "
        f"{sorted(expected - set(denies))}\n"
        f"  present but undeclared: {sorted(set(denies) - expected)}\n"
        f"Add a new deny to GLOB_ENFORCED_DENIES (with a command it decides) or "
        f"to GUARD_BACKSTOPPED_DENIES (with the command guard_core holds)."
    )

    unpinned, unheld, downgraded = [], [], []
    for pat in denies:
        if pat in GUARD_BACKSTOPPED_DENIES:
            cmd = GUARD_BACKSTOPPED_DENIES[pat]
            # With the glob gone, the guard must still deny it outright.
            if guard_verdict(cmd) != "deny":
                unheld.append((pat, cmd, effective_bash_action_without(pat, cmd, None)))
            probes = [cmd]
        else:
            probes = _sole_decider_commands(pat, MUST_DENY + DANGEROUS_FAMILIES)
            if not probes:
                unpinned.append(pat)
        if probes and not any(effective_bash_action(c, None) == "deny" for c in probes):
            downgraded.append((pat, probes[0], effective_bash_action(probes[0], None)))

    # NOTE deliberately NO "stale declaration" assertion here, unlike the ask
    # ledger. The set assertion above subsumes it — a declared pattern that left
    # the config already fails there — so a second check would be UNREACHABLE,
    # and an unreachable assertion reports safety while testing nothing.
    # (Verified by mutation: dropping `*mkswap*` fails on the set assertion.)

    assert not unpinned, (
        f"{len(unpinned)} `deny` rule(s) are pinned by NOTHING at the glob "
        f"layer and are not declared guard-backstopped: {unpinned}. Add a "
        f"MUST_DENY command only this rule matches, or add it to "
        f"GUARD_BACKSTOPPED_DENIES with the command the guard holds."
    )
    assert not unheld, (
        f"🔴 rule(s) declared GUARD_BACKSTOPPED_DENIES are NOT actually held by "
        f"guard_core: {unheld}. The glob is the ONLY control for these — either "
        f"the guard check was removed, or it never covered this spelling. Do "
        f"not fix this by widening the glob; the header explains why."
    )
    assert not downgraded, (
        f"🔴 `deny` rule(s) do NOT resolve deny at the GLOB layer: {downgraded}. "
        f"Either the rule was silently downgraded to `ask`, or a later rule "
        f"shadows it. This is invisible end-to-end whenever guard_core covers "
        f"the same command — and the deny block exists precisely for the case "
        f"where guard.js does not load."
    )


def test_guard_core_catches_recursive_rm_without_the_force_flag():
    """The `rm -r` attribution, measured rather than assumed.

    🔴 LABEL: this is an INVARIANT GUARD, not regression coverage — it passed
    before this file's per-family rows were added and passes after. It exists
    because a plausible-sounding claim ("guard_core only handles `-rf` forms, so
    `rm -r /` is glob-only") is FALSE, and acting on it would mean widening a
    glob or a guard that already holds. check_rm_rf_critical tests the RECURSIVE
    flag alone — `--recursive`, or any short bundle containing r/R — and never
    requires `-f`.

    The complement is the part that IS regression coverage, and it lives in
    MUST_ASK: an ordinary recursive delete (`rm -r /repo/build`) is deliberately
    NOT in the guard's fatal-target set, so the `*rm*-r*` glob is its only gate.
    """
    for cmd in ["rm -r /", "rm --recursive /", "rm -R /", "rm -r $HOME",
                "rm --recursive $HOME", "rm -r ~", "rm -r .", "rm -r /etc",
                "rm --recursive /nix"]:
        assert guard_verdict(cmd) == "deny", (
            f"{cmd!r} is NOT denied by guard_core's opencode policy. The `-rf` "
            f"spelling is not the boundary of that check — if this fails, the "
            f"recursive-flag test in check_rm_rf_critical was narrowed."
        )
    # …and the deliberate NON-coverage, so the narrowness stays a decision.
    assert guard_verdict("rm -r /repo/build") == "allow", (
        "guard_core now denies an ordinary recursive delete. That may be an "
        "improvement, but it is a behaviour change: check_rm_rf_critical's "
        "fatal-target set was deliberately narrow so routine cleanup would not "
        "train the operator to route around the guard (see its docstring). "
        "Update this assertion deliberately, with the measurement that "
        "justified widening it."
    )


# --------------------------------------------------------------------------- #
# 3. tool-level permissions
# --------------------------------------------------------------------------- #
def test_no_blanket_read_allow():
    """🔴 opencode ships a built-in `.env` guard:
        read: {"*": allow, "*.env": ask, "*.env.*": ask, "*.env.example": allow}
    A blanket `"read": "allow"` here is appended AFTER those (measured: it landed
    at index 30, the guards at 25-27) and silently defeats them on every agent.
    The default already allows everything except `.env`, so there is nothing to
    add — the correct config is to say nothing.
    """
    perm = load_config()["permission"]
    assert "read" not in perm, (
        "`read: allow` defeats opencode's built-in .env guard on every agent. "
        "Remove the key; the default already allows all non-.env reads."
    )


# The TOOL-level permission rows, verbatim. `bash` is excluded — it has its own
# ordered-glob block and its own per-rule ledger above.
EXPECTED_TOOL_PERMISSIONS = {
    "glob": "allow",
    "grep": "allow",
    "edit": "allow",
    "write": "allow",
    "webfetch": "allow",
    "todowrite": "allow",
    "task": "allow",
    "skill": "allow",
    "doom_loop": "ask",
    "external_directory": "ask",
}


def test_tool_level_permissions_are_pinned_exactly():
    """🔴 The per-rule ledger, for the NON-bash half of the block.

    These ten rows were the entire residue of the deletion sweep after the bash
    ledger landed: 10 of 77 mutants still survived, and all ten were here.
    `doom_loop` and `external_directory` are the ones that matter — they are the
    only `ask` rows outside the bash block, and flipping either to `allow`
    removed a real control (an unbounded loop; reaching outside the project
    directory) with the suite fully green.

    Pinned as an EXACT mapping rather than a set of `in` checks, so the sweep's
    three mutant shapes all fail: deleting a row, commenting it out, and
    inverting its verdict. An exact map also fails on an ADDED row, which is
    deliberate — a new tool-level permission should be a reviewed decision, and
    `read` in particular must never appear (see test_no_blanket_read_allow).
    """
    perm = {k: v for k, v in load_config()["permission"].items() if k != "bash"}
    assert perm == EXPECTED_TOOL_PERMISSIONS, (
        f"tool-level permission rows differ from the pinned set.\n"
        f"  missing/changed: "
        f"{ {k: v for k, v in EXPECTED_TOOL_PERMISSIONS.items() if perm.get(k) != v} }\n"
        f"  unexpected:      "
        f"{ {k: v for k, v in perm.items() if k not in EXPECTED_TOOL_PERMISSIONS} }\n"
        f"If the change is intended, update EXPECTED_TOOL_PERMISSIONS in the "
        f"SAME commit and say why in the message."
    )


@pytest.mark.parametrize("dead", ["list", "websearch"])
def test_no_nonexistent_tools_in_permission_block(dead):
    """There is no `list` and no `websearch` tool on 1.18.4. The resolved tool
    map is exactly {bash, edit, glob, grep, invalid, question, read, skill,
    task, todowrite, webfetch, write}. Naming a nonexistent tool is a silent
    no-op that reads like configuration."""
    assert dead not in load_config()["permission"], (
        f"{dead!r} is not a tool on opencode 1.18.4 — the key does nothing"
    )


@pytest.mark.parametrize("name", ["title", "summary", "compaction"])
def test_hidden_agents_are_pinned_and_tool_less(name):
    """🔴 Cost AND blast radius.

    Their STOCK tool set is EMPTY (measured against a bare config dir:
    `enabled=[]`). But every entry in the global `permission` block is appended
    to their resolved list too, which re-enabled bash, write, edit, task and
    skill on all three. `compaction` runs automatically on every context
    overflow, so that handed a shell and a writer to the cheap model on a path
    nobody watches, and made every title generation carry the ~3,730-token skill
    catalogue.

    Verified after the fix: all three resolve `enabled=[]` again.
    """
    agents = load_config()["agent"]
    assert name in agents, f"hidden agent {name!r} is not pinned"
    assert "flash" in agents[name]["model"], (
        f"{name!r} is pinned to {agents[name]['model']!r}, not the cheap model"
    )
    assert agents[name].get("permission", {}).get("*") == "deny", (
        f"{name!r} must carry `permission: {{'*': 'deny'}}` — otherwise the "
        f"global permission block re-enables bash/write/skill on it"
    )


def test_plan_agent_is_genuinely_read_only():
    """`task: {general: deny}` is a RESTORATION, not an addition.

    Stock `plan` resolves `task 'general' deny` at index 30 — it may not spawn
    the `general` subagent, which HAS a shell. The global `"task": "allow"`
    landed at index 41, after it, and flipped it to allow: `plan` could reach a
    shell by delegating. Restating it at agent level puts it last again.
    """
    plan = load_config()["agent"]["plan"]["permission"]
    assert plan["edit"] == "deny"
    assert plan["bash"] == "deny"
    assert plan["write"] == "deny"
    assert plan["task"] == {"general": "deny"}, (
        "plan must re-deny the `general` subagent — the global `task: allow` "
        "overrides opencode's built-in deny, giving plan a shell by proxy"
    )


def test_no_deprecated_keys():
    cfg = load_config()
    for dead in ("mode", "layout", "autoshare", "reference", "maxSteps", "theme", "keybinds", "tui"):
        assert dead not in cfg, f"{dead!r} is deprecated on 1.18.4 and must not be set"


def test_core_settings():
    cfg = load_config()
    assert cfg["autoupdate"] is False
    assert cfg["share"] == "disabled"
    assert cfg["snapshot"] is True
    assert cfg["subagent_depth"] == 2
    assert cfg["compaction"] == {"auto": True, "prune": True, "reserved": 16000}
    assert cfg["tool_output"] == {"max_lines": 800, "max_bytes": 24576}
    assert set(cfg["watcher"]["ignore"]) == {
        "node_modules/**", ".git/**", "result/**", ".direnv/**", "**/*.enc.yaml",
    }


# --------------------------------------------------------------------------- #
# 4. the shell.env plugin + the shared handle definitions
# --------------------------------------------------------------------------- #
def test_env_plugin_is_generated_not_a_hardcoded_file():
    """🔴 `scripts/opencode/env.js` used to be a checked-in file with a
    hardcoded `/home/zach/workspace/homelab-talos`, duplicating (and drifted
    from) nix/programs/zsh. It is now GENERATED from nix/agent-handles.nix."""
    assert not (OC_DIR / "env.js").exists(), (
        "scripts/opencode/env.js is back. It hardcoded an absolute home path "
        "and duplicated the zsh handle block; generate it from "
        "nix/agent-handles.nix instead."
    )
    nix = HOME_NIX.read_text()
    assert 'home.file.".config/opencode/plugin/env.js".text' in nix, (
        "env.js must be GENERATED (.text) from agent-handles.nix, not symlinked"
    )
    assert "./agent-handles.nix" in nix
    # The glob is NON-RECURSIVE — a `plugin/` dir symlink would break the moment
    # anything nests, and a `.mjs` would never load at all.
    assert 'home.file.".config/opencode/plugin" =' not in nix
    assert not (OC_DIR / "env.mjs").exists()


def test_env_plugin_generation_registers_a_shell_env_hook():
    nix = HOME_NIX.read_text()
    assert '"shell.env"' in nix, (
        "the generated plugin must register a `shell.env` hook — there is NO "
        "`env` config key in opencode, so this hook is the only way to reach "
        "the bash tool"
    )
    assert "output.env." in nix, "the hook must MUTATE output.env"


def test_env_plugin_existence_guards_every_handle():
    """An unguarded handle pointing at a missing kubeconfig is worse than an
    absent one: the command runs against NO cluster while looking like it
    worked. zsh has always guarded; the old env.js did not."""
    nix = HOME_NIX.read_text()
    for needle in ("statSync", "isDirectory()", "const isDir =", "const isFile =",
                   'entry "isDir"', 'entry "isFile"'):
        assert needle in nix, f"generated env.js lacks {needle!r} — no existence guard"


@pytest.mark.parametrize(
    "group,var,expected",
    [
        ("repos", "HOMELAB", "/home/testuser/workspace/homelab-talos"),
        ("repos", "DEVRC", "/home/testuser/workspace/devrc"),
        ("repos", "DATAPACKET", "/home/testuser/workspace/civit/datapacket-talos"),
        ("repos", "CIVITAI", "/home/testuser/workspace/civit/civitai"),
        ("repos", "CIVITAI_CLI", "/home/testuser/workspace/civit/civitai-cli"),
        ("kubeconfigs", "KC_HOMELAB", "/home/testuser/workspace/homelab-talos/homelab-kubeconfig"),
        ("kubeconfigs", "KC_WORKBENCH", "/home/testuser/workspace/homelab-talos/workbench-kubeconfig"),
        ("kubeconfigs", "KC_PROD", "/home/testuser/workspace/homelab-talos/production-kubeconfig"),
        ("kubeconfigs", "KC_DPPROD", "/home/testuser/workspace/civit/datapacket-talos/prod-kubeconfig"),
        ("kubeconfigs", "KC_NEBULA", "/home/testuser/.kube/homelab-nebula.yaml"),
    ],
)
def test_handles_resolve_to_the_exact_expected_paths(group, var, expected):
    """🔴 FULL literal paths, derived from a NON-real home.

    The previous version asserted only the filename tail, so it passed with
    `HOMELAB` mutated to `/tmp/totally-wrong` and with the KC_HOMELAB /
    KC_WORKBENCH targets SWAPPED. Pinning the whole path against a synthetic
    home (`/home/testuser`) also catches a re-hardcoded `/home/zach`.
    """
    got = handles()[group].get(var)
    assert got == expected, f"{var} resolves to {got!r}, expected {expected!r}"


def test_zsh_and_opencode_share_one_handle_definition():
    """Both consumers must import agent-handles.nix. Two hand-written copies is
    exactly how KC_PROD came to exist for opencode and not for zsh."""
    assert "agent-handles.nix" in ZSH_NIX.read_text(), (
        "programs/zsh must generate its exports from nix/agent-handles.nix"
    )
    assert "agent-handles.nix" in HOME_NIX.read_text(), (
        "home.nix must generate plugin/env.js from nix/agent-handles.nix"
    )
    # And the hand-written export lines must be gone, or they would shadow it.
    zsh = ZSH_NIX.read_text()
    assert "export KC_HOMELAB=$HOME/workspace" not in zsh, (
        "hand-written handle exports survive in zsh alongside the generated "
        "ones — delete them, they are the copy that drifts"
    )


# --------------------------------------------------------------------------- #
# 5. the subagents
# --------------------------------------------------------------------------- #
def test_exactly_the_expected_agents_exist():
    found = {p.stem for p in AGENT_DIR.glob("*.md")}
    assert found == EXPECTED_AGENTS, f"expected {EXPECTED_AGENTS}, found {found}"


@pytest.mark.parametrize("name", sorted(EXPECTED_AGENTS))
def test_agent_frontmatter_is_valid(name):
    text = (AGENT_DIR / f"{name}.md").read_text()
    fm, body = parse_frontmatter(text)
    keys = frontmatter_top_level_keys(fm)

    assert "description" in keys, f"{name}.md frontmatter has no `description`"
    assert "mode" in keys, f"{name}.md frontmatter has no `mode`"

    desc = re.search(r"^description:\s*(.+)$", fm, re.M).group(1).strip()
    assert len(desc) > 20, f"{name}.md description is too short to route on: {desc!r}"

    mode = re.search(r"^mode:\s*(\S+)", fm, re.M).group(1)
    assert mode == "subagent", f"{name}.md mode is {mode!r}, expected 'subagent'"

    assert body.strip(), f"{name}.md has an empty body (no system prompt)"


@pytest.mark.parametrize("name", sorted(EXPECTED_AGENTS))
def test_agent_frontmatter_parses_as_yaml(name):
    fm, _ = parse_frontmatter((AGENT_DIR / f"{name}.md").read_text())
    data = yaml.safe_load(fm)
    assert isinstance(data, dict), f"{name}.md frontmatter is not a YAML mapping"
    assert data.get("mode") == "subagent"
    assert isinstance(data.get("description"), str) and data["description"]


def test_nav_has_no_shell():
    """🔴 `bash: deny` on nav is the DETERMINISTIC fix for ~356 file-navigation
    shell-outs. A prose instruction to "prefer the native tools" is exactly the
    heuristic patch this replaces — if this flips to allow, the fix is gone."""
    perm = agent_permission("nav")
    assert perm["bash"] == "deny", "nav MUST have bash denied"
    assert perm["edit"] == "deny"
    assert perm["write"] == "deny"


def test_nav_is_kept_lean():
    """nav must not carry the skill catalogue or be able to recurse.

    VERIFIED against `opencode debug agent nav` on 1.18.4: with these denies the
    resolved tool set is exactly {glob, grep, read} (+ the internal `invalid`).
    Without `skill: deny` it also carries {skill, task, todowrite, webfetch} —
    and `skill` alone injects the whole catalogue, measured at ~3,730 tokens on
    EVERY request. This is a cost guard, and it is the high-frequency agent.
    """
    perm = agent_permission("nav")
    for tool in ("skill", "task"):
        assert perm.get(tool) == "deny", (
            f"nav must deny {tool!r} — it is the cheap high-frequency navigator "
            f"and `skill` alone costs ~3,730 tokens per request"
        )


def test_no_agent_promises_a_list_tool():
    """There is NO `list` tool on opencode 1.18.4."""
    targets = [AGENT_DIR / f"{n}.md" for n in EXPECTED_AGENTS] + [ADDENDUM]
    bad = []
    for p in targets:
        for i, ln in enumerate(p.read_text().split("\n"), 1):
            if re.search(r"`list`", ln) and "no `list` tool" not in ln:
                bad.append(f"{p.name}:{i}: {ln.strip()}")
    assert not bad, f"reference(s) to a nonexistent `list` tool: {bad}"


def test_review_denies_bash_first_then_allows_read_only_git():
    """review's block is THREE phases: `"*": "deny"`, then the read-only
    git/rg allows, then the writing verbs re-denied LAST.

    The third phase is not decoration — see
    test_review_allowlist_cannot_be_ridden_by_argument_text below for the
    execution-verified bypass it closes.
    """
    bash = agent_permission("review")["bash"]
    items = list(bash.items())
    assert items[0] == ("*", "deny"), (
        f"review's bash block must start with '*': deny, got {items[0]!r}"
    )
    actions = [v for _, v in items[1:]]
    assert set(actions) <= {"allow", "deny"}
    assert "allow" in actions and "deny" in actions, (
        "review must have BOTH an allow-list and re-stated denies after it"
    )
    last_allow = max(i for i, a in enumerate(actions) if a == "allow")
    first_deny = min(i for i, a in enumerate(actions) if a == "deny")
    assert first_deny > last_allow, (
        "every re-stated deny must come AFTER every allow. opencode is "
        "last-match-wins, so a deny placed before the allow-list is a no-op."
    )


@pytest.mark.parametrize("command", [
    # 🔴 VERIFIED BY EXECUTION at c1e4c02: this RAN and created a stash. The
    # allow-list's `git -C * diff*` has a MIDDLE `*`, and opencode's `*` is an
    # unrestricted `.*` crossing spaces — so the word "diff" anywhere in the
    # ARGUMENT TEXT satisfied it. The control was a message without "diff",
    # which was correctly denied.
    "git -C /tmp/wt stash push -m 'wip on the diff'",
    "git -C /tmp/wt commit -m 'review the diff'",
    "git -C /tmp/wt reset --hard  # diff",
    "git -C /tmp/wt clean -fd  # diff",
    "git -C /tmp/wt push --force  # log",
    "git -C /tmp/wt checkout main  # show the diff",
    "git -C /tmp/wt worktree remove /tmp/wt  # status",
    "rm -rf /tmp/wt  # diff",
])
def test_review_allowlist_cannot_be_ridden_by_argument_text(command):
    """Layer 1 (globs) must now refuse these, and layer 2 must refuse the
    destructive subset regardless of glob spelling."""
    assert layered_verdict(command, "review") == "deny", (
        f"{command!r} resolves {layered_verdict(command, 'review')!r} on the "
        f"review agent. glob-only={effective_bash_action(command, 'review')!r}"
    )


@pytest.mark.parametrize(
    "command",
    [
        "git -C /home/zach/workspace/devrc-opencode diff",
        "git -C /tmp/wt log --oneline -20",
        "git -C /tmp/wt show HEAD",
        "git -C /tmp/wt status",
        "git diff",
        "git status",
        "rg needle",
    ],
)
def test_review_can_actually_read_a_worktree_diff(command):
    """🔴 The silent-failure bug.

    With only the bare `git diff*` spelling, `git -C <path> diff` resolved DENY
    — and in the worktree-first workflow RULES.md mandates, that is the ONLY
    spelling a reviewer uses. The agent then fell back to read/grep and reported
    a review of a diff it had never seen.
    """
    assert effective_bash_action(command, "review") == "allow", (
        f"review cannot run {command!r} — it will silently fall back to "
        f"read/grep and report a review it did not perform"
    )


@pytest.mark.parametrize("command", ["FOO=1 git diff", "sudo git diff", "env git diff"])
def test_review_does_not_accidentally_allow_wrapped_git(command):
    """The allow-list is anchored ON PURPOSE. A leading-`*` allow here would
    punch a hole straight through the global deny block (which is all
    leading-`*`), so the wrapper forms must stay denied.

    NOTE these are all SINGLE command nodes — see the model's scope note.
    """
    assert effective_bash_action(command, "review") == "deny"


def test_k8s_names_the_handles_verbatim():
    text = (AGENT_DIR / "k8s.md").read_text()
    for handle in ("$KC_HOMELAB", "$KC_WORKBENCH", "$KC_PROD", "$HOMELAB"):
        assert handle in text, f"k8s.md does not mention {handle}"
    for phrase in ("trunk", "rollout restart", "Never construct"):
        assert phrase in text, f"k8s.md is missing guidance on {phrase!r}"


def test_k8s_only_tightens():
    """k8s may add rules, never re-open. Its one agent-specific tightening is
    broadening talosctl to `ask`, with the narrow `reset` deny restated AFTER
    it (last-match-wins would otherwise let the broad ask re-open `reset`)."""
    bash = agent_permission("k8s")["bash"]
    assert "*" not in bash, "k8s must not declare a bash wildcard at all"
    assert bash.get("*talosctl*") == "ask"
    assert bash.get("*talosctl reset*") == "deny"
    assert list(bash).index("*talosctl reset*") > list(bash).index("*talosctl*"), (
        "the narrow deny must come AFTER the broad ask, or last-match-wins "
        "re-opens `talosctl reset`"
    )


# --------------------------------------------------------------------------- #
# 6. the pre-existing unmanaged opencode.jsonc
# --------------------------------------------------------------------------- #
def test_switch_cannot_be_blocked_by_the_unmanaged_config():
    nix = HOME_NIX.read_text()
    assert "home.activation.opencodeDropStaleConfig" in nix
    block = nix.split("home.activation.opencodeDropStaleConfig", 1)[1][:800]
    assert 'entryBefore ["checkLinkTargets"]' in block
    assert "! -L" in block
    assert "mv" in block and "rm -f" not in block


# --------------------------------------------------------------------------- #
# 7. browser-agent config-dir isolation AND warming
# --------------------------------------------------------------------------- #
BROWSER_AGENT = ROOT / "scripts" / "browser-bridge" / "browser-agent"


def browser_agent_code() -> str:
    """browser-agent's source with COMMENTS AND BLANK LINES STRIPPED.

    🔴 Every assertion in this section must run against this, not the raw text.
    The audit found `assert "--version" in src` passing off a COMMENT that says
    "Deliberately not `opencode --version`" — i.e. an assertion satisfied by
    prose stating the code does the opposite. A substring test over a
    heavily-commented shell script is a test of the comments.

    Crude but sufficient: strip whole-line `#` comments. Trailing comments after
    code survive, so this is a floor on rigour, not a ceiling — which is why the
    assertions below also pin STRUCTURE (ordering, call sites) rather than the
    presence of a word.
    """
    return "\n".join(
        ln for ln in BROWSER_AGENT.read_text().split("\n")
        if ln.strip() and not ln.lstrip().startswith("#")
    )


def test_browser_agent_code_helper_actually_strips_comments():
    """Negative control for the helper above — without it every assertion in
    this section is a claim about prose."""
    raw = BROWSER_AGENT.read_text()
    code = browser_agent_code()
    assert "Deliberately not `opencode --version`" in raw
    assert "Deliberately not `opencode --version`" not in code


def test_browser_agent_isolates_its_opencode_config_dir():
    assert "export OPENCODE_CONFIG_DIR=" in browser_agent_code()


def test_browser_agent_checks_for_opencode_before_touching_the_cache():
    """🔴 ORDERING BUG, not a presence bug.

    `oc_warm_version` falls back to the BARE string "$OPENCODE_BIN" when
    `command -v` finds nothing, and `readlink -f` then resolves that against the
    CURRENT WORKING DIRECTORY. The stamp becomes cwd-dependent, `oc_is_warm` can
    never match, and `_oc_bootstrap_locked` takes its "stale tree" branch and
    `rm -rf`s node_modules out of the SHARED cache on every run — then fails to
    re-warm (no opencode), leaving the dir cold for the next invocation. That is
    reachable from systemd/cron/a home-manager switch, where PATH is not a login
    shell's.

    So the preflight must come BEFORE the bootstrap, and a presence-only
    assertion cannot see that: the check existed at c1e4c02, ~180 lines too
    late.
    """
    code = browser_agent_code()
    # 🔴 Anchored on the `|| die` PREFLIGHT, not on any `command -v`. The first
    # draft of this test used the bare `command -v "$OPENCODE_BIN"` substring —
    # which also matches the one INSIDE `oc_warm_version()` at line ~136, i.e.
    # before the bootstrap even at c1e4c02. It therefore passed against the
    # buggy ordering it was written to catch. Caught by running this suite
    # against a pre-change seed tree; without that run it would have shipped as
    # coverage for a bug it could not see.
    preflight = code.index('command -v "$OPENCODE_BIN" >/dev/null 2>&1 || die')
    bootstrap_call = code.index('oc_is_warm "$_oc_ver" || oc_bootstrap')
    rm_in_bootstrap = code.index('rm -rf "$OC_CONFIG_DIR/node_modules"')
    assert preflight < bootstrap_call, (
        "the `command -v opencode` preflight must run BEFORE the config-dir "
        "bootstrap — otherwise a missing binary makes the warm stamp "
        "cwd-dependent and the bootstrap rm -rf's the shared cache every run"
    )
    assert preflight < rm_in_bootstrap


def test_browser_agent_config_dir_is_not_the_live_one():
    """INVARIANT GUARD, not regression coverage — it is green at c1e4c02 too.
    It exists because a mutation pointing this at the REAL ~/.config/opencode
    passed every substring test in this file's earlier form."""
    line = next(ln for ln in browser_agent_code().split("\n")
                if ln.startswith("OC_CONFIG_DIR="))
    assert ".config/opencode" not in line, (
        "the isolated config dir must NOT be the live ~/.config/opencode — that "
        "re-imports the ~37 KB AGENTS.md this mechanism exists to shed, and puts "
        "the warm step's `rm -rf` on the managed directory"
    )


def test_browser_agent_config_dir_is_stable_not_per_run():
    """🔴 A FRESH config dir per run is NOT acceptable: it makes opencode
    materialise 62 MB of node_modules, and offline it HUNG (killed at 120 s, 0
    bytes, tripping the harness's own tool-set gate)."""
    line = next(ln for ln in browser_agent_code().split("\n")
                if ln.startswith("OC_CONFIG_DIR="))
    assert "mktemp" not in line
    assert ".cache" in line


def test_browser_agent_warms_the_config_dir():
    """🔴 Stable is only half of it — an EMPTY-but-existing dir IS the cold-start
    case, and that is what shipped (the dir existed with 0 entries).

    The warm step must also be verified by OUTCOME: `debug paths`, `debug
    config`, `debug skill` and `debug agent` from a plain directory all exit 0
    while installing NOTHING. Only resolving a project's `.opencode/tools/`
    (browser.js imports `@opencode-ai/plugin`) triggers the install.
    """
    code = browser_agent_code()
    assert 'oc_is_warm "$_oc_ver" || oc_bootstrap "$_oc_ver"' in code, (
        "the warm must actually be INVOKED — a mutation that defines "
        "oc_bootstrap and never calls it passed the old `'oc_bootstrap' in src` "
        "assertion"
    )
    assert 'mkdir -p "$seed/.opencode/tools"' in code, (
        "the warm step must run from a seed project carrying the tools — a bare "
        "`opencode debug` command exits 0 and leaves the dir just as cold"
    )
    assert '[ -d "$OC_CONFIG_DIR/node_modules" ]' in code, (
        "warmth must be verified by node_modules existing, never by exit code"
    )


def test_browser_agent_stamp_only_after_a_COMPLETE_warm():
    """🔴 `[ -d node_modules ]` alone is not completeness.

    A warm killed by `timeout` mid-install leaves the tree present and PARTIAL;
    stamping that marks a broken tree valid forever, because every later run
    then short-circuits on `oc_is_warm`. Require that the timeout did not fire
    AND that the one package the warm exists to install resolves.
    """
    code = browser_agent_code()
    assert '[ "$warm_rc" -ne 124 ]' in code, (
        "a `timeout`-killed warm (exit 124) must not be stamped valid"
    )
    assert '[ -d "$OC_CONFIG_DIR/node_modules/@opencode-ai/plugin" ]' in code, (
        "completeness must be judged by the package the warm exists to install"
    )


def test_browser_agent_warm_handles_races_staleness_and_failure():
    """INVARIANT GUARD — green at c1e4c02 as well. What changed is that its
    assertions now run against comment-stripped source: the previous
    `"--version" in src` was satisfied by a COMMENT saying the code deliberately
    does NOT use `--version`. Strengthening a vacuous assertion is not the same
    as adding regression coverage, and is not counted as such."""
    code = browser_agent_code()
    assert 'mkdir "$OC_LOCK"' in code, (
        "concurrent runs must be serialised by an atomic lock"
    )
    # 🔴 The stamp is the RESOLVED BINARY PATH + size:mtime, deliberately NOT
    # `opencode --version` (an extra process per run that also breaks the test
    # rig's invocation-counting assertions). The old assertion here was
    # `"--version" in src`, which matched only the COMMENT saying exactly that.
    assert 'readlink -f "$p"' in code and "stat -c '%s:%Y'" in code, (
        "the version stamp must be derived from the resolved binary identity"
    )
    assert '[ "$(cat "$OC_STAMP" 2>/dev/null)" = "$1" ]' in code, (
        "oc_is_warm must COMPARE the stamp, not merely check it exists"
    )
    assert "OC_ISOLATED=1" in code and "WARNING" in code, (
        "failure to warm must degrade to the global config LOUDLY, not silently "
        "hang or die"
    )


def test_browser_agent_lock_wait_outlasts_the_work_it_guards():
    """A 30 s wait around a 90 s job force-steals the lock and `rm -rf`s
    node_modules while the first process is still writing into it."""
    code = browser_agent_code()
    assert "max=$(( (OC_WARM_TIMEOUT + 30) * 2 ))" in code, (
        "the lock wait must be derived from OC_WARM_TIMEOUT, not a fixed count "
        "shorter than the warm it serialises"
    )


def test_browser_agent_isolated_config_keeps_the_global_safety_settings():
    """Isolation silently drops autoupdate/share/tool_output. Each is worth
    re-stating in the isolated dir; the permission block and AGENTS.md are
    deliberately NOT copied (they are the cost this exists to shed)."""
    src = BROWSER_AGENT.read_text()
    for needle in ('"autoupdate": false', '"share": "disabled"', '"tool_output"'):
        assert needle in src, f"isolated opencode.jsonc does not set {needle}"


def test_browser_agent_fails_loud_if_an_instruction_file_appears():
    src = BROWSER_AGENT.read_text()
    assert '"$OC_CONFIG_DIR/AGENTS.md"' in src


# --------------------------------------------------------------------------- #
# 8. 🔴 the guard plugin's DEPLOYMENT
#
# The guard is only a control if it is actually deployed. Three home.file
# entries have to line up, and the plugin resolves guard_core.py RELATIVE to its
# own module URL — so `plugin/guard.js` + `../guard_core.py` must both land.
# --------------------------------------------------------------------------- #
GUARD_PLUGIN = OC_DIR / "plugin" / "guard.js"
GUARD_CORE = ROOT / "scripts" / "claude-hooks" / "guard_core.py"


@pytest.mark.parametrize("attr,src", [
    ('home.file.".config/opencode/plugin/guard.js".source',
     "../scripts/opencode/plugin/guard.js"),
    ('home.file.".config/opencode/guard_core.py".source',
     "../scripts/claude-hooks/guard_core.py"),
    ('home.file.".claude/hooks/guard_core.py"',
     "../scripts/claude-hooks/guard_core.py"),
])
def test_home_nix_deploys_the_guard(attr, src):
    nix = HOME_NIX.read_text()
    assert attr in nix, f"home.nix does not declare {attr}"
    assert src in nix, f"home.nix does not reference {src}"


def test_every_source_path_home_nix_claims_actually_exists():
    """A `source = ../…` pointing at a missing file fails the switch, not the
    tests — unless something asserts it here."""
    for rel in ["../scripts/opencode/plugin/guard.js",
                "../scripts/claude-hooks/guard_core.py",
                "../scripts/claude-hooks/bash-guard.py"]:
        assert (ROOT / "nix" / rel).resolve().is_file(), f"{rel} does not exist"


def test_plugin_resolves_the_core_next_to_the_config_dir():
    """🔴 The two deployments must AGREE — but NOT via the plugin's own location.

    🔴 THIS TEST USED TO ASSERT THE BUG. Its previous body was:

        assert 'new URL("../guard_core.py", import.meta.url)' in GUARD_PLUGIN.read_text()

    with a docstring reasoning that guard.js "does `../guard_core.py` from
    ~/.config/opencode/plugin/, i.e. ~/.config/opencode/guard_core.py — which is
    exactly where home.nix links it." That reasoning is about the DEPLOY path,
    and the deploy path is a SYMLINK: `home.file` links the plugin into the nix
    store, node resolves `import.meta.url` THROUGH it, and the store is FLAT, so
    `..` was `/nix`. The guard failed closed on every bash call in opencode while
    this test — which pinned the broken line as the contract — stayed green.

    A substring assertion over source text cannot see a deployment bug. The real
    coverage now lives in scripts/tests/test_opencode_guard_plugin.py, which
    builds the store-symlink layout on disk and RUNS the plugin. What is left
    here is the structural half: the plugin must resolve the core from $HOME, and
    home.nix must deploy it there.
    """
    src = GUARD_PLUGIN.read_text()
    assert "homedir()" in src, (
        "guard.js must locate guard_core.py from $HOME, not from its own module "
        "URL — `import.meta.url` resolves into the FLAT nix store"
    )
    assert '.config/opencode/guard_core.py' in HOME_NIX.read_text()


def test_bash_guard_imports_the_core_from_its_own_directory():
    src = (ROOT / "scripts" / "claude-hooks" / "bash-guard.py").read_text()
    assert "os.path.dirname(os.path.abspath(__file__))" in src
    assert "import guard_core" in src
    assert '.claude/hooks/guard_core.py' in HOME_NIX.read_text()


def test_guard_core_is_a_single_source_file_used_by_both():
    """One implementation, two harnesses. If this ever becomes two files they
    will drift — which is precisely what happened to bash-guard.py itself
    (workbench had 6 checks, the laptop a stale copy with 4)."""
    nix = HOME_NIX.read_text()
    refs = nix.count("../scripts/claude-hooks/guard_core.py")
    assert refs == 2, (
        f"guard_core.py is referenced {refs}x in home.nix; expected exactly 2 "
        f"(~/.claude/hooks/ for Claude Code, ~/.config/opencode/ for opencode)"
    )


def test_readme_is_honest_about_what_globs_guarantee():
    """🔴 The docs claim is a claim like any other. The old header asserted the
    patterns were airtight ("EVERY DANGEROUS PATTERN IS LEADING-`*` … catches
    all four spellings"), which is what made two rounds of pattern-patching feel
    like a fix. It must now say plainly that globs are friction."""
    header = (OC_DIR / "opencode.jsonc").read_text()
    assert "FRICTION" in header and "ENFORCEMENT" in header
    assert "guard_core.py" in header
    readme = (OC_DIR / "README.md").read_text()
    assert "Two layers, and only one of them is a safety control" in readme
    assert "tool.execute.before" in readme and "permission.ask" in readme


def test_readme_documents_the_one_time_command():
    readme = (OC_DIR / "README.md").read_text()
    assert "opencode.jsonc" in readme
    assert "mv ~/.config/opencode/opencode.jsonc" in readme
