"""Tests for the claude-source tailer (scripts/collector/claude/tailer.py).

Covers:
  * extraction / noise-filtering (typed vs slash-command vs synthetic noise,
    content-as-list blocks, unicode/multiline/quotes survival),
  * idempotency (run twice → each message once; append → only the new one;
    state file round-trips),
  * emit-format correctness — the emitted spool lines parse back via the real
    collector's parse_line to the expected event dict.

No network. The real `emit` shell helper is invoked (writes to a temp spool),
and the real collector module is imported by sys.path like test_collector.py.
"""
import json
import os
import sys
from pathlib import Path

import pytest

# Import the tailer (this dir's parent) and the collector daemon (sibling dir),
# mirroring how scripts/collector/tests/test_collector.py imports collector.
_CLAUDE_DIR = Path(__file__).resolve().parent.parent          # scripts/collector/claude
_COLLECTOR_DIR = _CLAUDE_DIR.parent                            # scripts/collector
sys.path.insert(0, str(_CLAUDE_DIR))
sys.path.insert(0, str(_COLLECTOR_DIR))
import tailer as T      # noqa: E402
import collector as C   # noqa: E402

EMIT = _COLLECTOR_DIR / "emit"


# --------------------------------------------------------------------------- #
# Transcript fixture helpers
# --------------------------------------------------------------------------- #
def _user_line(text_or_blocks, *, uuid, ts="2026-06-24T01:25:00.759Z",
               cwd="/home/zach/workspace/devrc", branch="main",
               isMeta=False, isSidechain=False, role="user"):
    obj = {
        "type": "user",
        "uuid": uuid,
        "timestamp": ts,
        "cwd": cwd,
        "gitBranch": branch,
        "isMeta": isMeta,
        "isSidechain": isSidechain,
        "message": {"role": role, "content": text_or_blocks},
    }
    return json.dumps(obj)


def _write_transcript(projects_dir: Path, project_dirname: str, session: str, lines):
    d = projects_dir / project_dirname
    d.mkdir(parents=True, exist_ok=True)
    p = d / f"{session}.jsonl"
    p.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return p


# --------------------------------------------------------------------------- #
# Extraction / filtering
# --------------------------------------------------------------------------- #
def test_typed_message_extracted():
    assert T.classify("please refactor the parser") == ("typed", "please refactor the parser")


def test_slash_command_becomes_command_kind():
    raw = "<command-message>handoff is running…</command-message><command-name>handoff</command-name><command-args>now</command-args>"
    kind, text = T.classify(raw)
    assert kind == "command"
    assert text == "handoff now"


def test_system_reminder_filtered_out():
    raw = "<system-reminder>internal note that is fairly long and synthetic content</system-reminder>"
    assert T.classify(raw) is None


def test_local_command_stdout_stripped():
    raw = "<local-command-stdout>some tool output here padding padding</local-command-stdout>"
    assert T.classify(raw) is None


def test_boilerplate_prefixes_filtered():
    assert T.classify("[Request interrupted by user]") is None
    assert T.classify("Caveat: The messages below were generated by the user") is None
    assert T.classify("API Error: 500 overloaded") is None


def test_system_reminder_stripped_but_real_text_kept():
    raw = "<system-reminder>noise noise noise noise noise</system-reminder>\nreal question here"
    assert T.classify(raw) == ("typed", "real question here")


def test_content_as_list_blocks_handled():
    content = [
        {"type": "tool_result", "content": "ignored"},
        {"type": "text", "text": "first text block"},
        {"type": "image"},
        {"type": "text", "text": "second text block"},
    ]
    blocks = T.extract_blocks(content)
    assert blocks == ["first text block", "second text block"]


def test_unicode_multiline_quotes_survive():
    msg = 'héllo "wörld"\nline two\ttabbed — emoji 🚀 and \\backslash\\'
    kind, text = T.classify(msg)
    assert kind == "typed"
    assert text == msg.strip()


def test_isMeta_and_isSidechain_lines_skipped(tmp_path):
    projects = tmp_path / "projects"
    _write_transcript(projects, "-home-zach-workspace-devrc", "sess1", [
        _user_line("real typed message", uuid="u-real"),
        _user_line("meta junk", uuid="u-meta", isMeta=True),
        _user_line("sidechain subagent msg", uuid="u-side", isSidechain=True),
    ])
    evs = list(T.iter_messages([str(projects)]))
    texts = [e["text"] for e in evs]
    assert texts == ["real typed message"]


def test_subagents_dir_skipped(tmp_path):
    projects = tmp_path / "projects"
    _write_transcript(projects, "subagents", "sess1", [
        _user_line("agent transcript", uuid="u-1"),
    ])
    assert list(T.iter_messages([str(projects)])) == []


def test_event_mapping_fields(tmp_path):
    projects = tmp_path / "projects"
    _write_transcript(projects, "-home-zach-workspace-devrc", "abc123", [
        _user_line("hello", uuid="u-1", cwd="/home/zach/workspace/devrc", branch="feat/x"),
    ])
    ev = next(iter(T.iter_messages([str(projects)])))
    assert ev["source"] == "claude"
    assert ev["kind"] == "prompt"
    assert ev["project"] == "devrc"
    assert ev["session"] == "abc123"
    assert ev["app"] == "claude-code"
    assert ev["cwd"] == "/home/zach/workspace/devrc"
    assert ev["gitBranch"] == "feat/x"
    assert ev["ts"] is not None and ev["ts"][:4] == "2026"


def test_ts_conversion_to_ch_format():
    out = T.to_ch_ts("2026-06-24T01:25:00.759Z")
    # local-time string in CH DateTime64(3) format: 'YYYY-MM-DD HH:MM:SS.mmm'
    assert len(out) == len("2026-06-24 01:25:00.759")
    assert out[4] == "-" and out[10] == " " and out[19] == "."
    assert out.endswith(".759")


# --------------------------------------------------------------------------- #
# Idempotency
# --------------------------------------------------------------------------- #
@pytest.fixture
def env(tmp_path, monkeypatch):
    spool = tmp_path / "spool"
    spool.mkdir()
    state = tmp_path / "claude-state.json"
    projects = tmp_path / "projects"
    projects.mkdir()
    monkeypatch.setenv("ACTIVITY_SPOOL_DIR", str(spool))
    monkeypatch.setenv("CLAUDE_SOURCE_STATE", str(state))
    monkeypatch.setenv("CLAUDE_SOURCE_EMIT", str(EMIT))
    monkeypatch.setenv("CLAUDE_PROJECTS_DIR", str(projects))
    return {"spool": spool, "state": state, "projects": projects}


def _spool_events(spool: Path) -> list[dict]:
    cur = spool / "current.log"
    if not cur.exists():
        return []
    out = []
    for line in cur.read_text(encoding="utf-8").splitlines():
        ev = C.parse_line(line)
        if ev:
            out.append(ev)
    return out


def test_run_twice_emits_each_once(env):
    _write_transcript(env["projects"], "-home-zach-workspace-devrc", "s1", [
        _user_line("msg one", uuid="u-1"),
        _user_line("msg two", uuid="u-2"),
    ])
    assert T.run() == 0
    assert T.run() == 0  # second run must add nothing
    evs = _spool_events(env["spool"])
    assert len(evs) == 2
    assert sorted(e["text"] for e in evs) == ["msg one", "msg two"]


def test_append_new_message_emits_only_new(env):
    p = _write_transcript(env["projects"], "-home-zach-workspace-devrc", "s1", [
        _user_line("first", uuid="u-1"),
    ])
    T.run()
    assert len(_spool_events(env["spool"])) == 1
    # append a new message + re-run
    with p.open("a", encoding="utf-8") as f:
        f.write(_user_line("second", uuid="u-2") + "\n")
    T.run()
    evs = _spool_events(env["spool"])
    assert len(evs) == 2
    assert sorted(e["text"] for e in evs) == ["first", "second"]


def test_state_file_round_trips(env):
    _write_transcript(env["projects"], "-home-zach-workspace-devrc", "s1", [
        _user_line("hello", uuid="u-1"),
    ])
    T.run()
    seen = T.load_state(env["state"])
    assert "u-1" in seen
    # round-trip through save/load
    T.save_state(env["state"], seen | {"u-extra"})
    seen2 = T.load_state(env["state"])
    assert {"u-1", "u-extra"} <= seen2


def test_uuidless_line_deduped_by_content(env, monkeypatch):
    # Build a line with no uuid and confirm two runs emit it once.
    obj = {
        "type": "user", "timestamp": "2026-06-24T01:25:00.759Z",
        "cwd": "/home/zach/workspace/devrc", "gitBranch": "main",
        "message": {"role": "user", "content": "no uuid here"},
    }
    d = env["projects"] / "-home-zach-workspace-devrc"
    d.mkdir(parents=True, exist_ok=True)
    (d / "s1.jsonl").write_text(json.dumps(obj) + "\n", encoding="utf-8")
    T.run()
    T.run()
    assert len(_spool_events(env["spool"])) == 1


# --------------------------------------------------------------------------- #
# Emit-format correctness (round-trip through the real collector parser)
# --------------------------------------------------------------------------- #
def test_emitted_lines_parse_back_via_collector(env):
    _write_transcript(env["projects"], "-home-zach-workspace-devrc", "sess-xyz", [
        _user_line('typed "with quotes"\nand newline 🚀', uuid="u-typed",
                   cwd="/home/zach/workspace/devrc", branch="feat/claude-src"),
        _user_line(
            "<command-name>handoff</command-name><command-args>now</command-args>",
            uuid="u-cmd"),
    ])
    assert T.run() == 0
    evs = _spool_events(env["spool"])
    by_text = {e["text"]: e for e in evs}

    typed = by_text['typed "with quotes"\nand newline 🚀']
    assert typed["source"] == "claude"
    assert typed["kind"] == "prompt"
    assert typed["project"] == "devrc"
    assert typed["session"] == "sess-xyz"
    assert typed["app"] == "claude-code"
    payload = json.loads(typed["payload"])
    assert payload["gitBranch"] == "feat/claude-src"
    assert payload["role"] == "user"
    assert payload["claude_kind"] == "typed"

    cmd = by_text["handoff now"]
    assert cmd["kind"] == "command"
    assert json.loads(cmd["payload"])["claude_kind"] == "command"


def test_emitted_ts_is_message_time_not_now(env):
    _write_transcript(env["projects"], "-home-zach-workspace-devrc", "s1", [
        _user_line("old message", uuid="u-1", ts="2020-01-02T03:04:05.678Z"),
    ])
    T.run()
    ev = _spool_events(env["spool"])[0]
    # The ts reflects the (local-converted) message time, not the current run
    # time. Compare against the tailer's own conversion of the message stamp.
    assert ev["ts"] == T.to_ch_ts("2020-01-02T03:04:05.678Z")
    assert ev["ts"].startswith("2020-01-0")  # year 2020, not 2026 (run time)
