#!/usr/bin/env bash
# Read-only check: does this host ADVERTISE a nebula relay?
#
# `relay.relays` in a nebula config is the list of mesh IPs that PEERS MAY USE TO
# RELAY PACKETS TO THIS HOST. It is NOT the list of relays this host uses to reach
# others -- that distinction is why `use_relays: true` on its own changes nothing.
# An empty `relays: []` means no peer can relay here at all, so a peer that cannot
# hole-punch (CGNAT, symmetric NAT, off-LAN) simply never connects.
#
# On NixOS the list comes from `services.nebula.networks.<net>.settings.relay.relays`
# in /etc/nixos/configuration.nix. This script does NOT edit that file and does NOT
# rebuild -- it only reads the config the running unit actually loaded, so it needs
# no sudo and can be run before and after a change.
#
#   bash nix/system/check-nebula-relays.sh                  # expect the default relay
#   bash nix/system/check-nebula-relays.sh 10.42.0.7        # expect a specific one
#   NEBULA_NET=other bash nix/system/check-nebula-relays.sh # a network other than `mesh`
#   bash nix/system/check-nebula-relays.sh --self-test      # validate the parser only
#
# Exit: 0 = the expected relay is advertised · 1 = it is not · 2 = could not read the config
#
# 🔴 Do NOT verify this by grepping the rendered YAML for the relay's address. The
# lighthouse list (`lighthouse.hosts`) contains the SAME mesh addresses, so a pattern
# like `^\s+- 10\.42\.0\.2$` matches a config whose `relays:` is EMPTY -- measured; it
# reported a match on the pre-change file and would have certified a change that had
# not happened. Read the `relay.relays` key, which is what this script does.
set -euo pipefail

NET="${NEBULA_NET:-mesh}"
EXPECT="${1:-10.42.0.2}"          # prod lighthouse mesh IP; its public underlay is
                                  # deliberately NOT in this file -- see the header of
                                  # apply-nebula-443.sh, this repo is PUBLIC.

# --- the parser -------------------------------------------------------------------
# Stdlib only, on purpose: PyYAML is NOT importable from the python3 on the default
# PATH here, so a `import yaml` version of this cannot run as documented.
# Reads one top-level block key by indentation. The rendered nebula config is
# generated by the NixOS module (pkgs.formats.yaml), so it is always block style with
# 2-space indents and no anchors, flow maps or multi-line scalars in these keys.
_parse_relay() {  # $1 = rendered config path; prints "am_relay|use_relays|csv-of-relays"
  python3 - "$1" <<'PY'
import re, sys

text = open(sys.argv[1]).read().splitlines()
block, in_block = [], False
for line in text:
    if not line.strip() or line.lstrip().startswith("#"):
        continue
    if re.match(r"^relay:\s*$", line):
        in_block = True
        continue
    if in_block:
        if not line.startswith((" ", "\t")):   # next top-level key ends the block
            break
        block.append(line)

am = use = ""
relays, in_relays = [], False
for line in block:
    indent = len(line) - len(line.lstrip())
    s = line.strip()
    if in_relays:
        if s.startswith("- ") and indent >= 2:
            relays.append(s[2:].strip().strip("'\""))
            continue
        in_relays = False
    if s.startswith("am_relay:"):
        am = s.split(":", 1)[1].strip()
    elif s.startswith("use_relays:"):
        use = s.split(":", 1)[1].strip()
    elif s.startswith("relays:"):
        rest = s.split(":", 1)[1].strip()
        if rest in ("", "~", "null"):
            in_relays = True              # block-style list follows
        elif rest.startswith("["):        # flow style, incl. the empty `[]`
            relays += [x.strip().strip("'\"") for x in rest[1:-1].split(",") if x.strip()]

print("%s|%s|%s" % (am or "?", use or "?", ",".join(relays)))
PY
}

# --- self-test: prove the parser can say BOTH answers before trusting either -------
# A checker that cannot go red is not evidence, and one that has never gone green may
# simply be wired to nothing. Both fixtures are real rendered-config shapes: the
# lighthouse list carries the same addresses as the relay list, which is exactly the
# trap the header warns about.
_self_test() {
  local dir rc=0
  dir=$(mktemp -d)
  trap 'rm -rf "$dir"' RETURN

  cat >"$dir/empty.yml" <<'EOF'
lighthouse:
  am_lighthouse: false
  hosts:
  - 10.42.0.1
  - 10.42.0.2
relay:
  am_relay: false
  relays: []
  use_relays: true
static_host_map:
  10.42.0.2:
  - 198.51.100.7:4242
EOF
  cat >"$dir/set.yml" <<'EOF'
lighthouse:
  am_lighthouse: false
  hosts:
  - 10.42.0.1
  - 10.42.0.2
relay:
  am_relay: false
  relays:
  - 10.42.0.2
  use_relays: true
static_host_map:
  10.42.0.2:
  - 198.51.100.7:4242
EOF

  local got
  got=$(_parse_relay "$dir/empty.yml")
  if [ "$got" = "false|true|" ]; then
    echo "  [self-test] NEGATIVE control: empty relays read as empty      -> ok"
  else
    echo "  [self-test] NEGATIVE control FAILED: got '$got', want 'false|true|'"; rc=1
  fi

  got=$(_parse_relay "$dir/set.yml")
  if [ "$got" = "false|true|10.42.0.2" ]; then
    echo "  [self-test] POSITIVE control: one relay read back            -> ok"
  else
    echo "  [self-test] POSITIVE control FAILED: got '$got', want 'false|true|10.42.0.2'"; rc=1
  fi

  # The trap itself: the naive grep matches the EMPTY fixture, via lighthouse.hosts.
  if grep -qE '^[[:space:]]+- 10\.42\.0\.2$' "$dir/empty.yml"; then
    echo "  [self-test] the naive grep matches a config with relays: []  -> trap confirmed"
  else
    echo "  [self-test] the naive grep did NOT match the empty fixture; the warning in this file's header no longer describes reality"; rc=1
  fi
  return $rc
}

if [ "${1:-}" = "--self-test" ]; then
  echo "parser self-test:"
  _self_test
  exit $?
fi

# --- read the config the RUNNING unit actually loaded ------------------------------
unit="nebula@${NET}.service"
if ! unit_text=$(systemctl cat "$unit" 2>/dev/null); then
  echo "FAIL: cannot read $unit (not loaded on this host?)" >&2
  exit 2
fi
# `tail -1`, not `head -1`: systemctl cat prints the base unit first and drop-ins after,
# so the LAST ExecStart is the one that wins if a drop-in overrides it.
rendered=$(printf '%s\n' "$unit_text" | sed -n 's/^ExecStart=.*[[:space:]]-config[[:space:]]\{1,\}\([^[:space:]]\{1,\}\).*/\1/p' | tail -1)
if [ -z "$rendered" ] || [ ! -r "$rendered" ]; then
  echo "FAIL: could not resolve a readable rendered config from $unit (got '${rendered:-<empty>}')" >&2
  exit 2
fi

echo "unit    : $unit"
echo "rendered: $rendered"

echo "parser self-test:"
if ! _self_test; then
  echo "FAIL: the parser failed its own controls -- its verdict below would mean nothing" >&2
  exit 2
fi

IFS='|' read -r am use relays <<<"$(_parse_relay "$rendered")"
echo "relay   : am_relay=$am use_relays=$use relays=[${relays}]"

case ",${relays}," in
  *,"${EXPECT}",*)
    echo "PASS: this host advertises ${EXPECT} as a relay -- peers that cannot hole-punch can reach it"
    exit 0
    ;;
esac

if [ -z "$relays" ]; then
  echo "FAIL: relays is EMPTY -- NO peer can relay to this host."
else
  echo "FAIL: relays does not include ${EXPECT} (advertised: ${relays})."
fi
cat <<EOF

To fix, add this to services.nebula.networks.${NET}.settings in /etc/nixos/configuration.nix
(alongside the existing \`punchy = { ... };\`), then \`sudo nixos-rebuild switch\`:

      relay = {
        use_relays = true;
        relays = [ "${EXPECT}" ];
      };

Anything listed must carry \`am_relay: true\` in ITS own config, and this host must be
able to reach it. Re-run this script afterwards; it re-reads the unit, so a PASS means
the running service loaded the new value, not merely that the file was edited.
EOF
exit 1
