#!/usr/bin/env bash
# Read-only root-partition / inode breakdown, used when df disagrees with what you can
# measure. Sibling to scripts/diagnose-disk-accounting.sh; changes nothing.
#
#     bash scripts/diagnose-nix-disk.sh          # some sections need root for full data
#     sudo bash scripts/diagnose-nix-disk.sh
#
# 🔴 THIS IS SLOW — HOURS, NOT MINUTES, AND NOBODY HAS SEEN IT FINISH.
# Sections 3 and 4 each walk /nix recursively, and section 4 additionally stats every
# regular file; `df -i /` reports ~80M inodes in use on the workbench.
#
# What was actually MEASURED (2026-09-08, workbench): 4h05m wall clock, reaching only
# section 3 of 10. Two caveats that make that a FLOOR rather than the runtime:
# the box was running the test gate throughout and the process sat at 3% CPU
# (95s user + 452s system across four hours), i.e. I/O-starved; and the run was
# killed by an unrelated artefact, so it did not stop of its own accord.
#
# 🔴 So the honest state: NO CLEAN FULL RUN HAS EVER BEEN OBSERVED, and the final
# banner's "all 10 sections attempted" is untested end to end. Do not quote a runtime
# from this header as if it were measured — replace this paragraph with a real number
# once someone completes a run on an idle box.
#
# Each section pipes through `sort`, which buffers, so NOTHING prints between the start
# of a walk and its end — a run that looks hung is normal. Start it in a background
# shell or under tmux; do not wait on it interactively.
#
# ⚠ And do not EDIT this file while a copy of it is running: bash reads a script by
# byte offset as it executes, so an edit mid-run shifts the file underneath the
# interpreter and produces a syntax error on a line that is fine on disk. That is what
# ended the 4h05m run, and it looked exactly like a defect in the script.
#
# 🔴 NO `set -e`, ON PURPOSE. Nearly every command here is allowed to fail: `find`
# exits non-zero on a permission-denied entry, `lsof` is not installed on either host,
# and a device or path may not exist. Under `set -euo pipefail` this script aborted at
# section 3 of 10 as an ordinary user and section 2 on the laptop — printing NOTHING
# about why, because `set -e` is silent and the stderr was already discarded. For a
# diagnostic, a section that says "(unavailable)" is worth more than a clean exit that
# skipped eight of them.
set -uo pipefail

# The root device is DERIVED, never hardcoded: it is nvme0n1p2 on the workbench and
# nvme0n1p1 on the laptop, and a frozen literal silently reports the wrong device.
ROOT_DEV="$(findmnt -no SOURCE / 2>/dev/null || echo unknown)"
ROOT_FS="$(findmnt -no FSTYPE / 2>/dev/null || echo unknown)"
ROOT_SIZE="$(df -h --output=size / 2>/dev/null | tail -1 | tr -d ' ')"
ROOT_USED="$(df -h --output=used / 2>/dev/null | tail -1 | tr -d ' ')"

have() { command -v "$1" >/dev/null 2>&1; }
skip() { echo "  (unavailable: $*)"; }

# Under `sudo` with env_reset (the default, and NixOS does not build sudo with
# --with-always-set-home), HOME is the TARGET user's — i.e. /root — so a bare $HOME
# would make section 8 walk root's home and print almost nothing. SUDO_USER names who
# actually invoked us; fall back to HOME when not under sudo.
HOME_SOURCE="\$HOME"
if [ -n "${SUDO_USER:-}" ]; then
  resolved="$(getent passwd "$SUDO_USER" 2>/dev/null | cut -d: -f6)"
  # Gate the attribution on the RESOLUTION, not on SUDO_USER being set: an unresolvable
  # user fell back to $HOME while the line claimed it had used SUDO_USER.
  if [ -n "$resolved" ]; then
    TARGET_HOME="$resolved"
    HOME_SOURCE="SUDO_USER=$SUDO_USER"
  else
    HOME_SOURCE="\$HOME (SUDO_USER=$SUDO_USER did not resolve)"
  fi
fi
TARGET_HOME="${TARGET_HOME:-$HOME}"

echo "============================================"
echo "  NixOS Root Partition Diagnosis"
echo "  ${ROOT_DEV}  (${ROOT_FS}, ${ROOT_SIZE:-?} total, ${ROOT_USED:-?} used)"
echo "  $(hostname)  $(date -Is)"
echo "============================================"
echo ""

# 1. Filesystem block stats
echo "=== 1. Filesystem block stats ==="
echo "--- df ---"
df -hT /
echo ""
echo "--- stat -f ---"
stat -f /
echo ""

# 2. dumpe2fs summary (block groups, free blocks, journal)
echo "=== 2. dumpe2fs summary ==="
if ! have dumpe2fs; then
  skip "dumpe2fs not on PATH"
elif [ "$ROOT_FS" != "ext2" ] && [ "$ROOT_FS" != "ext3" ] && [ "$ROOT_FS" != "ext4" ]; then
  skip "root is $ROOT_FS, not ext*"
else
  dumpe2fs -h "$ROOT_DEV" 2>/dev/null \
    | grep -iE 'Block count|Free blocks|Inode count|Free inodes|Journal|Reserved|Filesystem features|Mount count|Last checked|State' \
    || skip "dumpe2fs failed on $ROOT_DEV (needs root?)"
fi
echo ""

# 3. Inode usage per top-level dir
echo "=== 3. Inode count per top-level directory ==="
echo "  (walking /nix and friends — several minutes, no output until it completes)"
for d in /nix /home /var /tmp /etc /usr /root /srv /opt /boot /mnt /run; do
  if [ -d "$d" ]; then
    count=$(find "$d" 2>/dev/null | wc -l)
    printf "%12d  %s\n" "$count" "$d"
  fi
done | sort -rn
if [ "$(id -u)" != "0" ]; then
  echo "  (counts are a FLOOR: as non-root, find skips unreadable dirs)"
fi
echo ""

# 4. Actual file sizes per top-level dir (apparent size)
echo "=== 4. Apparent file size per top-level directory ==="
echo "  (a second full walk, statting every file — slower than section 3)"
for d in /nix /home /var /tmp /etc /usr /root /srv /opt /boot /mnt; do
  if [ -d "$d" ]; then
    size=$(find "$d" -type f -printf '%s\n' 2>/dev/null | awk '{s+=$1} END {printf "%.1f", s/1073741824}')
    printf "%8sGB  %s\n" "${size:-0.0}" "$d"
  fi
done | sort -rn
echo ""

# 5. Check for deleted-but-referenced files
echo "=== 5. Deleted files still holding space ==="
if have lsof; then
  lsof +L1 2>/dev/null | head -20
  # -1 for lsof's own header row; clamp so an empty result reads 0, not -1.
  n=$(lsof +L1 2>/dev/null | wc -l)
  echo "Count: $(( n > 0 ? n - 1 : 0 ))"
else
  skip "lsof not installed — try: nix-shell -p lsof --run 'lsof +L1'"
fi
echo ""

# 6. Ext4 journal
echo "=== 6. Ext4 journal ==="
ls -lh /proc/1/root/.journal 2>/dev/null || echo "  No journal file at /proc/1/root/.journal"
if have dumpe2fs; then
  dumpe2fs -h "$ROOT_DEV" 2>/dev/null | grep -i journal || skip "dumpe2fs failed on $ROOT_DEV"
else
  skip "dumpe2fs not on PATH"
fi
echo ""

# 7. Nix store breakdown
echo "=== 7. Nix store breakdown ==="
if [ -d /nix/store ]; then
  echo "Top-level entries:"
  ls /nix/store/ 2>/dev/null | wc -l
  echo "  Directories: $(ls -d /nix/store/*/ 2>/dev/null | wc -l)"
  echo "  Files:       $(ls -l /nix/store/ 2>/dev/null | grep -c '^-')"
  echo "  Symlinks:    $(ls -l /nix/store/ 2>/dev/null | grep -c '^l')"
  echo ""
  echo ".links unique data:"
  du -sh /nix/store/.links 2>/dev/null || skip "cannot read /nix/store/.links (needs root)"
  echo "Files in .links:"
  find /nix/store/.links -type f 2>/dev/null | wc -l
else
  skip "no /nix/store on this host"
fi
echo ""

# 8. /home breakdown
echo "=== 8. home breakdown ==="
echo "  (home: ${TARGET_HOME}  — from ${HOME_SOURCE})"
found8=0
for d in "$TARGET_HOME"/.local/share/Steam "$TARGET_HOME"/.ollama "$TARGET_HOME"/.cache \
         "$TARGET_HOME"/.config "$TARGET_HOME"/workspace "$TARGET_HOME"/go \
         "$TARGET_HOME"/Downloads "$TARGET_HOME"/hetzner-volumes; do
  if [ -d "$d" ]; then
    size=$(du -sh "$d" 2>/dev/null | awk '{print $1}')
    printf "%8s  %s\n" "${size:-?}" "$d"
    found8=1
  fi
done
# Section 8 was the one section with no fallback, so a wrong home read as an empty
# section rather than as a reason — the exact failure the rest of this script avoids.
[ "$found8" = "1" ] || skip "none of the expected directories exist under ${TARGET_HOME}"
echo ""

# 9. Swapfile
echo "=== 9. Swap ==="
swapon --show 2>/dev/null || skip "swapon failed"
ls -lh /swapfile 2>/dev/null || echo "  (no /swapfile on this host)"
echo ""

# 10. Reserved blocks
echo "=== 10. Reserved blocks for root ==="
if have tune2fs; then
  tune2fs -l "$ROOT_DEV" 2>/dev/null | grep -i 'reserved' || skip "tune2fs failed on $ROOT_DEV (needs root?)"
else
  skip "tune2fs not on PATH"
fi
echo ""

echo "============================================"
echo "  Done — all 10 sections attempted."
echo "============================================"
