#!/usr/bin/env bash
#
# install-session-stamp.sh — install the prepare-commit-msg session-id stamper
# into ONE repo's common .git/hooks/.
#
# DRY-RUN BY DEFAULT. Prints what it would do and changes nothing unless
# --apply is passed — the same operator-act shape as scripts/sync-skill-tiers.py,
# and for the same reason: this modifies a developer's git behaviour, so arming
# it is a decision, not a side effect of merging a PR.
#
# 🔴 THE HOOK LIVES IN scripts/git-hooks/, NOT githooks/. `githooks/install.sh`
# points core.hooksPath GLOBALLY at `githooks/`, so a file placed there is armed
# on every repo on the box for anyone who has ever run that installer — which
# would make "merging this activates nothing" false. It would also drag the
# devrc pre-push TEST GATE along (devrc#322, where a pre-push hook running the
# suite rewrote the branch it was pushing). This installer touches exactly one
# file in one repo and never writes git config at all.
#
# 🔴 ONE INSTALL COVERS EVERY WORKTREE. Hooks live in the COMMON git dir, which
# every `git worktree add` of a clone shares.
set -euo pipefail

# shellcheck disable=SC1007
DIR="$(CDPATH= cd -P -- "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CHECKOUT="$(dirname "$DIR")"

usage() {
  cat <<'USAGE'
usage: install-session-stamp.sh [--repo <path>] [--source <devrc-checkout>]
                                [--apply|--uninstall] [--force]

  --repo <path>     repo to install into (default: this script's own checkout)
  --source <path>   devrc checkout the hook is symlinked FROM
                    (default: this script's own checkout — see the worktree note)
  --apply           actually install (default is dry-run)
  --uninstall       remove a previously installed hook
  --force           replace an existing FOREIGN prepare-commit-msg hook

Exit codes:
  0  ok (or dry-run completed)
  2  bad usage
  3  target is not a git repo
  4  a foreign prepare-commit-msg exists and --force was not given
  5  core.hooksPath is set, so an install into .git/hooks would be INERT
USAGE
}

die_usage() { echo "$1" >&2; usage >&2; exit 2; }

REPO=""
SOURCE_ROOT=""
MODE="dry"
FORCE=0
_repairing=0

while [ $# -gt 0 ]; do
  case "$1" in
    --repo)   [ $# -ge 2 ] || die_usage "--repo needs a path";   REPO="$2"; shift 2 ;;
    --source) [ $# -ge 2 ] || die_usage "--source needs a path"; SOURCE_ROOT="$2"; shift 2 ;;
    --apply) MODE="apply"; shift ;;
    --uninstall) MODE="uninstall"; shift ;;
    --force) FORCE=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) die_usage "unknown argument: $1" ;;
  esac
done

REPO="${REPO:-$CHECKOUT}"
SOURCE_ROOT="${SOURCE_ROOT:-$CHECKOUT}"

if ! COMMON="$(git -C "$REPO" rev-parse --path-format=absolute --git-common-dir 2>/dev/null)"; then
  echo "install-session-stamp: not a git repo: $REPO" >&2
  exit 3
fi

HOOKS="$COMMON/hooks"
TARGET="$HOOKS/prepare-commit-msg"
IMPL="$SOURCE_ROOT/scripts/git-hooks/prepare_commit_msg.py"
# Identifies a hook THIS script generated, so uninstall and the foreign-hook
# refusal can tell devrc's own from somebody else's. A generated file has no
# symlink target to compare, so the marker is the ownership test.
MARKER="Generated by devrc scripts/install-session-stamp.sh"

echo "install-session-stamp:"
echo "  repo:    $REPO"
echo "  common:  $COMMON"
echo "  target:  $TARGET"
echo "  impl:    $IMPL"

if [ ! -r "$IMPL" ]; then
  echo "  ✘ the hook implementation does not exist: $IMPL" >&2
  exit 3
fi

# 🔴 THE SYMLINK TARGET OUTLIVES THIS PROCESS, so warn when it points into an
# EPHEMERAL worktree. There are ~115 agent worktrees on this box; installing
# from one bakes its path into the link, and when that worktree is removed the
# link dangles. Git skips a dangling hook (the commit is still safe) but the
# feature is silently dead — and a later re-install from the base clone then
# refuses, calling devrc's own dangling link "a FOREIGN hook".
if [ -f "$SOURCE_ROOT/.git" ]; then
  echo "  ⚠ --source is a LINKED WORKTREE ($SOURCE_ROOT)."
  echo "    The install symlink would point into it and dangle when it is removed."
  echo "    Prefer:  --source <the base clone>"
fi

# 🔴 READ THE EFFECTIVE VALUE, NOT --local AND --global. `git config --global`
# reads ~/.gitconfig ONLY; a core.hooksPath in ~/.config/git/config (XDG), in
# --system, or via GIT_CONFIG_GLOBAL is invisible to it — so the earlier
# two-scope check printed "unset ✓" while a real value was in force. Asking the
# repo for the effective value is the one read that cannot miss a scope.
EFFECTIVE_HOOKSPATH="$(git -C "$REPO" config --get core.hooksPath || true)"
if [ -n "$EFFECTIVE_HOOKSPATH" ]; then
  echo "  ✘ core.hooksPath is SET to '$EFFECTIVE_HOOKSPATH'."
  echo "    git reads hooks from THERE, not from $HOOKS — this install would be INERT."
  echo "    Unset it, or install into that directory instead."
  # 🔴 Refuse rather than print INSTALLED on a dead install. The previous version
  # printed the warning and then "INSTALLED ... rc=0", so an operator reading the
  # last line or the exit code got a green on a hook that would never run.
  [ "$MODE" = "uninstall" ] || exit 5
else
  echo "  core.hooksPath: unset (git will read $HOOKS) ✓"
fi

# 🔴 ANCHORED, AND TWO LINES, NOT A LOOSE grep.
# An unanchored `grep -q "$MARKER"` matched any hook that merely MENTIONS the
# marker — measured: someone who based their own prepare-commit-msg on devrc's
# generated wrapper (and kept the comment) had it DELETED by `--uninstall`.
# Requiring the marker at the start of its own line AND an `impl=` line makes
# "ours" a claim about structure rather than about a substring anyone can quote.
is_ours() {
  [ -f "$1" ] || return 1
  grep -q "^# $MARKER" "$1" 2>/dev/null || return 1
  grep -q '^impl=' "$1" 2>/dev/null
}

# 🔴 OURS AND INTACT ARE DIFFERENT QUESTIONS, and conflating them stranded the
# repo. A hook TRUNCATED mid-write still carries the marker and the `impl=` line,
# so the already-installed check matched it, printed "already installed ✓" and
# exited 0 — leaving an executable, syntactically invalid hook that refuses every
# commit, and no path back short of `rm`. The generated wrapper ends with a
# sentinel; its absence means the file was cut short.
END_MARKER="# devrc-session-stamp: end"
is_intact() { [ -f "$1" ] && grep -q "^$END_MARKER\$" "$1" 2>/dev/null; }

# 🔴 THE DISCRIMINATOR IS A BYTE-EXACT PREFIX, NOT A SHELL'S OPINION.
#
# "Is this devrc's own hook, cut short?" has an exact answer: a partially-written
# copy of what THIS run would generate is a byte-exact PREFIX of it, and shorter.
# A hook someone DERIVED from ours is not — it diverges at the first line they
# changed (measured: line 2).
#
# The two proxies this replaces were both wrong, in OPPOSITE directions:
#   * a missing END SENTINEL called a valid, commit-serving derived hook
#     "broken", and it was destroyed with no --force;
#   * `sh -n` asks whatever `sh` is first on PATH, which is NOT the shell git
#     runs the hook under. Measured on this host they are different binaries;
#     with dash on PATH a working hook using bash syntax is declared broken and
#     overwritten. And an ABSENT `sh` exits 127, `2>/dev/null` hides it, and `!`
#     turns "I could not check" into "it is broken" — the instrument's own
#     absence reading as a positive verdict, with an in-place `mv -f` and no
#     backup behind it.
#
# Comparing bytes asks no shell anything and cannot be fooled in either
# direction. It is also the exact question: only a partial write of OUR OWN
# output can be a prefix of it.
is_truncated_ours() {           # $1 = existing hook, $2 = freshly generated
  [ -f "$1" ] && [ -f "$2" ] || return 1
  local _have _want
  _have=$(wc -c < "$1") || return 1
  _want=$(wc -c < "$2") || return 1
  [ "$_have" -lt "$_want" ] || return 1     # equal-or-longer is not "cut short"
  cmp -s -n "$_have" "$1" "$2" || return 1  # …and every byte it has must match
  # 🔴 …and it must have got far enough to carry our marker. Without this, a
  # bare `#!/bin/sh` hook — someone's deliberate no-op — is a byte-exact prefix
  # of our output and would be silently replaced with a working stamper.
  grep -q "^# $MARKER" "$1" 2>/dev/null
}

generate_wrapper() {            # $1 = destination path
{
  printf '#!/bin/sh\n'
  printf '# Generated by devrc scripts/install-session-stamp.sh — do not edit.\n'
  printf '# Stamps the resumable session id onto an agent'"'"'s commit.\n'
  printf '#\n'
  printf '# EVERY EXIT IS 0. A prepare-commit-msg hook exit status decides whether\n'
  printf '# the commit happens; a missing interpreter must be a no-op, never a refusal.\n'
  printf '#\n'
  printf '# The `command -v python3` test below is an EQUIVALENT MUTANT: deleting it\n'
  printf '# does not fail the suite, because the trailing `exit 0` already swallows a\n'
  printf '# missing interpreter. Measured both ways — mutating the guard away leaves\n'
  printf '# every interpreter test green; mutating the trailing `exit 0` away kills one\n'
  printf '# immediately. The `exit 0` is the load-bearing half and has its own test.\n'
  printf '# The guard is kept only to avoid a spurious "command not found" on the\n'
  printf '# terminal and a pointless fork per commit. Do not read it as the thing that\n'
  printf '# makes this hook fail-open.\n'
  printf 'impl=%s\n' "$(printf '%q' "$IMPL")"
  cat <<'WRAPPER'
[ -r "$impl" ] || exit 0
if [ -n "$DEVRC_SESSION_TRAILER_PYTHON" ] && [ -x "$DEVRC_SESSION_TRAILER_PYTHON" ]; then
    py="$DEVRC_SESSION_TRAILER_PYTHON"
elif command -v python3 >/dev/null 2>&1; then
    py=python3
else
    exit 0
fi
"$py" "$impl" "$@" 2>/dev/null
exit 0
# devrc-session-stamp: end
WRAPPER
} > "$1"
}

# ⚠ THERE IS DELIBERATELY NO LEGACY-SYMLINK MIGRATION, and a previous revision's
# attempt at one was REMOVED as a net negative.
#
# It matched a symlink whose target ended `/scripts/git-hooks/prepare-commit-msg`
# — a path devrc has never installed. Verified three ways: the only revision that
# ever created a symlink here (`9164486e`) pointed at `githooks/prepare-commit-msg`;
# `git log --all --diff-filter=A` shows `scripts/git-hooks/prepare-commit-msg` was
# never added in ANY ref; and that revision is not an ancestor of `main`, so it
# reached no host. The branch was therefore inert for its stated purpose while
# being a live false-positive surface — measured, it happily `UNINSTALLED` a
# symlink belonging to an unrelated tool that merely shared the suffix. That is
# the same "deletes something that is not ours" class this installer had just
# fixed on the regular-file side, re-opened one axis narrower.
#
# Its test was a SPELLED guard too: it symlinked to the matcher's own string, so
# it could only ever agree with the matcher and could not notice the shape being
# wrong.
#
# If a real legacy state is ever found in the wild, add the migration THEN, keyed
# to the path that was actually installed.

# 🔴 THE SCRATCH FILE LIVES IN $TMPDIR, NOT IN .git/hooks, AND IS MADE AFTER THE
# UNINSTALL BRANCH. Generating it into the hooks directory made this script WRITE
# on paths that promise not to: the dry run created `.git/hooks` when it did not
# exist (falsifying this file's own "changes nothing unless --apply" header), and
# with the hooks dir mode 500 both the dry run and `--uninstall` aborted rc 1 —
# a code absent from the exit table above, and byte-for-byte the class already
# recorded further down as a past defect. `--uninstall` never needed the bytes at
# all.
_tmp="$(mktemp "${TMPDIR:-/tmp}/devrc-session-stamp.XXXXXX")"
cleanup_tmp() { rm -f "$_tmp"; }
trap cleanup_tmp EXIT

if [ "$MODE" = "uninstall" ]; then
  if is_ours "$TARGET"; then
    rm -f "$TARGET"; echo "  UNINSTALLED"
  else
    echo "  nothing to uninstall (no devrc-managed hook at that path)"
  fi
  exit 0
fi

generate_wrapper "$_tmp"

# 🔴 CHECKED BEFORE `is_ours`, AND THAT ORDER IS LOAD-BEARING. `is_ours` requires
# an `^impl=` line, which is line 16 of the 27 this script writes — so a partial
# write that stopped earlier is NOT "ours" by that test, and 15 of the 26 cut
# points never reached the prefix check at all (measured: cuts 1-15 refused with
# rc 4, cuts 16+ repaired). Being a byte-exact prefix of our own output is
# stronger evidence of authorship than the marker is, so it is asked first.
if is_truncated_ours "$TARGET" "$_tmp"; then
  # 🔴 THE WORDING IS SCOPED TO WHAT THE BYTES ACTUALLY PROVE. A prefix shorter
  # than the `impl=` line (line 16 of 27) is CHECKOUT-INDEPENDENT — lines 1-15 are
  # identical whichever checkout generated them — so calling such a file "this
  # checkout's own hook" was false, and it was re-pointed at this checkout with no
  # --force while announcing the opposite. The repair is still right (a partial
  # write of our wrapper is dead either way, and refusing it leaves the operator
  # stuck), so the BEHAVIOUR stands and the CLAIM is narrowed to what is true.
  echo "  ⚠ a devrc-generated hook here is a PARTIAL WRITE — a byte-exact prefix"
  echo "    of what this run would install ($(wc -c < "$TARGET") of $(wc -c < "$_tmp") bytes)."
  echo "    Only a partial write of that output can be a prefix of it, so completing"
  echo "    it does not wait for --force."
  if ! grep -q "^impl=$(printf '%q' "$IMPL")\$" "$TARGET" 2>/dev/null; then
    echo "    NOTE: it stopped before its \`impl=\` line, so which checkout wrote it"
    echo "    is not recorded in the bytes. It will be completed against THIS one:"
    echo "      $IMPL"
  fi
  FORCE=1
  _repairing=1
fi

if [ -e "$TARGET" ] || [ -L "$TARGET" ]; then
  if [ "$_repairing" -ne 1 ] && is_ours "$TARGET"; then
    # 🔴 `|| true` IS LOAD-BEARING, NOT DEFENSIVE PADDING. Under `set -euo
    # pipefail`, a bare `grep … | sed` in this position KILLED the script when the
    # hook carried the marker but no `impl=` line: rc 1, no message, and — because
    # it fires before the DRY-RUN branch too — even the read-only default run
    # aborted. rc 1 is not in this script's exit-code table, and it made the
    # installer unable to replace the one hook state it most needed to repair.
    _existing="$(grep -m1 '^impl=' "$TARGET" 2>/dev/null || true)"
    if [ "$_existing" = "impl=$(printf '%q' "$IMPL")" ] && is_intact "$TARGET"; then
      echo "  already installed (generated wrapper -> this checkout) ✓"
      exit 0
    fi
    # ⚠ 28 LINES OF PROSE HERE DESCRIBED A CONDITION THAT NO LONGER EXISTS, and
    # asserted the opposite of what this file now does — a maintainer reading it
    # could reasonably have deleted the wrong thing. It documented the `is_ours`
    # + missing-sentinel + `sh -n` triple, all three of which were replaced by the
    # byte-exact prefix test above (see its own comment for why each was wrong).
    # The history is kept there, at the code that carries it, rather than here.
    # 🔴 GUARDED BY `_repairing`, not a fall-through. (An earlier comment here
    # said "`elif`" — there is no elif; the mechanism is the flag set above and
    # read below. Behaviourally the same, but an auditor grepping for `elif` to
    # confirm this landed finds nothing.) The repair branch above used to fall
    # straight into this one, so a single run printed three mutually
    # contradictory lines: "repairing", then "points at another checkout"
    # naming THIS checkout's own path, then "Re-point it with --force" —
    # followed by doing it without --force. It also made the dangerous case
    # log-indistinguishable from the benign one.
    #
    # OUR hook, pointing at a DIFFERENT checkout — typically installed from an
    # agent worktree that has since been removed, leaving the impl path dangling.
    # Say so, rather than calling devrc's own hook foreign and demanding --force
    # for what is really a re-point.
    # 🔴 `if`, not `[ … ] && echo`. Under `set -euo pipefail` a trailing
    # `&&` whose left side is false makes the whole statement the script's
    # last status and EXITS — re-creating the rc-1 abort this installer was
    # just fixed for. `is_ours` currently guarantees `_existing` is non-empty,
    # so the branch is unreachable today; it is written safely anyway because
    # "unreachable" is a property of another function that may be relaxed.
    if [ "${_repairing:-0}" -ne 1 ]; then
      echo "  ⚠ an EXISTING devrc hook points at another checkout:"
      if [ -n "$_existing" ]; then echo "      $_existing"; fi
      echo "    Re-point it with --force; this is devrc's own hook, not a foreign one."
    fi
  fi
  if [ "$FORCE" -ne 1 ]; then
    echo "  ✘ a prepare-commit-msg already exists and is not ours. Look at it first:" >&2
    echo "      $TARGET" >&2
    echo "    Re-run with --force to replace it." >&2
    exit 4
  fi
fi

if [ "$MODE" = "dry" ]; then
  echo "  DRY-RUN — would generate $TARGET, calling $IMPL"
  echo "  re-run with --apply to install"
  exit 0
fi

mkdir -p "$HOOKS"

# 🔴 THE WRAPPER IS GENERATED HERE RATHER THAN SHIPPED, and the reason is
# devrc#1083's 🟡-9: a shipped file has to be SYMLINKED into .git/hooks, and this
# box runs ~115 ephemeral agent worktrees. Installing from one baked THAT
# worktree's path into the link; when the worktree was removed the link dangled,
# git silently skipped the hook (commits stayed safe, the feature was dead), and
# a later re-install from the base clone REFUSED, calling devrc's own dangling
# link "a FOREIGN prepare-commit-msg". A generated wrapper names the Python half
# by absolute path, so edits to the LOGIC still apply with no re-install — only
# this 12-line shim is frozen.
#
# ⚠ A RETRACTED DIAGNOSIS LIVED HERE, and is written down so it is not
# re-derived. An earlier revision claimed this file had to be generated because
# shipping it as an executable `#!/bin/sh` under `scripts/` made the nix-sandbox
# gate tier fail, blaming nixpkgs' `patchShebangs`. That was WRONG. The real
# cause was the BUILD INVOCATION: `nix build path:<a git WORKTREE>` copies the
# worktree's `.git` — which is a FILE reading `gitdir: …/worktrees/<name>`, not a
# directory — into the sandbox, so `src` looks like a repository whose gitdir is
# unreachable and every `git` call there dies on repo discovery. That is what
# tripped GUARD 10's `git config --global` preflight, before any test ran.
# Reproduced directly:
#
#     $ printf 'gitdir: /nonexistent/worktrees/x\n' > $D/.git
#     $ GIT_CONFIG_GLOBAL=$D/gc git -C $D config --global probe.k v
#     fatal: not a git repository: (null)
#
# The bisect that "proved" the shebang theory was CONFOUNDED: every bisect copy
# was a `cp -a` with `.git` removed (per the worktree-copy rule in RULES.md), so
# each one silently varied `.git` presence as well as the file under test. Build
# the sandbox tier from a real CLONE, never from a worktree.
# 🔴 QUOTED HEREDOC + %q, BECAUSE THE UNQUOTED ONE WAS A SHELL INJECTION.
# `$SOURCE_ROOT` used to be interpolated raw into an unquoted heredoc. An
# operator-supplied `--source` containing a double quote or a backtick therefore
# emitted shell that RAN ON EVERY `git commit` (both verified by creating a
# marker file), and one containing `$` expanded at hook time to a path that did
# not exist, silently killing the feature. `<<'WRAPPER'` makes the body literal;
# the single interpolated value is emitted separately through `printf %q`, which
# is what makes an arbitrary path safe to embed.
#
# 🔴 AND IT IS WRITTEN ATOMICALLY, for the same reason the message write is.
# `cat > "$TARGET"` truncates on open: a re-install (`--force`, which this script
# itself recommends) that failed mid-write left an executable, syntactically
# INVALID /bin/sh hook — measured, `git commit` rc=1 with the commit refused,
# i.e. this installer could re-create the exact defect the wrapper exists to fix.

chmod +x "$_tmp"
mv -f "$_tmp" "$TARGET"
trap - EXIT
chmod +x "$SOURCE_ROOT/scripts/git-hooks/prepare_commit_msg.py" 2>/dev/null || true
echo "  INSTALLED (generated wrapper -> $SOURCE_ROOT/scripts/git-hooks/prepare_commit_msg.py)"
echo "  edits to the Python half apply with no re-install; the shim itself is frozen"
echo
echo "  🔴 THAT IS ONLY THE GIT HALF. Nothing is stamped until the RECORDING half"
echo "     is registered as a PreToolUse hook in ~/.claude/settings.json, which is"
echo "     per-host and unmanaged by design. Add:"
echo
cat <<'SNIPPET'
       {
         "hooks": {
           "PreToolUse": [
             {
               "matcher": "Bash",
               "hooks": [
                 { "type": "command",
                   "command": "python3 ~/.claude/hooks/session-stamp.py" }
               ]
             }
           ]
         }
       }
SNIPPET
echo
echo "     Then verify end to end: make a commit from an agent session and check"
echo "     'git log -1 --format=%B' carries a Claude-Session-Id: line."
