#!/usr/bin/env bash
#
# install-session-stamp.sh — install the prepare-commit-msg session-id stamper
# into ONE repo's common .git/hooks/.
#
# DRY-RUN BY DEFAULT. Prints what it would do and changes nothing unless
# --apply is passed — the same operator-act shape as scripts/sync-skill-tiers.py,
# and for the same reason: this modifies a developer's git behaviour, so arming
# it is a decision, not a side effect of merging a PR.
#
# 🔴 THE HOOK LIVES IN scripts/git-hooks/, NOT githooks/. `githooks/install.sh`
# points core.hooksPath GLOBALLY at `githooks/`, so a file placed there is armed
# on every repo on the box for anyone who has ever run that installer — which
# would make "merging this activates nothing" false. It would also drag the
# devrc pre-push TEST GATE along (devrc#322, where a pre-push hook running the
# suite rewrote the branch it was pushing). This installer touches exactly one
# file in one repo and never writes git config at all.
#
# 🔴 ONE INSTALL COVERS EVERY WORKTREE. Hooks live in the COMMON git dir, which
# every `git worktree add` of a clone shares.
set -euo pipefail

# shellcheck disable=SC1007
DIR="$(CDPATH= cd -P -- "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CHECKOUT="$(dirname "$DIR")"

usage() {
  cat <<'USAGE'
usage: install-session-stamp.sh [--repo <path>] [--source <devrc-checkout>]
                                [--apply|--uninstall] [--force]

  --repo <path>     repo to install into (default: this script's own checkout)
  --source <path>   devrc checkout the hook is symlinked FROM
                    (default: this script's own checkout — see the worktree note)
  --apply           actually install (default is dry-run)
  --uninstall       remove a previously installed hook
  --force           replace an existing FOREIGN prepare-commit-msg hook

Exit codes:
  0  ok (or dry-run completed)
  2  bad usage
  3  target is not a git repo
  4  a foreign prepare-commit-msg exists and --force was not given
  5  core.hooksPath is set, so an install into .git/hooks would be INERT
USAGE
}

die_usage() { echo "$1" >&2; usage >&2; exit 2; }

REPO=""
SOURCE_ROOT=""
MODE="dry"
FORCE=0

while [ $# -gt 0 ]; do
  case "$1" in
    --repo)   [ $# -ge 2 ] || die_usage "--repo needs a path";   REPO="$2"; shift 2 ;;
    --source) [ $# -ge 2 ] || die_usage "--source needs a path"; SOURCE_ROOT="$2"; shift 2 ;;
    --apply) MODE="apply"; shift ;;
    --uninstall) MODE="uninstall"; shift ;;
    --force) FORCE=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) die_usage "unknown argument: $1" ;;
  esac
done

REPO="${REPO:-$CHECKOUT}"
SOURCE_ROOT="${SOURCE_ROOT:-$CHECKOUT}"

if ! COMMON="$(git -C "$REPO" rev-parse --path-format=absolute --git-common-dir 2>/dev/null)"; then
  echo "install-session-stamp: not a git repo: $REPO" >&2
  exit 3
fi

HOOKS="$COMMON/hooks"
TARGET="$HOOKS/prepare-commit-msg"
IMPL="$SOURCE_ROOT/scripts/git-hooks/prepare_commit_msg.py"
# Identifies a hook THIS script generated, so uninstall and the foreign-hook
# refusal can tell devrc's own from somebody else's. A generated file has no
# symlink target to compare, so the marker is the ownership test.
MARKER="Generated by devrc scripts/install-session-stamp.sh"

echo "install-session-stamp:"
echo "  repo:    $REPO"
echo "  common:  $COMMON"
echo "  target:  $TARGET"
echo "  impl:    $IMPL"

if [ ! -r "$IMPL" ]; then
  echo "  ✘ the hook implementation does not exist: $IMPL" >&2
  exit 3
fi

# 🔴 THE SYMLINK TARGET OUTLIVES THIS PROCESS, so warn when it points into an
# EPHEMERAL worktree. There are ~115 agent worktrees on this box; installing
# from one bakes its path into the link, and when that worktree is removed the
# link dangles. Git skips a dangling hook (the commit is still safe) but the
# feature is silently dead — and a later re-install from the base clone then
# refuses, calling devrc's own dangling link "a FOREIGN hook".
if [ -f "$SOURCE_ROOT/.git" ]; then
  echo "  ⚠ --source is a LINKED WORKTREE ($SOURCE_ROOT)."
  echo "    The install symlink would point into it and dangle when it is removed."
  echo "    Prefer:  --source <the base clone>"
fi

# 🔴 READ THE EFFECTIVE VALUE, NOT --local AND --global. `git config --global`
# reads ~/.gitconfig ONLY; a core.hooksPath in ~/.config/git/config (XDG), in
# --system, or via GIT_CONFIG_GLOBAL is invisible to it — so the earlier
# two-scope check printed "unset ✓" while a real value was in force. Asking the
# repo for the effective value is the one read that cannot miss a scope.
EFFECTIVE_HOOKSPATH="$(git -C "$REPO" config --get core.hooksPath || true)"
if [ -n "$EFFECTIVE_HOOKSPATH" ]; then
  echo "  ✘ core.hooksPath is SET to '$EFFECTIVE_HOOKSPATH'."
  echo "    git reads hooks from THERE, not from $HOOKS — this install would be INERT."
  echo "    Unset it, or install into that directory instead."
  # 🔴 Refuse rather than print INSTALLED on a dead install. The previous version
  # printed the warning and then "INSTALLED ... rc=0", so an operator reading the
  # last line or the exit code got a green on a hook that would never run.
  [ "$MODE" = "uninstall" ] || exit 5
else
  echo "  core.hooksPath: unset (git will read $HOOKS) ✓"
fi

is_ours() { [ -f "$1" ] && grep -q "$MARKER" "$1" 2>/dev/null; }

if [ "$MODE" = "uninstall" ]; then
  if is_ours "$TARGET"; then
    rm -f "$TARGET"; echo "  UNINSTALLED"
  else
    echo "  nothing to uninstall (no devrc-managed hook at that path)"
  fi
  exit 0
fi

if [ -e "$TARGET" ] || [ -L "$TARGET" ]; then
  if is_ours "$TARGET"; then
    if grep -q "^impl=\"$IMPL\"$" "$TARGET" 2>/dev/null; then
      echo "  already installed (generated wrapper -> this checkout) ✓"
      exit 0
    fi
    # OUR hook, pointing at a DIFFERENT checkout — typically installed from an
    # agent worktree that has since been removed, leaving the impl path dangling.
    # Say so, rather than calling devrc's own hook foreign and demanding --force
    # for what is really a re-point.
    echo "  ⚠ an EXISTING devrc hook points at another checkout:"
    grep -m1 '^impl=' "$TARGET" 2>/dev/null | sed 's/^/      /'
    echo "    Re-point it with --force; this is devrc's own hook, not a foreign one."
  fi
  if [ "$FORCE" -ne 1 ]; then
    echo "  ✘ a prepare-commit-msg already exists and is not ours. Look at it first:" >&2
    echo "      $TARGET" >&2
    echo "    Re-run with --force to replace it." >&2
    exit 4
  fi
fi

if [ "$MODE" = "dry" ]; then
  echo "  DRY-RUN — would generate $TARGET, calling $IMPL"
  echo "  re-run with --apply to install"
  exit 0
fi

mkdir -p "$HOOKS"

# 🔴 THE WRAPPER IS GENERATED HERE RATHER THAN SHIPPED, and the reason is
# devrc#1083's 🟡-9: a shipped file has to be SYMLINKED into .git/hooks, and this
# box runs ~115 ephemeral agent worktrees. Installing from one baked THAT
# worktree's path into the link; when the worktree was removed the link dangled,
# git silently skipped the hook (commits stayed safe, the feature was dead), and
# a later re-install from the base clone REFUSED, calling devrc's own dangling
# link "a FOREIGN prepare-commit-msg". A generated wrapper names the Python half
# by absolute path, so edits to the LOGIC still apply with no re-install — only
# this 12-line shim is frozen.
#
# ⚠ A RETRACTED DIAGNOSIS LIVED HERE, and is written down so it is not
# re-derived. An earlier revision claimed this file had to be generated because
# shipping it as an executable `#!/bin/sh` under `scripts/` made the nix-sandbox
# gate tier fail, blaming nixpkgs' `patchShebangs`. That was WRONG. The real
# cause was the BUILD INVOCATION: `nix build path:<a git WORKTREE>` copies the
# worktree's `.git` — which is a FILE reading `gitdir: …/worktrees/<name>`, not a
# directory — into the sandbox, so `src` looks like a repository whose gitdir is
# unreachable and every `git` call there dies on repo discovery. That is what
# tripped GUARD 10's `git config --global` preflight, before any test ran.
# Reproduced directly:
#
#     $ printf 'gitdir: /nonexistent/worktrees/x\n' > $D/.git
#     $ GIT_CONFIG_GLOBAL=$D/gc git -C $D config --global probe.k v
#     fatal: not a git repository: (null)
#
# The bisect that "proved" the shebang theory was CONFOUNDED: every bisect copy
# was a `cp -a` with `.git` removed (per the worktree-copy rule in RULES.md), so
# each one silently varied `.git` presence as well as the file under test. Build
# the sandbox tier from a real CLONE, never from a worktree.
cat > "$TARGET" <<WRAPPER
#!/bin/sh
# Generated by devrc scripts/install-session-stamp.sh — do not edit.
# Stamps the resumable session id onto an agent's commit.
#
# 🔴 EVERY EXIT IS 0. A prepare-commit-msg hook's exit status decides whether the
# commit happens. As a \`#!/usr/bin/env python3\` hook this refused commits
# outright when the interpreter could not be resolved (measured: rc=1 and no
# commit, against a control of rc=0 with the hook removed). /bin/sh is the one
# interpreter always present, and a missing python must be a no-op, never a
# refusal.
impl="$SOURCE_ROOT/scripts/git-hooks/prepare_commit_msg.py"
[ -r "\$impl" ] || exit 0
if [ -n "\$DEVRC_SESSION_TRAILER_PYTHON" ] && [ -x "\$DEVRC_SESSION_TRAILER_PYTHON" ]; then
    py="\$DEVRC_SESSION_TRAILER_PYTHON"
elif command -v python3 >/dev/null 2>&1; then
    py=python3
else
    exit 0
fi
"\$py" "\$impl" "\$@" 2>/dev/null
exit 0
WRAPPER
chmod +x "$TARGET"
chmod +x "$SOURCE_ROOT/scripts/git-hooks/prepare_commit_msg.py" 2>/dev/null || true
echo "  INSTALLED (generated wrapper -> $SOURCE_ROOT/scripts/git-hooks/prepare_commit_msg.py)"
echo "  edits to the Python half apply with no re-install; the shim itself is frozen"
echo
echo "  🔴 THAT IS ONLY THE GIT HALF. Nothing is stamped until the RECORDING half"
echo "     is registered as a PreToolUse hook in ~/.claude/settings.json, which is"
echo "     per-host and unmanaged by design. Add:"
echo
cat <<'SNIPPET'
       {
         "hooks": {
           "PreToolUse": [
             {
               "matcher": "Bash",
               "hooks": [
                 { "type": "command",
                   "command": "python3 ~/.claude/hooks/session-stamp.py" }
               ]
             }
           ]
         }
       }
SNIPPET
echo
echo "     Then verify end to end: make a commit from an agent session and check"
echo "     'git log -1 --format=%B' carries a Claude-Session-Id: line."
