#!/usr/bin/env bash
# Regenerate scripts/collector/known_repos.py — the static {repo_name: "owner/repo"}
# mapping used by mention-open.py for fast mention resolution.
#
# Usage:  scripts/regen-known-repos.sh
#         (run from anywhere; writes to the repo's scripts/collector/)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$REPO_ROOT/scripts/collector/known_repos.py"
TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

python3 -c "
import json, subprocess, re, sys
from pathlib import Path

# 1. All repos from gh API (paginated)
repos = {}
try:
    r = subprocess.run(
        ['gh', 'api', 'user/repos', '--paginate', '--jq', '.[].full_name'],
        capture_output=True, text=True, timeout=30)
    for line in r.stdout.splitlines():
        line = line.strip()
        if '/' in line:
            name = line.split('/')[-1]
            # BOTH spellings: mention_scan._resolve_repo does an EXACT dict
            # lookup (repos.get(repo)), so a canonical-case key alone cannot
            # match 'comfyui#12'. GitHub repo names are case-insensitive.
            repos[name] = line
            repos[name.lower()] = line
except Exception as e:
    print(f'warning: gh api failed: {e}', file=sys.stderr)

# 2. Overlay local checkout directory names
SSH_REMOTE = re.compile(r'^(?:ssh://)?git@[^:/]+[:/](?P<path>.+?)(?:\.git)?/?\$')
HTTP_REMOTE = re.compile(r'^https?://[^/]+/(?P<path>.+?)(?:\.git)?/?\$')
workspace = Path.home() / 'workspace'
for entry in sorted(p for p in workspace.iterdir() if p.is_dir()):
    dotgit = entry / '.git'
    if not dotgit.exists():
        continue
    # Skip LINKED WORKTREES (their .git is a FILE holding 'gitdir: …', a real
    # clone's is a directory). They share the base clone's remote, so they add
    # no owner this mapping does not already have — and they are transient, so
    # including them churns this generated file on every regen with names like
    # 'devrc-integ-1261' that nobody ever writes as a mention.
    if dotgit.is_file():
        continue
    try:
        r = subprocess.run(['git', 'remote', 'get-url', 'origin'], cwd=str(entry),
                           capture_output=True, text=True, timeout=5)
        url = r.stdout.strip() if r.returncode == 0 else ''
    except Exception:
        continue
    m = SSH_REMOTE.match(url) or HTTP_REMOTE.match(url)
    if not m:
        continue
    parts = [p for p in m.group('path').split('/') if p]
    if len(parts) == 2:
        full = f'{parts[0]}/{parts[1]}'
        repos[entry.name] = full
        repos[entry.name.lower()] = full
        repos[parts[1]] = full
        repos[parts[1].lower()] = full

# 3. Write the Python module
with open('$TMP', 'w') as f:
    f.write('# Auto-generated by scripts/regen-known-repos.sh — do not edit.\n')
    f.write('# Keys are lowercased for case-insensitive GitHub repo name matching.\n')
    f.write('KNOWN_REPOS = {\n')
    for k, v in sorted(repos.items()):
        f.write(f'    {k!r}: {v!r},\n')
    f.write('}\n')
" && mv "$TMP" "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") entries)"
