map('n', '<leader>h', '<cmd>wincmd h<CR>')
map('n', '<leader>j', '<cmd>wincmd j<CR>')
map('n', '<leader>k', '<cmd>wincmd k<CR>')
map('n', '<leader>l', '<cmd>wincmd l<CR>')
map('n', '<leader>pv', ':wincmd v<bar> :Explore<bar> :vertical resize 30<CR>')
map('n', '<leader>ee', 'oif err != nil {<CR>return errors.WithStack(err)<CR>}<CR><esc>kk>>_')
map('t', '<Esc>', '<C-\\><C-n>')
map('n', '<leader>t', ':wincmd s<bar> :wincmd j<bar> :resize 10<bar> :terminal<CR>')
map('n', '<leader>b', ':G blame %<CR>')
map('n', '<leader>c', '~<CR>')
map('n', '<leader>F', ':wincmd_<CR> :wincmd|<CR>')
map('n', '<leader>M', ':wincmd=<CR>')
map('n', '<leader>d', 'ofmt.Printf("%+v\\n", )<Esc>i')
map('n', '<leader>cl', 'oconsole.log("")<Esc>i')
map('n', '<leader>clp', 'oconsole.log(\'\')<Esc>hP<Esc>la, <Esc>p')
map('n', '<leader>cn', 'a className=""<Esc>i')
map('n', '<leader>hd', 'o<div class=""><CR></div><Esc>O')
map('n', '<leader>hb', 'o<button class=""><CR></button><Esc>O')
map('n', '<leader>hl', 'o<label class=""><CR></label><Esc>O')
map('n', '<leader>hs', 'o<span class=""><CR></span><Esc>O')
map('n', '<leader>hf', 'o<div class="flex "><CR></div><Esc>O')
map('n', '<leader>Y', ':%y+<CR>')
map('n', '<C-j>', '4j')
map('n', '<C-k>', '4k')
map('v', '<C-j>', '4j')
map('v', '<C-k>', '4k')
map('i', '<C-l>', '<Esc>')
map('t', '<C-l>', '<C-\\><C-n>')
map('v', '<C-l>', '<Esc>')
map('i', '<C-c>', '<cmd>echo "nah"<CR>')
map('n', 'L', 'f)')
map('n', 'M', '%')
map('v', 'M', '%')
map('v', 'Y', '"+y')

