map('n', '<leader>h', '<cmd>wincmd h<CR>')
map('n', '<leader>j', '<cmd>wincmd j<CR>')
map('n', '<leader>k', '<cmd>wincmd k<CR>')
map('n', '<leader>l', '<cmd>wincmd l<CR>')
map('n', '<leader>pv', ':wincmd v<bar> :Explore<bar> :vertical resize 30<CR>')
map('n', '<leader>ee', 'oif err != nil {<CR>return errors.WithStack(err)<CR>}<CR><esc>kk>>_')
map('t', '<Esc>', '<C-\\><C-n>')
map('n', '<leader>t', ':wincmd s<bar> :wincmd j<bar> :resize 10<bar> :terminal<CR>')
map('n', '<leader>b', ':G blame %<CR>')
map('n', '<leader>c', '~<CR>')
map('n', '<leader>F', ':wincmd_<CR> :wincmd|<CR>')
map('n', '<leader>M', ':wincmd=<CR>')
map('n', '<leader>d', 'ofmt.Printf("%+v\\n", )<Esc>i')
map('n', '<leader>D', 'oconsole.log("")<Esc>i')
map('i', '<C-j>', '<C-n>')
map('i', '<C-l>', '<Esc>')
map('t', '<C-l>', '<C-\\><C-n>')
map('v', '<C-l>', '<Esc>')
map('i', '<C-c>', '<cmd>echo "nah"<CR>')
map('n', 'L', 'f)')
map('n', 'M', '%')
map('v', 'M', '%')

