#!/usr/bin/env python3
"""LLM recap generation for the initiatives store (Phase B2).

The deterministic `summary` line parsed from each handoff is often still not legible
enough. Phase B adds a **one-to-two-sentence, plain-language recap** per initiative —
"what this is and where it stands" — generated by a homelab-served, OpenAI-compatible
vLLM model (stood up by the sibling B1 task) and CACHED in its own table so we only
(re)generate when the underlying facts actually change.

Division of responsibility (mirrors sync.py / viewer.py):
  * PURE logic — `recap_context` (the salient fields), `input_hash` (stable,
    order-independent), and `build_messages` (the anti-confabulation prompt). No I/O;
    unit-tested directly with fixtures.
  * I/O — `VllmClient` (the OpenAI-compatible HTTP call over a kubectl port-forward),
    the `initiatives.recaps` table DDL + `fetch_recaps` / `upsert_recap`, and the
    best-effort orchestration (`sync_recaps` / `maybe_sync_recaps`).

The "cached, regenerate-on-change" contract:
  For each initiative we hash the fields that define "what / where it stands". If the
  hash matches the stored recap's `input_hash` (and a recap exists), we REUSE it — no
  model call. Otherwise we (re)generate and upsert. This bounds cost to actual change.

Best-effort / non-breaking (CRITICAL): the vLLM endpoint being down, slow, or erroring
must NEVER break the sync or the snapshot write. Every generation is wrapped in
try/except + a timeout; on failure we keep the existing cached recap (or none) and
continue, and `maybe_sync_recaps` rolls the connection back so the UNCONDITIONAL
`write_snapshot` that follows is unaffected.

Configuration (endpoint / model / namespace / service) is all env-overridable with
PLACEHOLDER defaults — the human wires the real vLLM service name/port after B1 lands.
See `recap_config()` for the full list. Recap generation is OFF until
`INITIATIVES_RECAP_ENABLED` is truthy, so the sync stays a no-op (beyond ensuring the
recaps table exists) until the model service is real.
"""
from __future__ import annotations

import contextlib
import hashlib
import json
import os
import socket
import subprocess
import time
import urllib.request
from datetime import datetime, timezone

# --------------------------------------------------------------------------- #
# Configuration — PLACEHOLDER defaults; the human fills these after B1 lands.
# --------------------------------------------------------------------------- #
# Every value is env-overridable so the real vLLM service name / port / model id can be
# wired without a code change. Until then the placeholders let the module import + the
# tests run, but generation stays disabled (INITIATIVES_RECAP_ENABLED unset → off).
#
#   INITIATIVES_RECAP_ENABLED  — master switch (truthy → generate). Default OFF.
#   RECAP_BASE_URL             — if set (e.g. a NodePort/nebula URL like the ClickHouse
#                                reader), call it DIRECTLY and skip the port-forward.
#   RECAP_NAMESPACE            — k8s namespace of the vLLM service.       [FILL AFTER B1]
#   RECAP_SERVICE              — k8s service ref for kubectl port-forward.[FILL AFTER B1]
#   RECAP_SERVICE_PORT         — the service's OpenAI-API port.           [FILL AFTER B1]
#   RECAP_MODEL                — the served model id (OpenAI `model`).    [FILL AFTER B1]
#   RECAP_TIMEOUT              — per-call HTTP timeout (seconds).
RECAP_NAMESPACE = "vllm"                 # PLACEHOLDER — set to the real namespace
RECAP_SERVICE = "svc/vllm"               # PLACEHOLDER — set to the real service ref
RECAP_SERVICE_PORT = 8000                # vLLM OpenAI server default; override if B1 differs
RECAP_MODEL = "PLACEHOLDER-MODEL-ID"     # PLACEHOLDER — set to the served model id
RECAP_TIMEOUT = 30.0
RECAP_MAX_TOKENS = 160                   # a 1-2 sentence recap is well under this
RECAP_TEMPERATURE = 0.2                  # low — we want faithful, not creative
# The OpenAI-compatible chat-completions path (stable across vLLM / OpenAI).
RECAP_CHAT_PATH = "/v1/chat/completions"

# Only the N most-recent prompts / commits feed the hash + prompt (older ones don't
# change "what this is / where it stands" and would churn the hash needlessly).
RECAP_MAX_MESSAGES = 6
RECAP_MAX_COMMITS = 6


def _truthy(v) -> bool:
    return str(v or "").strip().lower() in ("1", "true", "yes", "on")


def recap_config(env: dict | None = None) -> dict:
    """Resolve the recap config from the environment (PLACEHOLDER defaults otherwise).

    PURE w.r.t. `env` (defaults to os.environ). `enabled` is the master switch; when
    False the sync only ensures the recaps table exists and does zero model work."""
    env = os.environ if env is None else env
    return {
        "enabled": _truthy(env.get("INITIATIVES_RECAP_ENABLED")),
        "base_url": (env.get("RECAP_BASE_URL") or "").strip(),
        "namespace": (env.get("RECAP_NAMESPACE") or RECAP_NAMESPACE).strip(),
        "service": (env.get("RECAP_SERVICE") or RECAP_SERVICE).strip(),
        "service_port": _int(env.get("RECAP_SERVICE_PORT"), RECAP_SERVICE_PORT),
        "model": (env.get("RECAP_MODEL") or RECAP_MODEL).strip(),
        "timeout": _float(env.get("RECAP_TIMEOUT"), RECAP_TIMEOUT),
    }


def _int(v, default: int) -> int:
    try:
        return int(v)
    except (TypeError, ValueError):
        return default


def _float(v, default: float) -> float:
    try:
        return float(v)
    except (TypeError, ValueError):
        return default


# --------------------------------------------------------------------------- #
# The prompt — anti-confabulation discipline (mirrors session_insight/schema.py).
# --------------------------------------------------------------------------- #
# Reuses the pipeline's non-negotiable contract: the model works from the PROVIDED
# context ONLY and may not invent counts, dates, PR numbers, or a status the inputs
# don't support. The result is the substance itself (no "this initiative…" meta),
# present tense, terse.
ANTI_CONFABULATION_CONTRACT = (
    "ANTI-CONFABULATION CONTRACT. Write ONLY from the context object provided below. "
    "You MUST NOT invent or guess any count, date, PR number, name, or status that is "
    "not present in that context (if the number of commits/PRs/sessions isn't given, "
    "do not state one — there is no metric to cite). Do NOT restate raw counts as if "
    "you tallied them. If the context is too thin to say what the work is, write a "
    "single honest clause from whatever IS present rather than fabricating detail."
)

RECAP_INSTRUCTIONS = (
    "You summarize one software initiative for a status board. Produce a plain-language "
    "recap of ONE to TWO sentences: what the initiative is (the actual work / system) "
    "and where it currently stands. "
    "Describe the WORK ITSELF, never the paperwork about it. You MUST NEVER mention or "
    "describe a handoff doc, a resume/canonical doc, a markdown or notes file, any "
    "filename, the word \"supersedes\", or the existence of documentation — the recap is "
    "about the feature / system and its status, NOT about any document that tracks it. "
    "If the only context is doc-meta (e.g. one file superseding another, a \"resume "
    "doc\"), write from whatever substantive work IS present, or a single honest clause "
    "about the work — never \"this is a doc that…\" or a reference to the document. "
    "Requirements: present tense; terse and concrete; describe the substance directly — "
    "do NOT open with meta like \"This initiative…\" / \"The goal is…\"; no preamble, no "
    "bullet points, no markdown, no quotes around the output. Return ONLY the recap text."
)

SYSTEM_PROMPT = RECAP_INSTRUCTIONS + "\n\n" + ANTI_CONFABULATION_CONTRACT

# A short, deterministic fingerprint of the prompt text (system message). Folding it into
# `input_hash` means any edit to SYSTEM_PROMPT (tightening the instructions, or the
# anti-confabulation contract) changes EVERY initiative's hash → the whole recap cache is
# busted and the next sync regenerates all recaps under the new prompt. This is automatic:
# no manual version bump to remember (a stale RECAP_PROMPT_VERSION constant is the classic
# way to serve recaps from an old prompt forever). Only a prefix is used — full 256-bit
# collision resistance is irrelevant for a cache key.
_PROMPT_FINGERPRINT = hashlib.sha256(SYSTEM_PROMPT.encode("utf-8")).hexdigest()[:16]


def recap_context(ini: dict) -> dict:
    """PURE: one store/insert row -> the salient context that defines "what / where it
    stands". This is BOTH what the hash covers and what the prompt sees, so the two can
    never drift. Empty/missing fields normalize to ""/[] (never raises)."""
    return {
        "momentum": (ini.get("momentum") or "").strip(),
        "summary": (ini.get("summary") or "").strip(),
        "next_step": (ini.get("next_step") or "").strip(),
        "open_investigations": [
            s for s in (str(x).strip() for x in (ini.get("open_investigations") or [])) if s
        ],
        "recent_messages": [
            t for t in (_msg_text(m) for m in (ini.get("recent_messages") or []))
            if t
        ][:RECAP_MAX_MESSAGES],
        "recent_commits": [
            s for s in (str(x).strip() for x in (ini.get("recent_commits") or [])) if s
        ][:RECAP_MAX_COMMITS],
        "open_prs": [s for s in (_pr_text(p) for p in (ini.get("open_prs") or [])) if s],
    }


def _msg_text(m) -> str:
    if isinstance(m, dict):
        return str(m.get("text") or "").strip()
    return str(m or "").strip()


def _pr_text(p) -> str:
    if isinstance(p, dict):
        num = p.get("number")
        title = str(p.get("title") or "").strip()
        return (f"#{num} " if num is not None else "") + title
    return str(p or "").strip()


def input_hash(ctx: dict, model: str = "") -> str:
    """PURE + STABLE: a sha256 over everything that determines the generated recap — the
    context fields that define "what / where it stands", PLUS the prompt fingerprint and
    the served `model`. Order-INDEPENDENT for the set-like fields (open_investigations /
    open_prs are sorted) and for dict-key order (sort_keys), so a mere reordering never
    triggers a regenerate; a genuine content change (a new/edited message, commit,
    next-step, summary, momentum, investigation, or PR) DOES. `recent_messages`/
    `recent_commits` keep their newest-first order — a reorder there implies added/removed
    content, which is exactly a change we want to re-recap.

    Folding the prompt fingerprint and model in means a PROMPT edit (see
    `_PROMPT_FINGERPRINT`) or a MODEL swap also busts the cache, so the next sync
    regenerates every recap under the new prompt/model instead of serving stale output
    from the old one. Everything else stays deterministic (the same sorted-fields /
    sort_keys properties), so an unchanged prompt + model + context yields a stable hash
    (a cache hit)."""
    canonical = {
        "prompt": _PROMPT_FINGERPRINT,
        "model": (model or "").strip(),
        "momentum": ctx.get("momentum", ""),
        "summary": ctx.get("summary", ""),
        "next_step": ctx.get("next_step", ""),
        "open_investigations": sorted(ctx.get("open_investigations") or []),
        "open_prs": sorted(ctx.get("open_prs") or []),
        "recent_messages": list(ctx.get("recent_messages") or []),
        "recent_commits": list(ctx.get("recent_commits") or []),
    }
    blob = json.dumps(canonical, sort_keys=True, ensure_ascii=False, separators=(",", ":"))
    return hashlib.sha256(blob.encode("utf-8")).hexdigest()


def build_messages(ctx: dict) -> list[dict]:
    """PURE: context dict -> OpenAI chat `messages`. The system message carries the
    instructions + anti-confabulation contract; the user message is the context object
    as JSON — the model sees ONLY these provided fields, nothing else."""
    user = (
        "Recap this initiative from the following context (JSON). Use only these "
        "fields.\n\n" + json.dumps(ctx, ensure_ascii=False, indent=2, sort_keys=True)
    )
    return [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": user},
    ]


# --------------------------------------------------------------------------- #
# Store — a STANDALONE recaps table (a true cache; NOT in the snapshot/views).
# --------------------------------------------------------------------------- #
# Deliberately separate from `initiative_snapshot` and the `latest`/`current` views:
#   * it persists ACROSS snapshots (the cache survives every sync), and
#   * keeping it out of the views means NO view-version bump / DDL change here (a recap
#     column would reorder the frozen `SELECT i.*, s.captured_at` and force yet another
#     migration). The viewer LEFT-JOINs this table by (repo, slug) instead.
# Created idempotently inside sync.ensure_schema, under the SAME advisory lock as the
# rest of the schema.
RECAPS_DDL = """
CREATE TABLE IF NOT EXISTS initiatives.recaps (
    repo         text NOT NULL,
    slug         text NOT NULL,
    recap        text,
    input_hash   text,
    model        text,
    generated_at timestamptz DEFAULT now(),
    PRIMARY KEY (repo, slug)
);
"""


def create_recaps_table(cur) -> None:
    """Execute the idempotent recaps-table DDL on an OPEN cursor (called from
    sync.ensure_schema, inside its advisory-locked transaction — no commit here)."""
    cur.execute(RECAPS_DDL)


def fetch_recaps(conn) -> dict:
    """Read the cached recaps -> {(repo, slug): {"input_hash", "recap"}}.

    The keys are what `sync_recaps` matches an initiative's freshly-computed hash
    against to decide cache-hit vs regenerate."""
    out: dict = {}
    with conn.cursor() as cur:
        cur.execute("SELECT repo, slug, recap, input_hash FROM initiatives.recaps")
        for repo, slug, recap, ihash in cur.fetchall():
            out[(repo, slug)] = {"recap": recap, "input_hash": ihash}
    return out


def upsert_recap(cur, repo: str, slug: str, recap: str, ihash: str, model: str) -> None:
    """Upsert one (repo, slug) recap (INSERT … ON CONFLICT DO UPDATE). `generated_at`
    is stamped now() on both insert and update so it tracks the last (re)generation."""
    cur.execute(
        """
        INSERT INTO initiatives.recaps (repo, slug, recap, input_hash, model, generated_at)
        VALUES (%s, %s, %s, %s, %s, now())
        ON CONFLICT (repo, slug) DO UPDATE
           SET recap = EXCLUDED.recap,
               input_hash = EXCLUDED.input_hash,
               model = EXCLUDED.model,
               generated_at = now()
        """,
        (repo, slug, recap, ihash, model),
    )


# --------------------------------------------------------------------------- #
# I/O — the vLLM client (OpenAI-compatible chat, over a kubectl port-forward).
# --------------------------------------------------------------------------- #
def _free_local_port() -> int:
    """Ask the OS for a free TCP port (bind to 0, read it back, release). Same trick
    as mail-actions/_db.py's port-forward bridge."""
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.bind(("127.0.0.1", 0))
    port = s.getsockname()[1]
    s.close()
    return port


class VllmClient:
    """Context manager: an OpenAI-compatible chat client for the homelab vLLM service.

    Two reach modes (config-driven):
      * `base_url` set  -> POST directly to `<base_url>/v1/chat/completions` (e.g. a
        NodePort/nebula URL, like the ClickHouse reader endpoint). No port-forward.
      * otherwise       -> `kubectl -n <ns> port-forward <service> <local>:<svc_port>`
        on an ephemeral local port for the batch, torn down on exit (mirrors _db.py).

    Uses stdlib urllib (no `requests` dependency). `generate(messages)` returns the
    completion text or raises — callers wrap it best-effort so a model outage is inert.
    """

    def __init__(self, cfg: dict, ready_timeout: float = 20.0):
        self._cfg = cfg
        self._ready_timeout = ready_timeout
        self._pf: subprocess.Popen | None = None
        self._url: str | None = None

    def __enter__(self) -> "VllmClient":
        base = self._cfg.get("base_url")
        if base:
            self._url = base.rstrip("/") + RECAP_CHAT_PATH
            return self
        local_port = _free_local_port()
        self._pf = subprocess.Popen(
            [
                "kubectl", "-n", self._cfg["namespace"], "port-forward",
                self._cfg["service"], f"{local_port}:{self._cfg['service_port']}",
            ],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.PIPE,
        )
        self._wait_for_port("127.0.0.1", local_port)
        self._url = f"http://127.0.0.1:{local_port}{RECAP_CHAT_PATH}"
        return self

    def __exit__(self, *_exc) -> None:
        if self._pf is not None:
            self._pf.terminate()
            with contextlib.suppress(Exception):
                self._pf.wait(timeout=5)

    def _wait_for_port(self, host: str, port: int) -> None:
        deadline = time.monotonic() + self._ready_timeout
        while time.monotonic() < deadline:
            if self._pf and self._pf.poll() is not None:
                err = self._pf.stderr.read().decode() if self._pf.stderr else ""
                raise RuntimeError(f"kubectl port-forward exited early:\n{err}")
            with contextlib.suppress(OSError):
                with socket.create_connection((host, port), timeout=1):
                    return
            time.sleep(0.25)
        raise TimeoutError(f"vLLM port-forward to {host}:{port} not ready in time")

    def generate(self, messages: list[dict]) -> str:
        """POST an OpenAI chat-completions request; return choices[0].message.content."""
        if not self._url:
            raise RuntimeError("VllmClient used outside its context manager")
        body = json.dumps({
            "model": self._cfg["model"],
            "messages": messages,
            "temperature": RECAP_TEMPERATURE,
            "max_tokens": RECAP_MAX_TOKENS,
            "stream": False,
        }).encode("utf-8")
        req = urllib.request.Request(
            self._url, data=body,
            headers={"Content-Type": "application/json"}, method="POST",
        )
        with urllib.request.urlopen(req, timeout=self._cfg["timeout"]) as resp:
            data = json.loads(resp.read().decode("utf-8"))
        return data["choices"][0]["message"]["content"]


# --------------------------------------------------------------------------- #
# Orchestration — cached, regenerate-on-change, best-effort per initiative.
# --------------------------------------------------------------------------- #
def sync_recaps(conn, rows: list[dict], *, client, model: str) -> dict:
    """For each row: hash its context, and regenerate ONLY when the hash differs from the
    cached recap (or none exists). A cache hit skips the model entirely. Each generation
    is wrapped best-effort — a single failure leaves that initiative's cached recap
    UNTOUCHED and moves on. Commits the upserts once at the end. Returns a stats dict.

    `client` is an object with `.generate(messages) -> str` (a `VllmClient`, or a fake in
    tests). `conn`/`client` I/O is the only impurity; the decision logic is deterministic."""
    stats = {"total": len(rows), "regenerated": 0, "cached": 0,
             "failed": 0, "skipped": 0}
    cached = fetch_recaps(conn)
    with conn.cursor() as cur:
        for r in rows:
            repo, slug = r.get("repo"), r.get("slug")
            if not repo or not slug:
                stats["skipped"] += 1
                continue
            ctx = recap_context(r)
            ihash = input_hash(ctx, model=model)
            prev = cached.get((repo, slug))
            if prev and prev.get("input_hash") == ihash and prev.get("recap"):
                stats["cached"] += 1  # unchanged → reuse the cached recap, no model call
                continue
            try:
                text = (client.generate(build_messages(ctx)) or "").strip()
            except Exception:  # noqa: BLE001 - a model outage must not break the sync
                stats["failed"] += 1
                continue      # keep the existing cached recap (or none); do NOT upsert
            if not text:
                stats["failed"] += 1
                continue
            upsert_recap(cur, repo, slug, text, ihash, model)
            stats["regenerated"] += 1
    conn.commit()
    return stats


def maybe_sync_recaps(conn, rows: list[dict], env: dict | None = None,
                      client_factory=None) -> dict:
    """Best-effort entry point called from the sync BEFORE the (unconditional) snapshot
    write. Reads config; if disabled, returns immediately (the recaps table still exists,
    created in ensure_schema). Otherwise opens ONE vLLM client for the whole batch and
    runs `sync_recaps`. ANY failure (config, port-forward, DB) is caught and the
    connection is ROLLED BACK so the following `write_snapshot` is never affected.

    `client_factory(cfg) -> context-manager client` is injectable for tests (defaults to
    `VllmClient`). Returns a stats dict with a `status` key for the sync's log line."""
    cfg = recap_config(env)
    if not cfg["enabled"]:
        return {"status": "disabled",
                "message": "recap generation disabled (INITIATIVES_RECAP_ENABLED unset)"}
    factory = client_factory or VllmClient
    try:
        with factory(cfg) as client:
            stats = sync_recaps(conn, rows, client=client, model=cfg["model"])
        stats["status"] = "ok"
        return stats
    except Exception as exc:  # noqa: BLE001 - recap is best-effort; never break the sync
        with contextlib.suppress(Exception):
            conn.rollback()  # clear any aborted-transaction state before write_snapshot
        return {"status": "error", "error": f"{type(exc).__name__}: {exc}"}


def format_recap_note(stats: dict) -> str:
    """A compact one-liner for the sync's stdout summary (e.g. ', recap 2 new/9 cached')."""
    status = stats.get("status")
    if status == "disabled":
        return ", recap off"
    if status == "error":
        return ", recap error (best-effort, skipped)"
    if status == "ok":
        return (f", recap {stats.get('regenerated', 0)} new/"
                f"{stats.get('cached', 0)} cached"
                + (f"/{stats['failed']} failed" if stats.get("failed") else ""))
    return ""


def _utc_now() -> datetime:
    return datetime.now(timezone.utc)
